[[_0_]]
= 뇌 척수로 운동법
Joy <arbago@gmail.com>
v1.0, 2015-5-11
:icons: font
:sectanchors:
:imagesdir: images
:homepage: http://arbago.com
:toc: macro

toc::[]

[preface]
== 추천사

암을 비롯한 난치병의 원인은 CSD (Cranio-sacral System Disorder)입니다 +
다시 말하면 두개천골 시스템 (몸의 골격)이 틀어지고 1분에 6~12회 움직이는 시스템이 작동하지 않아서입니다 +
자동차로 비유하면 엔진이 꺼져 버리는 것입니다

특정한 손가락과 발가락을 움직이거나 자극을 주면 두개천골 시스템 (인체골격)의 Physiological correction 이 일어나서 치아를 제외한 인체의 골격이 생리의 균형상태에 도달하게 됩니다 +
그리하여 인체의 생리균형과 치아의 교합 (턱관절) 불균형을 해소하는 방법으로 난치병 진료에서 의미있는 림상결과를 얻고 있습니다

[quote, 데이비드 B. 아구스, 질병의 종말]
____
의술은 기술이 아니라 관찰과 해석의 예술
____

[preface]
== 추천사

검지 하나의 감각입력량과 운동출력량은 등 전체보다도 넓다

손가락 하나 발가락 하나의 움직임으로 신경상태 및 관련 장부와 인체조직간의 역학관계를 파악하는 가장 좋은 진단방법이 뇌척수로 진단입니다 +
또한 해당 뇌척수로운동을 하는 것이 치료방법입니다

뇌척수로운동을 통해 자가진단과 자가치료가 가능하게 합니다

[preface]
== 추천사

기계나 장비의 도움 없이 오직 환자의 손가락과 발가락 운동만으로 머리에서 발끝까지 통합 유기로 진단할 수 있음은 물론 +
환자 자신이 스스로의 몸에 대한 진단과 치료에 직접 참여할 수 있는 장점이 있다

[preface]
== 머리말

척수로 수행의 근거경전은 릉엄경 楞嚴經 이다 +
릉엄경에서 제시하는 수행체계가 척수로 수행의 근거가 된다

릉엄경의 수행체계::
1. 삼관(三觀)
2. 직심(直心
3. 쌍차쌍조(雙遮雙照)
4. 양신배양
5. 32진로
6. 25 원통체게: 6가지 의식체계에 립각한 것으로 앞의 5 가지 수행에 포함됨

뇌척수로::
인체내부의 생명경로

뇌척수로 수행법::
1. 시개척수로
2. 전정척수로
3. 적핵척수로
4. 피질척수로
5. 그물척수로

시개, 전정, 피질 수행법은 부처님께서 아난에게 질문한 내용을 근거로 한 것이다

[[_1_0_0_]]
== 1. 법문의 배경

시개척수로::
보는 마음의 생명경로

뇌척수로 수행::
본성에서 의식과 감정과 의지가 드러나는 경로를 주시하는 것

생명경로를 알려면 신경, 장부, 뼈, 근육, 경락, 혈관, 힘줄 등 모든 육체구조물 간의 련관성에 대해 알아야 한다

몸이라는 도구가 있기에 그런 수행을 할 수 있다

시작인 '`본성`'이 결과인 '`본다`'는 것으로 드러나기까지의 어떤 과정을 거쳐서 그것이 일어나는지 그것을 관찰할 수 있는 지각력을 몸을 도구로 해서 키우는 것이다

[[_2_0_1_]]
== 2. 검지손가락 보기(시개 척수로 운동)

[[_3_0_2_]]
== 3. 다섯손가락 운동(피질 척수로 운동)

[[_4_0_3_]]
== 4. 검지손가락 구부리기(전정 척수로 운동)

[[_5_0_4_]]
== 5. 검지 억제하기

[[_6_0_5_]]
== 6. 엄지손가락 운동과 엄지발가락 운동(적핵 척수로 운동)

[[_7_0_6_]]
== 7. 그물 척수로 운동

[[_8_0_7_]]
== 8. 호흡, 발성, 척수로의 관계와 신경조절물질의 연관성

[[_9_0_8_]]
== 9. 시개 척수로를 통해 본성 인식하기

[[_10_0_9_]]
== 10. 중풍 치료기

[[_11_0_10_]]
== 11. 적핵 척수로와 피질 척수로의 통합 1

[[_12_0_11_]]
== 12. 적핵 척수로와 피질 척수로의 통합 2

[[_13_0_12_]]
== 13. 경락

[[_14_0_13_]]
== 14. 의식과 장부, 척수로와의 연관성

[[_15_0_14_]]
== 15. 척수로의 기능과 의식의 관계

[[_16_0_15_]]
== 16. 진단과 치유

[[_17_0_16_]]
== 자음 발성을 활용한 뇌 척수로 진단법

[[_18_0_17_]]
== 뇌 척수로 운동을 활용한 교정