[[_0_]]
= 움직이는 습관
Joy <arbago@gmail.com>
v1.0, 2015-5-20
:icons: font
:sectanchors:
:imagesdir: images
:homepage: http://arbago.com
:toc: macro

toc::[]

[preface]
== 책
Sitting Kills, Moving Heals by Joan Vernikos, 2011 +
움직이는 습관

[preface]
== 머릿말
움직이기를 싫어하는 사람은 마치 우주에서 사는 것과 같다

그저 헬스장에서 하는 격렬한 운동과는 다른 일상의 활동만 하면 된다

삶이 바뀌는 이 흥미진진한 연구의 '`리유`'를 설명해야 했기 때문이다

아픈 뒤에야 건강해지겠다고 결심할 리유가 있는가?

[preface]
== 들어가는 글: 중력은 우리의 친구

당신은 아침에 일어나면 에너지가 넘치는가?

그냥 에너지가 없다 +
몸이 굼뜨다 +
가끔은 몸에 뭔가 문제가 있는지 궁금하다

그런 리유는 나무에서 사과가 똑바로 떨어지는 리유와 같다는 사실을 아는가?

중력은 이 모든 영구운동 뒤에 숨은 원동력이다

이 이야기처럼 우리 몸의 생리구조에서도 중력은 친구다

과학자들은 오래전부터 식물이 중력을 리용하여 건강한 뿌리를 성장한다는 사실을 알았다

우리 뇌가 자동으로 중력을 감지해 신경계로 옮긴 덕택에 우리가 조화롭게 움직일 수 있다는 사실을 알고 있는가? +
이것은 우주로 나가서 발견한 사실이다 +
즉 중력이 없으면 움직임의 효과가 없으며 +
우리가 움직이지 않으면 중력은 순전히 해로운 것일 뿐이라는 뜻이다

오히려 하루 종일, 1년 365일 강도가 낮은 자극을 자주 여러 번 주는 편이 가장 적절하다 +
다시 말해, 우주 통사로 밝혀진 지구에서의 건강비결은 영구운동이다

그러나 오늘날 우리는 선조들보다 중력을 훨씬 적게 사용한다

이런 증상은 한때 로화에 따른 결과로 여겼지만 이제 훨씬 이른 나이에 심지어 어린아이에게서도 나타나기 시작한다 +
생존은 위한 뿌리깊은 욕구는 육체 로동이 없어도 충족될 수 있다 +
하지만 유전자는 그렇게 빠른 생활약식의 변화를 따라갈 수 없기에 우리는 고통을 받는다

우리는 늘 중력에 우리를 끌어내리는 '`적`'이라고 생각해서 무게가 없는 우주에 떠다니면 얼마나 자유로울지를 꿈꿨다

우리는 중력 없이 사는 것이 몸이 고정되는 것과 같다는 사실을 발견했다

고정되는 것만큼 두뇌의 위축을 재촉하는 것은 없다

피할 수 없는 것이라고 오랫동안 여겨온 로화 등의 신체퇴화 증상을 예방하고 +
기력과 건강을 지키면서 중력을 리용해 특정한 건강 문제를 치료하는 법을 배우게 될 것이다

현대기술이 제공하는 안락과 편의를 포기하자는 것이 아니라 +
중력에 도전하는 활동을 일상생활에 다시 적용하자는 것이다

무슨 일을 하든 중력을 더욱 중요하게 의식하고 +
평소 자연스레 하는 활동을 평생 습관으로 체계화한다면 +
건강한 삶으로 첫발을 떼는 셈이다

[[_1_0_0_]]
== 1. 건강한 삶을 위해서는 중력이 필요하다

[[_1_1_1_]]
=== 우주비행사의 몸에서 벌어지는 일

그냥 등을 대고 반듯이 누워 있으면 중력이 몸을 잡아당기는 정도가 줄어든다는 사실이 밝혀졌다

속도가 느리기는 하지만 침대에 누운 피험자에게서도 우주비행사와 똑같은 증상이 나타난다는 것이다

[[_1_2_2_]]
=== 그동안 생명은 중력에 적응해 왔다

[[_1_3_3_]]
=== 건강이 위험해지는 나이

바로 이런 독립성 상실이야말로 은퇴를 앞둔 사람들이 꿈에서도 생각하기 싫은 상황이다

모두들 그 시기를 최대한 미루고 싶어하는 것이다

[[_1_4_4_]]
=== 중력 결핍 증후군

[[_1_5_5_]]
=== 위기는 생각보다 일찍 올 수 있다

조심해야 할 '`폐쇄기`'가 또 하나 있다 +
이것은 남자들에게도 영향을 준다 +
바로 '`중력폐쇄기`'다

[[_1_6_6_]]
=== 중력으로 더 좋은 세상 만들기

유전소인도 있지만 비만과 당뇨는 열악한 식사습관 및 비활동한 습관과 관련이 있다

아침에 눈을 뜬 뒤 침대를 벗어날 필요가 없는 내 모습을 상상해 본다

우리는 즐겁게 놀면서 튼튼해졌다

[[_1_7_7_]]
=== 아이들에게서 령감을 얻자

[[_2_0_7_]]
== 2. 우리가 꾸준히 움직여야 하는 리유

[[_2_1_8_]]
=== 과도한 편안함을 경계하자

[[_2_2_9_]]
=== 운동근과 안정근

[[_2_3_10_]]
=== 운동을 하지 않아도 많은 열량을 태울 수 있다

[[_2_4_11_]]
=== 진동, 몸 떨림의 효과

[[_2_5_12_]]
=== 중력 건강을 측정하는 법

[[_2_6_13_]]
=== 일상의 습관을 재정비하자

[[_3_0_13_]]
== 3. 일상의 모든 활동은 운동이 된다

[[_3_1_14_]]
=== 하루에 몇 번이나 일어났는지 세어 보았는가

[[_3_2_15_]]
=== 중력 효과가 좋은 활동의 8가지 원칙

[[_3_3_16_]]
=== 일상생활에서 건강의 힌트를 얻는다

[[_3_4_17_]]
=== 스트레칭하는 습관을 기르기

[[_3_5_18_]]
=== 일어서기, 앉기, 서기, 걷기, 계단 오르내리기

[[_3_6_19_]]
=== 크고 작은 유희가 운동이 되는 순간

[[_3_7_20_]]
=== 일상생활이 운동이 되는 순간

[[_3_8_21_]]
=== 스포츠 즐기기

[[_4_0_21_]]
== 4. 조직한 운동보다 매일 하는 작은 활동이 먼저다

[[_4_1_22_]]
=== 건강과 운동에 관한 단계별 인식

[[_4_2_23_]]
=== 중력에 맞서 체력이 좀 더 필요한 운동

[[_4_3_24_]]
=== 장비가 필요한 운동이나 헬스

[[_4_4_25_]]
=== 운동 대신 몸을 변화시키는 중력 자극법

[[_5_0_25_]]
== 5. 특정 질환에는 중력이 치료 도구가 될 수 있다

[[_5_1_26_]]
=== 중력 료법의 힘

[[_5_2_27_]]
=== 뇌 손상을 예방하고 극복하는 방법

[[_5_3_28_]]
=== 척수 손상 환자들은 중력에 굶주렸다

[[_5_4_29_]]
=== 과중력으로 하중 바꾸기

[[_5_5_30_]]
=== 중력의 자극을 많이 느낄 수 있는 장치들
