[[_0_]]
= Feed Your Brain Lose Your Belly
Joy <arbago@gmail.com>
v1.0, 2015-06-2
:icons: font
:sectanchors:
:imagesdir: images
:homepage: http://arbago.com
:toc: macro

toc::[]

[preface]
== 책

Feed Your Brain Lose Your Belly, Larry McCleary, 2011

A Brain Surgeon Reveals the Weight-Loss Secrets of the [big bold blue]#Brain-Belly Connection#

[preface]
== Preface

pediatrics (pē′dē-ăt′rĭks) 소아과(학)::
The branch of medicine that deals with the care of infants and children and the treatment of their diseases.
* pedo-= a combining form meaning “child,” used in the formation of compound words: _pedophilia_

brain starvation

glucose (glo͞o′kōs′) 포도당::
A monosaccharide sugar, C~6~H~12~O~6~, that is used by living things to obtain energy through the process of aerobic respiration within cells. It is the principal circulating sugar in the blood of humans and other mammals.

brownout (broun′out′) (절전을 위한) 전압 저하; 부분적 정전, 등화 관제::
A reduction or cutback in electric power, especially as a result of a shortage, a mechanical failure, or overuse by consumers.
* [brown + (black)out.]
* A situation in which the voltage in a power grid is reduced below its normal level but not entirely eliminated. ( Compare blackout.) +
Note : This reduced voltage can result in damage to many electronic devices.

senior moment (유머) 깜빡함(특히 나이 많은 사람의 특징으로 여겨지는 건망증 현상)::
An instance in which one is unable to remember something or to focus adequately on the matter at hand, viewed as typical of aging.
* 1995-2000; senior (citizen) + moment

dement (dĭ-mĕnt′) 이성을 빼앗다; 미치게 하다, 발광하게 하다(make mad or insane)::
. To cause (a person) to become mentally deranged.
. To cause (a person) to lose intellectual capacity.
* [Late Latin dēmentāre, from Latin dēmēns, dēment-, senseless : dē-, de- + mēns, mind; see men- in Indo-European roots.]

[big bold blue yellow-background]#How can our brains be starving while we're overfeeding our bodies?# +
It seemed to me that many of the calories we were consuming somehow bypassed our brains and ended up being stored in fat cells +
I began wondering whether there might be a relationship between the rise in brain problems and our expanding waistlines +
and, if so, what we could do about it.

insulin (ĭn′sə-lĭn)::
A polypeptide hormone secreted by the islets of Langerhans and functioning in the regulation of the metabolism of carbohydrates and fats, especially the conversion of glucose to glycogen, which lowers the blood glucose level.
* [New Latin īnsula, island (of Langerhans) (from Latin, island) + -in.]
* 1922 (earlier insuline, 1914), coined in English from Latin insula "island," so called because the hormone is secreted by the islets of Langerhans in the pancreas. Insuline was coined independently in French in 1909.

hypoglycemia (hī′pō-glī-sē′mē-ə) 저혈당(低血糖)(증):: An abnormally low level of glucose in the blood.
* 1893, from Latinized form of Greek elements hypo- "under" (see hypo- ) + glykys "sweet" (see glucose ) + haima "blood" (see -emia ).

endocrinology (ĕn′də-krə-nŏl′ə-jē) 내분비학::
The branch of medicine that deals with the diagnosis and treatment of diseases and disorders of the endocrine glands.

endocrine (ĕn′də-krĭn, -krēn′)  내분비의:: Secreting internally
* [French : Greek endo-, endo- + Greek krīnein, to separate; see krei- in Indo-European roots.]
* "secretly, internally," 1914, from endo- + Latinized form of Greek krinein "to separate, distinguish" (see crisis )

Endocrinologists (hormone doctors) have long known that insulin controls blood sugar by transporting glucose out of the blood intovarious other cells throughout the body, and away from brain cells +
Not receiving enough glucose has the same effect on the brain as not getting enough oxygen -- it stops working properly, and this canhappen suddenly +
That is when it dawned on me that elevated insulin levels might play a key role in both the fattening of America and the brain starvationbeing seen in aging brains!

It appeared as if becoming overweight or developing diabetes were risk factors for the development of some common brain disorders!
But how could this connection be explained?

dyslipidemia (dĭs-lĭp′ĭ-dē′mē-ə) 이상지질혈증:: An abnormal concentration of lipids or lipoproteins in the blood.
* [dys- + lipid + -emia.]

Freshman fifteen::
* The freshman 15 is an expression commonly used in the United States that refers to an amount (somewhat arbitrarily set at 15 pounds) of weight often gained during a student's first year at college. In Australia and New Zealand it is sometimes referred to as First Year Fatties, Fresher Spread, or Fresher Five, the latter referring to a five-kilogram gain.

* The purported causes of this weight gain are increased alcohol intake and the consumption of fat and carbohydrate-rich cafeteria-style food and fast food in university dormitories. Many dining halls in American universities are all-you-can-eat style and offer copious dessert choices. In addition, lack of sleep may lead to overeating and weight gain, because it lowers the level of leptin. Other causes include malnutrition, stress, and decreased levels of exercise. All of these factors can affect each person in a different way. Studies confirm many of these causes. Colleges and universities have recently been cracking down on this common problem and are trying to educate people on how to prevent it. This problem has grown so much that students are focusing on how to stop the freshman 15 before it happens.

* Despite how commonly the Freshman 15 is asserted, an Ohio State University study showed that the average college student gains only two to three pounds in their first year. Additionally, it showed that college students did not gain any more weight than non-college students of the same age, and that the only factor that did increase weight gain was heavy drinking.

inexorable (ĭn-ĕk′sər-ə-bəl) 과정이 멈출[변경할] 수 없는, 거침없는::
Impossible to stop, alter, or resist; inevitable: an inexorable fate; an inexorable law of nature.
* [Latin inexōrābilis : in-, not; see in-1 + exōrābilis, pliant (from exōrāre, to prevail upon : ex-, intensive pref.; see ex- + ōrāre, to argue).]

[[_1_0_0_]]
== 1. The Brain-Belly Connection

[[_1_1_1_]]
=== 1. “Built-In Pantries”

[[_1_1_1_]]
==== Warm-Blooded and Smart!

[[_1_1_1_]]
==== The Brain and the Mouth

[[_1_1_1_]]
==== The Importance of Bellies

[[_1_1_1_]]
==== The Third Link in the Brain–Belly Connection

[[_1_1_1_]]
==== Fat Storage

[[_1_1_1_]]
==== Food Addicts!

[[_1_2_2_]]
=== 2. Insulin:The Master Hormone

[[_1_2_2_]]
==== “Sticky” Fat Cells

[[_1_2_2_]]
==== The Operator of Your Fat Cells’ On-Off Switch

[[_1_2_2_]]
==== A Multitasking Hormone

[[_1_2_2_]]
==== “Good” Carbs, “Bad” Carbs

[[_1_2_2_]]
==== The Fat-Storing Trigger That Farmers Depend On

[[_1_2_2_]]
==== Modern Fat Storage Signals—Better Than Anything Mother Nature Ever Devised

[[_1_2_2_]]
==== Jay Cutler’s Secret

[[_1_3_3_]]
=== 3. The Clamor of Hunger—Lessons from Five Diets

[[_1_3_3_]]
==== 1. Calorie-Restricted Low-Fat Diet

[[_1_3_3_]]
==== 2. Calorie-Restricted Higher-Fat Diet

[[_1_3_3_]]
==== 3. Total Starvation Diet

[[_1_3_3_]]
==== 4. Cruise Ship Diet

[[_1_3_3_]]
==== 5. Typical American Diet

[[_1_3_3_]]
==== Let’s Compare

[[_1_3_3_]]
==== Some Important Concepts

[[_1_3_3_]]
==== Making Sense of the Diet Paradoxes

[[_1_4_4_]]
=== 4. Controlling Your Appetite by Feeding Your Brain

[[_1_4_4_]]
==== What Happens When You Eat?

[[_1_4_4_]]
==== An Ideal Scenario: John’s Morning

[[_1_4_4_]]
==== A Not-so-Ideal Scenario: Jane’s Morning

[[_1_4_4_]]
==== What’s the Difference Between These Two Scenarios?

[[_1_4_4_]]
==== Foods That Fool Your Body

[[_1_4_4_]]
==== She Eats Like a Bird and Still Gains Weight!

[[_1_4_4_]]
==== What About Adult-Onset (Type 2) Diabetes?

[[_1_4_4_]]
==== It All Adds Up!

[[_1_5_5_]]
=== 5. Feed Your Brain … or Suffer the Consequences

[[_1_5_5_]]
==== Sophie’s Story

[[_1_5_5_]]
==== Too Much of a Good Thing

[[_1_5_5_]]
==== Effect of Elevated Insulin on the Brain

[[_1_5_5_]]
==== How to Prevent Alzheimer’s Disease

[[_2_0_5_]]
== 2. The Feed Your Brain Lose Your Belly Diet and Activity Program

[[_2_1_6_]]
=== 6. Demonized Fat: Essential for Brain and Body Wellness

[[_2_1_6_]]
==== Eat Fat to Lose Fat?

[[_2_1_6_]]
==== Is There Such a Thing as Healthy Fat?

[[_2_1_6_]]
==== Why Limit Fat?

[[_2_1_6_]]
==== Different Types of Fat

[[_2_1_6_]]
==== The Importance of “Balance”

[[_2_1_6_]]
==== MUFAs

[[_2_1_6_]]
==== Coconut—The Miracle Oil!

[[_2_1_6_]]
==== Ketones and the Brain–Belly Connection

[[_2_1_6_]]
==== Other Sources of Ketones

[[_2_2_7_]]
=== 7. Making the Best Food Choices

[[_2_2_7_]]
==== Benefits of Herbs and Spices

[[_2_3_8_]]
=== 8. Seven-Day Meal Plan and Recipes

[[_2_3_8_]]
==== My Favorite Snack

[[_2_3_8_]]
==== How Many Calories Do You Need?

[[_2_4_9_]]
=== 9. Move It to Lose It

[[_2_4_9_]]
==== A Big Waste of Time?

[[_2_4_9_]]
==== Keep It Simple—Walk

[[_2_4_9_]]
==== Keep It Simple—Train with Weights

[[_2_4_9_]]
==== Keep It Simple—Improve Balance and Coordination

[[_2_4_9_]]
==== Positive Feedback

[[_3_0_9_]]
== 3. You Can Train Your Brain to Lose Your Belly

[[_3_1_10_]]
=== 10. Dealing with the Mind-Body Challenges of Losing Weight

[[_3_1_10_]]
==== The Personal Toll of Being Overweight

[[_3_1_10_]]
==== Get in Touch with Your Body

[[_3_1_10_]]
==== Now for the Hard Part—Dealing with the Emotions

[[_3_1_10_]]
==== Self-Esteem Is Key—Don’t Let Your Weight Define You as a Person!

[[_3_1_10_]]
==== Determine What Is Important in Your Life

[[_3_1_10_]]
==== Work at It, Don’t Get Depressed, and Accept Help from Others

[[_3_2_11_]]
=== 11. Practical Tips to Get You Going

[[_3_2_11_]]
==== Weight-Loss Gems

[[_3_3_12_]]
=== 12. Clinical Trials 101: How to Arrive at Your Weight-Loss Goal Faster

[[_3_3_12_]]
==== Description of the Human Clinical Trial

[[_4_0_12_]]
== Appendix 1. Scientific Research Applied to Dietary Supplements

[[_4_1_13_]]
=== Epidemiology Defined

[[_4_2_14_]]
=== Scientific Research

[[_4_3_15_]]
=== How Scientific Research Applies to Dietary Supplement Trials

[[_4_4_16_]]
=== Scientific Research Components

[[_4_5_17_]]
=== Placebo

[[_4_6_18_]]
=== Types of Studies or Trials

[[_4_7_19_]]
=== Sources

[[_5_0_19_]]
== Appendix 2. Fetal Programming: The Developmental Origins of Adult Disease

[[_6_0_19_]]
== Appendix 3. Suggested Reading

