[[_0_]]
= 자세 교정 억지로 하지 마라
Joy <arbago@gmail.com>
v1.0, 2015-5-14
:icons: font
:sectanchors:
:imagesdir: images
:homepage: http://arbago.com
:toc: macro

toc::[]

[preface]
== 책

자세 교정 억지로 하지 마라, 고이께 요시따까, 2011

[preface]
== 시작하는 글

먼저 바른 지식을 얻어라 그러면 전부 달라질 것이다

근력운동 또한 병들거나 약하게 된 사람들을 위한 것이지 보통 사람들에게는 큰 효과가 없다

올바른 지식을 접하면 그 다음 일은 저절로 풀리는 법이다

바른 호흡은 어디에 어떻게 좋은가?

팔의 힘을 강하게 하면 요통을 예방한다

[[_1_0_0_]]
== 01. 자세를 교정하려면 호흡부터 바꿔라

[[_1_1_1_]]
=== 당신은 얕은 호흡을 하고 있다

얕은 호흡이 우리 건강의 발목을 잡고 있다

세상에는 여러 가지 호흡법이 있고, 책도 많다 +
하지만 호흡법보다 먼저 알아야 할 것이 지금부터 소개할 지식이다 +
이 지식이 여러 가지 어려운 호흡법을 배우는 것보다 훨씬 더 도움이 될 것이다

[[_1_2_2_]]
=== 호흡은 생명활동의 근간

호흡의 깊이가 인간의 생명력을 끌어올려준다

이러한 얕은 호흡에는 단계가 있는데, 심지어 가슴이 전혀 움직이지 않고 호흡하는 사람도 있다

어떤 리유로든 호흡이 얕게 되어서 많든 적든 산소결핍 상태에 있는 사람이 대부분이다

[[_1_3_3_]]
=== 무서운 산소결핍

인간의 신체는 몸으로 들어오는 산소량이 부족하더라도 그것으로 어떻게든 살아가려고 애쓴다 +
모든 조직이나 세포에서 똑같이 산소가 부족하게 되는 현상은 일어나지 않는다 +
우선순위를 정해서 산소를 배분하도록 조정하기 때문이다

병원에서는 '`혈중산소농도`'를 측정해서 산소결핍 여부를 판단하다 +
하지만 그 방법으로는 산소결핍 상태를 확인할 수 없다 +
우리 몸이 산소를 배분하고 조정하는 활동은 현대의학의 눈에는 잘 보이지 않는다

근육이 산소결핍 상태가 되면 유연성이 떨어지고 경직된다 +
이는 혈류를 약화시키고 몸을 차게 만든다

[[_1_4_4_]]
=== 내 호흡을 확인해보자

[[_1_5_5_]]
=== 의식하지 않으면 모르는 것들

촛점을 맞추지 않으면 인식하지 못한다 +
기억 데이타는 남아도 촛을 맞추지 않은 것은 인식하지 않는다 +
의식이 어디를 향하느냐에 따라 사람이 인식하는 것도 완전히 다르게 된다

한 번 바로잡힌 올바른 인식은 계속 살아남는다 +
그러니 이보다 더 편한 건강법도 없다

[[_1_6_6_]]
=== 우리 몸을 바꾸는 심호흡

본인은 오십견이라고 생각했지만 사실은 단순히 근육에 산소가 전달되지 않은 경우였다 +
호흡을 개선하면 오십견이 금방 낫는다는 뜻이 아니라 +
산소결핍으로 인해 근육이 긴장한 상태였던 부분은 금방 해결된다는 것이다

질병에서 회복하려면 시간이 든다. 그 기간을 줄일 수는 있어도, 신체의 기능을 무시하고 기적을 일으킬 수는 없다

[[_1_7_7_]]
=== 운동능력을 향상하는 심호흡

보조근육에 계속 과도한 부담을 가하면 망가진다 +
운동을 하는 본인은 그런 사태를 깨닫지 못한다 +
부상을 입을 정도로 부담을 주지는 않았다고 생각하지만, +
근육이 약하게 된 상태에서에서는 이것마저 과로가 될 수 있다

어쩌면 부상이 잦은 선수는 몸 전체에 산소 공급이 적은 가운데 서로 돌려막다 보니 그렇게 된 것이다

휘발유가 부족한 차는 아무리 일류 정비사가 정비하고 량질의 기름을 넣은들 씽씽 달릴 수 없는 것처럼 말이다

근육 전체가 기능을 회복하면 운동하는 모양, 즉 자세가 달라진다

자세를 개선하면 동작이 아름답게 된다 +
인간은 적절하고 리치에 맞는 자세에서 기능미를 느낀다 +
스포츠 관람은 그런 기능미를 보는 오락으로 성립되었다

일부 스포츠 스타가 신처럼 숭배받는 것은 성적이 좋기 때문이기도 하지만 운동하는 모습에서 아름다움이 느껴지게 되기 때문이다

[[_1_8_8_]]
=== 마음을 안정하는 심호흡

심호흡을 하면 긴장이 풀리고 마음이 안정하게 된다

호흡은 마음과 직접 관련이 있다

[[_1_9_9_]]
=== 흉식호흡과 복식호흡

배에는 공기가 들어가지 않는다 +
공기가 들어가는 곳은 폐뿐이다

[[_1_10_10_]]
=== 전체호흡을 하라

[[_1_11_11_]]
=== 잘못된 생각이 잘못된 자세를 만든다

심장은 몸의 거의 중심에 있다 +
왼쪽 가슴에 있다고 생각해도 심장기능이 떨어지는 일은 없다

모든 장기는 제각기 생존하려는 명확한 목적의식이 있다

잠재의식은 표면의식이 범하는 실수를 하지 않는다 +
심장의 크기나 위치를 착각해서 기능을 떨어뜨리는 멍청한 실수를 하지는 않는다

#호흡근육은 의식으로 움직일 수 있다 +
그래서 잘못된 생각이 악영향을 미친다#

호흡 이외에 잘못된 인식으로 몸의 근육을 사용할 때 문제가 발생한다

[[_2_0_12_]]
== 02. 알면 고칠 수 있는 새우등

근육이 약해서 자세가 나빠진다고 생각하지 않는다 +
일상생활을 정상히 하는 사람이 근력부족으로 자세가 나쁘게 되는 일은 거의 없다

[[_2_1_13_]]
=== 가슴을 펴고 등을 쭉 늘린 자세가 좋은 자세?

구부정한 새우등이 되는 것은 서 있을 때와 앉아 있을 때다 +
자고 있을 때는 새우등이 되지 않는다 +
또 한 가지가 있으니, 바로 무릎으로 서 있을 때다 +
무릎으로 서면 배근이 쭉 펴진다 +
이것을 볼 때 배근과 복근이 약해서 자세가 나빠진다는 설은 설득력이 없다 +
만약 정말로 근력 부족이 원인이라면 무릎으로 섰을 때도 새우등이 될 것이다

무릎으로 선 자세에서 억지로 정강이에 체중을 실어보자 +
대퇴 앞의 근육이 땅길 것이다 +
뼈가 뼈를 자연히 지탱하지 못하고 균형이 깨진 상태가 되어 +
넘어지지 않으려고 근육으로 버티기 때문이다

#좋은 자세는 뼈가 자연스레 서 있는 상태다# +
억지로 근육을 펴서 강제로 만드는 것이 아니다 +
무릎으로 서면 등 근육은 자연히 펴진다 +
#바로 여기에 정답이 있다#

[[_2_2_14_]]
=== 신체를 지탱하는 대퇴골

[[_2_3_15_]]
=== 새우등이 되는 진짜 리유

[[_2_4_16_]]
=== 새우등의 메커니즘

새우등은 '`결과`'가 아니다 +
발바닥의 잘못된 무게중심 때문에 넘어질 것 같은 몸을 지탱하는 '`수단`'이다 +
그런데 수단을 교정해서 자세를 고치려고 해봤짜 잘되기는 어렵다 +
억지로 좋은 자세를 만들려고 하니 몸만 힘들 뿐이다

손가락으로 실을 잡고 진자를 흔드는 모습을 상상해보자 +
사람들의 시선은 진자의 끝을 따라가지 실을 든 손을 향하지는 않는다 +
진자를 움직이는 것은 손이지만 그 움직임은 정말 작다 +
그래서 끝에 있는 진자의 큰 동작이 눈에 들어오면 의식이 그곳에 집중된다 +
#크고 눈에 띄는 현상 앞에 작고 조용한 원인이 가려지는 것이다#

*원인을 바르게 알고 나면 문제를 고치는 것은 어렵지 않다 +
진자를 흔드는 손을 멈추기만 하면 된다 +
단지 그것을 알고 있느냐 그렇지 못하느냐의 차이일 뿐이다*

[[_2_5_17_]]
=== 신기한 무게중심

[[_2_6_18_]]
=== 글쓰기와 컴퓨터 작업이 편한 바른 자세

앞으로 굽었을 때의 상체는 중력에 의해 아래로 당겨지므로 저항하지 않으면 앞으로 넘어진다 +
그것을 방지하려면 근육으로 계속 지탱할 수밖에 없다 +
그때 사용하는 근육은 주로 등이나 목 뒷부분이다 +
그러니 앉아서 장시간 작업을 하면 지치고, 목과 어깨가 결리는 것이 당연하다

에너지는 유한하다 +
나쁜 자세로 쓸데없이 소비하기는 아깝다

[[_2_7_19_]]
=== 일반상식은 그저 다수결일 뿐이다

잘못된 상식::
* 가슴을 펴고 강제로 배근을 곧게 세운다
* 의식해서라도 배근을 펴면 좋은 자세가 만들어진다

일반상식의 무서운 점은 '`정말로 그런 것일까?`'라는 의심을 하기 어렵다는 것이다

내가 중학생일 때는 '`운동 중에는 물을 마시지 않는 것이 좋다`'는 것이 상식이었다 +
하지만 지금은 그것이 잘못되었다는 것이 상식이 되었다 +
물을 마시지 않는 것이 좋다는 이야기에는 애초에 대단한 리유 따위는 존재하지 않았다 +
어디선가 무엇인가 잘못되어 일반상식으로까지 발전했을 뿐이다

아무런 혹실한 근거도 없는 생각이 이런 식으로 일반상식으로까지 성장한다

교정벨트도 근력운동도 같은 선상에 있는 잘못된 인식이다 +
다소의 성과는 있기 때문에 이 역시 잘못되었다는 것을 느끼기가 어렵다

#정강이의 굵은 뼈에 체중을 싣고, +
앚은 때는 좌골에 체중을 싣는다# +
단지 이것만으로 지긋지긋한 새우등이 자동으로 고쳐진다 +
그 원리는 의외로 간단하다

[[_2_8_20_]]
=== 바른 자세로 목 결림, 어깨 결림, 요통이 개선된다

바른자세가 아닐 때 아픈 곳::
* 목
* 어깨
* 등
* 허리

[[_2_9_21_]]
=== 빠르게 걷고 민첩하게 동작할 수 있다

새우등인 자세로 서 있으면 넘어지지 않도록 대퇴의 앞쪽이 긴장한다 +
경사진 길을 내려갈 때도 대퇴의 앞쪽에 힘을 주어 굴러 넘어지지 않도록 한다

대퇴의 앞쪽에 힘을 넣고 버티는 것은 브레이크를 걸고 멈춰 있는 상태와 비슷하다 +
새우등은 브레이크가 걸린 채로 있는 상태라서 당연히 걸음도 느리다

몸을 대퇴의 앞쪽이 지탱하므로 다리를 크게 앞으로 내딛지 못한다 +
그래서 보폭이 좁아지고 +
새우등인 사람은 터벅터벅 걷는 인상을 준다 +
급한 언덕을 내려갈 때 작은 보폭으로 조금씩 브레이크를 거는 행위를 평지에서 하고 있는 셈이다

#바른 자세란 골격에 체중을 잘 맡기고 편안하게 된 상태를 말한다# +
힘이 빠져 있으므로 필요한 근육이 재빨리 반응할 수 있다 +
왠지 무술의 진수 같은 이야기지만, 실제 일상생활에도 통한다

[[_2_10_22_]]
=== 바른 자세에 깃드는 바른 마음

인간은 자기도 모르는 사이에 기분에 맞는 자세를 선택한다

자세는 바른데 융통성이 없는 사람을 관찰해보자 +
분명히 가슴을 펴고 억지로 배근을 세우고 있을 것이다 +
과거의 엄격한 아버지상과 통한다

융통성은 있지만 맺고 끊음이 분명하지 못한 우유부단한 사람은 새우등일 경우가 많다

[[_2_11_23_]]
=== 인생을 바꾸는 올바른 자세

성공하려면 우선 지식이 중요하다

정보는 많을수록 합리하게 사고하게 된다

바른 자세에서는 랭정하고 명료하며 합리한 사고를 하게 된다

어떠한 자세를 하고 있느냐에 따라서 마음 상태도 같이 변한다 +
그러므로 바른 자세는 바른 마음을 의미한다고 할 수 있다

하지만 체중을 싣는 위치를 잘못 안 탓에 나쁜 자세가 기본이 되어 버리는 것은 이런 것들과 다르다 +
잘못된 인식으로 진취성을 잃거나 동기부여가 떨어진다면 인생에 있어서 얼마나 큰 손실인가

[[_3_0_24_]]
== 03. 강하고 우아한 팔을 만드는 법

[[_3_1_25_]]
=== 팔의 뿌리를 파악하라

[[_3_2_26_]]
=== 견갑골을 알면 답이 나온다

[[_3_3_27_]]
=== 견갑골을 마음껏 활용하자!

[[_3_4_28_]]
=== 자유자재로 사용하는 견갑골

[[_3_5_29_]]
=== 견갑골을 사용하면 요통에 걸리지 않는다?

[[_3_6_30_]]
=== 운동능력이 향상된다

[[_3_7_31_]]
=== 견갑골을 의식하면 마음을 전할 수 있다

[[_3_8_32_]]
=== 자각하지 못하는 마음의 움직임

[[_3_9_33_]]
=== 경락과 차크라

[[_4_0_34_]]
== 04. 바르고 힘차게 걷는 법

[[_4_1_35_]]
=== 다리는 어디서 뻗어 나왔나?

[[_4_2_36_]]
=== 견갑골을 의식해 팔을 흔들며 걸어보자

[[_4_3_37_]]
=== 등뼈를 강하게 의식해보자

[[_4_4_38_]]
=== 골반, 호흡, 혈류가 개선된다

[[_4_5_39_]]
=== 상반신과 하반신을 련결해서 의식하자

[[_4_6_40_]]
=== 바른 마음을 부르는 바른 걷기

[[_4_7_41_]]
=== 마음과 동작을 련결하다
