[[_0_]]
= 論語集註
Joy <arbago@gmail.com>
v1.0, 2015-5-20
:icons: font
:sectanchors:
:imagesdir: images
:homepage: http://arbago.com
:toc: macro

toc::[]

[preface]
== 論語集註序說

史記世家曰 孔子名丘 字仲尼 其先宋人 父叔梁紇 母顔氏 以魯襄公二十二年庚戌之歲十一月庚子生孔子於魯昌平縣鄒邑 爲兒嘻戱 常陳俎豆 設禮容 及長爲委吏 料量平 爲司職吏 畜蕃息 適周問禮於老子 旣反而弟子益進 昭公二十五年甲申 孔子年三十五 而昭公奔齊 魯亂 於是適齊 爲高昭子家臣以通乎景公 公欲封以尼谿之田 晏嬰不可 公惑之 孔子遂行反乎魯 定公元年壬辰 孔子年四十三 而季氏疆僭 其臣陽虎作亂專政 故孔子不仕而退 修詩書禮樂 弟子彌衆 九年庚子 孔子年五十一 公山不狃以費畔 季氏召 孔子欲往而卒不行 定公以孔子爲中都宰 一年四方則之 遂爲司空 又爲大司寇 十年辛丑 相定公會齊侯于夾谷 齊人歸魯侵地 十二年癸卯 使仲由爲季氏宰 墮三都 收其甲兵 孟氏不肯墮成 圍之不克 十四年乙巳 孔子年五十六 攝行相事 誅少正卯 與聞國政 三月魯國大治 齊人歸女樂以沮之 季桓子受之 郊又不致膰俎於大夫 孔子行 適衛主於子路妻兄顔濁鄒家 適陳過匡 匡人以爲陽虎而拘之 旣解 還衛主蘧伯玉家 見南子 去適宋 司馬桓魋欲殺之 又去適陳 主司城貞子家 居三歲而反于衛 靈公不能用 晉趙氏家臣佛肹以中牟畔 召孔子 孔子欲往 亦不果 將西見趙簡子 至河而反 又主蘧伯玉家 靈公問陳 不對而行 復如陳 季桓子卒 遺言謂康子 必召孔子 其臣止之 康子乃召冉求 孔子如蔡及葉 楚昭王將以書社地封孔子 令尹子西不可 乃止 又反乎衛 時靈公已卒 衛君輒欲得孔子爲政 而冉求爲季氏 將與齊戰有功 康子乃召孔子 而孔子歸魯 實哀公之十一年丁巳 而孔子年六十八矣 然魯終不能用孔子 孔子亦不求仕 乃叙書傳禮記 刪詩正樂 序易篆繫象說卦文言 弟子蓋三千焉 身通六藝者 七十二人 十四年庚申 魯西狩獲麟 孔子作春秋 明年辛酉 子路死於衛 十六年壬戌四月己丑 孔子卒 年七十三 葬魯城北泗上 弟子皆服心喪三年而去 惟子貢廬於塚上凡六年 孔子生鯉 字伯魚 先卒 伯魚生伋 字子思 作中庸

何氏曰 魯論語二十篇 齊論語別有問王知道 凡二十二篇 其二十篇中 章句頗多於魯論 古論出孔氏壁中 分堯曰下章子張問以爲一篇 有兩子張 凡二十一篇 篇次不與齊魯論同

程子曰 論語之書 成於有子曾子之門人 故其書獨二子以子稱

程子曰 讀論語有讀了全然無事者 有讀了後其中得一兩句喜者 有讀了後知好之者 有讀了後直有不知手之舞之足之蹈之者

程子曰 今人不會讀書 如讀論語 未讀時是此等人 讀了後 又只是此等人 便是不曾讀

程子曰 頤自十七八讀論語 當時已曉文義 讀之愈久 但覺意味深長

論語集註大全卷之一

[_01_]
== 學而第一

此爲書之首篇 故所記多務本之意 乃入道之門 積德之基 學者之先務也. 凡十六章

[_01_01_01_]
=== ○子曰 學而時習之 不亦說乎 (學而-01-01-01)

學之爲言 效也. 人性皆善 而覺有先後 後覺者 必效先覺之所爲 乃可以明善而復其初也. 習 鳥數飛也. 學之不已 如鳥數飛也. 說 喜意也. 旣學而又時時習之 則所學者熟 而中心喜說 其心自不能已矣. 程子曰 習 重習也. 時復思繹 浹洽於中 則說也. 又曰 學者將以行之也. 時習之 則所學者在我 故悅. 謝氏曰 時習者 無時而不習. 坐如尸 坐時習也. 立如齊 立時習也.

[_01_01_02_]
=== 有朋自遠方來 不亦樂乎 (學而-01-01-02)

朋 同類也. 自遠方來 則近者可知. 程子曰 以善及人 而信從者衆. 故可樂. 又曰說在心 樂主發散在外.

[_01_01_03_]
=== 人不知而不慍 不亦君子乎 (學而-01-01-03)

慍 含怒意. 君子 成德之名. 尹氏曰 學在己 知不知在人 何慍之有. 程子曰 雖樂於及人 不見是而無悶 乃所謂君子. 愚謂及人而樂者 順而易. 不知而不慍者 逆而難. 故惟成德者能之. 然德之所以成 亦由學之正 習之熟 說之深而不已焉耳. ○程子曰 樂由說而後得 非樂不足以語君子.

[_01_02_01_]
=== ○有子曰 其爲人也孝弟 而好犯上者鮮矣 不好犯上 而好作亂者 未之有也 (學而-01-02-01)

有子 孔子弟子 名若. 善事父母爲孝 善事兄長爲弟. 犯上 謂干犯在上之人. 鮮 少也. 作亂則爲悖逆爭鬪之事矣. 此言人能孝弟 則其心和順. 少好犯上 必不好作亂也.

[_01_02_02_]
=== 君子 務本 本立而道生 孝弟也者 其爲仁之本與 (學而-01-02-02)

務 專力也. 本 猶根也. 仁者 愛之理 心之德也. 爲仁猶曰行仁. 與者 疑辭 謙退不敢質言也. 言君子凡事專用力於根本 根本旣立 則其道自生 若上文所謂孝弟 乃是爲仁之本 學者務此 則仁道自此而生也. ○程子曰 孝弟 順德也. 故不好犯上 豈復有逆理亂常之事. 德有本 本立則其道充大. 孝弟行於家 而後仁愛及於物 所謂親親而仁民也. 故爲仁以孝弟爲本 論性則以仁爲孝弟之本. 或問孝弟爲仁之本 此是由孝弟可以至仁否. 曰非也. 謂行仁自孝弟始 孝弟 是仁之一事 謂之行仁之本則可 謂是仁之本則不可. 蓋仁是性也 孝弟是用也. 性中只有箇仁義禮智四者而已 曷嘗有孝弟來. 然仁主於愛 愛莫大於愛親 故曰孝弟也者 其爲仁之本與.

[_01_03_01_]
=== ○子曰 巧言令色 鮮矣仁 (學而-01-03-01)

巧 好. 令 善也. 好其言 善其色 致飾於外 務以悅人 則人欲肆而本心之德亡矣. 聖人辭不迫切 專言鮮 則絶無可知. 學者所當深戒也. ○程子曰 知巧言令色之非仁 則知仁矣.

[_01_04_01_]
=== ○曾子曰 吾日三省吾身 爲人謀而不忠乎 與朋友交而不信乎 傳不習乎 (學而-01-04-01)

曾子 孔子弟子 名參字子輿. 盡己之謂忠 以實之謂信. 傳 謂受之於師 習 謂熟之於己. 曾子以此三者 日省其身 有則改之 無則加勉 其自治誠切如此 可謂得爲學之本矣. 而三者之序 則又以忠信爲傳習之本也. ○尹氏曰 曾子守約 故動必求諸身. 謝氏曰 諸子之學 皆出於聖人. 其後愈遠而愈失其眞. 獨曾子之學專用心於內 故傳之無弊. 觀於子思孟子可見矣. 惜乎其嘉言善行不盡傳於世也. 其幸存而未泯者 學者其可不盡心乎.

[_01_05_01_]
=== ○子曰 道千乘之國 敬事而信 節用而愛人 使民以時 (學而-01-05-01)

道 治也. 千乘 諸侯之國 其地可出兵車千乘者也. 敬者 主一無適之謂. 敬事而信者 敬其事而信於民也. 時 謂農隙之時 言治國之要在此五者 亦務本之意也. ○程子曰 此言至淺 然當時諸侯果能此 亦足以治其國矣. 聖人言雖至近 上下皆通 此三言者 若推其極 堯舜之治 亦不過此. 若常人之言近 則淺近而已矣. 楊氏曰 上不敬則下慢 不信則下疑. 下慢而疑 事不立矣. 敬事而信 以身先之也. 易曰 節以制度 不傷財 不害民. 蓋侈用則傷財 傷財必至於害民. 故愛民必先於節用 然使之不以其時 則力本者不獲自盡 雖有愛人之心 而人不被其澤矣. 然此特論其所存而已 未及爲政也. 苟無是心 則雖有政 不行焉. 胡氏曰 凡此數者 又皆以敬爲主. 愚謂五者反復相因 各有次第 讀者宜細推之.

[_01_06_01_]
=== ○子曰 弟子入則孝 出則弟 謹而信 汎愛衆 而親仁 行有餘力 則以學文 (學而-01-06-01)

謹者 行之有常也. 信者 言之有實也. 汎 廣也. 衆 謂衆人. 親 近也. 仁 謂仁者. 餘力 猶言暇日. 以 用也. 文 謂詩書六藝之文. ○程子曰 爲弟子之職 力有餘則學文. 不脩其職而先文 非爲己之學也. 尹氏曰 德行本也 文藝末也. 窮其本末 知所先後 可以入德矣. 洪氏曰 未有餘力而學文 則文滅其質. 有餘力而不學文 則質勝而野. 愚謂力行而不學文 則無以考聖賢之成法 識事理之當然 而所行或出於私意 非但失之於野而已.

[_01_07_01_]
=== ○子夏曰 賢賢易色 事父母能竭其力 事君能致其身 與朋友交 言而有信 雖曰未學 吾必謂之學矣 (學而-01-07-01)

子夏 孔子弟子 姓卜名商. 賢 人之賢而易其好色之心 好善有誠也. 致 猶委也. 委致其身 謂不有其身也. 四者皆人倫之大者 而行之必盡其誠 學求如是而已. 故子夏言有能如是之人 苟非生質之美 必其務學之至. 雖或以爲未嘗爲學 我必謂之已學也. ○游氏曰 三代之學 皆所以明人倫也. 能是四者 則於人倫厚矣. 學之爲道 何以加此. 子夏以文學名 而其言如此 則古人之所謂學者 可知矣. 故學而一篇 大抵皆在於務本. 吳氏曰 子夏之言 其意善矣. 然詞氣之間 抑揚大過 其流之弊 將或至於廢學. 必若上章夫子之言 然後爲無弊也.

[_01_08_01_]
=== ○子曰 君子不重則不威 學則不固 (學而-01-08-01)

重 厚重. 威 威嚴. 固 堅固也. 輕乎外者 必不能堅乎內 故不厚重 則無威嚴而所學亦不堅固也.

[_01_08_02_]
=== 主忠信 (學而-01-08-02)

人不忠信 則事皆無實. 爲惡則易 爲善則難. 故學者必以是爲主焉. ○程子曰 人道唯在忠信 不誠則無物. 且出入無時 莫知其鄕者 人心也. 若無忠信 豈復有物乎.

[_01_08_03_]
=== 無友不如己者 (學而-01-08-03)

無 毋通. 禁止辭也. 友 所以輔仁 不如己則無益而有損.

[_01_08_04_]
=== 過則勿憚改 (學而-01-08-04)

勿 亦禁止之辭. 憚 畏難也. 自治不勇 則惡日長. 故有過則當速改 不可畏難而苟安也. 程子曰 學問之道無他也. 知其不善 則速改以從善而已. ○程子曰 君子自脩之道 當如是也. 游氏曰 君子之道 以威重爲質 而學以成之. 學之道 必以忠信爲主 而以勝己者輔之. 然或吝於改過 則終無以入德 而賢者未必樂告以善道 故以過勿憚改終焉.

[_01_09_01_]
=== ○曾子曰 愼終追遠 民德歸厚矣 (學而-01-09-01)

愼終者 喪盡其禮 追遠者 祭盡其誠. 民德歸厚 謂下民化之 其德亦歸於厚. 蓋終者人之所易忽也 而能謹之. 遠者人之所易忘也 而能追之. 厚之道也. 故以此自爲則己之德厚 下民化之 則其德亦歸於厚也.

[_01_10_01_]
=== ○子禽問於子貢曰 夫子至於是邦也 必聞其政 求之與 抑與之與 (學而-01-10-01)

子禽 姓陳 名亢. 子貢 姓端木 名賜. 皆孔子弟子. 或曰 亢 子貢弟子. 未知孰是. 抑 反語辭.

[_01_10_02_]
=== 子貢曰 夫子溫良恭儉讓以得之 夫子之求之也 其諸異乎 人之求之與 (學而-01-10-02)

溫 和厚也. 良 易直也. 恭 莊敬也. 儉 節制也. 讓 謙遜也. 五者夫子之盛德 光輝接於人者也. 其諸 語辭也. 人 他人也. 言夫子未嘗求之 但其德容如是 故時君敬信 自以其政 就而問之耳 非若他人必求之而後得也. 聖人過化存神之妙 未易窺測. 然卽此而觀 則其德盛禮恭而不願乎外 亦可見矣. 學者所當潛心而勉學也. ○謝氏曰 學者觀於聖人威儀之間 亦可以進德矣. 若子貢亦可謂善觀聖人矣 亦可謂善言德行矣. 今去聖人千五百年 以此五者想見其形容 尙能使人興起 而況於親炙之者乎. 張敬夫曰 夫子至是邦 必聞其政 而未有能委國而授之以政者 蓋見聖人之儀刑而樂告之者 秉彛好德之良心也. 而私欲害之 是以終不能用耳.

[_01_11_01_]
=== ○子曰 父在觀其志 父沒觀其行 三年無改於父之道 可謂孝矣 (學而-01-11-01)

父在 子不得自專 而志則可知. 父沒 然後其行可見 故觀此足以知其人之善惡. 然又必能三年無改於父之道 乃見其孝. 不然 則所行雖善 亦不得爲孝矣. ○尹氏曰 如其道 雖終身無改可也. 如其非道 何待三年. 然則三年無改者 孝子之心有所不忍故也. 游氏曰 三年無改 亦謂在所當改而可以未改者耳.

[_01_12_01_]
=== ○有子曰 禮之用 和爲貴 先王之道 斯爲美 小大由之 (學而-01-12-01)

禮者 天理之節文 人事之儀則也. 和者 從容不迫之意. 蓋禮之爲體雖嚴 然皆出於自然之理 故其爲用 必從容而不迫 乃爲可貴. 先王之道 此其所以爲美 而小事大事 無不由之也,

[_01_12_02_]
=== 有所不行 知和而和 不以禮節之 亦不可行也 (學而-01-12-02)

承上文而言 如此而復有所不行者 以其徒知和之爲貴 而一於和 不復以禮節之 則亦非復禮之本然矣. 所以流蕩忘反 而亦不可行也. ○程子曰 禮勝則離 故禮之用 和爲貴 先王之道以斯爲美 而小大由之. 樂勝則流 故有所不行者 知和而和 不以禮節之 亦不可行. 范氏曰 凡禮之體 主於敬 而其用則以和爲貴. 敬者 禮之所以立也. 和者 樂之所由生也. 若有子可謂達禮樂之本矣. 愚謂嚴而泰 和而節 此理之自然 禮之全體也. 毫釐有差 則失其中正而各倚於一偏 其不可行均矣.

[_01_13_01_]
=== ○有子曰 信近於義 言可復也 恭近於禮 遠恥辱也 因不失其親 亦可宗也 (學而-01-13-01)

信 約信也. 義者 事之宜也. 復 踐言也. 恭 致敬也. 禮 節文也. 因 猶依也. 宗 猶主也. 言約信而合其宜 則言必可踐矣. 致恭而中其節 則能遠恥辱矣. 所依者不失其可親之人 則亦可以宗而主之矣. 此言人之言行交際 皆當謹之於始 而慮其所終. 不然則因仍苟且之間 將有不勝其自失之悔者矣.

[_01_14_01_]
=== ○子曰 君子食無求飽 居無求安 敏於事而愼於言 就有道而正焉 可謂好學也已 (學而-01-14-01)

不求安飽者 志有在而不暇及也. 敏於事者 勉其所不足. 謹於言者 不敢盡其所有餘也. 然猶不敢自是而必就有道之人 以正其是非 則可謂好學矣. 凡言道者 皆謂事物當然之理 人之所共由者也. ○尹氏曰 君子之學能是四者 可謂篤志力行者矣. 然不取正於有道 未免有差 如楊墨學仁義而差者也. 其流至於無父無君 謂之好學可乎.

[_01_15_01_]
=== ○子貢曰 貧而無諂 富而無驕 何如 子曰 可也 未若貧而樂 富而好禮者也 (學而-01-15-01)

諂 卑屈也. 驕 矜肆也. 常人溺於貧富之中 而不知所以自守 故必有二者之病. 無諂無驕 則知自守矣 而未能超乎貧富之外也. 凡曰可者 僅可而有所未盡之辭也. 樂則心廣體胖而忘其貧. 好禮則安處善 樂循理 亦不自知其富矣. 子貢貨殖 蓋先貧後富 而嘗用力於自守者 故以此爲問. 而夫子答之如此 蓋許其所已能 而勉其所未至也.

[_01_15_02_]
=== 子貢曰 詩云 如切如磋 如琢如磨 其斯之謂與 (學而-01-15-02)

詩 衛風淇奧之篇. 言治骨角者 旣切之 而復磋之. 治玉石者 旣琢之 而復磨之. 治之已精而益求其精也. 子貢自以無諂無驕爲至矣 聞夫子之言 又知義理之無窮 雖有得焉 而未可遽自足也. 故引是詩以明之.

[_01_15_03_]
=== 子曰 賜也 始可與言詩已矣 告諸往而知來者 (學而-01-15-03)

往者 其所已言者 來者 其所未言者. ○愚按此章問答 其淺深高下 固不待辨說而明矣. 然不切則磋 無所施 不琢則磨 無所措. 故學者雖不可安於小成 而不求造道之極致 亦不可騖於虛遠 而不察切己之實病也.

[_01_16_01_]
=== ○子曰 不患人之不己知 患不知人也 (學而-01-16-01)

尹氏曰 君子求在我者 故不患人之不己知. 不知人 則是非邪正或不能辨 故以爲患也.

論語集註大全卷之二

[_02_]
== 爲政第二

凡二十四章

[_02_01_01_]
=== ○子曰 爲政以德 譬如北辰 居其所 而衆星共之 (爲政-02-01-01)

政之爲言 正也 所以正人之不正也. 德之爲言 得也 行道而有得於心也. 北辰 北極 天之樞也. 居其所 不動也. 共 向也. 言衆星四面旋繞而歸向之也. 爲政以德 則無爲而天下歸之 其象如此. ○程子曰 爲政以德 然後無爲. 范氏曰 爲政以德 則不動而化 不言而信 無爲而成. 所守者至簡 而能御煩 所處者至靜 而能制動 所務者至寡 而能服衆.

[_02_02_01_]
=== ○子曰 詩三百 一言以蔽之 曰 思無邪 (爲政-02-02-01)

詩三百十一篇 言三百者 擧大數也. 蔽 猶蓋也. 思無邪 魯頌駉篇之辭. 凡詩之言善者可以感發人之善心 惡者可以懲創人之逸志 其用歸於使人得其情性之正而已. 然其言微婉 且或各因一事而發 求其直指全體 則未有若此之明且盡者. 故夫子言詩三百篇 而惟此一言 足以盡蓋其義 其示人之意 亦深切矣. ○程子曰 思無邪者 誠也. 范氏曰 學者必務知要 知要則能守約 守約則足以盡博矣 經禮三百 曲禮三千 亦可以一言以蔽之 曰毋不敬.

[_02_03_01_]
=== ○子曰 道之以政 齊之以刑 民免而無恥 (爲政-02-03-01)

道 猶引導 謂先之也. 政 謂法制禁令也. 齊 所以一之也. 道之而不從者 有刑以一之也. 免而無恥 謂苟免刑罰 而無所羞愧 蓋雖不敢爲惡 而爲惡之心 未嘗亡也.

[_02_03_02_]
=== 道之以德 齊之以禮 有恥且格 (爲政-02-03-02)

禮 謂制度品節也. 格 至也. 言躬行以率之 則民固有所觀感而興起矣. 而其淺深厚薄之不一者 又有禮以一之 則民恥於不善 而又有以至於善也. 一說 格 正也. 書曰 格其非心. ○愚謂 政者爲治之具 刑者 輔治之法. 德禮 則所以出治之本 而德又禮之本也. 此其相爲終始 雖不可以偏廢 然政刑能使民遠罪而已 德禮之效 則有以使民日遷善而不自知. 故治民者 不可徒恃其末 又當深探其本也.

[_02_04_01_]
=== ○子曰吾 十有五而志于學 (爲政-02-04-01)

古者 十五而入大學 心之所之 謂之志. 此所謂學 卽大學之道也. 志乎此 則念念在此 而爲之不厭矣.

[_02_04_02_]
=== 三十而立 (爲政-02-04-02)

有以自立 則守之固 而無所事志矣.

[_02_04_03_]
=== 四十而不惑 (爲政-02-04-03)

於事物之所當然 皆無所疑 則知之明而無所事守矣.

[_02_04_04_]
=== 五十而知天命 (爲政-02-04-04)

天命 卽天道之流行 而賦於物者 乃事物所以當然之故也. 知此則知極其精 而不惑又不足言矣.

[_02_04_05_]
=== 六十而耳順 (爲政-02-04-05)

聲入心通 無所違逆 知之之至 不思而得也.

[_02_04_06_]
=== 七十而從心所欲 不踰矩 (爲政-02-04-06)

從 隨也. 矩 法度之器 所以爲方者也. 隨其心之所欲 而自不過於法度 安而行之 不勉而中也. ○程子曰 孔子生而知者也. 言亦由學而至 所以勉進後人也. 立 能自立於斯道也. 不惑 則無所疑矣. 知天命 窮理盡性也. 耳順 所聞皆通也. 從心所欲不踰矩 則不勉而中矣. 又曰 孔子自言其進德之序如此者 聖人未必然 但爲學者立法 使之盈科而後進 成章而後達耳. 胡氏曰 聖人之敎亦多術 然其要使人不失其本心而已. 欲得此心者 惟志乎聖人所示之學 循其序而進焉. 至於一疵不存 萬理明盡之後 則其日用之間 本心瑩然 隨所意欲 莫非至理. 蓋心卽體 欲卽用. 體卽道 用卽義. 聲爲律 而身爲度矣. 又曰 聖人言此 一以示學者當優游涵泳 不可躐等而進 二以示學者 當日就月將 不可半途而廢也. 愚謂聖人生知安行 固無積累之漸. 然其心未嘗自謂已至此也. 是其日用之間 必有獨覺其進 而人不及知者 故因其近似以自名 欲學者以是爲則 而自勉. 非心實自聖 而姑爲是退託也. 後凡言謙辭之屬 意皆放此.

[_02_05_01_]
=== ○孟懿子問孝 子曰 無違 (爲政-02-05-01)

孟懿子 魯大夫仲孫氏 名何忌. 無違 謂不背於理.

[_02_05_02_]
=== 樊遲御 子告之曰 孟孫問孝於我 我對曰 無違 (爲政-02-05-02)

樊遲 孔子弟子 名須. 御 爲孔子御車也. 孟孫 卽仲孫也. 夫子以懿子未達而不能問 恐其失指 而以從親之令爲孝 故語樊遲以發之.

[_02_05_03_]
=== 樊遲曰 何謂也 子曰 生事之以禮 死葬之以禮 祭之以禮 (爲政-02-05-03)

生事葬祭 事親之始終具矣. 禮 卽理之節文也. 人之事親 自始至終一於禮而不苟 其尊親也至矣. 是時三家僣禮 故夫子以是警之. 然語意渾然 又若不專爲三家發者 所以爲聖人之言也. ○胡氏曰 人之欲孝其親 心雖無窮 而分則有限 得爲而不爲 與不得爲而爲之 均於不孝. 所謂以禮者 爲其所得爲者而已矣.

[_02_06_01_]
=== ○孟武伯問孝 子曰 父母唯其疾之憂 (爲政-02-06-01)

武伯 懿子之子 名彘. 言父母愛子之心 無所不至 唯恐其有疾病 常以爲憂也. 人子體此 而以父母之心爲心 則凡所以守其身者 自不容於不謹矣. 豈不可以爲孝乎. 舊說 人子能使父母不以其陷於不義爲憂 而獨以其疾爲憂 乃可爲孝亦通.

[_02_07_01_]
=== ○子游問孝 子曰 今之孝者 是謂能養 至於犬馬 皆能有養 不敬何以別乎 (爲政-02-07-01)

子游 孔子弟子 姓言 名偃. 養 謂飮食供奉也. 犬馬待人而食 亦若養然. 言人畜犬馬 皆能有以養之. 若能養其親而敬不至 則與養犬馬者何異. 甚言不敬之罪 所以深警之也. ○胡氏曰 世俗事親 能養足矣. 狎恩恃愛 而不知其漸流於不敬 則非小失也. 子游 聖門高弟 未必至此 聖人直恐其愛踰於敬 故以是深警發之也.

[_02_08_01_]
=== ○子夏問孝 子曰 色難 有事弟子服其勞 有酒食 先生饌 曾是以爲孝乎 (爲政-02-08-01)

色難 謂事親之際 惟色爲難也. 食 飯也. 先生 父兄也. 饌 飮食之也. 曾 猶嘗也. 蓋孝子之有深愛者 必有和氣 有和氣者 必有愉色 有愉色者 必有婉容. 故事親之際 惟色爲難耳. 服勞奉養 未足爲孝也. 舊說 承順父母之色爲難 亦通. ○程子曰 告懿子 告衆人者也. 告武伯者 以其人多可憂之事. 子游能養而或失於敬 子夏能直義 而或少溫潤之色 各因其材之高下與其所失而告之 故不同也.

[_02_09_01_]
=== ○子曰 吾與回言終日 不違如愚 退而省其私 亦足以發 回也 不愚 (爲政-02-09-01)

回 孔子弟子 姓顔 字子淵. 不違者 意不相背 有聽受而無問難也. 私 謂燕居獨處 非進見請問之時. 發 謂發明所言之理. 愚聞之師曰 顔子深潛純粹 其於聖人 體段已具. 其聞夫子之言 黙識心融 觸處洞然 自有條理 故終日言但見其不違如愚人而已. 及退省其私 則見其日用動靜語黙之間 皆足以發明夫子之道. 坦然由之而無疑 然後知其不愚也.

[_02_10_01_]
=== ○子曰 視其所以 (爲政-02-10-01)

以 爲也. 爲善者爲君子 爲惡者爲小人.

[_02_10_02_]
=== 觀其所由 (爲政-02-10-02)

觀比視爲詳矣. 由 從也. 事雖爲善 而意之所從來者 有未善焉 則亦不得爲君子矣. 或曰 由 行也. 謂所以行其所爲者也.

[_02_10_03_]
=== 察其所安 (爲政-02-10-03)

察則又加詳矣. 安 所樂也. 所由雖善 而心之所樂者 不在於是 則亦僞耳. 豈能久而不變哉.

[_02_10_04_]
=== 人焉廋哉 人焉廋哉 (爲政-02-10-04)

焉 何也. 廋 匿也. 重言以深明之. ○程子曰 在己者能知言窮理 則能以此察人如聖人也.

[_02_11_01_]
=== ○子曰 溫故而知新 可以爲師矣 (爲政-02-11-01)

溫 尋繹也. 故者 舊所聞. 新者 今所得. 言學能時習舊聞 而每有新得 則所學在我 而其應不窮. 故可以爲人師. 若夫記問之學 則無得於心 而所知有限 故學記譏其不足以爲人師. 正與此意互相發也.

[_02_12_01_]
=== ○子曰 君子不器 (爲政-02-12-01)

器者 各適其用 而不能相通. 成德之士 體無不具 故用無不周 非特爲一才一藝而已.

[_02_13_01_]
=== ○子貢問君子 子曰 先行其言 而後從之 (爲政-02-13-01)

周氏曰 先行其言者 行之於未言之前. 而後從之者 言之於旣行之後. ○范氏曰 子貢之患 非言之艱而行之艱 故告之以此.

[_02_14_01_]
=== ○子曰 君子周而不比 小人比而不周 (爲政-02-14-01)

周 普徧也. 比 偏黨也. 皆與人親厚之意 但周公而比私爾. ○君子小人 所爲不同 如陰陽晝夜 每每相反 然究其所以分 則在公私之際 毫釐之差耳. 故聖人於周比和同驕泰之屬 常對擧而互言之 欲學者察乎兩間 而審其取舍之幾也.

[_02_15_01_]
=== ○子曰 學而不思則罔 思而不學則殆 (爲政-02-15-01)

不求諸心 故昏而無得. 不習其事 故危而不安. ○程子曰 博學 審問 愼思 明辨 篤行五者 廢其一非學也.

[_02_16_01_]
=== ○子曰 攻乎異端 斯害也已 (爲政-02-16-01)

范氏曰 攻 專治也. 故治木石金玉之工曰攻. 異端 非聖人之道 而別爲一端 如楊墨是也. 其率天下至於無父無君 專治而欲精之 爲害甚矣. ○程子曰 佛氏之言 比之楊墨 尤爲近理 所以其害爲尤甚. 學者當如淫聲美色以遠之 不爾則駸駸然入於其中矣.

[_02_17_01_]
=== ○子曰 由誨女知之乎 知之爲知之 不知爲不知 是知也 (爲政-02-17-01)

由 孔子弟子 姓仲 字子路. 子路好勇 蓋有强其所不知以爲知者 故夫子告之曰 我敎女以知之之道乎. 但所知者則以爲知 所不知者則以爲不知 如此則雖或不能盡知 而無自欺之蔽 亦不害其爲知矣. 況由此而求之 又有可知之理乎.

[_02_18_01_]
=== ○子張學干祿 (爲政-02-18-01)

子張 孔子弟子 姓顓孫 名師. 干 求也. 祿 仕者之奉也.

[_02_18_02_]
=== 子曰 多聞闕疑 愼言其餘則寡尤 多見闕殆 愼行其餘則寡悔 言寡尤 行寡悔 祿在其中矣 (爲政-02-18-02)

呂氏曰 疑者 所未信. 殆者 所未安. 程子曰 尤 罪自外至者也. 悔 理自內出者也. 愚謂多聞見者 學之博 闕疑殆者 擇之精. 謹言行者 守之約. 凡言在其中者 皆不求而自至之辭. 言此以救子張之失 而進之也. ○程子曰 脩天爵則人爵至 君子言行能謹 得祿之道也. 子張學干祿 故告之以此 使定其心而不爲利祿動. 若顔閔則無此問矣. 或疑如此亦有不得祿者. 孔子蓋曰 耕也餒在其中 惟理可爲者 爲之而已矣.

[_02_19_01_]
=== ○哀公問曰 何爲則民服 孔子對曰 擧直錯諸枉 則民服 擧枉錯諸直 則民不服 (爲政-02-19-01)

哀公 魯君 名蔣. 凡君問 皆稱孔子對曰者 尊君也. 錯 捨置也. 諸 衆也. 程子曰 擧錯得義 則人心服. ○謝氏曰 好直而惡枉 天下之至情也. 順之則服 逆之則去 必然之理也. 然或無道以照之 則以直爲枉 以枉爲直者多矣. 是以君子大居敬 而貴窮理也.

[_02_20_01_]
=== ○季康子問使民 敬忠以勸 如之何 子曰 臨之以莊則敬 孝慈則忠 擧善而敎不能則勸 (爲政-02-20-01)

季康子 魯大夫 季孫氏 名肥. 莊 謂容貌端嚴也. 臨民以莊 則民敬於己. 孝於親 慈於衆 則民忠於己. 善者擧之 而不能者敎之 則民有所勸 而樂於爲善. ○張敬夫曰 此皆在我所當爲 非爲欲使民敬忠以勸而爲之也. 然能如是 則其應蓋有不期然而然者矣.

[_02_21_01_]
=== ○或謂孔子曰 子奚不爲政 (爲政-02-21-01)

定公初年 孔子不仕 故或人疑其不爲政也.

[_02_21_02_]
=== 子曰 書云孝乎 惟孝友于兄弟 施於有政 是亦爲政 奚其爲爲政 (爲政-02-21-02)

書 周書君陳篇. 書云孝乎者 言書之言孝如此也. 善兄弟曰友. 書言君陳 能孝於親 友於兄弟 又能推廣此心 以爲一家之政 孔子引之 言如此則是亦爲政矣 何必居位乃爲爲政乎. 蓋孔子之不仕 有難以語或人者. 故託此以告之 要之至理亦不外是.

[_02_22_01_]
=== ○子曰 人而無信 不知其可也 大車無輗 小車無軏 其何以行之哉 (爲政-02-22-01)

大車 謂平地任載之車. 輗 轅端橫木 縛軛以駕牛者. 小車 謂田車兵車乘車. 軏 轅端上曲鉤衡以駕馬者. 車無此二者 則不可以行 人而無信 亦猶是也.

[_02_23_01_]
=== ○子張問十世 可知也 (爲政-02-23-01)

陸氏曰 也一作乎. ○王者易姓受命爲一世. 子張問自此以後 十世之事 可前知乎.

[_02_23_02_]
=== 子曰 殷因於夏禮 所損益可知也 周因於殷禮 所損益可知也 其或繼周者 雖百世可知也 (爲政-02-23-02)

馬氏曰 所因 謂三綱五常. 所損益 謂文質三統. 愚按三綱 謂君爲臣綱 父爲子綱 夫爲妻綱. 五常 謂仁義禮智信. 文質 謂夏尙忠 商尙質 周尙文. 三統 謂夏正建寅 爲人統. 商正建丑 爲地統 周正建子 爲天統. 三綱五常 禮之大體 三代相繼 皆因之而不能變. 其所損益 不過文章制度 小過不及之間. 而其已然之迹 今皆可見. 則自今以往 或有繼周而王者 雖百世之遠 所因所革 亦不過此 豈但十世而已乎. 聖人所以知來者 蓋如此. 非若後世讖緯術數之學也. ○胡氏曰 子張之問 蓋欲知來 而聖人言其旣往者以明之也. 夫自修身以至於爲天下 不可一日而無禮. 天敍天秩 人所共由 禮之本也. 商不能改乎夏 周不能改乎商 所謂天地之常經也. 若乃制度文爲 或太過則當損 或不足則當益. 益之損之 與時宜之 而所因者不壞 是古今之通義也. 因往推來 雖百世之遠 不過如此而已矣.

[_02_24_01_]
=== ○子曰 非其鬼而祭之 諂也 (爲政-02-24-01)

非其鬼 謂非其所當祭之鬼. 諂 求媚也.

[_02_24_02_]
=== 見義不爲 無勇也 (爲政-02-24-02)

知而不爲 是無勇也.

論語集註大全卷之三

[_03_]
== 八佾第三

凡二十六章 通前篇末二章 皆論禮樂之事.

[_03_01_01_]
=== ○孔子謂季氏 八佾舞於庭 是可忍也 孰不可忍也 (八佾-03-01-01)

季氏 魯大夫季孫氏也. 佾 舞列也. 天子八 諸侯六 大夫四 士二. 每佾人數如其佾數. 或曰每佾八人. 未詳孰是. 季氏以大夫而僣用天子之禮樂 孔子言其此事 尙忍爲之 則何事不可忍爲. 或曰 忍 容忍也. 蓋深疾之之辭. ○范氏曰 樂舞之數 自上而下 降殺以兩而已. 故兩之間 不可以毫髮僣差也. 孔子爲政 先正禮樂 則季氏之罪 不容誅矣. 謝氏曰 君子於其所不當爲 不敢須臾處 不忍故也. 而季氏忍此矣 則雖弑父與君 亦何所憚而不爲乎.

[_03_02_01_]
=== ○三家者 以雍徹 子曰 相維辟公 天子穆穆 奚取於三家之堂 (八佾-03-02-01)

三家 魯大夫孟孫叔孫季孫之家也. 雍 周頌篇名. 徹 祭畢而收其俎也. 天子宗廟之祭 則歌雍以徹. 是時三家僣而用之. 相 助也. 辟公 諸侯也. 穆穆 深遠之意 天子之容也. 此雍詩之辭 孔子引之 言三家之堂 非有此事 亦何取於此義而歌之乎. 譏其無知妄作 以取僣竊之罪. ○程子曰 周公之功固大矣 皆臣子之分所當爲. 魯安得獨用天子禮樂哉. 成王之賜 伯禽之受 皆非也 其因襲之弊 遂使季氏僣八佾 三家僣雍徹 故仲尼譏之.

[_03_03_01_]
=== ○子曰 人而不仁 如禮何 人而不仁 如樂何 (八佾-03-03-01)

游氏曰 人而不仁 則人心亡矣 其如禮樂何哉. 言雖欲用之而禮樂不爲之用也. ○程子曰 仁者天下之正理 失正理則無序而不和. 李氏曰 禮樂待人而後行. 苟非其人 則雖玉帛交錯 鐘鼓鏗鏘 亦將如之何哉. 然記者序此於八佾雍徹之後 疑其爲僣禮樂者發也.

[_03_04_01_]
=== ○林放問禮之本 (八佾-03-04-01)

林放 魯人. 見世之爲禮者 專事繁文 而疑其本之不在是也 故以爲問.

[_03_04_02_]
=== 子曰 大哉問 (八佾-03-04-02)

孔子以時方逐末 而放獨有志於本 故大其問. 蓋得其本 則禮之全體無不在其中矣.

[_03_04_03_]
=== 禮 與其奢也 寧儉 喪 與其易也 寧戚 (八佾-03-04-03)

易 治也. 孟子曰 易其田疇. 在喪禮 則節文習熟 而無哀痛慘怛之實者也. 戚則一於哀 而文不足矣. 禮貴得中 奢易則過於文 儉戚則不及而質 二者皆未合禮 然凡物之理 必先有質而後有文 則質乃禮之本也. ○范氏曰 夫祭 與其敬不足而禮有餘也 不若禮不足而敬有餘也. 喪 與其哀不足而禮有餘也 不若禮不足而哀有餘也. 禮失之奢 喪失之易 皆不能反本而隨其末故也. 禮奢而備 不若儉而不備之愈也. 喪易而文 不若戚而不文之愈也. 儉者物之質 戚者心之誠. 故爲禮之本. 楊氏曰 禮始諸飮食 故汙尊而杯飮 爲之簠簋籩豆罍爵之飾 所以文之也 則其本儉而已. 喪不可以徑情而直行 爲之衰麻哭踊之數 所以節之也. 則其本戚而已. 周衰 世方以文滅質 而林放獨能問禮之本 故夫子大之 而告之以此.

[_03_05_01_]
=== ○子曰 夷狄之有君 不如諸夏之亡也 (八佾-03-05-01)

吳氏曰 亡 古無字通用 程子曰 夷狄且有君長 不如諸夏之僣亂 反無上下之分也. ○尹氏曰 孔子傷時之亂而歎之也. 無 非實無也. 雖有之不能盡其道爾.

[_03_06_01_]
=== ○季氏旅於泰山 子謂冉有曰 女弗能救與 對曰 不能 子曰 嗚乎 曾謂泰山 不如林放乎 (八佾-03-06-01)

旅 祭名. 泰山 山名在魯地. 禮 諸侯祭封內山川, 季氏祭之 僣也. 冉有 孔子弟子 名求. 時爲季氏宰. 救 謂救其陷於僣竊之罪. 嗚呼 歎辭. 言神不享非禮 欲季氏知其無益而自止 又進林放以厲冉有也. ○范氏曰 冉有從季氏 夫子豈不知其不可告也. 然而聖人不輕絶人 盡己之心 安知冉有之不能救 季氏之不可諫也. 旣不能正 則美林放以明泰山之不可誣 是亦敎誨之道也.

[_03_07_01_]
=== ○子曰 君子無所爭 必也射乎 揖讓而升 下而飮 其爭也君子 (八佾-03-07-01)

揖讓而升者 大射之禮 耦進 三揖而後升堂也. 下而陰 謂射畢揖降 以俟衆耦皆降 勝者乃揖不勝者 升取觶立飮也. 言君子恭遜 不與人爭 惟於射而後有爭. 然其爭也 雍容揖遜乃如此 則其爭也君子 而非若小人之爭也.

必也射乎::
* 군자에게는 다툴거리가 없지만 (군자는 인격이 높은데 싸울거리가 있겠는가), 반드시 해야 할 때가 있는데 활 쏠 때다
* 군자는 다툴거리를 없애야 하는데 (싸우고 다니지 마라), 꼭 그래야 한다면, 활쏘기를 할 때처럼 해야겠지! (례를 갖추어서 다퉈라)

下而飮::
* 내려와서 마신다 (또는 마시게 한다)
* 활쏘기가 끝나고 모두 내려와서 술마시는 절차를 갖는다
* 지면(下) 마신다

[_03_08_01_]
=== ○子夏問曰 巧笑倩兮 美目盼兮 素以爲絢兮 何爲也 (八佾-03-08-01)

此逸詩也. 倩 好口輔也. 盼 目黑白分也. 素 粉地 畵之質也. 絢 采色 畵之飾也. 言人有此倩盼之美質 而又加以華采之飾 如有素地而加采色也. 子夏疑其反謂以素爲飾 故問之.

[_03_08_02_]
=== 子曰 繪事後素 (八佾-03-08-02)

繪事 繪畵之事也. 後素 後於素也. 考工記曰 繪畵之事後素功. 謂先以粉地爲質 而後施五采 猶人有美質 然後可加文飾.

[_03_08_03_]
=== 曰 禮後乎 子曰 起予者商也 始可與言詩已矣 (八佾-03-08-03)

禮必以忠信爲質 猶繪事必以粉素爲先. 起 猶發也. 起予 言能起發我之志意. 謝氏曰 子貢因論學而知詩 子夏因論詩而知學 故皆可與言詩. ○楊氏曰 甘受和 白受采 忠信之人 可以學禮. 苟無其質 禮不虛行. 此繪事後素之說也. 孔子曰 繪事後素 而子夏曰禮後乎 可謂能繼其志矣. 非得之言意之表者 能之乎. 商賜可與言詩者以此 若夫玩心於章句之末 則其爲詩也 固而已矣. 所謂起予 則亦相長之義也.

[_03_09_01_]
=== ○子曰 夏禮 吾能言之 杞不足徵也 殷禮 吾能言之 宋不足徵也 文獻不足故也 足則吾能徵之矣 (八佾-03-09-01)

杞 夏之後. 宋 殷之後. 徵 證也. 文 典籍也. 獻 賢也. 言二代之禮 我能言之 而二國不足取以爲證 以其文獻不足故也. 文獻若足 則我能取之以證吾言矣.

[_03_10_01_]
=== ○子曰 禘自旣灌而往者 吾不欲觀之矣 (八佾-03-10-01)

趙伯循曰 禘 王者之大祭也. 王者旣立始祖之廟 又推始祖所自出之帝 祀之於始祖之廟 而以始祖配之也. 成王以周公有大勳勞 賜魯重祭 故得禘於周公之廟 以文王爲所出之帝 而周公配之 然非禮矣. 灌者 方祭之始 用鬱鬯之酒 灌地以降神也. 魯之君臣 當此之時 誠意未散 猶有可觀 自此以後 則浸以懈怠 而無足觀矣. 蓋魯祭非禮 孔子本不欲觀 至此而失禮之中 又失禮焉 故發此歎也. ○謝氏曰 夫子嘗曰 我欲觀夏道 是故之杞 而不足證也. 我欲觀商道 是故之宋 而不足證也. 又曰 我觀周道 幽厲傷之 吾舍魯何適矣. 魯之郊禘 非禮也. 周公其衰矣. 考之杞宋已如彼 考之當今又如此 孔子所以深歎也.

[_03_11_01_]
=== ○或問禘之說 子曰 不知也 知其說者之於天下也 其如示諸斯乎 指其掌 (八佾-03-11-01)

先王報本追遠之意 莫深於禘 非仁孝誠敬之至 不足以與此 非或人之所及也. 而不王不禘之法 又魯之所當諱者. 故以不知答之. 示 與視同 指其掌. 弟子記夫子言此而自指其掌 言其明且易也. 蓋知禘之說 則理無不明誠無不格 而治天下不難矣. 聖人於此豈眞有所不知也哉.

[_03_12_01_]
=== ○祭如在 祭神如神在 (八佾-03-12-01)

程子曰 祭 祭先祖也. 祭神 祭外神也. 祭先 主於孝 祭神 主於敬. 愚謂此門人記孔子祭祀之誠意.

[_03_12_02_]
=== 子曰 吾不與祭 如不祭 (八佾-03-12-02)

又記孔子之言以明之. 言己當祭之時 或有故不得與 而使他人攝之 則不得致其如在之誠 故雖己祭 而此心缺然 如未嘗祭也. ○范氏曰 君子之祭 七日戒 三日齊 必見所祭者 誠之至也. 是故郊則天神格 廟則人鬼享 皆由己以致之也. 有其誠則有其神 無其誠則無其神 可不謹乎. 吾不與祭如不祭 誠爲實 禮爲虛也.

[_03_13_01_]
=== ○王孫賈問曰 與其媚於奧 寧媚於竈 何謂也 (八佾-03-13-01)

王孫賈 衛大夫. 媚 親順也. 室西南隅爲奧. 竈者 五祀之一 夏所祭也. 凡祭五祀 皆先設主而祭於其所 然後迎尸而祭於奧 略如祭宗廟之儀. 如祀竈 則設主於竈陘 祭畢而更設饌於奧以迎尸也. 故時俗之語 因以奧有常尊 而非祭之主 竈雖卑賤 而當時用事. 喩自結於君 不如阿附權臣也. 賈 衛之權臣 故以此諷孔子.

[_03_13_02_]
=== 子曰 不然 獲罪於天 無所禱也 (八佾-03-13-02)

天 卽理也. 其尊無對 非奧竈之可比也. 逆理則獲罪於天矣 豈媚於奧竈所能禱而免乎. 言但當順理 非特不當媚竈 亦不可媚於奧也. ○謝氏曰 聖人之言 遜而不迫 使王孫賈而知此意 不爲無益. 使其不知 亦非所以取禍.

[_03_14_01_]
=== ○子曰 周監於二代 郁郁乎文哉 吾從周 (八佾-03-14-01)

監 視也. 二代 夏商也. 言其視二代之禮而損益之. 郁郁 文盛貌. ○尹氏曰 三代之禮 至周大備 夫子美其文而從之.

[_03_15_01_]
=== ○子入大廟 每事問 或曰 孰謂鄹人之子知禮乎 入大廟 每事問 子聞之曰 是禮也 (八佾-03-15-01)

大廟 魯周公廟 此蓋孔子始仕之時 入而助祭也. 鄹 魯邑名 孔子父叔梁紇 嘗爲其邑大夫. 孔子自少以知禮聞 故或人因此而譏之. 孔子言是禮者 敬謹之至 乃所以爲禮也. ○尹氏曰 禮者敬而已矣. 雖知亦問 謹之至也. 其爲敬 莫大於此. 謂之不知禮者 豈足以知孔子哉.

[_03_16_01_]
=== ○子曰 射不主皮 爲力不同科 古之道也 (八佾-03-16-01)

射不主皮 鄕射禮文. 爲力不同科 孔子解禮之意如此也. 皮 革也. 布侯而棲革於其中以爲的 所謂鵠也. 科 等也. 古者射以觀德 但主於中 而不主於貫革 蓋以人之力有强弱不同等也. 記曰 武王克商 散軍郊射 而貫革之射息 正謂此也. 周衰禮廢 列國兵爭 復尙貫革 故孔子歎之. ○楊氏曰 中可以學而能 力不可以强而至. 聖人言古之道 所以正今之失.

[_03_17_01_]
=== ○子貢欲去告朔之餼羊 (八佾-03-17-01)

告朔之禮 古者天子常以季冬頒來歲十二月之朔于諸侯. 諸侯受而藏之祖廟 月朔則以特羊告廟請而行之. 餼 生牲也. 魯自文公 始不視朔 而有司猶供此羊 故子貢欲去之.

[_03_17_02_]
=== 子曰 賜也 爾愛其羊 我愛其禮 (八佾-03-17-02)

愛 猶惜也. 子貢蓋惜其無實而妄費 然禮雖廢 羊存猶得以識之而可復焉. 若倂去其羊 則此禮遂亡矣. 孔子所以惜之. ○楊氏曰 告朔 諸侯所以禀命於君親 禮之大者. 魯不視朔矣 然羊存則告朔之名未泯 而其實因可擧 此夫子所以惜之也.

[_03_18_01_]
=== ○子曰 事君盡禮 人以爲諂也 (八佾-03-18-01)

黃氏曰 孔子於事君之禮 非有所加也. 如是而後盡爾. 時人不能 反以爲諂 故孔子言之 以明禮之當然也. ○程子曰 聖人事君盡禮 當時以爲諂. 若他人言之 必曰我事君盡禮 小人以爲諂. 而孔子之言 止於如此 聖人道大德宏 此亦可見.

[_03_19_01_]
=== ○定公問君使臣 臣事君 如之何 孔子對曰 君使臣以禮 臣事君以忠 (八佾-03-19-01)

定公 魯君 名宋. 二者皆理之當然 各欲自盡而已. ○呂氏曰 使臣不患其不忠 患禮之不至. 事君不患其無禮 患忠之不足. 尹氏曰 君臣以義合者也. 故君使臣以禮 則臣事君以忠.

[_03_20_01_]
=== ○子曰 關雎樂而不淫 哀而不傷 (八佾-03-20-01)

關雎 周南國風詩之首篇也. 淫者 樂之過 而失其正者也. 傷者 哀之過 而害於和者也. 關雎之詩 言后妃之德宜配君子. 求之未得 則不能無寤寐反側之憂. 求而得之 則宜其有琴瑟鐘鼓之樂. 蓋其憂雖深 而不害於和 其樂雖盛 而不失其正. 故夫子稱之如此 欲學者玩其辭審其音 而有以識其性情之正也.

[_03_21_01_]
=== ○哀公問社於宰我 宰我對曰 夏后氏以松 殷人以栢 周人以栗 曰 使民戰栗 (八佾-03-21-01)

宰我 孔子弟子 名予. 三代之社不同者 古者立社各樹其土之所宜木 以爲主也. 戰栗 恐懼貌. 宰我又言周所以用栗之意如此. 豈以古者戮人於社 故附會其說與.

[_03_21_02_]
=== 子聞之曰 成事不說 遂事不諫 旣往不咎 (八佾-03-21-02)

遂事 謂事雖未成 而勢不能已者. 孔子以宰我所對 非立社之本意 又啓時君殺伐之心 而其言已出 不可復救 故歷言此以深責之 欲使謹其後也. ○尹氏曰 古者各以所宜木名其社 非取義於木也. 宰我不知而妄對 故夫子責之.

[_03_22_01_]
=== ○子曰 管仲之器小哉 (八佾-03-22-01)

管仲 齊大夫 名夷吾 相桓公 覇諸侯. 器小 言其不知聖賢大學之道 故局量褊淺 規模卑狹 不能正身脩德 以致主於王道.

[_03_22_02_]
===  或曰 管仲儉乎 曰 管氏有三歸 官事不攝 焉得儉 (八佾-03-22-02)

或人 蓋疑器小之爲儉. 三歸 臺名 事見說苑. 攝 兼也. 家臣不能具官 一人常兼數事. 管仲不然 皆言其侈.

[_03_22_03_]
=== 然則管仲知禮乎 曰 邦君樹塞門 管氏亦樹塞門 邦君爲兩君之好有反坫 管氏亦有反坫 管氏而知禮 孰不知禮 (八佾-03-22-03)

或人又疑不儉爲知禮. 屛 謂之樹. 塞 猶蔽也. 設屛於門 以蔽內外也. 好 謂好會. 坫 在兩楹之間 獻酬飮畢 則反爵於其上. 此皆諸侯之禮 而管仲僣之 不知禮也. ○愚謂 孔子譏管仲之器小 其旨深矣. 或人不知 而疑其儉 故斥其奢 以明其非儉. 或又疑其知禮 故又斥其僣 以明其不知禮. 蓋雖不復明言小器之所以然 而其所以小者 於此亦可見矣. 故程子曰 奢而犯禮 其器之小可知. 蓋器大則自知禮而無此失矣. 此言當深味也. 蘇氏曰 自修身正家以及於國 則其本深 其及者遠 是謂大器. 揚雄所謂大器猶規矩準縄 先自治而後治人者 是也. 管仲三歸反坫 桓公內嬖六人 而覇天下 其本固已淺矣. 管仲死 桓公薨 天下不復宗齊. 楊氏曰 夫子大管仲之功 而小其器 蓋非王佐之才 雖能合諸侯正天下 其器不足稱也. 道學不明 而王覇之略 混爲一途 故聞管仲之器小 則疑其爲儉 以不儉告之 則又疑其知禮. 蓋世方以詭遇爲功 而不知爲之範 則不悟其小宜矣.

[_03_23_01_]
=== ○子語魯大師樂 曰 樂其可知也 始作翕如也 從之純如也 皦如也 繹如也 以成 (八佾-03-23-01)

語 告也. 大師 樂官名. 時音樂廢缺 故孔子敎之. 翕 合也. 從 放也. 純 和也. 皦 明也. 繹 相續不絶也. 成 樂之一終也. ○謝氏曰 五音六律不具 不足以言樂. 翕如 言其合也. 五音合矣 淸濁高下如五味之相濟而後和 故曰純如. 合而和矣 欲其無相奪倫 故曰皦如. 然豈宮自宮 而商自商乎 不相反而相連如貫珠可也. 故曰繹如也 以成.

[_03_24_01_]
=== ○儀封人請見曰 君子之至於斯也 吾未嘗不得見也 從者見之 出曰 二三子何患於喪乎 天下之無道也久矣 天將以夫子爲木鐸 (八佾-03-24-01)

儀 衛邑. 封人 掌封疆之官. 蓋賢而隱於下位者也. 君子 謂當時賢者 至此皆得見之 自言其平日不見絶於賢者 而求以自通也. 見之 謂通使得見. 喪 謂失位去國. 禮曰 喪欲速貧是也. 木鐸 金口木舌 施政敎時所振以警衆者也. 言亂極當治 天必將使夫子得位設敎 不久失位也. 封人一見夫子 而遽以是稱之 其得於觀感之間者深矣. 或曰 木鐸所以徇于道路 言天使夫子失位 周流四方 以行其敎 如木鐸之徇于道路也.

[_03_25_01_]
=== ○子謂韶 盡美矣 又盡善也 謂武 盡美矣 未盡善也 (八佾-03-25-01)

韶 舜樂. 武 武王樂. 美者 聲容之盛. 善者 美之實也. 舜紹堯致治 武王伐紂救民 其功一也. 故其樂皆盡美. 然舜之德 性之也. 又以揖遜而有天下. 武王之德 反之也. 又以征誅而得天下. 故其實有不同者. ○程子曰 成湯放桀 惟有慙德. 武王亦然. 故未盡善. 堯舜湯武 其揆一也. 征伐非其所欲 所遇之時然爾.

[_03_26_01_]
=== ○子曰 居上不寬 爲禮不敬 臨喪不哀 吾何以觀之哉 (八佾-03-26-01)

居上 主於愛人 故以寬爲本. 爲禮 以敬爲本 臨喪 以哀爲本. 旣無其本 則以何者而觀其所行之得失哉.

論語集註大全卷之四

[_04_]
== 里仁第四

凡二十六章

[_04_01_01_]
=== ○子曰 里仁爲美 擇不處仁 焉得知 (里仁-04-01-01)

里有仁厚之俗爲美 擇里而不居於是焉 則失其是非之本心 而不得爲知矣.

[_04_02_01_]
=== ○子曰 不仁者 不可以久處約 不可以長處樂 仁者安仁 知者利仁 (里仁-04-02-01)

約 窮困也. 利 猶貪也. 蓋深知篤好 而必欲得之也. 不仁之人 失其本心 久約必濫 久樂必淫 惟仁者則安其仁 而無適不然 知者則利於仁 而不易所守. 蓋雖深淺之不同 然皆非外物所能奪矣. ○謝氏曰 仁者心無內外遠近精粗之間. 非有所存 而自不亡. 非有所理 而自不亂. 如目視而耳聽 手持而足行也. 知者謂之有所見則可 謂之有所得則未可. 有所存斯不亡 有所理斯不亂 未能無意也. 安仁則一 利仁則二. 安仁者 非顔閔以上 去聖人爲不遠 不知此味也. 諸子雖有卓越之才 謂之見道不惑則可 然未免於利之也.

[_04_03_01_]
=== ○子曰 惟仁者 能好人 能惡人 (里仁-04-03-01)

惟之爲言獨也. 蓋無私心 然後好惡當於理. 程子所謂得其公正是也. ○游氏曰 好善而惡惡 天下之同情. 然人每失其正者 心有所繫而不能自克也. 惟仁者無私心 所以能好惡也.

[_04_04_01_]
=== ○子曰 苟志於仁矣 無惡也 (里仁-04-04-01)

苟 誠也 志者 心之所之也. 其心誠在於仁 則必無爲惡之事矣. ○楊氏曰 苟志於仁 未必無過擧也. 然而爲惡則無矣.

[_04_05_01_]
=== ○子曰 富與貴 是人之所欲也 不以其道得之 不處也 貧與賤 是人之所惡也 不以其道得之 不去也 (里仁-04-05-01)

不以其道得之 謂不當得而得之. 然於富貴則不處 於貧賤則不去. 君子之審富貴 而安貧賤也 如此.

[_04_05_02_]
=== 君子去仁 惡乎成名 (里仁-04-05-02)

言君子所以爲君子 以其仁也. 若貪富貴而厭貧賤 則是自離其仁而無君子之實矣 何所成其名乎.

[_04_05_03_]
=== 君子無終食之間違仁 造次必於是 顚沛必於是 (里仁-04-05-03)

終食者 一飯之頃. 造次 急遽苟且之時. 顚沛 傾覆流離之際. 蓋君子之不去乎仁如此 不但富貴貧賤取舍之間而已也. ○言君子爲仁 自富貴貧賤取舍之間 以至於終食造次顚沛之頃 無時無處而不用其力也. 然取舍之分明 然後存養之功密 存養之功密 則其取舍之分益明矣.

[_04_06_01_]
=== ○子曰 我未見好仁者 惡不仁者 好仁者 無以尙之 惡不仁者 其爲仁矣 不使不仁者加乎其身 (里仁-04-06-01)

夫子自言未見好仁者惡不仁者 蓋好仁者眞知仁之可好 故天下之物無以加之. 惡不仁者 眞知不仁之可惡 故其所以爲仁者 必能絶去不仁之事 而不使少有及於其身. 此皆成德之事 故難得而見之也.

[_04_06_02_]
=== 有能一日用其力於仁矣乎 我未見力不足者 (里仁-04-06-02)

言好仁惡不仁者 雖不可見 然或有人果能一旦奮然用力於仁 則我又未見其力有不足者. 蓋爲仁在己 欲之則是. 而志之所至 氣必至焉. 故仁雖難能 而至之亦易也.

[_04_06_03_]
=== 蓋有之矣 我未之見也 (里仁-04-06-03)

蓋 疑辭. 有之 謂有用力而力不足者. 蓋人之氣質不同 故疑亦容或有此昏弱之甚 欲進而不能者. 但我偶未之見耳. 蓋不敢終以爲易 而又歎人之莫肯用力於仁也. ○此章言仁之成德 雖難其人 然學者苟能實用其力 則亦無不可至之理. 但用力而不至者 今亦未見其人焉. 此夫子所以反覆而歎息之也.

[_04_07_01_]
=== ○子曰 人之過也 各於其黨 觀過 斯知仁矣 (里仁-04-07-01)

黨 類也. 程子曰 人之過也 各於其類. 君子常失於厚 小人常失於薄. 君子過於愛 小人過於忍. 尹氏曰 於此觀之 則人之仁不仁可知矣. ○吳氏曰 後漢吳祐謂掾以親故 受汙辱之名 所謂觀過知仁是也. 愚按此亦但言人雖有過 猶可卽此而知其厚薄 非謂必俟其有過 而後賢否可知也.

[_04_08_01_]
=== ○子曰 朝聞道 夕死可矣 (里仁-04-08-01)

道者 事物當然之理. 苟得聞之 則生順死安 無復遺恨矣. 朝夕所以甚言其時之近. ○程子曰 言人不可以不知道 苟得聞道 雖死可也. 又曰 皆實理也. 人知而信者爲難 死生亦大矣. 非誠有所得 豈以夕死爲可乎.

[_04_09_01_]
=== ○子曰 士志於道 而恥惡衣惡食者 未足與議也 (里仁-04-09-01)

心欲求道 而以口體之奉不若人爲恥 其識趣之卑陋甚矣 何足與議於道哉. ○程子曰 志於道 而心役乎外 何足與議也.

[_04_10_01_]
=== ○子曰 君子之於天下也 無適也 無莫也 義之與比 (里仁-04-10-01)

適 專主也. 春秋傳曰 吾誰適從 是也. 莫 不肯也. 比 從也. ○謝氏曰 適 可也. 莫 不可也. 無可無不可 苟無道以主之 不幾於猖狂自恣乎. 此佛老之學 所以自謂心無所住而能應變 而卒得罪於聖人也. 聖人之學不然 於無可無不可之間 有義存焉. 然則君子之心 果有所倚乎.

[_04_11_01_]
=== ○子曰 君子懷德 小人懷土 君子懷刑 小人懷惠 (里仁-04-11-01)

懷 思念也. 懷德 謂存其固有之善. 懷土 謂溺其所處之安. 懷刑 謂畏法 懷惠 謂貪利. 君子小人趣向不同 公私之間而已矣. ○尹氏曰 樂善惡不善 所以爲君子. 苟安務得所以爲小人.

[_04_12_01_]
=== ○子曰 放於利而行 多怨 (里仁-04-12-01)

孔氏曰 放 依也. 多怨 謂多取怨. ○程子曰 欲利於己 必害於人 故多怨.

[_04_13_01_]
=== ○子曰 能以禮讓爲國乎 何有 不能以禮讓爲國 如禮何 (里仁-04-13-01)

讓者 禮之實也. 何有 言不難也. 言有禮之實以爲國 則何難之有. 不然 則其禮文雖具 亦且無如之何矣 而況於爲國乎.

[_04_14_01_]
=== ○子曰 不患無位 患所以立 不患莫己知 求爲可知也 (里仁-04-14-01)

所以立 謂所以立乎其位者. 可知 謂可以見知之實. ○程子曰 君子求其在己者而已矣.

[_04_15_01_]
=== ○子曰 參乎 吾道一以貫之 曾子曰 唯 (里仁-04-15-01)

參乎者 呼曾子之名而告之. 貫 通也. 唯者 應之速而無疑者也. 聖人之心 渾然一理 而泛應曲當 用各不同. 曾子於其用處 蓋已隨事精察 而力行之. 但未知其體之一爾 夫子知其眞積力久 將有所得 是以呼而告之. 曾子果能黙契其指 卽應之速而無疑也.

[_04_15_02_]
=== 子出 門人問曰 何謂也 曾子曰 夫子之道 忠恕而已矣 (里仁-04-15-02)

盡己之謂忠 推己之謂恕 而已矣者 竭盡而無餘之辭也. 夫子之一理 渾然而泛應曲當 譬則天地之至誠無息 而萬物各得其所也. 自此之外 固無餘法 而亦無待於推矣. 曾子有見於此而難言之 故借學者盡己推己之目以著明之 欲人之易曉也. 蓋至誠無息者 道之體也 萬殊之所以一本也. 萬物各得其所者 道之用也 一本之所以萬殊也. 以此觀之 一以貫之之實 可見矣. 或曰 中心爲忠 如心爲恕 於義亦通. ○程子曰 以己及物 仁也. 推己及物 恕也. 違道不遠是也. 忠恕一以貫之 忠者天道 恕者人道. 忠者無妄 恕者所以行乎忠也. 忠者體 恕者用 大本 達道也. 此與違道不遠異者 動以天爾. 又曰 維天之命 於穆不已 忠也. 乾道變化 各正性命 恕也. 又曰 聖人敎人各因其才. 吾道一以貫之 惟曾子爲能達此 孔子所以告之也. 曾子告門人曰 夫子之道 忠恕而已矣 亦猶夫子之告曾子也. 中庸所謂忠恕違道不遠 斯乃下學上達之義.

[_04_16_01_]
=== ○子曰 君子喩於義 小人喩於利 (里仁-04-16-01)

喩 猶曉也. 義者 天理之所宜 利者 人情之所欲. ○程子曰 君子之於義 猶小人之於利也 惟其深喩 是以篤好. 楊氏曰 君子有舍生而取義者 以利言之 則人之所欲無甚於生 所惡無甚於死 孰肯舍生而取義哉. 其所喩者義而已 不知利之爲利故也. 小人反是.

[_04_17_01_]
=== ○子曰 見賢思齊焉 見不賢而內自省也 (里仁-04-17-01)

思齊者 冀己亦有是善. 內自省者 恐己亦有是惡. ○胡氏曰 見人之善惡不同 而無不反諸身者 則不徒羨人而甘自棄 不徒責人而忘自責矣.

[_04_18_01_]
=== ○子曰 事父母幾諫 見志不從 又敬不違 勞而不怨 (里仁-04-18-01)

此章與內則之言相表裏. 幾 微也. 微諫 所謂父母有過 下氣怡色 柔聲以諫也. 見志不從 又敬不違 所謂諫若不入 起敬起孝 悅則復諫也. 勞而不怨 所謂與其得罪於鄕黨州閭 寧孰諫. 父母怒不悅 而撻之流血 不敢疾怨 起敬起孝也.

[_04_19_01_]
=== ○子曰 父母在 不遠遊 遊必有方 (里仁-04-19-01)

遠遊 則去親遠而爲日久 定省曠而音問疎 不惟己之思親不置 亦恐親之念我不忘也. 遊必有方 如己告云之東 則不敢更適西 欲親必知己之所在而無憂 召己則必至而無失也. 范氏曰 子能以父母之心爲心 則孝矣.

[_04_20_01_]
=== ○子曰 三年無改於父之道 可謂孝矣 (里仁-04-20-01)

胡氏曰 已見首篇 此蓋復出而逸其半也.

[_04_21_01_]
=== ○子曰 父母之年 不可不知也 一則以喜 一則以懼 (里仁-04-21-01)

知 猶記憶也. 常知父母之年 則旣喜其壽 又懼其衰 而於愛日之誠自有不能已者.

[_04_22_01_]
=== ○子曰 古者言之不出 恥躬之不逮也 (里仁-04-22-01)

言古者 以見今之不然. 逮 及也. 行不及 言可恥之甚. 古者所以不出其言 爲此故也. ○范氏曰 君子之於言也 不得已而後出之. 非言之難 而行之難也. 人惟其不行也 是以輕言之. 言之如其所行 行之如其所言 則出諸其口 必不易矣.

[_04_23_01_]
=== ○子曰 以約失之者鮮矣 (里仁-04-23-01)

謝氏曰 不侈然以自放之謂約. 尹氏曰 凡事約則鮮失 非止謂儉約也.

[_04_24_01_]
=== ○子曰 君子欲訥於言而敏於行 (里仁-04-24-01)

謝氏曰 放言易 故欲訥. 力行難 故欲敏. ○胡氏曰 自吾道一貫至此十章 疑皆曾子門人所記也.

[_04_25_01_]
=== ○子曰 德不孤 必有隣 (里仁-04-25-01)

隣 猶親也. 德不孤立 必以類應. 故有德者 必有其類從之 如居之有隣也.

[_04_26_01_]
=== ○子游曰 事君數 斯辱矣 朋友數 斯疏矣 (里仁-04-26-01)

程子曰 數 煩數也. 胡氏曰 事君諫不行則當去 導友善不納則當止. 至於煩瀆 則言者輕聽者厭矣. 是以求榮而反辱 求親而反疏也. 范氏曰 君臣朋友 皆以義合 故其事同也.

論語集註大全卷之五

[_05_]
== 公冶長第五

此篇皆論古今人物 賢否得失 蓋格物窮理之一端也 凡二十七章. 胡氏以爲 疑多子貢之徒所記云 .

[_05_01_01_]
=== ○子謂公冶長 可妻也 雖在縲絏之中 非其罪也 以其子妻之 (公冶長-05-01-01)

公冶長 孔子弟子. 妻 爲之妻也. 縲 黑索也. 絏 攣也. 古者 獄中以黑色拘攣罪人. 長之爲人無所考 而夫子稱其可妻 其必有以取之矣. 又言其人雖嘗陷於縲絏之中 而非其罪 則固無害於可妻也. 夫有罪無罪 在我而已 豈以自外至者爲榮辱哉.

[_05_01_02_]
=== 子謂南容 邦有道不廢 邦無道 免於刑戮 以其兄之子妻之 (公冶長-05-01-02)

南容 孔子弟子 居南宮 名縚又名适 字子容 諡敬叔 孟懿子之兄也. 不廢 言必見用也. 以其謹於言行 故能見用於治朝 免禍於亂世也. 事又見第十一篇. ○或曰 公冶長之賢 不及南容 故聖人以其子妻長 而以兄子妻容 蓋厚於兄而薄於己也. 程子曰 此以己之私心 窺聖人也. 凡人避嫌者 皆內不足也. 聖人自至公 何避嫌之有. 況嫁女必量其才而求配 尤不當有所避也. 若孔子之事 則其年之長幼 時之先後 皆不可知. 惟以爲避嫌則大不可. 避嫌之事 賢者且不爲 況聖人乎.

[_05_02_01_]
=== ○子謂子賤 君子哉若人 魯無君子者 斯焉取斯 (公冶長-05-02-01)

子賤 孔子弟子 姓宓 名不齊. 上斯 斯此人. 下斯 斯此德. 子賤蓋能尊賢取友以成其德者 故夫子旣歎其賢 而又言若魯無君子 則此人何所取以成此德乎. 因以見魯之多賢也. ○蘇氏曰 稱人之善 必本其父兄師友 厚之至也.

[_05_03_01_]
=== ○子貢問曰 賜也何如 子曰 女器也 曰何器也 曰瑚璉也 (公冶長-05-03-01)

器者 有用之成材. 夏曰瑚 商曰璉 周曰簠簋. 皆宗廟盛黍稷之器 而飾以玉 器之貴重而華美者也. 子貢見孔子以君子許子賤 故以己爲問. 而孔子告之以此 然則子貢雖未至於不器 其亦器之貴者歟.

[_05_04_01_]
=== ○或曰 雍也 仁而不佞 (公冶長-05-04-01)

雍 孔子弟子 姓冉 字仲弓. 佞 口才也. 仲弓爲人重厚簡黙 而時人以佞爲賢 故美其優於德 而病其短於才也.

[_05_04_02_]
=== 子曰 焉用佞 禦人以口給 屢憎於人 不知其仁 焉用佞 (公冶長-05-04-02)

禦 當也. 猶應答也. 給 辨也. 憎 惡也. 言何用佞乎. 佞人所以應答人者 但以口取辨而無情實 徒多爲人所憎惡爾. 我雖未知仲弓之仁 然其不佞 乃所以爲賢 不足以爲病也. 再言焉用佞 所以深曉之. ○或疑仲弓之賢 而夫子不許其仁 何也. 曰仁道至大 非全體而不息者 不足以當之. 如顔子亞聖 猶不能無違於三月之後 況仲弓雖賢 未及顔子. 聖人固不得而輕許之也.

[_05_05_01_]
=== ○子使漆雕開仕 對曰 吾斯之未能信 子說 (公冶長-05-05-01)

漆雕開 孔子弟子 字子若. 斯 指此理而言. 信 謂眞知其如此 而無毫髮之疑也. 開自言未能如此 未可以治人 故夫子說其篤志. ○程子曰 漆雕開已見大意 故夫子說之. 又曰 古人見道分明 故其言如此. 謝氏曰 開之學無可考 然聖人使之仕 必其材可以仕矣. 至於心術之微 則一毫不自得 不害其爲未信. 此聖人所不能知 而開自知之. 其材可以仕 而其器不安於小成 他日所就 其可量乎. 夫子所以說之也.

[_05_06_01_]
=== ○子曰 道不行 乘桴浮于海 從我者 其由與 子路聞之喜 子曰 由也好勇過我 無所取材 (公冶長-05-06-01)

桴 筏也. 程子曰 浮海之歎 傷天下之無賢君也. 子路勇於義 故謂其能從己 皆假設之言耳. 子路以爲實然 而喜夫子之與己 故夫子美其勇 而譏其不能裁度事理 以適於義也.

[_05_07_01_]
=== ○孟武伯問 子路仁乎 子曰 不知也 (公冶長-05-07-01)

子路之於仁 蓋日月至焉者 或在或亡 不能必其有無 故以不知告之.

[_05_07_02_]
=== 又問 子曰 由也 千乘之國 可使治其賦也 不知其仁也 (公冶長-05-07-02)

賦 兵也. 古者以田賦出兵 故謂兵爲賦. 春秋傳所謂悉索敞賦是也. 言子路之才可見者如此 仁則不能知也.

[_05_07_03_]
=== 求也何如 子曰 求也 千室之邑 百乘之家 可使爲之宰也 不知其仁也 (公冶長-05-07-03)

千室 大邑. 百乘 卿大夫之家. 宰 邑長 家臣之通號.

[_05_07_04_]
=== 赤也何如 子曰 赤也 束帶立於朝 可使與賓客言也 不知其仁也 (公冶長-05-07-04)

赤 孔子弟子 姓公西 字子華.

[_05_08_01_]
=== ○子謂子貢曰 女與回也 孰愈 (公冶長-05-08-01)

愈 勝也.

[_05_08_02_]
=== 對曰 賜也 何敢望回 回也 聞一以知十 賜也聞一以知二 (公冶長-05-08-02)

一 數之始. 十 數之終. 二者 一之對也. 顔子明睿所照 卽始而見終. 子貢推測而知 因此而識彼. 無所不說 告往知來 是其驗矣.

[_05_08_03_]
=== 子曰 弗如也 吾與女 弗如也 (公冶長-05-08-03)

與 許也. ○胡氏曰 子貢方人 夫子旣語以不暇 又問其與回孰愈 以觀其自知之如何. 聞一知十 上知之資 生知之亞也. 聞一知二 中人以上之資 學而知之之才也. 子貢平日 以己方回 見其不可企及 故喩之如此. 夫子以其自知之明 而又不難於自屈 故旣然之 又重許之 此其所以終聞性與天道 不特聞一知二而已也.

[_05_09_01_]
=== ○宰予晝寢 子曰 朽木不可雕也 糞土之墻 不可杇也 於予與何誅 (公冶長-05-09-01)

晝寢 謂當晝而寐. 朽 腐也. 雕 刻畵也. 杇 鏝也. 言其志氣昏惰 敎無所施也. 與 語辭. 誅 責也. 言不足責 乃所以深責之.

[_05_09_02_]
=== 子曰 始吾於人也 聽其言而信其行 今吾於人也 聽其言而觀其行 於予與改是 (公冶長-05-09-02)

宰予能言而行不逮 故孔子自言於予之事而改此失 亦以重警之也. 胡氏曰 子曰 疑衍文 不然則非一日之言也. ○范氏曰 君子之於學 惟日孜孜 斃而後已 惟恐其不及也. 宰予晝寢 自棄孰甚焉. 故夫子責之. 胡氏曰 宰予不能以志帥氣 居然而倦 是宴安之氣勝 儆戒之志惰也. 古之聖賢 未嘗不以懈惰荒寧爲懼 勤勵不息自彊. 此孔子所以深責宰予也. 聽言觀行 聖人不待是而後能 亦非緣此而盡疑學者 特因此立敎以警群弟子 使謹於言而敏於行耳.

[_05_10_01_]
=== ○子曰 吾未見剛者 或對曰 申棖 子曰 棖也慾 焉得剛 (公冶長-05-10-01)

剛 堅彊不屈之意 最人所難能者 故夫子歎其未見. 申棖 弟子姓名. 慾 多嗜慾也. 多嗜慾 則不得爲剛矣. ○程子曰 人有慾則無剛 剛則不屈於慾. 謝氏曰 剛與慾正相反 能勝物之謂剛 故常伸於萬物之上. 爲物揜之謂慾 故常屈於萬物之下. 自古有志者少 無志者多 宜夫子之未見也. 棖之慾不可知 其爲人得非悻悻自好者乎. 故或者疑以爲剛 然不知此其所以爲慾耳.

[_05_11_01_]
=== ○子貢曰 我不欲人之加諸我也 吾亦欲無加諸人 子曰 賜也 非爾所及也 (公冶長-05-11-01)

子貢言 我所不欲人加於我之事 我亦不欲以此加之於人 此仁者之事 不待勉强 故夫子以爲非子貢所及. ○程子曰 我不慾人之加諸我 吾亦欲無加諸人 仁也. 施諸己而不願 亦勿施於人 恕也. 恕則子貢或能勉之 仁則非所及矣. 愚謂無者自然而然 勿者 禁止之謂. 此所以爲仁恕之別.

[_05_12_01_]
=== ○子貢曰 夫子之文章 可得而聞也 夫子之言性與天道 不可得而聞也 (公冶長-05-12-01)

文章 德之見乎外者. 威儀文辭皆是也. 性者 人所受之天理. 天道者 天理自然之本體 其實一理也. 言夫子之文章日見乎外 固學者所共聞. 至於性與天道 則夫子罕言之 而學者有不得聞者. 蓋聖門敎不躐等 子貢至是始得聞之而歎其美也. ○程子曰 此子貢聞夫子之至論 而歎美之言也.

[_05_13_01_]
=== ○子路有聞 未之能行 唯恐有聞 (公冶長-05-13-01)

前所聞者 旣未及行 故恐復有所聞 而行之不給也. ○范氏曰 子路聞善 勇於必行 門人自以爲弗及也. 故著之. 若子路 可謂能用其勇矣.

[_05_14_01_]
=== ○子貢問曰 孔文子 何以謂之文也 子曰 敏而好學 不恥下問 是以謂之文也 (公冶長-05-14-01)

孔文子 衛大夫 名圉. 凡人性敏者 多不好學. 位高者 多恥下問. 故諡法有以勤學好問爲文者 蓋亦人所難也. 孔圉得諡爲文 以此而已. ○蘇氏曰 孔文子使太叔疾出其妻而妻之 疾通於初妻之娣. 文子怒 將攻之 訪於仲尼 仲尼不對 命駕而行 疾奔宋. 文子使疾弟遺室孔姞. 其爲人如此 而諡曰文 此子貢之所以疑而問也. 孔子不沒其善 言能如此 亦足以爲文矣 非經天緯地之文也.

[_05_15_01_]
=== ○子謂子産 有君子之道四焉 其行己也恭 其事上也敬 其養民也惠 其使民也義 (公冶長-05-15-01)

子産 鄭大夫公孫僑. 恭 謙遜也. 敬 謹恪也. 惠 愛利也. 使民義 如都鄙有章 上下有服 田有封洫 廬井有伍之類. ○吳氏曰 數其事而責之者 其所善者多也. 臧文仲不仁者三 不知者三 是也. 數其事而稱之者 猶有所未至也 子産有君子之道四焉 是也. 今或以一言蓋一人 一事蓋一時 皆非也.

[_05_16_01_]
=== ○子曰 晏平仲 善與人交 久而敬之 (公冶長-05-16-01)

晏平仲 齊大夫 名嬰. 程子曰 人交久則敬衰 久而能敬 所以爲善.

[_05_17_01_]
=== ○子曰 臧文仲 居蔡 山節藻梲 何如其知也 (公冶長-05-17-01)

臧文仲 魯大夫臧孫氏 名辰. 居 猶藏也. 蔡 大龜也. 節 柱頭斗栱也. 藻 水草名. 梲 梁上短柱也. 蓋爲藏龜之室 而刻山於節 畵藻於梲也. 當時以文仲爲知 孔子言其不務民義 而諂瀆鬼神如此 安得爲知 春秋傳所謂作虛器 卽此事也. ○張子曰 山節藻梲爲藏龜之室 祀爰居之義 同歸於不知宜矣.

[_05_18_01_]
=== ○子張問曰 令尹子文 三仕爲令尹 無喜色 三已之 無慍色 舊令尹之政 必以告新令尹 何如 子曰 忠矣 曰 仁矣乎 曰 未知 焉得仁 (公冶長-05-18-01)

令尹 官名 楚上卿執政者也. 子文姓鬪 名穀於菟. 其爲人也 喜怒不形 物我無間 知有其國 而不知有其身 其忠盛矣. 故子張疑其仁 然其所以三仕三已而告新令尹者 未知其皆出於天理而無人欲之私也. 是以夫子但許其忠 而未許其仁也.

[_05_18_02_]
=== 崔子弑齊君 陳文子有馬十乘 棄而違之 至於他邦 則曰 猶吾大夫崔子也 違之 之一邦 則又曰猶吾大夫崔子也 違之 何如 子曰 淸矣 曰 仁矣乎 曰 未知 焉得仁 (公冶長-05-18-02)

崔子 齊大夫 名杼. 齊君 莊公 名光. 陳文子 亦齊大夫 名須無. 十乘 四十匹也. 違 去也. 文子潔身去亂 可謂淸矣 然未知其心果見義理之當然 而能脫然無所累乎 抑不得已於利害之私 而猶未免於怨悔也. 故夫子特許其淸 而不許其仁. 愚聞之師曰 當理而無私心則仁矣. 今以是而觀二子之事 雖其制行之高 若不可及. 然皆未有以見其必當於理 而眞無私心也. 子張未識仁體 而悅於苟難 遂以小者信其大者 夫子之不許也 宜哉. 讀者於此 更以上章不知其仁 後篇仁則吾不知之語 幷與三仁夷齊之事觀之 則彼此交盡 而仁之爲義可識矣. 今以他書考之 子文之相楚 所謀者無非僣王猾夏之事 文子之仕齊 旣失正君討賊之義 又不數歲而復反於齊焉 則其不仁亦可見矣.

[_05_19_01_]
=== ○季文子三思而後行 子聞之曰 再 斯可矣 (公冶長-05-19-01)

季文子 魯大夫 名行父. 每事必三思而後行 若使晉而求遭喪之禮以行 亦其一事也. 斯 語辭. 程子曰 爲惡之人 未嘗知有思 有思則爲善矣. 然至於再則已審 三則私意起而反惑矣. 故夫子譏之. ○愚按季文子慮事如此 可謂詳審而宜無過擧矣. 而宣公簒立 文子乃不能討 反爲之使齊而納賂焉 豈非程子所謂私意起而反惑之驗歟 是以君子務窮理而貴果斷 不徒多思之爲尙.

[_05_20_01_]
=== ○子曰 甯武子 邦有道則知 邦無道則愚 其知可及也 其愚不可及也 (公冶長-05-20-01)

寗武子 衛大夫 名兪. 按春秋傳 武子仕衛 當文公成公之時. 文公有道 而武子無事可見此其知之可及也. 成公無道 至於失國 而武子周旋其間 盡心竭力 不避艱險 凡其所處 皆智巧之士所深避而不肯爲者 而能卒保其身以濟其君 此其愚之不可及也. ○程子曰 邦無道 能沈晦以免患 故曰不可及也. 亦有不當愚者 比干是也.

[_05_21_01_]
=== ○子在陳曰 歸與歸與 吾黨之小子狂簡 斐然成章 不知所以裁之 (公冶長-05-21-01)

此孔子周流四方 道不行而思歸之歎也. 吾黨小子 指門人之在魯者. 狂簡 志大而略於事也. 斐 文貌. 成章 言其文理成就 有可觀者. 裁 割正也. 夫子初心 欲行其道於天下 至是而知其終不用也. 於是始欲成就後學 以傳道於來世 又不得中行之士 而思其次. 以爲狂士志意高遠 猶或可與進於道也. 但恐其過中失正 而或陷於異端耳. 故欲歸而裁之也.

[_05_22_01_]
=== ○子曰 伯夷叔齊 不念舊惡 怨是用希 (公冶長-05-22-01)

伯夷叔齊 孤竹君之二子 孟子稱其不立於惡人之朝 不與惡人言 與鄕人立 其冠不正 望望然去之 若將浼焉. 其介如此 宜若無所容矣. 然其所惡之人 能改卽止 故人亦不甚怨之也. ○程子曰 不念舊惡 此淸者之量. 又曰 二子之心 非夫子孰能知之.

[_05_23_01_]
=== ○子曰 孰謂微生高直 或乞醯焉 乞諸其鄰而與之 (公冶長-05-23-01)

微生姓 高名 魯人 素有直名者. 醯 醋也. 人來乞時 其家無有 故乞諸鄰家以與之. 夫子言此 譏其曲意徇物 掠美市恩 不得爲直也. ○程子曰 微生高所枉雖小 害直爲大. 范氏曰 是曰是 非曰非 有謂有 無謂無 曰直. 聖人觀人 於其一介之取予 而千駟萬鍾從可知焉. 故以微事斷之 所以敎人不可不謹也.

[_05_24_01_]
=== ○子曰 巧言 令色 足恭 左丘明恥之 丘亦恥之 匿怨而友其人 左丘明恥之 丘亦恥之 (公冶長-05-24-01)

足 過也. 程子曰 左丘明 古之聞人也. 謝氏曰 二者之可恥 有甚於穿窬也. 左丘明恥之 其所養可知矣. 夫子自言丘亦恥之 蓋竊比老彭之意 又以深戒學者 使察乎此而立心以直也.

[_05_25_01_]
=== ○顔淵季路侍 子曰 盍各言爾志 (公冶長-05-25-01)

盍 何不也.

[_05_25_02_]
=== 子路曰 願車馬 衣輕裘 與朋友共 敝之而無憾 (公冶長-05-25-02)

衣 服之也. 裘 皮服. 敝 壞也. 憾 恨也.

[_05_25_03_]
=== 顔淵曰 願無伐善 無施勞 (公冶長-05-25-03)

伐 誇也. 善 謂有能. 施 亦張大之意. 勞 謂有功. 易曰 勞而不伐 是也. 或曰 勞 勞事也. 勞事非己所欲 故亦不欲施之於人 亦通.

[_05_25_04_]
=== 子路曰 願聞子之志 子曰 老者安之 朋友信之 少者懷之 (公冶長-05-25-04)

老者 養之以安. 朋友 與之以信. 少者 懷之以恩. 一說 安之 安我也 信之 信我也 懷之 懷我也 亦通. ○程子曰 夫子安仁 顔淵不違仁 子路求仁. 又曰 子路顔淵孔子之志 皆與物共者也. 但有小大之差爾. 又曰 子路勇於義者 觀其志豈可以勢利拘之哉 亞於浴沂者也. 顔子不自私己 故無伐善. 知同於人. 故無施勞. 其志可謂大矣. 然未免於有意也. 至於夫子 則與天地之化工 付與萬物 而己不勞焉. 此聖人之所爲也 今夫覊靮以御馬 而不以制牛. 人皆知覊靮之作在乎人 而不知覊靮之生由於馬. 聖人之化 亦猶是也. 先觀二子之言 後觀聖人之言 分明天地氣象. 凡看論語 非但欲理會文字 須要識得聖賢氣象.

[_05_26_01_]
=== ○子曰 已矣乎 吾未見能見其過 而內自訟者也 (公冶長-05-26-01)

已矣乎者 恐其終不得見而歎之也. 內自訟者 口不言而心自咎也. 人有過而能自知者 鮮矣. 知過而能內自訟者 爲尤鮮. 能內自訟則其悔悟深切 而能改必矣. 夫子自恐終不得見而歎之 其警學者深矣.

[_05_27_01_]
=== ○子曰 十室之邑 必有忠信如丘者焉 不如丘之好學也 (公冶長-05-27-01)

十室 小邑也. 忠信 如聖人生質之美者也. 夫子生知 而未嘗不好學 故言此以勉人. 言美質易得 至道難聞 學之至則可以爲聖人 不學則不免爲鄕人而已 可不勉哉.

論語集註大全卷之六

[_06_]
== 雍也第六

凡二十八章 篇內第十四章以前 大意與前篇同.

[_06_01_01_]
=== ○子曰 雍也 可使南面 (雍也-06-01-01)

南面者 人君聽治之位. 言仲弓 寬洪簡重 有人君之度也.

[_06_01_02_]
=== 仲弓問子桑佰子 子曰 可也簡 (雍也-06-01-02)

子桑伯子 魯人. 胡氏以爲疑卽莊周所稱子桑戶者 是也. 仲弓以夫子許己南面 故問伯子如何. 可者 僅可而有所未盡之辭 簡者 不煩之謂.

[_06_01_03_]
=== 仲弓曰 居敬而行簡 以臨其民 不亦可乎 居簡而行簡 無乃大簡乎 (雍也-06-01-03)

言自處以敬則中有主 而自治嚴 如是而行簡以臨民 則事不煩而民不擾 所以爲可. 若先自處以簡 則中無主而自治疎矣. 而所行又簡 豈不失之大簡 而無法度之可守乎. 家語記伯子不衣冠而處 夫子譏其欲同人道於牛馬. 然則伯子蓋大簡者 而仲弓疑夫子之過許與.

[_06_01_04_]
=== 子曰 雍之言然 (雍也-06-01-04)

仲弓蓋未喩夫子可字之意 而其所言之理有黙契焉者 故夫子然之. ○程子曰 子桑伯子之簡雖可取 而未盡善 故夫子云可也. 仲弓因言內主於敬而簡 則爲要直. 內存乎簡而簡 則爲疎略. 可謂得其旨矣. 又曰 居敬則心中無物 故所行自簡. 居簡則先有心於簡 而多一簡字矣 故曰大簡.

[_06_02_01_]
=== ○哀公問弟子 孰爲好學 孔子對曰 有顔回者好學 不遷怒 不貳過 不幸短命死矣 今也則亡 未聞好學者也 (雍也-06-02-01)

遷 移也. 貳 復也. 怒於甲者不移於乙 過於前者不復於後. 顔子克己之功 至於如此 可謂眞好學矣. 短命者 顔子三十二而卒也. 旣云今也則亡 又言未聞好學者 蓋深惜之 又以見眞好學者之難得也. ○程子曰 顔子之怒在物不在己 故不遷. 有不善未嘗不知 知之未嘗復行 不貳過也. 又曰 喜怒在事 則理之當喜怒者也. 不在血氣則不遷 若舜之誅四凶也. 可怒在彼 己何與焉. 如鑑之照物 姸媸在彼 隨物應之而已 何遷之有. 又曰 如顔子地位 豈有不善. 所謂不善 只是微有差失. 纔差失 便能知之. 纔知之 便更不萌作. 張子曰 慊於己者不使萌於再. 或曰 詩書六藝 七十子非不習而通也. 而夫子獨稱顔子爲好學 顔子之所好 果何學歟. 程子曰 學以至乎聖人之道也. 學之道奈何 曰天地儲精 得五行之秀者爲人. 其本也眞而精 其未發也 五性具焉 曰仁義禮智信. 形旣生矣 外物觸其形 而動於中矣. 其中動 而七情出焉 曰喜怒哀懼愛惡欲. 情旣熾而益蕩 其性鑿矣. 故覺者約其情使合於中 正其心養其性而已. 然必先明諸心知所往 然後力行以求至焉. 若顔子之非禮勿視聽言動 不遷怒貳過者 則其好之篤 而學之得其道也. 然其未至於聖人者 守之也 非化之也. 假之以年 則不日而化矣. 今人乃謂聖本生知 非學可至 而所以爲學者 不過記誦文辭之間 其亦異乎顔子之學矣.

[_06_03_01_]
=== ○子華使於齊 冉子爲其母請粟 子曰 與之釜 請益 曰 與之庾 冉子與之粟五秉 (雍也-06-03-01)

子華 公西赤也. 使爲孔子使也. 釜 六斗四升. 庾 十六斗. 秉 十六斛.

[_06_03_02_]
=== 子曰 赤之適齊也乘肥馬 衣輕裘 吾聞之也 君子周急不繼富 (雍也-06-03-02)

乘肥馬衣輕裘 言其富也. 急 窮迫也. 周者 補不足. 繼者 續有餘.

[_06_03_03_]
=== 原思爲之宰 與之粟九百 辭 (雍也-06-03-03)

原思 孔子弟子 名憲. 孔子爲魯司寇時 以思爲宰. 粟 宰之祿也. 九百 不言其量 不可考.

[_06_03_04_]
=== 子曰 毋 以與爾鄰里鄕黨乎 (雍也-06-03-04)

毋 禁止辭. 五家爲鄰 二十五家爲里 萬二千五百家爲鄕 五百家爲黨. 言常祿不當辭 有餘自可推之以周貧乏. 蓋鄰里鄕黨 有相周之義. ○程子曰 夫子之使子華 子華之爲夫子使 義也. 而冉有乃爲之請 聖人寬容 不欲直拒人 故與之少 所以示不當與也. 請益而與之亦少 所以示不當益也. 求未達 而自與之多 則己過矣. 故夫子非之. 蓋赤苟至乏 則夫子必自周之 不待請矣. 原思爲宰 則有常祿 思辭其多 故又敎以分諸鄰里之貧者. 蓋亦莫非義也. 張子曰 於斯二者 可見聖人之用財矣.

[_06_04_01_]
=== ○子謂仲弓曰 犁牛之子 騂且角 雖欲勿用 山川其舍諸 (雍也-06-04-01)

犁 雜文. 騂 赤色. 周人尙赤 牲用騂. 角 角周正中犧牲也. 用 用以祭也. 山川 山川之神也. 言人雖不用 神必不舍也. 仲弓父賤而行惡 故夫子以此譬之. 言父之惡 不能廢其子之善 如仲弓之賢 自當見用於世也. 然此論仲弓云爾 非與仲弓言也. ○范氏曰 以瞽叟爲父而有舜 以鯀爲父而有禹 古之聖賢 不係於世類 尙矣. 子能改父之過 變惡以爲美 則可謂孝矣.

[_06_05_01_]
=== ○子曰 回也 其心三月不違仁 其餘 則日月至焉而已 (雍也-06-05-01)

三月 言其久. 仁者 心之德. 心不違仁者 無私欲而有其德也. 日月至焉者 或日一至焉 或月一至焉. 能造其域而不能久也. ○程子曰 三月 天道小變之節 言其久也. 過此則聖人矣. 不違仁 只是無纖毫私欲. 少有私欲 便是不仁. 尹氏曰 此顔子於聖人 未達一間者也 若聖人則渾然無間斷矣. 張子曰 始學之要 當知三月不違 與日月至焉 內外賓主之辨 使心意勉勉循循而不能已 過此幾非在我者.

[_06_06_01_]
=== ○季康子問仲由 可使從政也與 子曰 由也果 於從政乎何有 曰賜也 可使從政也與 曰 賜也達 於從政乎何有 曰 求也可使從政也與 曰求也藝 於從政乎何有 (雍也-06-06-01)

從政 謂爲大夫. 果 有決斷. 達 通事理. 藝 多才能. ○程子曰 季康子問三子之才 可以從政乎 夫子答以各有所長. 非惟三子 人各有所長 能取其長 皆可用也.

[_06_07_01_]
=== ○季氏使閔子騫 爲費宰 閔子騫曰 善爲我辭焉 如有復我者 則吾必在汶上矣 (雍也-06-07-01)

閔子騫 孔子弟子 名損. 費 季氏邑. 汶 水名 在齊南魯北竟上. 閔子不欲臣季氏 令使者善爲己辭 言若再來召我 則當去之齊. ○程子曰 仲尼之門 能不仕大夫之家者 閔子曾子數人而已. 謝氏曰 學者能少知內外之分 皆可以樂道而忘人之勢. 況閔子得聖人爲之依歸 彼其視季氏不義之富貴不啻犬彘 又從而臣之 豈其心哉. 在聖人則有不然者 蓋居亂邦見惡人 在聖人則可 自聖人以下 剛則必取禍 柔則必取辱. 閔子豈不能早見而豫待之乎 如由也不得其死 求也爲季氏附益 夫豈其本心哉. 蓋旣無先見之知 又無克亂之才故也. 然則閔子其賢乎.

[_06_08_01_]
=== ○伯牛有疾 子問之 自牖執其手 曰 亡之命矣夫 斯人也 而有斯疾也 斯人也 而有斯疾也 (雍也-06-08-01)

伯牛 孔子弟子 姓冉 名耕. 有疾 先儒以爲癩也. 牖 南牖也. 禮 病者居北牖下 君視之則遷於南牖下 使君得以南面視己. 時伯牛家以此禮尊孔子 孔子不敢當 故不入其室 而自牖執其手 蓋與之永訣也. 命 謂天命 言此人不應有此疾 而今乃有之 是乃天之所命也. 然則非其不能謹疾而有以致之 亦可見矣. ○侯氏曰 伯牛以德行稱亞於顔閔 故其將死也 孔子尤痛惜之.

[_06_09_01_]
=== ○子曰 賢哉回也 一簞食 一瓢飮 在陋巷 人不堪其憂 回也不改其樂 賢哉 回也 (雍也-06-09-01)

簞 竹器. 食 飯也. 瓢 瓠也. 顔子之貧如此 而處之泰然 不以害其樂 故夫子再言賢哉回也 以深歎美之. ○程子曰 顔子之樂 非樂簞瓢陋巷也. 不以貧窶累其心 而改其所樂也. 故夫子稱其賢. 又曰 簞瓢陋巷非可樂 蓋自有其樂爾. 其字當玩味 自有深意. 又曰 昔受學於周茂叔 每令尋仲尼顔子樂處. 所樂何事. 愚按 程子之言 引而不發 蓋欲學者深思而自得之 今亦不敢妄爲之說. 學者但當從事於博文約禮之誨 以至於欲罷不能而竭其才 則庶乎有以得之矣.

[_06_10_01_]
=== ○冉求曰 非不說子之道 力不足也 子曰 力不足者 中道而廢 今女畫 (雍也-06-10-01)

力不足者 欲進而不能. 畫者 能進而不欲. 謂之畫者 如畫地以自限也. ○胡氏曰 夫子稱顔回不改其樂 冉求聞之 故有是言. 然使求說夫子之道 誠如口之說芻豢 則必將盡力以求之 何患力之不足哉. 畫而不進 則日退而已矣. 此冉求之所以局於藝也.

[_06_11_01_]
=== ○子謂子夏曰 女爲君子儒 無爲小人儒 (雍也-06-11-01)

儒 學者之稱. 程子曰 君子儒爲己 小人儒爲人. ○謝氏曰 君子小人之分 義與利之而已. 然所謂利者 豈必殖貨財之謂 以私滅公 適己自便 凡可以害天理者 皆利也. 子夏文學雖有餘 然意其遠者大者 或昧焉. 故夫子語之以此.

[_06_12_01_]
=== ○子游爲武城宰 子曰 女得人焉爾乎 曰 有澹臺滅明者 行不由徑 非公事 未嘗至於偃之室也 (雍也-06-12-01)

武城 魯下邑. 澹臺姓. 滅明名. 字子羽. 徑 路之小而捷者. 公事 如飮射讀法之類. 不由徑則動必以正 而無見小欲速之意可知. 非公事不見邑宰 則其有以自守而無枉己徇人之私可見矣. ○楊氏曰 爲政以人才爲先 故孔子以得人爲問. 如滅明者 觀其二事之小 而其正大之情可見矣. 後世有不由徑者 人必以爲迂. 不至其室 人必以爲簡. 非孔氏之徒 其孰能知而取之. 愚謂 持身以滅明爲法 則無苟賤之羞. 取人以子游爲法 則無邪媚之惑.

[_06_13_01_]
=== ○子曰 孟之反不伐 奔而殿 將入門 策其馬 曰 非敢後也 馬不進也 (雍也-06-13-01)

孟之反 魯大夫 名側. 胡氏曰 反卽莊周所稱孟子反者 是也. 伐 誇功也. 奔 敗走也. 軍後曰殿. 策 鞭也. 戰敗而還 以後爲功. 反奔而殿 故以此言自揜其功也. 事在哀公十一年. ○謝氏曰 人能操無欲上人之心 則人欲日消 天理日明 而凡可以矜己誇人者 皆無足道矣. 然不知學者欲上人之心 無時而忘也. 若孟之反可以爲法矣.

[_06_14_01_]
=== ○子曰 不有祝鮀之佞 而有宋朝之美 難乎免於今之世矣 (雍也-06-14-01)

祝 宗廟之官 鮀 衛大夫 字子魚 有口才. 朝 宋公子 有美色. 言衰世好諛悅色 非此難免 蓋傷之也.

[_06_15_01_]
=== ○子曰 誰能出不由戶 何莫由斯道也 (雍也-06-15-01)

言人不能出不由戶 何故乃不由此道邪. 怪而歎之之辭也. ○洪氏曰 人知出必由戶 而不知行必有道 非道遠人 人自遠爾.

[_06_16_01_]
=== ○子曰 質勝文則野 文勝質則史 文質彬彬 然後君子 (雍也-06-16-01)

野 野人 言鄙略也. 史 掌文書 多聞習事 而誠或不足也. 彬彬 猶班班 物相雜而適均之貌. 言學者當損有餘補不足 至於成德 則不期然而然矣. ○楊氏曰 文質不可以相勝. 然質之勝文 猶之甘可以受和. 白可以受采也. 文勝而至於滅質 則其本亡矣. 雖有文將安施乎. 然則與其史也 寧野.

[_06_17_01_]
=== ○子曰 人之生也直 罔之生也幸而免 (雍也-06-17-01)

程子曰 生理本直. 罔 不直也. 而亦生者 幸而免耳.

[_06_18_01_]
=== ○子曰 知之者 不如好之者 好之者 不如樂之者 (雍也-06-18-01)

尹氏曰 知之者 知有此道也. 好之者 好而未得也. 樂之者 有所得而樂之也. ○張敬夫曰 譬之五穀 知者 知其可食者也. 好者 食而嗜之者也. 樂者 嗜之而飽者也. 知而不能好 則是知之未至也. 好之而未及於樂 則是好之未至也. 此古之學者 所以自彊而不息者與.

[_06_19_01_]
=== ○子曰 中人以上 可以語上也 中人以下 不可以語上也 (雍也-06-19-01)

語 告也. 言敎人者 當隨其高下而告語之 則其言易入 而無躐等之弊也. ○張敬夫曰 聖人之道 精粗雖無二致 但其施敎則必因其材而篤焉. 蓋中人以下之質 驟而語之太高 非惟不能以入 且將妄意躐等而有不切於身之弊 亦終於下而已矣. 故就其所及而語之 是乃所以使之切問近思 而漸進於高遠也.

[_06_20_01_]
=== ○樊遲問知 子曰 務民之義 敬鬼神而遠之 可謂知矣 問仁 曰 仁者先難而後獲 可謂仁矣 (雍也-06-20-01)

民 亦人也. 獲 謂得也. 專用力於人道之所宜 而不惑於鬼神之不可知 知者之事也. 先其事之所難 而後其效之所得 仁者之心也. 此必因樊遲之失而告之. ○程子曰 人多信鬼神惑也. 而不信者 又不能敬. 能敬能遠 可謂知矣. 又曰 先難克己也. 以所難爲先 而不計所獲 仁也. 呂氏曰 當務爲急 不求所難知. 力行所知 不憚所難爲.

[_06_21_01_]
=== ○子曰 知者樂水 仁者樂山 知者動 仁者靜 知者樂 仁者壽 (雍也-06-21-01)

樂 喜好也. 知者達於事理而周流無滯 有似於水 故樂水. 仁者安於義理而厚重不遷 有似於山 故樂山. 動靜以體言 樂壽以效言也. 動而不括故樂 靜而有常故壽. ○程子曰 非體仁知之深者 不能如此形容之.

[_06_22_01_]
=== ○子曰 齊一變 至於魯 魯一變 至於道 (雍也-06-22-01)

孔子之時 齊俗急功利 喜夸詐 乃覇政之餘習. 魯則重禮敎 崇信義 猶有先王之遺風焉. 但人亡政息 不能無廢墜耳. 道則先王之道也. 言二國之政俗有美惡 故其變而之道有難易. ○程子曰 夫子之時 齊强魯弱 孰不以爲齊勝魯也. 然魯猶存周公之法制 齊由桓公之覇 爲從簡尙功之治 太公之遺法變易盡矣. 故一變乃能至魯. 魯則脩擧廢墜而已 一變則至於先王之道也. 愚謂二國之俗 惟夫子爲能變之 而不得試. 然因其言以考之 則其施爲緩急之序 亦略可見矣.

[_06_23_02_]
=== ○子曰 觚不觚 觚哉觚哉 (雍也-06-23-02)

觚 棱也. 或曰酒器. 或曰木簡. 皆器之有棱者也. 不觚者 蓋當時失其制 而不爲棱也. 觚哉觚哉 言不得爲觚也. ○程子曰 觚而失其形制 則非觚也. 擧一器而天下之物莫不皆然. 故君而失其君之道 則不爲君. 臣而失其臣之職 則爲虛位. 范氏曰 人而不仁則非人 國而不治則不國矣.

[_06_24_01_]
=== ○宰我問曰 仁者雖告之曰 井有仁焉 其從之也 子曰 何爲其然也 君子可逝也 不可陷也 可欺也 不可罔也 (雍也-06-24-01)

劉聘君曰 有仁之仁 當作人. 今從之. 從 謂隨之於井而救之也. 宰我信道不篤 而憂爲仁之陷害 故有此問. 逝 謂使之往救. 陷 謂陷之於井. 欺 謂誑之以理之所有. 罔 謂昧之以理之所無. 蓋身在井上 乃可以救井中之人. 若從之於井 則不復能救之矣. 此理甚明 人所易曉 仁者雖切於救人 而不私其身 然不應如此之患也.

[_06_25_01_]
=== ○子曰 君子博學於文 約之以禮 亦可以弗畔矣夫 (雍也-06-25-01)

約 要也. 畔 背也. 君子學欲其博 故於文無不考. 守欲其要 故其動必以禮. 如此則可以不背於道矣. ○程子曰 博學於文而不約之以禮 必至於汗慢. 博學矣 又能守禮而由於規矩 則亦可以不畔道矣.

[_06_26_01_]
=== ○子見南子 子路不說 夫子矢之曰 予所否者 天厭之 天厭之 (雍也-06-26-01)

南子 衛靈公之夫人 有淫行. 孔子至衛 南子請見 孔子辭謝不得已而見之. 蓋古者仕於其國 有見其小君之禮. 而子路以夫子見此淫亂之人爲辱 故不悅. 矢 誓也. 所 誓辭也. 如云所不與崔慶者之類. 否 謂不合於禮 不由其道也. 厭 棄絶也.  聖人道大德全 無可不可. 其見惡人 固謂在我有可見之禮 則彼之不善 我何與焉. 然此豈子路所能測哉. 故重言以誓之 欲其姑信此而深思以得之也.

[_06_27_01_]
=== ○子曰 中庸之爲德也 其至矣乎 民鮮久矣 (雍也-06-27-01)

中者 無過不及之名也. 庸 平常也. 至 極也. 鮮 少也. 言民少此德 今已久矣. ○程子曰 不偏之謂中 不易之謂庸. 中者天下之正道 庸者天下之定理. 自世敎衰 民不興於行 少有此德久矣.

[_06_28_01_]
=== ○ 子貢曰 如有博施於民 而能濟衆 何如 可謂仁乎 子曰 何事於仁 必也聖乎 堯舜其猶病諸 (雍也-06-28-01)

博 廣也. 仁 以理言 通乎上下. 聖 以地言 則造其極之名也. 乎者 疑而未定之辭. 病 心有所不足也, 言此何止於仁 必也 聖人能之乎. 則雖堯舜之聖 其心猶有所不足於此也. 以是求仁 愈難而愈遠矣.

[_06_28_02_]
=== 夫仁者 己欲立而立人 己欲達而達人 (雍也-06-28-02)

以己及人 仁者之心也. 於此觀之 可以見天理之周流而無間矣. 狀仁之體 莫切於此.

[_06_28_03_]
=== 能近取譬 可謂仁之方也已 (雍也-06-28-03)

譬 喩也. 方 術也. 近取諸身 以己所欲 譬之他人 知其所欲 亦猶是也. 然後推其所欲 以及於人 則恕之事 而仁之術也. 於此勉焉 則有以勝其人欲之私 而全其天理之公矣. ○程子曰 醫書以手足痿痺爲不仁 此言最善名狀. 仁者以天地萬物爲一體 莫非己也. 認得爲己 何所不至. 若不屬己 自與己不相干 如手足之不仁 氣已不貫 皆不屬己. 故博施濟衆 乃聖人之功用. 仁至難言 故止曰己欲立而立人 己欲達而達人 能近取譬 可謂仁之方也已. 欲令如是觀仁 可以得仁之體. 又曰 論語言堯舜其猶病諸者二 夫博施者 豈非聖人之所欲 然必五十乃衣帛 七十乃食肉 聖人之心 非不欲少者亦衣帛食肉也 顧其養有所不贍爾. 此病其施之不博也. 濟衆者 豈非聖人之所欲 然治不過九州 聖人非不欲四海之外 亦兼濟也. 顧其治有所不及爾. 此病其濟之不衆也 推此以求 脩己以安百姓 則爲病可知. 苟以吾治已足 則便不是聖人. 呂氏曰 子恐有志於仁 徒事高遠 未知其方. 孔子敎以於己取之 庶近而可入. 是乃爲仁之方 雖博施濟衆 亦由此進.

論語集註大全卷之七

[_07_]
== 述而第七

此篇多記聖人謙己誨人之辭 及其容貌行事之實. 凡三十七章.

[_07_01_01_]
=== ○子曰 述而不作 信而好古 竊比於我老彭 (述而-07-01-01)

述 傳舊而已. 作則創始也. 故作非聖人不能 而述則賢者可及. 竊比 尊之之辭. 我 親之之辭. 老彭 商賢大夫 見大戴禮 蓋信古而傳述者也. 孔子刪詩書 定禮樂 贊周易 修春秋 皆傳先王之舊 而未嘗有所作也. 故其自言如此. 蓋不惟不敢當作者之聖 而亦不敢顯然自附於古之賢人. 蓋其德愈盛 而心愈下 不自知其辭之謙也. 然當是時 作者略備. 夫子蓋集群聖之大成 而折衷之 其事雖述 而功則培於作矣. 此又不可不知也.

[_07_02_01_]
=== ○子曰 黙而識之 學而不厭 誨人不倦 何有於我哉 (述而-07-02-01)

識 記也. 黙識 謂不言而存諸心也. 一說 識 知也 不言而心解也. 前說近是. 何有於我 言何者能有於我也. 三者己非聖人之極至 而猶不敢當 則謙而又謙之辭也.

[_07_03_01_]
=== ○子曰 德之不修 學之不講 聞義不能徙 不善不能改 是吾憂也 (述而-07-03-01)

尹氏曰 德必脩而後成 學必講而後明. 見善能徙 改過不吝 此四者 日新之要也. 苟未能之 聖人猶憂 況學者乎.

[_07_04_01_]
=== ○子之燕居 申申如也 夭夭如也 (述而-07-04-01)

燕居 閒暇無事之時. 楊氏曰 申申 其容舒也. 夭夭 其色愉也. ○程子曰 此弟子善形容聖人處也. 爲申申字說不盡 故更著夭夭字. 今人燕居之時 不怠惰放肆 必大嚴厲 嚴厲時 著此四字不得. 怠惰放肆時 亦著此四字不得 惟聖人便自有中和之氣 .

[_07_05_01_]
=== ○子曰 甚矣 吾衰也 久矣吾不復夢見周公 (述而-07-05-01)

孔子盛時 志欲行周公之道 故夢寐之間 如或見之. 至其老而不能行也 則無復是心 而亦無復是夢矣. 故因此而自歎其衰之甚也. ○程子曰 孔子盛時 寤寐常存行周公之道 及其老也 則志慮衰而不可以有爲矣. 蓋存道者 心無老少之異 而行道者 身老則衰也.

[_07_06_01_]
=== ○子曰 志於道 (述而-07-06-01)

志者 心之所之之謂. 道則人倫日用之間所當行者 是也. 知此而心必之焉 則所適者正 而無他岐之惑矣.

[_07_06_02_]
=== 據於德 (述而-07-06-02)

據者 執守之意. 德則行道而有得於心者也. 得之於心 而守之不失 則終始惟一 而有日新之功矣.

[_07_06_03_]
=== 依於仁 (述而-07-06-03)

依者 不違之謂. 仁則私欲盡去 而心德之全也. 工夫至此 而無終食之違 則存養之熟 無適而非天理之流行矣.

[_07_06_04_]
=== 游於藝 (述而-07-06-04)

游者 玩物適情之謂. 藝則禮樂之文 射御書數之法 皆至理所寓 而日用之不可闕者也. 朝夕游焉 以博其義理之趣 則應務有餘 而心亦無所放矣. ○此章言人之爲學 當如是也. 蓋學莫先於立志 志道則心存於正 而不他. 據德 則道得於心而不失. 依仁 則德性常用 而物欲不行. 游藝 則小物不遺 而動息有養. 學者於此 有以不失其先後之序 輕重之倫焉 則本末兼該 內外交養 日用之間 無少間隙 而涵泳從容 忽不自知其入於聖賢之域矣.

[_07_07_01_]
=== ○子曰 自行束脩以上 吾未嘗無誨焉 (述而-07-07-01)

脩 脯也. 十脡爲束. 古者相見 必執贄以爲禮. 束脩其至薄者. 蓋人之有生 同具此理 故聖人之於人無不欲其入於善. 但不知來學 則無往敎之禮. 故苟以禮來 則無不有以敎之也.

[_07_08_01_]
=== ○子曰 不憤不啓 不悱不發 擧一隅 不以三隅反 則不復也 (述而-07-08-01)

憤者 心求通而未得之意. 悱者 口欲言而未能之貌. 啓 謂開其意. 發 謂達其辭. 物之有四隅者 擧一可知其三. 反者 還以相證之義. 復 再告也. 上章已言聖人誨人不倦之意 因倂記此 欲學者勉於用力 以爲受敎之地也. ○程子曰 憤悱 誠意之見於色辭者也. 待其誠至而後告之 旣告之 又必待其自得 乃復古爾. 又曰 不待憤悱而發 則知之不能堅固. 待其憤悱而後發 則沛然矣.

[_07_09_01_]
=== ○子食於有喪者之側 未嘗飽也 (述而-07-09-01)

臨喪哀 不能甘也.

[_07_09_02_]
=== 子於是日哭 則不歌 (述而-07-09-02)

哭 謂弔哭. 一日之內 餘哀未忘 自不能歌也. ○謝氏曰 學者於此二者 可見聖人情性之正也. 能識聖人之情性 然後可以學道.

[_07_10_01_]
=== ○子謂顔淵曰 用之則行 舍之則藏 惟我與爾有是夫 (述而-07-10-01)

尹氏曰 用舍無與於己 行藏安於所遇 命不足道也. 顔子幾於聖人 故亦能之.

[_07_10_02_]
=== 子路曰 子行三軍 則誰與 (述而-07-10-02)

萬二千五百人爲軍. 大國三軍. 子路見孔子獨美顔淵 自負其勇 意夫子若行三軍 必與己同.

子曰 暴虎馮河 死而無悔者 吾不與也 必也臨事而懼 好謀而成者也(述而-07-10-03)

暴虎 徒搏. 馮河 徒涉. 懼 謂敬其事. 成 謂成其謀. 言此皆以抑其勇而敎之 然行師之要 實不外此. 子路蓋不知也. ○謝氏曰 聖人於行藏之間 無意無必. 其行非貪位 其藏非獨善也. 若有欲心 則不用而求行 舍之而不藏矣. 是以惟顔子爲可以與於此. 子路雖非有欲心者 然未能無固必也. 至以行三軍爲問 則其論益卑矣. 夫子之言 蓋因其失而救之. 夫不謀無成 不懼必敗. 小事尙然 而況於行三軍乎.

[_07_11_01_]
=== ○子曰 富而可求也 雖執鞭之士 吾亦爲之 如不可求 從吾所好 (述而-07-11-01)

執鞭 賤者之事. 設言富若可求 則雖身爲賤役以求之 亦所不辭. 然有命焉 非求之可得也. 則安於義理而已矣. 何必徒取辱哉. ○蘇氏曰 聖人未嘗有意於求富也. 豈問其可不可哉. 爲此語者 特以明其決不可求爾. 楊氏曰 君子非惡富貴而不求 以其在天 無可求之道也.

[_07_12_01_]
=== ○子之所愼 齊 戰 疾 (述而-07-12-01)

齊之爲言 齊也 將祭而齊其思慮之不齊者 以交於神明也. 誠之至與不至 神之享與不享 皆決於此. 戰則衆之死生 國之存亡繫焉. 疾又吾身之所以死生存亡者 皆不可以不謹也. ○尹氏曰 夫子無所不謹 弟子記其大者耳.

[_07_13_01_]
=== ○子在齊聞韶 三月不知肉味 曰 不圖爲樂之至於斯也 (述而-07-13-01)

史記三月上 有學之二字. 不知肉味 蓋心一於是而不及乎他也. 曰不意舜之作樂至於如此之美 則有以極其情文之備 而不覺其歎息之深也. 蓋非聖人不足以及此. ○范氏曰 韶盡美又盡善 樂之無以加此也. 故學之三月 不知肉味 而歎美之如此 誠之至 感之深也.

[_07_14_01_]
=== ○冉有曰 夫子爲衛君乎 子貢曰 諾 吾將問之 (述而-07-14-01)

爲 猶助也. 衛君 出公輒也. 靈公逐其世子蒯聵 公薨而國人立蒯聵之子輒 於是晉納蒯聵 而輒拒之. 時孔子居衛 衛人以蒯聵得罪於父 而輒嫡孫當立 故冉有疑而問之. 諾 應辭也.

[_07_14_02_]
=== 入曰 伯夷叔齊 何人也 曰 古之賢人也 曰 怨乎 曰 求仁而得仁 又何怨 出曰 夫子不爲也 (述而-07-14-02)

伯夷叔齊 孤竹君之二子 其父將死 遺命立叔齊. 父卒 叔齊遜伯夷. 伯夷曰 父命也. 遂逃去. 叔齊亦不立 而逃之. 國人立其中子. 其後武王伐紂 夷齊扣馬而諫. 武王滅商 夷齊恥食周粟 去隱于首陽山 遂餓而死. 怨 猶悔也. 君子居是邦 不非其大夫 況其君乎. 故子貢不斥衛君 而以夷齊爲問. 夫子告之如此 則其不爲衛君可知矣. 蓋伯夷以父命爲尊 叔齊以天倫爲重 其遜國也 皆求所以合乎天理之正 而卽乎人心之安. 旣而各得其志焉 則視棄其國猶敝蹝爾 何怨之有. 若衛輒之據國拒父 而唯恐失之 其不可同年而語明矣. ○程子曰 伯夷叔齊遜國而逃 諫伐而餓 終無怨悔. 夫子以爲賢 故知其不與輒也.

[_07_15_01_]
=== ○子曰 飯疏食飮水 曲肱而枕之 樂亦在其中矣 不義而富且貴 於我如浮雲 (述而-07-15-01)

飯 食之也. 疏食 麤飯也 聖人之心 渾然天理. 雖處困極 而樂亦無不在焉. 其視不義之富貴 如浮雲之無有 漠然無所動於其中也. ○程子曰 非樂疏食飮水也 雖疏食飮水不能改其樂也. 不義之富貴 視之輕如浮雲然. 又曰須知所樂者何事.

[_07_16_01_]
=== ○子曰 加我數年 五十以學易 可以無大過矣 (述而-07-16-01)

劉聘君 見元城劉忠定公 自言嘗讀他論 加作假 五十作卒. 蓋加假聲相近而誤讀 卒與五十字相似而誤分也. 愚按此章之言 史記作假我數年 若是我於易則彬彬矣. 加 正作假 而無五十字. 蓋是時孔子年已幾七十矣. 五十字誤無疑也. 學易則明乎吉凶消長之理 進退存亡之道 故可以無大過. 蓋聖人深見易道之無窮 而言此以敎人 使知其不可不學 而又不可以易而學也.

[_07_17_01_]
=== ○子所雅言 詩書執禮 皆雅言也 (述而-07-17-01)

雅 常也. 執 守也. 詩以理情性 書以道政事 禮以謹節文 皆切於日用之實 故常言之. 禮獨言執者 以人所執守而言 非徒誦說而已也. ○程子曰 孔子雅素之言 止於如此. 若性與天道 則有不可得而聞者 要在黙而識之也. 謝氏曰 此因學易之語而類記之.

[_07_18_01_]
=== ○葉公問孔子於子路 子路不對 (述而-07-18-01)

葉公 楚葉縣尹沈諸梁 字子高. 僣稱公也. 葉公不知孔子 必有非所問而問者 故子路不對. 抑亦以聖人之德 實有未易名言者與.

[_07_18_02_]
=== 子曰 女奚不曰 其爲人也 發憤忘食 樂以忘憂 不知老之將至云爾 (述而-07-18-02)

未得則發憤而忘食 已得則樂之而忘憂. 以是二者 俛焉日有孶孶 而不知年數之不足 但自言其好學之篤爾. 然深味之 則見其全體至極 純亦不已之妙 有非聖人不能及者. 蓋凡夫子之自言類如此 學者宜致思焉.

[_07_19_01_]
=== ○子曰 我非生而知之者 好古敏以求之者也 (述而-07-19-01)

生而知之者 氣質淸明 義理昭著 不待學而知也. 敏 速也 謂汲汲也. ○尹氏曰 孔子以生知之聖 每云好學者 非惟勉人也 蓋生而可知者 義理爾 若夫禮樂名物 古今事變 亦必待學而後有以驗其實也.

[_07_20_01_]
=== ○子不語 怪力亂神 (述而-07-20-01)

怪異 勇力 悖亂之事 非理之正 固聖人所不語. 鬼神 造化之迹 雖非不正 然非窮理之至 有未易明者 故亦不輕以語人也. ○謝氏曰 聖人語常而不語怪 語德而不語力 語治而不語亂 語人而不語神.

[_07_21_01_]
=== ○子曰 三人行必有我師焉 擇其善者而從之 其不善者而改之 (述而-07-21-01)

三人同行 其一我也. 彼二人者 一善一惡. 則我從其善而改其惡焉 是二人者 皆我師也. ○尹氏曰 見賢思齊 見不賢而內自省 則善惡皆我之師 進善其有窮乎.

[_07_22_01_]
=== ○子曰 天生德於予 桓魋其如予何 (述而-07-22-01)

桓魋 宋司馬向魋也. 出於桓公 故又稱桓氏. 魋欲害孔子 孔子言 天旣賦我以如是之德 則桓魋其奈我何. 言必不能違天害己.

[_07_23_01_]
=== ○子曰 二三子以我爲隱乎 吾無隱乎爾 吾無行而不與二三子者 是丘也 (述而-07-23-01)

諸弟子以夫子之道 高深不可幾及 故疑其有隱. 而不知聖人作止語黙 無非敎也. 故夫子以此言曉之. 與 猶示也. ○程子曰 聖人之道猶天然 門弟子親炙而冀及之 然後知其高且遠也. 使誠以爲不可及 則趨向之心不幾於怠乎. 故聖人之敎 常俯而就之如此 非獨使資質庸下者 勉思企及 而才氣高邁者 亦不敢躐易而進也. 呂氏曰 聖人體道無隱 與天象昭然 莫非至敎 常以示人 而人自不察.

[_07_24_01_]
=== ○子以四敎 文行忠信 (述而-07-24-01)

程子曰 敎人以學文脩行 而存忠信也. 忠信 本也.

[_07_25_01_]
=== ○子曰 聖人吾不得而見之矣 得見君子者 斯可矣 (述而-07-25-01)

聖人 神明不測之號. 君子 才德出衆之名.

[_07_25_02_]
=== 子曰 善人吾不得而見之矣 得見有恒者 斯可矣 (述而-07-25-02)

子曰字 疑衍文. 恒 常久之意. 張子曰 有恒者不二其心 善人者志於仁而無惡.

[_07_25_03_]
=== 亡而爲有 虛而爲盈 約而爲泰 難乎有恒矣 (述而-07-25-03)

三者 皆虛夸之事 凡若此者 必不能守其常也. ○張敬夫曰 聖人君子以學言 善人有恒者以質言. 愚謂 有恒者之於聖人 高下固懸絶矣. 然未有不自有恒而能至於聖者也. 故章末申言有恒之義 其示人入德之門 可謂深切而著明矣.

[_07_26_01_]
=== ○子釣而不網 弋不射宿 (述而-07-26-01)

綱 以大繩屬網 絶流而漁者也. 弋 以生絲繫矢而射也. 宿 宿鳥. ○洪氏曰 孔子少貧賤 爲養與祭 或不得已而釣弋 如獵較是也. 然盡物取之 出其不意 亦不爲也. 此可見仁人之本心矣. 待物如此 待人可知. 小者如此 大者可知.

[_07_27_01_]
=== ○子曰 蓋有不知而作之者 我無是也 多聞擇其善者而從之 多見而識之 知之次也 (述而-07-27-01)

不知而作 不知其理而妄作也. 孔子自言未嘗妄作 蓋亦謙辭. 然亦可見其無所不知也. 識 記也. 所從不可不擇 記則善惡皆當存之 以備參考. 如此者 雖未能實知其理 亦可以次於知之者也.

[_07_28_01_]
=== ○互鄕難與言 童子見 門人惑 (述而-07-28-01)

互鄕 鄕名. 其人習於不善 難與言善. 惑者 疑夫子不當見之也.

[_07_28_02_]
=== 子曰 與其進也 不與其退也 唯何甚 人潔己以進 與其潔也 不保其往也 (述而-07-28-02)

疑此章有錯簡. 人潔至往也十四字 當在與其進也之前. 潔 脩治也. 與 許也. 往 前日也. 言人潔己而來 但許其能自潔耳 固不能保其前日所爲之善惡也. 但許其進而來見耳 非許其旣退而爲不善也. 蓋不追其旣往 不逆其將來 以是心至斯受之耳. 唯字上下 疑有闕文. 大抵亦不爲己甚之意. ○程子曰 聖人待物之洪如此.

[_07_29_01_]
=== ○子曰 仁遠乎哉 我欲仁斯仁至矣 (述而-07-29-01)

仁者 心之德 非在外也. 放而不求 故有以爲遠者. 反而求之 則卽此而在矣. 夫豈遠哉. ○程子曰 爲仁由己 欲之則至 何遠之有.

[_07_30_01_]
=== ○陳司敗問昭公知禮乎 孔子曰 知禮 (述而-07-30-01)

陳 國名. 司敗 官名 卽司寇也. 昭公魯君 名稠 習於威儀之節. 當時以爲知禮 故司敗以爲問 而孔子答之如此.

[_07_30_02_]
=== 孔子退 揖巫馬期而進之 曰 吾聞君子不黨 君子亦黨乎 君取於吳爲同姓 謂之吳孟子 君而知禮 孰不知禮 (述而-07-30-02)

巫馬姓 期字 孔子弟子 名施. 司敗 揖而進之也. 相助匿非曰黨. 禮不取同姓 而魯與吳 皆姬姓 謂之吳孟子者 諱之 使若宋女子姓者然.

[_07_30_03_]
=== 巫馬期以告 子曰 丘也幸 苟有過 人必知之 (述而-07-30-03)

孔子不可自謂諱君之惡 又不可以取同姓爲知禮 故受以爲過而不辭. ○吳氏曰 魯蓋夫子父母之國 昭公 魯之先君也. 司敗又未嘗顯言其事 而遽以知禮爲問 其對之宜如此也. 及司敗以爲有黨 而夫子受以爲過 蓋夫子之盛德無所不可也. 然其受以爲過也 亦不正言其所以過 初若不知孟子之事者 可以爲萬世之法矣.

[_07_31_01_]
=== ○子與人歌而善 必使反之 而後和之 (述而-07-31-01)

反 復也. 必使復歌者 欲得其詳而取其善也. 而後和之者 喜得其詳而與其善也. 此見聖人氣象從容 誠意懇至 而其謙遜審密 不掩人善又如此. 蓋一事之微 而衆善之集 有不可勝旣者焉. 讀者宜詳味之.

[_07_32_01_]
=== ○子曰 文莫吾猶人也 躬行君子 則吾未之有得 (述而-07-32-01)

莫 疑辭. 猶人 言不能過人 而尙可以及人. 未之有得 則全未有得. 皆自謙之辭 而足以見言行之難易緩急 欲人之勉其實也. ○謝氏曰 文雖聖人無不與人同 故不遜 能躬行君子 斯可以入聖 故不居 猶言君子道者三 我無能焉.

[_07_33_01_]
=== ○子曰 若聖與仁 則吾豈敢 抑爲之不厭 誨人不倦 則可謂云爾已矣 公西華曰 正唯弟子不能學也 (述而-07-33-01)

此亦夫子之謙辭也. 聖者大而化之 仁則心德之全 而人道之備也. 爲之 謂爲仁聖之道. 誨人 亦謂以此敎人也. 然不厭不倦 非己有之則不能 所以弟子不能學也. 鼂氏曰 當時有稱夫子聖且仁者 以故夫子辭之. 苟辭之而已焉 則無以進天下之材 率天下之善 將使聖與仁爲虛器 而人終莫能至矣. 故夫子雖不居仁聖 而必以爲之不厭 誨人不倦自處也. 可謂云爾已矣者 無他之辭也. 公西華仰而歎之 其亦深知夫子之意矣.

[_07_34_01_]
=== ○子疾病 子路請禱 子曰 有諸 子路對曰 有之 誄曰 禱爾于上下神祇 子曰 丘之禱久矣 (述而-07-34-01)

禱 謂禱於鬼神. 有諸 問有此理否. 誄者 哀死而述其行之辭也. 上下 謂天地. 天曰神 地曰祗. 禱者 悔過遷善 以祈神之佑也. 無其理 則不必禱 旣曰有之 則聖人未嘗有過 無善可遷 其素行固已合於神明 故曰丘之禱久矣. 又士喪禮 疾病行禱五祀. 蓋臣子迫切之至 情有不能自已者 初不請於病者而後禱也. 故孔子之於子路 不直拒之 而但告以無所事禱之意.

[_07_35_01_]
=== ○子曰 奢則不孫 儉則固 與其不孫也 寧固 (述而-07-35-01)

孫 順也. 固 陋也. 奢儉俱失中 而奢之害大. ○鼂氏曰 不得已而救時之弊也.

[_07_36_01_]
=== ○子曰 君子坦蕩蕩 小人長戚戚 (述而-07-36-01)

坦 平也. 蕩蕩 寬廣貌. 程子曰 君子循理 故常舒泰. 小人役於物 故多憂戚. ○程子曰 君子坦蕩蕩 心廣體胖.

[_07_37_01_]
=== ○子溫而厲 戚而不猛 恭而安 (述而-07-37-01)

厲 嚴肅也. 人之德性 本無不備 而氣質所賦 鮮有不偏 惟聖人全體渾然 陰陽合德 故其中和之氣 見於容貌之間者 如此. 門人熟察而詳記之 亦可見其用心之密矣. 抑非知足以知聖人 而善言德行者 不能記. 故程子以爲曾子之言 學者所宜反復而玩心也.

論語集註大全卷之八

[_08_]
== 泰伯第八

凡二十一章

[_08_01_01_]
=== ○子曰 泰伯 其可謂至德也已矣 三以天下讓 民無得而稱焉 (泰伯-08-01-01)

泰伯 周大王之長子. 至德 謂德之至極 無以復加者也. 三讓 謂固遜也. 無得而稱 其遜隱微 無迹可見也. 蓋大王三子 長泰伯 次仲雍 次季歷. 大王之時 商道浸衰 而周日彊大. 季歷又生子昌 有聖德 大王因有翦商之志 而泰伯不從 大王遂欲傳位季歷 以及昌. 泰伯知之 卽與仲雍逃之荊蠻 於是大王乃立季歷. 傳國至昌 而三分天下有其二 是爲文王. 文王崩 子發立. 遂克商而有天下 是爲武王. 夫以泰伯之德 當商周之際 固足以朝諸侯 有天下矣. 乃棄不取 而又泯其迹焉 則其德之至極 爲如何哉. 蓋其心卽夷齊扣馬之心 而事之難處有甚焉者. 宜夫子之歎息 而贊美之也. 泰伯不從 事見春秋傳.

[_08_02_01_]
=== ○子曰 恭而無禮則勞 愼而無禮則葸 勇而無禮則亂 直而無禮則絞 (泰伯-08-02-01)

葸 畏懼貌. 絞 急切也. 無禮則無節文 故有四者之弊.

[_08_02_02_]
=== 君子篤於親 則民興於仁 故舊不遺 則民不偸 (泰伯-08-02-02)

君子 謂在上之人也. 興 起也. 偸 薄也. ○張子曰 人道知所先後 則恭不勞 愼不葸 勇不亂 直不絞 民化而德厚矣. ○吳氏曰 君子以下當自爲一章 乃曾子之言也. 愚按此一節 與上文不相蒙 而與首篇謹終追遠之意相類 吳說近是.

[_08_03_01_]
=== ○曾子有疾 召門弟子曰 啓予足 啓予手 詩云 戰戰兢兢 如臨深淵 如履薄氷 而今而後 吾知免夫 小子 (泰伯-08-03-01)

啓 開也. 曾子平日 以爲身體受於父母 不敢毁傷 故於此使弟子開其衾而視之. 詩 小旻之篇. 戰戰 恐懼. 兢兢 戒謹. 臨淵 恐墜. 履氷 恐陷也. 曾子以其所保之全 示門人 而言其所以保之之難如此. 至於將死而後知其得免於毁傷也. 小子 門人也. 語畢而又呼之 以致反復丁寧之意 其警之也深矣. ○程子曰 君子曰終 小人曰死. 君子保其身以沒爲終其事也. 故曾子以全歸爲免矣. 尹氏曰 父母全而生之 子全而歸之. 曾子臨終而啓手足爲是故也. 非有得於道 能如是乎. 范氏曰 身體猶不可虧也 況虧其行以辱其.親乎

[_08_04_01_]
=== ○曾子有疾 孟敬子問之 (泰伯-08-04-01)

孟敬子 魯大夫 仲孫氏 名捷. 問之者 問其疾也.

[_08_04_02_]
=== 曾子言曰 鳥之將死 其鳴也哀 人之將死 其言也善 (泰伯-08-04-02)

言 自言也. 鳥畏死 故鳴哀. 人窮反本 故言善. 此曾子之謙辭 欲敬子知其所言之善 而識之也.

[_08_04_03_]
=== 君子所貴乎道者三 動容貌斯遠暴慢矣 正顔色斯近信矣 出辭氣斯遠鄙倍矣 籩豆之事 則有司存 (泰伯-08-04-03)

貴 猶重也. 容貌 擧一身而言. 暴 粗厲也. 慢 放肆也. 信 實也. 正顔色而近信 則非色莊也. 辭 言語. 氣 聲氣也. 鄙 凡陋也. 倍 與背同 謂背理也. 籩 竹豆. 豆 木豆. 言道雖無所不在 然君子所重者 在此三事而已. 是皆修身之要 爲政之本 學者所當操存省察 而不可有造次顚沛之違者也. 若夫籩豆之事 器數之末 道之全體 固無不該. 然其分則有司之守 而非君子之所重矣. 程子曰 動容貌 擧一身而言也. 周旋中禮 暴慢斯遠矣. 正顔色則不妄 斯近信矣. 出辭氣 正由中出 斯遠鄙倍. 三者 正身而不外求 故曰籩豆之事 則有司存. 尹氏曰 養於中則見於外 曾子蓋以脩己爲爲政之本. 若乃器用事物之細 則有司存焉.

[_08_05_01_]
=== ○曾子曰 以能問於不能 以多問於寡 有若無 實若虛 犯而不校 昔者吾友 嘗從事於斯矣 (泰伯-08-05-01)

校 計校也. 友 馬氏以爲顔淵 是也. 顔子之心 惟知義理之無窮 不見物我之有間 故能如此. ○謝氏曰 不知有餘在己 不足在人 不必得爲在己 失爲在人 非幾於無我者 不能也.

[_08_06_01_]
=== ○曾子曰 可以託六尺之孤 可以寄百里之命 臨大節而不可奪也 君子人與 君子人也 (泰伯-08-06-01)

其才可以輔幼君攝國政 其節至於死生之際 而不可奪 可謂君子矣. 與 疑辭. 也 決辭. 設爲問答 所以深著其必然也. ○程子曰 節操如是 可謂君子矣.

[_08_07_01_]
=== ○曾子曰 士不可以不弘毅 任重而道遠 (泰伯-08-07-01)

弘 寬廣也. 毅 强忍也. 非弘不能勝其重 非毅無以致其遠.

[_08_07_02_]
=== 仁以爲己任 不亦重乎 死而後已 不亦遠乎 (泰伯-08-07-02)

仁者 人心之全德 而必欲以身體而力行之 可謂重矣. 一息尙存 此志不容少懈 可謂遠矣. ○程子曰 弘而不毅 則無規矩而難立. 毅而不弘 則隘陋而無以居之. 又曰 弘大剛毅 然後能勝重任而遠到.

[_08_08_01_]
=== ○子曰 興於詩 (泰伯-08-08-01)

興 起也. 詩本性情 有邪有正. 其爲言旣易知 而吟詠之間 抑揚反覆 其感人又易入 故學者之初 所以興起其好善惡惡之心 而不能自已者 必於此而得之.

[_08_08_02_]
=== 立於禮 (泰伯-08-08-02)

禮 以恭敬辭遜爲本 而有節文度數之詳 可以固人肌膚之會 筋骸之束 故學者之中 所以能卓然自立 而不爲事物之所搖奪者 必於此而得之.

[_08_08_03_]
=== 成於樂 (泰伯-08-08-03)

樂有五聲十二律 更唱迭和 以爲歌舞八音之節 可以養人之性情 而蕩滌其邪穢 消融其査滓 故學者之終 所以至於義精仁熟 而自和順於道德者 必於此而得之 是學之成也. ○按內則 十歲學幼儀 十三學樂誦詩 二十而後學禮 則此三者 非小學傳授之次 乃大學終身所得之難易先後淺深也. 程子曰 天下之英才不爲少矣 特以道學不明. 故不得有所成就. 夫古人之詩 如今之歌曲 雖閭里童稚 皆習聞之 而知其說 故能興起. 今雖老師宿儒 尙不能曉其義 況學者乎. 是不得興於詩也. 古人自灑掃應對 以至冠婚喪祭 莫不有禮. 今皆廢壞 是以人倫不明 治家無法 是不得立於禮也. 古人之樂 聲音所以養其耳 采色所以養其目 歌詠所以養其性情 舞蹈所以養其血脈. 今皆無之 是不得成於樂也. 是以古之成材也易 今之成材也難.

[_08_09_01_]
=== ○子曰 民可使由之 不可使知之 (泰伯-08-09-01)

民可使之由於是理之當然 而不能使之知其所以然也. ○程子曰 聖人設敎 非不欲人 家喩而戶曉也. 然不能使之知 但能使之由之爾. 若曰聖人不使民知 則是後世朝四暮三之術也 豈聖人之心乎.

[_08_10_01_]
=== ○子曰 好勇疾貧 亂也 人而不仁 疾之已甚 亂也 (泰伯-08-10-01)

好勇而不安分 則必作亂. 惡不仁之人 而使之無所容 則必致亂. 二者之心 善惡雖殊 然其生亂則一也.

[_08_11_01_]
=== ○子曰 如有周公之才之美 使驕且吝 其餘不足觀也已 (泰伯-08-11-01)

才美 謂智能技藝之美. 驕 矜夸. 吝 鄙嗇也. ○程子曰 此甚言驕吝之不可也. 蓋有周公之德 則自無驕吝 若但有周公之才 而驕吝焉 亦不足觀矣. 又曰 驕氣盈 吝氣歉. 愚謂驕吝雖有盈歉之殊 然其勢常相因. 蓋驕者吝之枝葉 吝者驕之本根 故嘗驗之天下之人 未有驕而不吝 吝而不驕者也.

[_08_12_01_]
=== ○子曰 三年學 不至於穀 不易得也 (泰伯-08-12-01)

穀 祿也. 至 疑當作志. 爲學之久而不求祿 如此之人 不易得也. ○楊氏曰 雖子張之賢 猶以干祿爲問 況其下者乎. 然則三年學而不至於穀 宜不易得也.

[_08_13_01_]
=== ○子曰 篤信好學 守死善道 (泰伯-08-13-01)

篤厚而力也. 不篤信 則不能好學. 然篤信而不好學 則所信或非其正. 不守死則不能以善其道 然守死而不足以善其道 則亦徒死而已. 蓋守死者 篤信之效 善道者 好學之功.

危邦不入 亂邦不居 天下有道則見 無道則隱 (泰伯-08-13-02 )

君子見危授命 則仕危邦者無可去之義 在外則不入可也. 亂邦未危 而刑政紀綱紊矣 故潔其身而去之. 天下 擧一世而言 無道則隱其身而不見也. 此惟篤信好學守死善道者 能之.

[_08_13_03_]
=== 邦有道 貧且賤焉 恥也 邦無道 富且貴焉 恥也 (泰伯-08-13-03)

世治而無可行之道 世亂而無能守之節 碌碌庸人 不足以爲士矣 可恥之甚也. ○鼂氏曰 有學有守 而去就之義潔 出處之分明 然後爲君子之全德也.

[_08_14_01_]
=== ○子曰 不在其位 不謀其政 (泰伯-08-14-01)

程子曰 不在其位 則不任其事也. 若君大夫問而告者 則有矣.

[_08_15_01_]
=== ○子曰 師摯之始 關雎之亂 洋洋乎盈耳哉 (泰伯-08-15-01)

師摯 魯樂師 名摯也. 亂 樂之卒章也. 史記曰 關雎之亂以爲風始. 洋洋 美盛意. 孔子自衛反魯而正樂 適師摯在官之初. 故樂之美盛如此.

[_08_16_01_]
=== ○子曰 狂而不直 侗而不愿 悾悾而不信 吾不知之矣 (泰伯-08-16-01)

侗 無知貌. 愿 謹厚也. 悾悾 無能貌. 吾不知之者 甚絶之之辭. 亦不屑之敎誨也. ○蘇氏曰 天之生物 氣質不齊. 其中材以下 有是德則有是病 有是病必有是德. 故馬之蹄齧者 必善走 其不善者必馴. 有是病而無是德 則天下之棄才也.

[_08_17_01_]
=== ○子曰 學如不及 猶恐失之 (泰伯-08-17-01)

言人之爲學 旣如有所不及矣 而其心猶竦然惟恐其或失之. 警學者當如是也. ○程子曰 學如不及 猶恐失之 不得放過. 才說姑待明日 便不可也.

[_08_18_01_]
=== ○子曰 巍巍乎 舜禹之有天下也 而不與焉 (泰伯-08-18-01)

巍巍 高大之貌. 不與 猶言不相關. 言其不以位爲樂也.

[_08_19_01_]
=== ○子曰 大哉堯之爲君也 巍巍乎 唯天爲大 唯堯則之 蕩蕩乎 民無能名焉 (泰伯-08-19-01)

唯 猶獨也. 則 猶準也. 蕩蕩 廣遠之稱也. 言物之高大 莫有過於天者 而獨堯之德 能與之準 故其德之廣遠 亦如天之不可以言語形容也.

[_08_19_02_]
=== 巍巍乎 其有成功也 煥乎 其有文章 (泰伯-08-19-02)

成功 事業也. 煥 光明之貌. 文章 禮樂法度也. 堯之德不可名 其可見者此爾. ○尹氏曰 天道之大 無爲而成. 唯堯則之 以治天下 故民無得而名焉. 所可名者 其功業文章巍然煥然而已.

[_08_20_01_]
=== ○舜有臣五人 而天下治 (泰伯-08-20-01)

五人 禹 稷 契 皐陶 伯益.

[_08_20_02_]
=== 武王曰 予有亂臣十人 (泰伯-08-20-02)

書 泰誓之辭. 馬氏曰 亂 治也. 十人 謂周公旦 召公奭 太公望 畢公 榮公 太顚 閎夭散宜生 南宮适. 其一人謂文母 劉侍讀以爲子無臣母之義 蓋邑姜也. 九人治外 邑姜治內. 或曰 亂 本作亂 古治字也 .

[_08_20_03_]
=== 孔子曰 才難 不其然乎 唐虞之際 於斯爲盛 有婦人焉 九人而已 (泰伯-08-20-03)

稱孔子者 上係武王君臣之際 記者謹之. 才難 蓋古語而孔子然之也. 才者 德之用也. 唐虞堯舜 有天下之號 際 交會之間. 言周室人才之多 惟唐虞之際 乃盛於此. 降自夏商 皆不能及. 然猶但有此數人爾 是才之難得也.

[_08_20_04_]
=== 三分天下有其二 以服事殷 周之德 其可謂至德也已矣 (泰伯-08-20-04)

春秋傳曰 文王率商之畔國以事紂 蓋天下歸文王者六州 荊 梁 雍 豫 徐 揚也. 惟靑 袞 冀 尙屬紂耳. 范氏曰 文王之德 足以代商. 天與之人歸之 乃不取而服事焉 所以爲至德也. 孔子因武王之言 而及文王之德 且與泰伯皆以至德稱之 其指微矣. 或曰 宜斷三分以下 別以孔子曰起之 而自爲一章.

[_08_21_01_]
=== ○子曰 禹 吾無間然矣 菲飮食 而致孝乎鬼神 惡衣服 而致美乎黻冕 卑宮室 而盡力乎溝洫 禹 吾無間然矣 (泰伯-08-21-01)

間 罅隙也. 謂指其罅隙而非議之也. 菲 薄也. 致孝鬼神 謂享祀豊潔. 衣服 常服. 黻 蔽膝也. 以韋爲之. 冕 冠也. 皆祭服也. 溝洫 田間水道 以正疆界 備旱潦者也. 或豊或儉 各適其宜 所以無罅隙之可議也. 故再言以深美之. ○楊氏曰 薄於自奉 而所勤者民之事 所致飾者 宗廟朝廷之禮 所謂有天下而不與也. 夫何間然之有.

論語集註大全卷之九

[_09_]
== 子罕第九

凡三十章

[_09_01_01_]
=== ○子罕言 利 與命與仁 (子罕-09-01-01)

罕 少也. 程子曰 計利則害義 命之理 微 仁之道 大 皆夫子所罕言也.

[_09_02_01_]
=== ○達巷黨人曰 大哉孔子 博學而無所成名 (子罕-09-02-01)

達巷 黨名 其人姓名不傳. 博學而無所成名 蓋美其學之博 而惜其不成一藝之名也.

[_09_02_02_]
=== 子聞之 謂門弟子曰 吾何執 執御乎 執射乎 吾執御矣 (子罕-09-02-02)

執 專執也. 射御 皆一藝 而御爲人僕 所執尤卑. 言欲使我何所執以成名乎. 然則吾將執御矣 聞人譽己 承之以謙也. ○尹氏曰 聖人道全而德備 不可以偏長目之也. 達巷黨人 見孔子之大 意其所學者博 而惜其不以一善得名於世 蓋慕聖人而不知者也. 故孔子曰 欲使我何所執而得爲名乎 然則吾將執御矣.

[_09_03_01_]
=== ○子曰 麻冕 禮也 今也純 儉 吾從衆 (子罕-09-03-01)

麻冕 緇布冠也. 純 絲也. 儉 謂省約. 緇布冠以三十升布爲之 升八十縷. 則其經二千四百縷矣. 細密難成 不如用絲之省約.

[_09_03_02_]
=== 拜下 禮也 今拜乎上 泰也 雖違衆 吾從下 (子罕-09-03-02)

臣與君行禮 當拜於堂下. 君辭之 乃升成拜. 泰 驕慢也. ○程子曰 君子處世 事之無害於義者 從俗可也. 害於義 則不可從也.

[_09_04_01_]
=== ○子絶四 毋意 毋必 毋固 毋我 (子罕-09-04-01)

絶 無之盡者. 毋 史記作無 是也. 意 私意也. 必 期必也. 固 執滯也. 我 私己也. 四者相爲終始 起於意 遂於必 留於固 而成於我也. 蓋意必常在事前 固我常在事後. 至於我 又生意 則物欲牽引 循環不窮矣. ○程子曰 此毋字 非禁止之辭 聖人絶此四者 何用禁止. 張子曰 四者有一焉 則與天地不相似. 楊氏曰 非知足以知聖人 詳視而黙識之 不足以記此.

[_09_05_01_]
=== ○子畏於匡 (子罕-09-05-01)

畏者 有戒心之謂. 匡 地名 史記云 陽虎曾暴於匡 夫子貌似陽虎 故匡人圍之.

[_09_05_02_]
=== 曰 文王旣沒 文不在玆乎 (子罕-09-05-02)

道之顯者 謂之文 蓋禮樂制度之謂. 不曰道而曰文 亦謙辭也. 玆 此也. 孔子自謂.

[_09_05_03_]
=== 天之將喪斯文也 後死者 不得與於斯文也 天之未喪斯文也 匡人其如予 何 (子罕-09-05-03)

馬氏曰 文王旣沒 故孔子自謂後死者. 言天若欲喪此文 則必不使我得與於此文. 今我旣得與於此文 則是天未欲喪此文也. 天旣未欲喪此文 則匡人其奈我何. 言必不能違天害己也.

[_09_06_01_]
=== ○大宰問於子貢曰 夫子聖者與 何其多能也 (子罕-09-06-01)

孔氏曰 大宰 官名 或吳或宋 未可知也. 與者 疑辭 大宰蓋以多能爲聖也.

[_09_06_02_]
=== 子貢曰 固天縱之將聖 又多能也 (子罕-09-06-02)

縱 猶肆也. 言不爲限量也. 將 殆也. 謙若不敢知之辭. 聖無不通 多能乃其餘事. 故言又以兼之.

子聞之曰 大宰知我乎 吾少也賤 故多能 鄙事 君子多乎哉 不多也(子罕-09-06-03)

言由少賤故多能. 而所能者鄙事爾 非以聖而無不通也. 且多能非所以率人 故又言君子 不必多能以曉之.

[_09_06_04_]
=== 牢曰 子云 吾不試 故藝 (子罕-09-06-04)

牢 孔子弟子 姓琴 字子開一字子張. 試 用也. 言由不爲世用. 故得以習於藝而通之. ○吳氏曰 弟子記夫子此言之時 子牢因言昔之所聞有如此者 其意相近 故幷記之.

[_09_07_01_]
=== ○子曰 吾有知乎哉 無知也 有鄙夫問於我 空空如也 我叩其兩端而竭焉 (子罕-09-07-01)

孔子謙言 己無知識 但其告人 雖於至愚 不敢不盡耳. 叩 發動也. 兩端 猶言兩頭. 言終始本末 上下精粗 無所不盡. ○程子曰 聖人之敎人 俯就之若此 猶恐衆人以爲高遠而不親也. 聖人之道 必降而自卑 不如此則人不親. 賢人之言 則引而自高 不如此則道不尊. 觀於孔子孟子可見矣. 尹氏曰 聖人之言 上下兼盡. 卽其近 衆人皆可與知. 極其至 則雖聖人亦無以加焉. 是之謂兩端. 如答樊遲之問仁智 兩端竭盡 無餘蘊矣. 若夫語上而遺下 語理而遺物 則豈聖人之言哉.

[_09_08_01_]
=== ○子曰 鳳鳥不至 河不出圖 吾已矣夫 (子罕-09-08-01)

鳳 靈鳥 舜時來儀 文王時鳴於岐山. 河圖 河中龍馬負圖 伏羲時出 皆聖王之瑞也. 已 止也 ○張子曰 鳳至圖出 文明之祥. 伏羲舜文之瑞不至 則夫子之文章知其已矣.

[_09_09_01_]
=== ○子見齊衰者 冕衣裳者 與瞽者 見之雖少必作 過之必趨 (子罕-09-09-01)

齊衰 喪服. 冕 冠也. 衣 上服. 裳 下服. 冕而衣裳 貴者之盛服也. 瞽 無目者. 作 起也. 趨 疾行也. 或曰少 當作坐. ○范氏曰 聖人之心 哀有喪 尊有爵 矜不成人. 其作與趨 蓋有不期然而然者. 尹氏曰 此聖人之誠心 內外一者也.

[_09_10_01_]
=== ○顔淵喟然歎曰 仰之彌高 鑽之彌堅 瞻之在前 忽焉在後 (子罕-09-10-01)

喟 歎聲. 仰彌高 不可及. 鑽彌堅 不可入. 在前在後 恍惚不可爲象 此顔淵深知夫子之道 無窮盡 無方體 而歎之也.

[_09_10_02_]
=== 夫子循循然善誘人 博我以文 約我以禮 (子罕-09-10-02)

循循 有次序貌. 誘 引進也. 博文約禮 敎之序也. 言夫子道雖高妙 而敎人有序也. ○侯氏曰 博我以文 致知格物也. 約我以禮 克己復禮也. 程子曰 此顔子稱聖人最切當處 聖人敎人 唯此二事而已.

[_09_10_03_]
=== 欲罷不能 旣竭吾才 如有所立卓爾 雖欲從之 末由也已 (子罕-09-10-03)

卓 立貌. 末 無也. 此顔子自言其學之所至也. 蓋悅之深而力之盡 所見益親 而又無所用其力也. 吳氏曰 所謂卓爾 亦在乎日用行事之間 非所謂窈冥昏黙者. 程子曰 到此地位 工夫尤難 直是峻絶 又大段著力不得. 楊氏曰 自可欲之謂善 充而至於大 力行之積也. 大而化之 則非力行所及矣. 此顔子所以未達一間也. ○程子曰 此顔子所以爲深知孔子 而善學之者也. 胡氏曰 無上事而喟然歎 此顔子學旣有得 故述其先難之故 後得之由 而歸功於聖人也. 高堅前後 語道體也. 仰鑽瞻忽 未領其要也. 惟夫子循循善誘 先博我以文 使我知古今達事變. 然後約我以禮 使我尊所聞 行所知 如行者之赴家 食者之求飽 是以欲罷不能. 盡心盡力 不少休廢 然後見夫子所立之卓然 雖欲從之 末由也已. 是蓋不怠所從 必求至乎卓立之地也. 抑 斯歎也 其在請事斯語之後 三月不違之時乎.

[_09_11_01_]
=== ○子疾病 子路使門人爲臣 (子罕-09-11-01)

夫子時已去位 無家臣 子路欲以家臣治其喪 其意實尊聖人 而未知所以尊也.

[_09_11_02_]
=== 病間曰 久矣哉 由之行詐也 無臣而爲有臣 吾誰欺 欺天乎 (子罕-09-11-02)

病間 少差也. 病時不知 旣差乃知其事. 故言我之不當有家臣 人皆知之 不可欺也. 而爲有臣 則是欺天而已. 人而欺天 莫大之罪. 引以自咎 其責子路深矣.

[_09_11_03_]
=== 且予與其死於臣之手也 無寧死於二三子之手乎 且予縱不得大葬 予死於道路乎 (子罕-09-11-03)

無寧 寧也. 大葬 謂君臣禮葬. 死於道路 謂棄而不葬. 又曉之以不必然之故. ○范氏曰 曾子將死 起而易簀曰 吾得正而斃焉 斯已矣. 子路欲尊夫子 而不知無臣之不可爲有臣 是以陷於行詐 罪至欺天. 君子之於言動 雖微不可不謹. 夫子深懲子路 所以警學者也. 楊氏曰 非知至而意誠 則用智自私 不知行其所無事 往往自陷於行詐欺天 而莫之知也. 其子路之謂乎.

[_09_12_01_]
=== ○子貢曰 有美玉於斯 韞匵而藏諸 求善賈而沽諸 子曰 沽之哉 沽之哉 我待賈者也 (子罕-09-12-01)

鞰 藏也. 匵 匱也. 沽 賣也. 子貢以孔子有道不仕 故設此二端以問也. 孔子言固當賣之 但當待賈而不當求之耳. ○范氏曰 君子未嘗不欲仕也 又惡不由其道. 士之待禮 猶玉之待賈也. 若伊尹之耕於野 伯夷太公之居於海濱 世無成湯文王 則終焉而已 必不枉道以從人 衒玉而求售也.

[_09_13_01_]
=== ○子欲居九夷 (子罕-09-13-01)

東方之夷 有九種 欲居之者 亦乘桴浮海之意.

[_09_13_02_]
=== 或曰 陋如之何 子曰 君子居之 何陋之有 (子罕-09-13-02)

君子所居則化 何陋之有.

[_09_14_01_]
=== ○子曰 吾自衛反魯 然後樂正 雅頌各得其所 (子罕-09-14-01)

魯哀公十一年冬 孔子自衛反魯 是時周禮在魯 然詩樂亦頗殘缺失次. 孔子周流四方 參互考訂 以知其說. 晩知道終不行 故歸而正之.

[_09_15_01_]
=== ○子曰 出則事公卿 入則事父兄 喪事不敢不勉 不爲酒困 何有於我哉 (子罕-09-15-01)

說見第七篇. 然此則其事愈卑而意愈切矣.

[_09_16_01_]
=== ○子在川上曰 逝者如斯夫 不舍晝夜 (子罕-09-16-01)

天地之化 往者過 來者續 無一息之停 乃道體之本然也. 然其可指而易見者 莫如川流. 故於此發以示人 欲學者時時省察 而無毫髮之間斷也. ○程子曰 此道體也. 天運而不已 日往則月來 寒往則暑來 水流而不息 物生而不窮 皆與道爲體 運乎晝夜 未嘗已也. 是以君子法之 自强不息. 及其至也 純亦不已焉. 又曰 自漢以來 儒者皆不識此義 此見聖人之心 純亦不已也. 純亦不已 乃天德也. 有天德便可語王道 其要只在謹獨. 愚按自此至終篇 皆勉人進學不已之辭.

[_09_17_01_]
=== ○子曰 吾未見好德 如好色者也 (子罕-09-17-01)

謝氏曰 好好色 惡惡臭 誠也. 好德如好色 斯誠好德矣. 然民鮮能之. ○史記 孔子居衛 靈公與夫人同車 使孔子爲次乘 招搖市過之. 孔子醜之 故有是言.

[_09_18_01_]
=== ○子曰 譬如爲山 未成一簣 止吾止也 譬如平地 雖覆一簣 進吾往也 (子罕-09-18-01)

簣 土籠也. 書曰 爲山九仞 功虧一簣. 夫子之言 蓋出於此. 言山成而但少一簣 其止者 吾自止耳. 平地而方覆一簣 其進者吾自往耳. 蓋學者自强不息 則積少成多. 中道而止 則前功盡棄. 其止其往 皆在我而不在人也.

[_09_19_01_]
=== ○子曰 語之而不惰者 其回也與 (子罕-09-19-01)

惰 懈怠也. 范氏曰 顔子聞夫子之言 而心解力行 造次顚沛 未嘗違之. 如萬物得時雨之潤 發榮滋長 何有於惰. 此群弟子所不及也.

[_09_20_01_]
=== ○子謂顔淵曰 惜乎吾見其進也 未見其止也 (子罕-09-20-01)

進止二字 說見上章. 顔子旣死 而孔子惜之 言其方進而未已也 .

[_09_21_01_]
=== ○子曰 苗而不秀者 有矣夫 秀而不實者 有矣夫 (子罕-09-21-01)

穀之始生曰苗 吐華曰秀 成穀曰實. 蓋學而不至於成 有如此者 是以君子貴自勉也.

[_09_22_01_]
=== ○子曰 後生可畏 焉知來者之不如今也 四十五十而無聞焉 斯亦不足畏也已 (子罕-09-22-01)

孔子言 後生年富力彊 足以積學而有待 其勢可畏. 安知其將來不如我之今日乎. 然或不能自勉 至於老而無聞 則不足畏矣. 言此以警人 使及時勉學也. 曾子曰 五十而不以善聞 則不聞矣. 蓋述此意. 尹氏曰 少而不勉 老而無聞 則亦已矣. 自少而進者 安知其不至於極乎. 是可畏也.

[_09_23_01_]
=== ○子曰 法語之言 能無從乎 改之爲貴 巽與之言 能無說乎 繹之爲貴 說而不繹 從而不改 吾末如之何也已矣 (子罕-09-23-01)

法語者 正言之也. 巽言者 婉而導之也. 繹 尋其緖也. 法言人所敬憚 故必從. 然不改 則面從而已. 巽言無所乖忤 故必說 然不繹 則又不足以知其微意之所在也. ○楊氏曰 法言 若孟子論行王政之類 是也. 巽言 若其論好貨好色之類 是也. 語之而不達 拒之而不受 猶之可也. 其或喩焉 則尙庶幾其能改繹矣 從且說矣. 而不改繹焉 則是終不改繹也已. 雖聖人其如之何哉.

[_09_24_01_]
=== ○子曰 主忠信 毋友不如己者 過則勿憚改 (子罕-09-24-01)

重出而逸其半.

[_09_25_01_]
=== ○子曰 三軍可奪帥也 匹夫不可奪志也 (子罕-09-25-01)

侯氏曰 三軍之勇在人 匹夫之志在己 故帥可奪而志不可奪. 如可奪 則亦不足謂之志矣.

[_09_26_01_]
=== ○子曰 衣敝縕袍 與衣狐貉者立 而不恥者 其由也與 (子罕-09-26-01)

敝 壞也. 縕 枲著也. 袍 衣有著者也. 蓋衣之賤者. 狐貉 以狐貉之皮爲裘 衣之貴者. 子路之志如此 則能不以貧富動其心 而可以進於道矣. 故夫子稱之.

[_09_26_02_]
=== 不忮不求 何用不臧 (子罕-09-26-02)

忮 害也. 求 貪也. 臧 善也. 言能不忮不求 則何爲不善乎. 此衛風雄雉之詩 孔子引之 以美子路也. 呂氏曰 貧與富交 彊者必忮 弱者必求.

[_09_26_03_]
=== 子路終身誦之 子曰 是道也 何足以臧 (子罕-09-26-03)

終身誦之 則自喜其能 而不復求進於道矣. 故夫子復言此以警之. ○謝氏曰 恥惡衣惡食 學者之大病 善心不存 蓋由於此. 子路之志如此 其過人遠矣. 然以衆人而能此 則可以爲善矣 子路之賢 宜不止此. 而終身誦之 則非所以進於日新也. 故激而進之.

[_09_27_01_]
=== ○子曰 歲寒 然後知松栢之後彫也 (子罕-09-27-01)

范氏曰 小人之在治世 或與君子無異. 惟臨利害 遇事變 然後君子之所守可見也. ○謝氏曰 士窮見節義 世亂識忠臣 欲學者必周于德.

[_09_28_01_]
=== ○子曰 知者不惑 仁者不憂 勇者不懼 (子罕-09-28-01)

明足以燭理 故不惑. 理足以勝私 故不憂. 氣足以配道義 故不懼 此學之序也.

[_09_29_01_]
=== ○子曰 可與共學 未可與適道 可與適道 未可與立 可與立 未可與權 (子罕-09-29-01)

可與者 言其可與共爲此事也. 程子曰 可與共學 知所以求之也. 可與適道 知所往也. 可與立者 篤志固執而不變也. 權 稱錘也. 所以稱物而知輕重者也. 可與權 謂能權輕重使合義也. ○楊氏曰 知爲己 則可與共學矣. 學足以明善 然後可與適道. 信道篤 然後可與立. 知時措之宜 然後可與權. 洪氏曰 易九卦 終於巽 以行權 權者聖人之大用. 未能立而言權 猶人未能立而欲行 鮮不仆矣. 程子曰 漢儒以反經合道爲權 故有權變權術之論 皆非也. 權只是經也. 自漢以下 無人識權字. 愚按先儒誤以此章連下文偏其反而爲一章 故有反經合道之說. 程子非之 是矣. 然以孟子嫂溺援之以手之義推之 則權與經亦當有辨.

[_09_30_01_]
=== ○唐棣之華 偏其反而 豈不爾思 室是遠而 (子罕-09-30-01)

唐棣 郁李也. 偏 晉書作翩. 然則反 亦當與翻同. 言華之搖動也. 而 助語也. 此逸詩也. 於六義屬興. 上兩句無意義 但以起下兩句之辭耳. 其所謂爾 亦不知其何所指也.

[_09_30_02_]
=== 子曰 未之思也 夫何遠之有 (子罕-09-30-02)

夫子借其言而反之 蓋前篇仁遠乎哉之意. ○程子曰 聖人未嘗言易以驕人之志 亦未嘗言難以阻人之進. 但曰未之思也 夫何遠之有. 此言極有涵蓄 意思深遠.

論語集註大全卷之十

[_10_]
== 鄕黨第十

楊氏曰 聖人之所謂道者 不離乎日用之間也. 故夫子之平日一動一靜 門人皆審視而詳記之. 尹氏曰 甚矣孔門弟子之嗜學也. 於聖人之容色言動 無不謹書而備錄之以貽後世. 今讀其書 卽其事 宛然如聖人之在目也. 雖然 聖人豈拘拘而爲之者哉 蓋盛德之至 動容周旋 自中乎禮耳. 學者欲潛心於聖人 宜於此求焉. 舊說凡一章 今分爲十七節.

[_10_01_01_]
=== ○孔子於鄕黨 恂恂如也 似不能言者 (鄕黨-10-01-01)

恂恂 信實之貌. 似不能言者 謙卑遜順 不以賢知先人也. 鄕黨 父兄宗族之所在 故孔子居之 其容貌辭氣如此.

[_10_01_02_]
=== 其在宗廟朝廷 便便言 唯謹爾 (鄕黨-10-01-02)

便便 辯也. 宗廟 禮法之所在. 朝廷 政事之所出. 言不可以不明辯 故必詳問而極言之 但謹而不放爾. ○此一節 記孔子在鄕黨宗廟朝廷言貌之不同.

[_10_02_01_]
=== ○朝 與下大夫言 侃侃如也 與上大夫言 誾誾如也 (鄕黨-10-02-01)

此君未視朝時也. 王制 諸侯上大夫卿下大夫五人. 許氏說文 侃侃 剛直也. 誾誾 和悅而諍也.

[_10_02_02_]
=== 君在踧踖如也 與與如也 (鄕黨-10-02-02)

君在 視朝也. 踧踖 恭敬不寧之貌. 與與 威儀中適之貌. ○張子曰 與與 不忘向君也 亦通. ○此一節 記孔子在朝廷 事上接下之不同也.

[_10_03_01_]
=== ○君召使擯 色勃如也 足躩如也 (鄕黨-10-03-01)

擯 主國之君所使出接賓者. 勃 變色貌. 躩 盤辟貌. 皆敬君命故也.

[_10_03_02_]
=== 揖所與立 左右手 衣前後 襜如也 (鄕黨-10-03-02)

所與立 謂同爲擯者也. 擯用命數之半 如上公九命 則用五人 以次傳命. 揖左人則左其手 揖右人則右其手 襜 整貌.

[_10_03_03_]
=== 趨進 翼如也 (鄕黨-10-03-03)

疾趨而進 張拱端好 如鳥舒翼.

[_10_03_04_]
=== 賓退 必復命曰 賓不顧矣 (鄕黨-10-03-04)

紓君敬也. ○此一節記孔子爲君擯相之容.

[_10_04_01_]
=== ○入公門 鞠躬如也 如不容 (鄕黨-10-04-01)

鞠躬 曲身也. 公門 高大而若不容 敬之至也.

[_10_04_02_]
=== 立不中門 行不履閾 (鄕黨-10-04-02)

中門 中於門也. 謂當棖闑之間 君出入處也. 閾 門限也. 禮士大夫出入公門由闑右 不踐閾. 謝氏曰 立中門 則當尊. 行履閾 則不恪.

[_10_04_03_]
=== 過位 色勃如也 足躩如也 其言似不足者 (鄕黨-10-04-03)

位 君之虛位 謂門屛之間 人君宁立之處 所謂宁也. 君雖不在 過之必敬 不敢以虛位 而慢之也. 言似不足 不敢肆也.

[_10_04_04_]
=== 攝齊升堂 鞠躬如也 屛氣似不息者 (鄕黨-10-04-04)

攝 摳也. 齊 衣下縫也. 禮 將升堂 兩手摳衣使去地尺 恐躡之而傾跌失容也. 屛 藏也. 息 鼻息出入者也. 近至尊 氣容肅也.

[_10_04_05_]
=== 出降一等 逞顔色 怡怡如也 沒階趨進 翼如也 復其位 踧踖如也 (鄕黨-10-04-05)

陸氏曰 趨下本無進字 俗本有之 誤也. ○等 階之級也. 逞 放也. 漸遠所尊 舒氣解顔. 怡怡 和悅也. 沒階 下盡階也. 趨 走就位也. 復位踧踖 敬之餘也. ○此一節 記孔子在朝之容.

[_10_05_01_]
=== ○執圭 鞠躬如也 如不勝 上如揖 下如授 勃如戰色 足蹜蹜如有循 (鄕黨-10-05-01)

圭 諸侯命圭 聘問鄰國則使大夫執以通信. 如不勝 執主器執輕如不克 敬謹之至也. 上如揖下如授 謂執圭平衡 手與心齊 高不過揖 卑不過授也. 戰色 戰而色懼也. 蹜蹜 擧足促狹也. 如有循 記所謂擧前曳踵 言行不離地 如緣物也.

[_10_05_02_]
=== 享禮 有容色 (鄕黨-10-05-02)

享 獻也. 旣聘而享 用圭璧 有庭實 有容色 和也. 儀禮曰 發氣滿容.

[_10_05_03_]
=== 私覿 愉愉如也 (鄕黨-10-05-03)

私覿 以私禮見也. 愉愉則又和矣. ○此一節 記孔子爲君聘於隣國之禮也. 鼂氏曰 孔子定公九年仕魯 至十三年適齊 其間絶無朝聘往來之事. 疑使擯執圭兩條 但孔子嘗言其禮 當如此爾.

[_10_06_01_]
=== ○君子不以紺緅飾 (鄕黨-10-06-01)

君子 謂孔子. 紺 深靑揚赤色 齊服也. 緅 絳色 三年之喪 以飾練服也. 飾 領緣也.

[_10_06_02_]
=== 紅紫 不以爲褻服 (鄕黨-10-06-02)

紅紫 間色不正 且近於婦人女子之服也. 褻服 私居服也. 言此則不以爲朝祭之服可知.

[_10_06_03_]
=== 當暑 袗絺綌 必表而出之 (鄕黨-10-06-03)

袗 單也. 葛之精者曰絺 麤者曰綌. 表而出之 謂先著裏衣 表絺綌而出之於外 欲其不見體也. 詩所謂蒙彼縐絺 是也.

[_10_06_04_]
=== 緇衣羔裘 素衣麑裘 黃衣狐裘 (鄕黨-10-06-04)

緇 黑色. 羔裘用黑羊皮. 麑 鹿子 色白. 狐 色黃. 衣以裼裘 欲其相稱.

[_10_06_05_]
=== 褻裘長 短右袂 (鄕黨-10-06-05)

長欲其溫. 短右袂 所以便作事.

[_10_06_06_]
=== 必有寢衣 長一身有半 (鄕黨-10-06-06)

齊主於敬 不可解衣而寢 又不可著明衣而寢 故別有寢衣. 其半 蓋以覆足. 程子曰 此錯簡 當在齊必有明衣布之下. 愚謂如此則此條與明衣變食旣得以類相從 而褻裘狐貉 亦得以類相從矣.

[_10_06_07_]
=== 狐貉之厚以居 (鄕黨-10-06-07)

狐貉毛深溫厚 私居取其適體.

[_10_06_08_]
=== 去喪無所不佩 (鄕黨-10-06-08)

君子無故 玉不去身. 觿礪之屬 亦皆佩也.

[_10_06_09_]
=== 非帷裳必殺之 (鄕黨-10-06-09)

朝祭之服 裳用正幅 如帷 要有襞積 而旁無殺縫. 其餘若深衣 要半下 齊倍要 則無襞積 而有殺縫矣.

[_10_06_10_]
=== 羔裘玄冠 不以吊 (鄕黨-10-06-10)

喪主素 吉主玄. 弔必變服 所以哀死.

[_10_06_11_]
=== 吉月必朝服而朝 (鄕黨-10-06-11)

吉月 月朔也. 孔子在魯致仕時 如此. ○此一節記孔子衣服之制. 蘇氏曰 此孔氏遺書

雜記曲禮 非特孔子事也.

[_10_07_01_]
=== ○齊 必有明衣 布 (鄕黨-10-07-01)

齊必沐浴 浴竟卽著明衣 所以明潔其體也 以布爲之 此下脫前章寢衣一簡

[_10_07_02_]
=== 齊必變食 居必遷坐 (鄕黨-10-07-02)

變食 謂不飮酒 不筎葷. 遷坐 易常處也. ○此一節 記孔子謹齊之事. 楊氏曰 齊所以交神 故致潔變常以盡敬.

[_10_08_01_]
=== ○食不厭精 膾不厭細 (鄕黨-10-08-01)

食 飯也. 精 鑿也. 牛羊與魚之腥 聶而切之爲膾. 食精則能養人 膾麤則能害人. 不厭 言以是爲善 非謂必欲如是也.

[_10_08_02_]
=== 食饐而餲 魚餒而肉敗不食 色惡不食 臭惡不食 失飪不食 不時不食 (鄕黨-10-08-02)

饐 飯傷熱濕也. 餲 味變也. 魚爛曰餒 肉腐曰敗. 色惡臭惡 未敗而色臭變也. 飪 烹調生熟之節也. 不時 五穀不成 果實未熟之類. 此數者 皆足以傷人 故不食.

[_10_08_03_]
=== 割不正不食 不得其醬不食 (鄕黨-10-08-03)

割肉不方正者 不食. 造次不離於正也. 漢陸績之母 切肉未嘗不方 斷葱以寸爲度 蓋其質美 與此暗合也. 食肉用醬 各有所宜 不得則不食 惡其不備也. 此二者 無害於人 但不以嗜味而苟食耳 .

[_10_08_04_]
=== 肉雖多 不使勝食氣 唯酒無量 不及亂 (鄕黨-10-08-04)

食以穀爲主 故不使肉勝食氣. 酒以爲人合懽 故不爲量 但以醉爲節 而不及亂耳. 程子曰 不及亂者 非唯不使亂志 雖血氣亦不可使亂 但浹洽而已可也.

[_10_08_05_]
=== 沽酒市脯不食 (鄕黨-10-08-05)

沽市 皆買也. 恐不精潔 或傷人也. 與不嘗康子之藥同意.

[_10_08_06_]
=== 不撤薑食 (鄕黨-10-08-06)

薑通神明 去穢惡 故不撤.

[_10_08_07_]
=== 不多食 (鄕黨-10-08-07)

適可而止 無貪心也.

[_10_08_08_]
=== 祭於公 不宿肉 祭肉不出三日 出三日 不食之矣 (鄕黨-10-08-08)

助祭於公 所得胙肉 歸卽頒賜 不俟經宿者 不留神惠也. 家之祭肉 則不過三日 皆以分賜 蓋過三日則肉必敗 而人不食之 是褻鬼神之餘也. 但比君所賜胙 可少緩耳.

[_10_08_09_]
=== 食不語 寢不言 (鄕黨-10-08-09)

答述曰語 自言曰言. 范氏曰 聖人存心不他 當食而食 當寢而寢 言語非其時也. 楊氏曰 肺爲氣主 而聲出焉. 寢食則氣窒而不通 語言恐傷之也. 亦通.

[_10_08_10_]
=== 雖疏食菜羹瓜祭 必齊如也 (鄕黨-10-08-10)

陸氏曰 魯論瓜作必. ○古人飮食 每種各出少許 置之豆間之地 以祭先代始爲飮食之人 不忘本也. 齊 嚴敬貌. 孔子雖薄物必祭 其祭必敬 聖人之誠也. ○此一節 記孔子飮食之節. 謝氏曰 聖人飮食如此 非極口腹之欲 蓋養氣體 不以傷生當如此. 然聖人之所不食 窮口腹者 或反食之 欲心勝而不暇擇也.

[_10_09_01_]
=== ○席不正 不坐 (鄕黨-10-09-01)

謝氏曰 聖人心安於正 故於位之不正者 雖小不處.

[_10_10_01_]
=== ○鄕人飮酒 杖者出 斯出矣 (鄕黨-10-10-01)

杖者 老人也. 六十杖於鄕. 未出不敢先 旣出不敢後.

[_10_10_02_]
=== 鄕人儺 朝服而立於阼階 (鄕黨-10-10-02)

儺 所以逐疫. 周禮方相氏掌之. 阼階 東階也. 儺雖古禮 而近於戱 亦朝服而臨之者 無所不用其誠敬也. 或曰 恐其驚先祖五祀之神 欲其依己而安也. ○此一節 記孔子居鄕之事.

[_10_11_01_]
=== ○問人於他邦 再拜而送之 (鄕黨-10-11-01)

拜送使者 如親見之 敬也.

[_10_11_02_]
=== 康子饋藥 拜而受之 曰 丘未達 不敢嘗 (鄕黨-10-11-02)

范氏曰 凡賜食 必嘗以拜. 藥未達則不敢嘗 受而不食 則虛人之賜 故告之如此. 然則可飮而飮 不可飮而不飮 皆在其中矣. 楊氏曰 大夫有賜 拜而受之 禮也. 未達不敢嘗 謹疾也. 必告之 直也. ○此一節 記孔子與人交之誠意.

[_10_12_01_]
=== ○廐焚 子退朝 曰 傷人乎 不問馬 (鄕黨-10-12-01)

非不愛馬 然恐傷人之意多 故未暇問. 蓋貴人賤畜 理當如此.

[_10_13_01_]
=== ○君賜食 必正席先嘗之 君賜腥 必熟而薦之 君賜生 必畜之 (鄕黨-10-13-01)

食恐或餕餘 故不以薦. 正席先嘗 如對君也. 言先嘗 則餘當以頒賜矣. 腥 生肉 熟而薦之祖考 榮君賜也. 畜之者 仁君之惠 無故不敢殺也.

[_10_13_02_]
=== 侍食於君 君祭先飯 (鄕黨-10-13-02)

周禮 王日一擧 膳夫授祭品嘗食 王乃食. 故侍食者 君祭 則己不祭而先飯. 若爲君嘗食 然 不敢當客禮也.

[_10_13_03_]
=== 疾 君視之 東首 加朝服拖紳 (鄕黨-10-13-03)

東首 以受生氣也. 病臥不能著衣束帶 又不可以褻服見君 故加朝服於身 又引大帶於上也.

[_10_13_04_]
=== 君命召 不俟駕行矣 (鄕黨-10-13-04)

急趨君命 行出而駕車隨之. ○此一節 記孔子事君之禮.

[_10_14_01_]
=== ○入太廟 每事問 (鄕黨-10-14-01)

[_10_15_01_]
=== ○朋友死 無所歸 曰 於我殯 (鄕黨-10-15-01)

朋友以義合 死無所歸 不得不嬪.

[_10_15_02_]
=== 朋友之饋 雖車馬 非祭肉 不拜 (鄕黨-10-15-02)

朋友有通財之義 故雖車馬之重 不拜. 祭肉則拜者 敬其祖考同於己親也. ○此一節 記孔子交朋友之義.

[_10_16_01_]
=== ○寢不尸 居不容 (鄕黨-10-16-01)

尸 謂偃臥似死人也. 居 居家. 容 容儀. 范氏曰 寢不尸 非惡其類於死也. 惰慢之氣 不設於身體 雖舒布其四體 而亦未嘗肆耳. 居不容 非惰也 但不若奉祭祀 見賓客而已. 申申夭夭是也.

[_10_16_02_]
=== 見齊衰者雖狎必變 見冕者與瞽者 雖褻必以貌 (鄕黨-10-16-02)

狎 謂素親狎. 褻 謂燕見. 貌 謂禮貌. 餘見前篇.

[_10_16_03_]
=== 凶服者式之 式負版者 (鄕黨-10-16-03)

式 車前橫木 有所敬則俯而憑之. 負版 持邦國圖籍者. 式此二者 哀有喪 重民數也. 人惟萬物之靈 而王者之所天也. 故周禮獻民數於王 王拜受之 況其下者 敢不敬乎.

[_10_16_04_]
=== 有盛饌 必變色而作 (鄕黨-10-16-04)

敬主人之禮 非以其饌也.

[_10_16_05_]
=== 迅雷 風烈必變 (鄕黨-10-16-05)

迅 疾也. 烈 猛也. 必變者 所以敬天之怒. 記曰 若有疾風迅雷甚雨 則必變 雖夜必興 衣服冠而坐. ○此一節 記孔子容貌之變.

[_10_17_01_]
=== ○升車 必正立執綏 (鄕黨-10-17-01)

綏 挽以上車之索也. 范氏曰 正立執綏 則心體無不正 而誠意肅恭矣. 蓋君子莊敬 無所不在 升車則見於此也.

[_10_17_02_]
=== 車中不內顧 不疾言 不親指 (鄕黨-10-17-02)

內顧 回視也. 禮曰 顧不過轂 三者皆失容 且惑人. ○此一節 記孔子升車之容.

[_10_18_01_]
=== ○色斯擧矣 翔而後集 (鄕黨-10-18-01)

言鳥見人之顔色不善 則飛去. 回翔審視 而後下止. 人之見幾而作 審擇所處 亦當如此. 然此上下必有闕文矣.

[_10_18_02_]
=== 曰 山梁雌雉 時哉時哉 子路共之 三嗅而作 (鄕黨-10-18-02)

邢氏曰 梁 橋也. 時哉 言雉之飮啄得其時. 子路不達 以爲時物而共具之. 孔子不食 三嗅其氣而起. 鼂氏曰 石經嗅作戞 謂雉鳴也. 劉聘君曰 嗅 當作狊 古闃反 張兩翅也 見爾雅. 愚按如後兩說 則共字當爲拱執之義 然此必有闕文 不可强爲之說. 姑記所聞 以俟知者.

論語集註大全卷之十一

[_11_]
== 先進第十一

此篇多評弟子賢否 凡二十五章. 胡氏曰 此篇記閔子蹇言行者四 而其一直稱閔子疑閔氏門人所記也.

[_11_01_01_]
=== ○子曰 先進 於禮樂 野人也 後進 於禮樂 君子也 (先進-11-01-01)

先進後進 猶言前輩後輩. 野人 謂郊外之民. 君子 謂賢士大夫也. 程子曰 先進於禮樂 文質得宜 今反謂之質朴 而以爲野人. 後進之於禮樂 文過其質 今反謂之彬彬 而以爲君子. 蓋周末文勝 故時人之言如此 不自知其過於文也.

[_11_01_02_]
=== 如用之 則吾從先進 (先進-11-01-02)

用之 謂用禮樂. 孔子旣述時人之言 又自言其如此 蓋欲損過以就中也.

[_11_02_01_]
=== ○子曰 從我於陳蔡者 皆不及門也 (先進-11-02-01)

孔子嘗厄於陳蔡之間 弟子多從之者 此時皆不在門 故孔子思之. 蓋不忘其相從於患難之中也.

[_11_02_02_]
=== 德行 顔淵閔子蹇冉伯牛仲弓 言語 宰我子貢 政事 冉有季路 文學子游子夏 (先進-11-02-02)

弟子因孔子之言 記此十人 而幷目其所長 分爲四科. 孔子敎人 各因其材 於此可見. ○程子曰 四科 乃從夫子於陳蔡者爾 門人之賢者 固不止此. 曾子傳道而不與焉 故知十哲世俗論也.

[_11_03_01_]
=== ○子曰 回也 非助我者也 於吾言 無所不說 (先進-11-03-01)

助我 若子夏之起予 因疑問而有以相長也. 顔子於聖人之言 黙識心通 無所疑問. 故夫子云然. 其辭若有憾焉 其實乃深喜之. ○胡氏曰 夫子之於回 豈眞以助我望之. 蓋聖人之謙德 又以深贊顔氏云爾.

[_11_04_01_]
=== ○子曰 孝哉閔子蹇 人不間於其父母昆弟之言 (先進-11-04-01)

胡氏曰 父母兄弟稱其孝友 人皆信之 無異辭者. 蓋其孝友之實 有以積於中而著於外 故夫子歎而美之.

[_11_05_01_]
=== ○南容三復白圭 孔子以其兄之子妻之 (先進-11-05-01)

詩 大雅抑之篇曰 白圭之玷 尙可磨也. 斯言之玷 不可爲也. 南容一日三復此言 事見家語. 蓋深有意於謹言也. 此邦有道所以不廢 邦無道所以免禍. 故孔子以兄子妻之. ○范氏曰 言者行之表 行者言之實. 未有易其言而能謹於行者. 南容欲謹其言如此 則必能謹其行矣.

[_11_06_01_]
=== ○季康子問弟子孰爲好學 孔子對曰 有顔回者好學 不幸短命死矣 今也則亡 (先進-11-06-01)

范氏曰 哀公康子 問同而對有詳略者 臣之告君 不可不盡. 若康子者 必待其能問乃告之. 此敎誨之道也.

[_11_07_01_]
=== ○顔淵死 顔路請子之車以爲之槨 (先進-11-07-01)

顔路 淵之父 名無繇 少孔子六歲. 孔子始敎而受學焉. 槨 外棺也. 請爲槨 欲賣車以買槨也.

[_11_07_02_]
=== 子曰 才不才 亦各言其子也 鯉也死 有棺而無槨 吾不徒行以爲之槨 以吾從大夫之後 不可徒行也 (先進-11-07-02)

鯉 孔子之子伯魚也. 先孔子卒. 言鯉之才雖不及顔淵 然己與顔路以父視之 則皆子也. 孔子時已致仕 尙從大夫之列. 言後 謙辭. ○胡氏曰 孔子遇舊館人之喪 嘗脫驂以賻之矣. 今乃不許顔路之請 何邪. 葬可以無槨 驂可以脫而復求. 大夫不可以徒行 命車不可以與人 而鬻諸市也. 且爲所識窮乏者得我 而勉强以副其意 豈誠心與直道哉. 或者以爲 君子行禮 視吾之有無而已. 夫君子之用財 視義之可否 豈獨視有無而已哉.

[_11_08_01_]
=== ○顔淵死 子曰 噫 天喪予 天喪予 (先進-11-08-01)

噫 傷痛聲. 悼道無傳 若天喪己也.

[_11_09_01_]
=== ○顔淵死 子哭之慟 從者曰 子慟矣 (先進-11-09-01)

慟 哀過也.

[_11_09_02_]
=== 曰 有慟乎 (先進-11-09-02)

哀傷之至 不自知也.

[_11_09_03_]
=== 非夫人之爲慟而誰爲 (先進-11-09-03)

夫人 謂顔淵. 言其死可惜 哭之宜慟 非他人之比也. ○胡氏曰 痛惜之至 施當其可皆情性之正也.

[_11_10_01_]
=== ○顔淵死 門人欲厚葬之 子曰 不可 (先進-11-10-01)

喪具 稱家之有無 貧而厚葬 不循理也. 故夫子止之.

[_11_10_02_]
=== 門人厚葬之 (先進-11-10-02)

蓋顔路聽之.

[_11_10_03_]
=== 子曰 回也 視予猶父也 予不得視猶子也 非我也 夫二三子也 (先進-11-10-03)

嘆不得如葬鯉之得宜 以責門人也.

[_11_11_01_]
=== ○季路問事鬼神 子曰 未能事人 焉能事鬼 敢問死 曰 未知生 焉知死 (先進-11-11-01)

問事鬼神 蓋求所以奉祭祀之意. 而死者人之所必有 不可不知 皆切問也. 然非誠敬足以事人 則必不能事神. 非原始而知所以生 則必不能反終而知所以死. 蓋幽明始終 初無二理 但學之有序 不可躐等 故夫子告之如此. ○程子曰 晝夜者 死生之道也. 知生之道 則知死之道. 盡事人之道 則盡事鬼之道. 死生人鬼 一而二 二而一者也. 或言夫子不告 子路 不知此乃所以深告之也.

[_11_12_01_]
=== ○閔子侍側 誾誾如也 子路 行行如也 冉有 子貢 侃侃如也 子樂 (先進-11-12-01)

行行 剛强之貌. 子樂者 樂得英才而敎育之.

[_11_12_02_]
=== 若由也不得其死然 (先進-11-12-02)

尹氏曰 子路剛强 有不得其死之理 故因以戒之. 其後子路卒死於衛孔悝之難. 洪氏曰 漢書引此句上有曰字. 或云 上文樂字 卽曰字之誤.

[_11_13_01_]
=== ○魯人爲長府 (先進-11-13-01)

長府 藏名. 藏貨財曰府 爲 蓋改作之.

[_11_13_02_]
=== 閔子騫曰 仍舊貫 如之何 何必改作 (先進-11-13-02)

仍 因也. 貫 事也. 王氏曰 改作勞民傷財 在於得已 則不如仍舊貫之善.

[_11_13_03_]
=== 子曰 夫人不言 言必有中 (先進-11-13-03)

言不妄發 發必當理. 惟有德者能之.

[_11_14_01_]
=== ○子曰 由之瑟 奚爲於丘之門 (先進-11-14-01)

程子曰 言其聲之不和 與己不同也. 家語云 子路鼓瑟 有北鄙殺伐之聲. 蓋其氣質剛勇 而不足於中和 故其發於聲者 如此.

[_11_14_02_]
=== 門人不敬子路 子曰 由也升堂矣 未入於室也 (先進-11-14-02)

門人以夫子之言 遂不敬子路. 故夫子釋之. 升堂入室 喩入道之次第. 言子路之學 已造乎正大高明之域 特未深入精微之奧耳. 未可以一事之失而遽忽之也.

[_11_15_01_]
=== ○子貢問 師與商也孰賢 子曰 師也過 商也不及 (先進-11-15-01)

子張 才高意廣 而好爲苟難 故常過中. 子夏 篤信謹守 而規模狹隘 故常不及.

[_11_15_02_]
=== 曰 然則師愈與 (先進-11-15-02)

愈 猶勝也.

[_11_15_03_]
=== 子曰 過猶不及 (先進-11-15-03)

道以中庸爲至. 賢知之過 雖若勝於愚不肖之不及 然其失中則一也. ○尹氏曰 中庸之爲德也 其至矣乎. 夫過與不及 均也. 差之毫釐 繆以千里. 故聖人之敎 抑其過 引其不及 歸於中道而已.

[_11_16_01_]
=== ○季氏富於周公 而求也爲之聚斂 而附益之 (先進-11-16-01)

周公以王室至親 有大功 位冢宰 其富宜矣. 季氏以諸侯之卿 而富過之 非攘奪其君 刻剝其民 何以得此. 冉求爲季氏宰 又爲之急賦稅以益其富.

[_11_16_02_]
=== 子曰 非吾徒也 小子鳴鼓而攻之可也 (先進-11-16-02)

非吾徒 絶之也. 小子鳴鼓而攻之 使門人聲其罪以責之也. 聖人之惡黨惡而害民也 如此. 然師嚴而友親 故己絶之 而猶使門人正之. 又見其愛人之無已也. ○范氏曰 冉有以政事之才 施於季氏 故爲不善至於如此 由其心術不明 不能反求諸身 而以仕爲急故也.

[_11_17_01_]
=== ○柴也愚 (先進-11-17-01)

柴 孔子弟子 姓高 字子羔. 愚者 知不足而厚有餘 家語記其足不履影 啓蟄不殺 方長不折 執親之喪 泣血三年 未嘗見齒. 避難而行 不徑不竇 可以見其爲人矣.

[_11_17_02_]
=== 參也魯 (先進-11-17-02)

魯 鈍也. 程子曰 參也竟以魯得之. 又曰 曾子之學 誠篤而已. 聖門學者 聰明才辨 不爲不多 而卒傳其道 乃質魯之人爾. 故學以誠實爲貴也. 尹氏曰 曾子之才魯 故其學也確 所以能深造乎道也.

[_11_17_03_]
=== 師也辟 (先進-11-17-03)

辟 便辟也. 謂習於容止 少誠實也.

[_11_17_04_]
=== 由也喭 (先進-11-17-04)

喭 粗俗也. 傳稱喭者 謂俗論也. ○楊氏曰 四者性之偏 語之使知自勵也. 吳氏曰 此章之首 脫子曰二字. 或疑下章子曰當在此章之首 而通爲一章.

[_11_18_01_]
=== ○子曰 回也 其庶乎 屢空 (先進-11-18-01)

庶 近也. 言近道也. 屢空 數至空匱也. 不以貧窶動心而求富 故屢至於空匱也. 言其近道 又能安貧也.

[_11_18_02_]
=== 賜不受命 而貨殖焉 億則屢中 (先進-11-18-02)

命 謂天命. 貨殖 貨財生殖也. 億 意度也. 言子貢不如顔子之安貧樂道 然其才識之明 亦能料事而多中也. 程子曰 子貢之貨殖 非若後人之豊財 但此心未忘耳. 然此亦子貢少時事 至聞性與天道 則不爲此矣. ○范氏曰 屢空者 簞食瓢飮屢絶而不改其樂也. 天下之物 豈有可動其中者哉. 貧富在天 而子貢以貨殖爲心 則是不能安受天命矣. 其言而多中者 億而已 非窮理樂天者也. 夫子嘗曰 賜不幸言而中 是使賜多言也. 聖人之不貴言也如是.

[_11_19_01_]
=== ○子張問善人之道 子曰 不踐迹 亦不入於室 (先進-11-19-01)

善人 質美而未學者也. 程子曰 踐迹 如言循途守轍. 善人雖不必踐舊迹 而自不爲惡. 然亦不能入聖人之室也. ○張子曰 善人欲仁而未志於學者也. 欲仁 故雖不踐成法 亦不蹈於惡 有諸己也. 由不學 故無自而入聖人之室也.

[_11_20_01_]
=== ○子曰 論篤是與 君子者乎 色壯者乎 (先進-11-20-01)

言但以其言論篤實而與之 則未知爲君子者乎 爲色莊者乎. 言不可以言貌取人也.

[_11_21_01_]
=== ○子路問聞斯行諸 子曰 有父兄在 如之何其聞斯行之 冉有問聞斯行諸 子曰 聞斯行之 公西華曰 由也問聞斯行諸 子曰 有父兄在 求也問聞斯行諸 子曰 聞斯行之 赤也惑 敢問 子曰 求也退 故進之 由也兼人 故退之 (先進-11-21-01)

兼人 謂勝人也. 張敬夫曰 聞義固當勇爲 然有父兄在 則有不可得而專者. 若不禀命而行 則反傷於義矣. 子路有聞 未之能行 唯恐有聞. 則於所當爲 不患其不能爲矣. 特患爲之之意或過 而於所當禀命者有闕耳. 若冉求之資禀 失之弱 不患其不禀命也 患其於所當爲者 逡巡畏縮 而爲之不勇耳. 聖人一進之一退之 所以約之於義理之中 而使之無過不及之患也.

[_11_22_01_]
=== ○子畏於匡 顔淵後 子曰 吾以女爲死矣 曰 子在 回何敢死 (先進-11-22-01)

後 謂相失在後. 何敢死 謂不赴鬪而必死也. 胡氏曰 先王之制 民生於三 事之如一 惟其所在 則致死焉. 況顔淵之於孔子 恩義兼盡 又非他人之爲師弟子者而已. 卽夫子不幸而遇難 回必捐生以赴之矣. 捐生以赴之 幸而不死 則必上告天子 下告方伯 請討以復讐 不但已也. 夫子而在 則回何爲而不愛其死 以犯匡人之鋒乎.

[_11_23_01_]
=== ○季子然問仲由冉求 可謂大臣與 (先進-11-23-01)

子然 季氏子弟 自多其家得臣二子 故問之.

[_11_23_02_]
=== 子曰 吾以子爲異之問 曾由與求之問 (先進-11-23-02)

異 非常也 曾 猶乃也. 輕二子 以抑季然也.

[_11_23_03_]
=== 所謂大臣者 以道事君 不可則止 (先進-11-23-03)

以道事君者 不從君之欲. 不可則止者 必行己之志.

[_11_23_04_]
=== 今由與求也 可謂具臣矣 (先進-11-23-04)

具臣 謂備臣數而已.

[_11_23_05_]
=== 曰 然則從之者與 (先進-11-23-05)

意二子旣非大臣 則從季氏之所爲而已.

[_11_23_06_]
=== 子曰 殺父與君 亦不從也 (先進-11-23-06)

言二子雖不足於大臣之道 然君臣之義 則聞之熟矣. 弑逆大故 必不從之. 蓋深許二子以死難不可奪之節 而又以陰折季氏不臣之心也. ○尹氏曰 季氏專權僣竊 二子仕其家 而不能正也 知其不可而不能止也 可謂具臣矣. 是時季氏已有無君之心 故自多其得人 意其可使從己也. 故曰弑父與君 亦不從也. 其庶乎二子可免矣.

[_11_24_01_]
=== ○子路使子羔 爲費宰 (先進-11-24-01)

子路爲季氏宰而擧之也.

[_11_24_02_]
=== 子曰 賊夫人之子 (先進-11-24-02)

賊 害也. 言子羔 質美而未學 遽使治民 適以害之.

[_11_24_03_]
=== 子路曰 有民人焉 有社稷焉 何必讀書 然後爲學 (先進-11-24-03)

言治民事神 皆所以爲學.

[_11_42_04_]
=== 子曰 是故惡夫佞者 (先進-11-42-04)

治民事神 固學者事. 然必學之己成 然後可仕以行其學. 若初未嘗學 而使之卽仕爲學 其不至於慢神而虐民者 幾希矣. 子路之言 非其本意 但理屈詞窮 而取辦於口以禦人耳. 故夫子不斥其非 而特惡其佞也. ○范氏曰 古者學而後入政 未聞以政學者也. 蓋道之本 在於修身 而後及於治人. 其說具於方冊 讀而知之. 然後能行 何可以不讀書也. 子路乃欲使子羔以政爲學 失先後本末之序矣. 不知其過而以口給禦人 故夫子惡其佞也.

[_11_25_01_]
=== ○子路 曾晳 冉有 公西華 侍坐 (先進-11-25-01)

晳 曾參父 名點.

[_11_25_02_]
=== 子曰 以吾一日長乎爾 毋吾以也 (先進-11-25-02)

言我雖年少長於女 然汝勿以我長而難言. 蓋誘之盡言以觀其志 而聖人和氣謙德 於此亦可見矣.

[_11_25_03_]
=== 居則曰 不吾知也 如或知爾 則何以哉 (先進-11-25-03)

言女平居 則言人不知我. 如或有人知女 則女將何以爲用也.

[_11_25_04_]
=== 子路率爾而對曰 千乘之國 攝乎大國之間 加之以師旅 因之以饑饉 由也爲之 比及三年 可使有勇 且知方也 夫子哂之 (先進-11-25-04)

率爾 輕遽之貌. 攝 管束也. 二千五百人爲師 五百人爲旅. 因 仍也. 穀不熟曰饑. 菜不熟曰饉. 方 向也 謂向義也. 民向義 則能親其上死其長矣. 哂 微笑也.

[_11_25_05_]
=== 求 爾何如 對曰 方六七十 如五六十 求也爲之 比及三年 可使足民 如其禮樂 以俟君子 (先進-11-25-05)

求爾何如 孔子問也 下放此. 方六七十里 小國也. 如 猶或也. 五六十里 則又小矣. 足 富足也. 俟君子 言非己所能. 冉有謙退 又以子路見哂故 其辭益遜.

[_11_25_06_]
=== 赤 爾何如 對曰 非曰能之 願學焉 宗廟之事 如會同 端章甫 願爲小相焉 (先進-11-25-06)

公西華 志於禮樂之事 嫌以君子自居 故將言己志而先爲遜辭. 言未能而願學也. 宗廟之事 謂祭祀. 諸侯時見曰會 衆覜曰同. 端 玄端. 服 章甫 禮冠. 相 贊君之禮者. 言小 亦謙辭.

[_11_25_07_]
=== 點 爾何如 鼓瑟希 鏗爾 舍瑟而作 對曰 異乎三子者之撰 子曰 何傷乎 亦各言其志也 曰 莫春者 春服旣成 冠者五六人童子六七人 浴乎沂 風乎舞雩 詠而歸 夫子喟然嘆曰 吾與點也 (先進-11-25-07)

四子侍坐 以齒爲序 則點當次對. 以方鼓瑟 故孔子先問求赤而後及點也. 希 間歇也. 作 起也. 撰 具也. 莫春 和煦之時. 春服 單袷之衣. 浴 盥濯也. 今上巳祓除 是也. 沂 水名 在魯城南 地志以爲有溫泉焉 理或然也. 風 乘凉也. 舞雩 祭天禱雨之處 有壇墠樹木也. 詠 歌也. 曾點之學 蓋有以見夫人欲盡處 天理流行 隨處充滿 無少欠闕. 故其動靜之際 從容如此. 而其言志 則又不過卽其所居之位 樂其日用之常 初無舍己爲人之意 而其胸次悠然 直與天地萬物上下同流 各得其所之妙 隱然自見於言外 視三子規規於事爲之末者 其氣象不侔矣. 故夫子嘆息而深許之 而門人記其本末 獨加詳焉. 蓋亦有以識此矣.

[_11_25_08_]
===  三子者出 曾晳後 曾晳曰 夫三子者之言何如 子曰 亦各言其志也已矣 曰 夫子何哂由也 (先進-11-25-08)

點以子路之志 乃所優爲 而夫子哂之 故請其說.

[_11_25_09_]
=== 曰 爲國以禮 其言不讓 是故哂之 (先進-11-25-09)

夫子蓋許其能 特哂其不遜.

[_11_25_10_]
=== 唯求 則非邦也與 安見方六七十 如五六十 而非邦也者 (先進-11-25-10)

曾點以冉求亦欲爲國 而不見哂 故微問之. 而夫子之答無貶詞 蓋亦許之.

[_11_25_11_]
=== 唯赤 則非邦也與 宗廟會同 非諸侯而何 赤也爲之小 孰能爲之大 (先進-11-25-11)

此亦曾晳問 而夫子答也. 孰能爲之大 言無能出其右者 亦許之之詞. ○程子曰 古之學者 優柔厭飫 有先後之序. 如子路冉有公西赤言志如此 夫子許之 亦以此自是實事. 後之學者好高 如人游心千里之外 然自身却只在此. 又曰 孔子與點 蓋與聖人之志同 便是堯舜氣象也. 誠異三子者之撰 特行有不掩焉耳. 此所謂狂也. 子路等所見者小 子路只爲不達爲國以禮道理 是以哂之. 若達 却便是這氣象也. 又曰 三子皆欲得國而治之 故夫子不取 曾點狂者也 未必能爲聖人之事 而能知夫子之志 故曰浴乎沂風乎舞雩詠而歸 言樂而得其所也. 孔子之志 在於老者安之 朋友信之 少者懷之 使萬物莫不遂其性 曾點知之. 故孔子喟然嘆曰 吾與點也. 又曰 曾點漆雕開 已見大意.

論語集註大全卷之十二

[_12_]
== 顔淵第十二

凡二十四章

[_12_01_01_]
=== ○顔淵問仁 子曰 克己復禮爲仁 一日克己復禮 天下歸仁焉 爲仁由己 而由人乎哉 (顔淵-12-01-01)

仁者 本心之全德. 克 勝也. 己 謂身之私欲也. 復 反也. 禮者 天理之節文也 爲仁者 所以全其心之德也. 蓋心之全德 莫非天理 而亦不能不壞於人欲 故爲仁者 必有以勝私欲而復於禮 則事皆天理 而本心之德復全於我矣. 歸 猶與也. 又言一日克己復禮 則天下之人皆與其仁 極言其效之甚速 而至大也. 又言爲仁由己而非他人所能預. 又見其機之在我而無難也. 日日克之 不以爲難 則私欲淨盡 天理流行而仁不可勝用矣. 程子曰 非禮處 便是私意. 旣是私意如何得仁. 須是克盡己私 皆歸於禮方始是仁. 又曰 克己復禮 則事事皆仁 故曰天下歸仁. 謝氏曰 克己須從性偏難克處 克將去.

[_12_01_02_]
=== 顔淵曰 請問其目 子曰 非禮勿視 非禮勿聽 非禮勿言 非禮勿動 顔淵曰 回雖不敏 請事斯語矣 (顔淵-12-01-02)

目 條件也. 顔淵聞夫子之言 則於天理人欲之際 已判然矣. 故不復有所疑問 而直請其條目也. 非禮者 己之私也. 勿者 禁止之辭. 是人心之所以爲主 而勝私復禮之機也. 私勝則動容周旋 無不中禮 而日用之間 莫非天理之流行矣. 事 如事事之事. 請事斯語 顔淵黙識其理 又自知其力有以勝之 故直以爲己任而不疑也. ○程子曰 顔淵問克己復禮之目 子曰 非禮勿視 非禮勿聽 非禮勿言 非禮勿動 四者身之用也. 由乎中而應乎外 制於外所以養其中也. 顔淵事斯語 所以進於聖人. 後之學聖人者 宜服膺而勿失也. 因箴以自警. 其視箴曰 心兮本虛 應物無迹. 操之有要 視爲之則. 蔽交於前 其中則遷. 制之於外 以安其內. 克己復禮 久而誠矣. 其聽箴曰 人有秉彛 本乎天性. 知誘物化 遂亡其正. 卓彼先覺 知止有定 閑邪存誠 非禮勿聽. 其言箴曰 人心之動 因言以宣. 發禁躁妄 內斯靜專. 矧是樞機 興戎出好. 吉凶榮辱 惟其所召. 傷易則誕 傷煩則支. 己肆物忤 出悖來違. 非法不道 欽哉訓辭. 其動箴曰 哲人知幾 誠之於思. 志士勵行 守之於爲. 順理則裕 從欲惟危. 造次克念 戰兢自持. 習與性成 聖賢同歸.  愚按此章問答 乃傳授心法切要之言 非至明不能察其幾 非至健不能致其決. 故惟顔子得聞之. 而凡學者 亦不可以不勉也. 程子之箴 發明親切 學者尤宜深玩.

[_12_02_01_]
=== ○仲弓問仁 子曰 出門如見大賓 使民如承大祭 己所不欲 勿施於人 在邦無怨 在家無怨 仲弓曰 雍雖不敏 請事斯語矣 (顔淵-12-02-01)

敬以持己 恕以及物 則私意無所容 而心德全矣. 內外無怨 亦以其效言之 使以自考也. ○程子曰 孔子言仁 只說出門如見大賓 使民如承大祭. 看其氣象 便須心廣體胖 動容周旋中禮. 唯謹獨 便是守之之法. 或問出門使民之時如此可也 未出門使民之時如之何. 曰 此儼若思時也. 有諸中 而後見於外. 觀其出門使民之時 其敬如此 則前乎此者 敬可知矣. 非因出門使民 然後有此敬也. 愚按克己復禮 乾道也. 主敬行恕 坤道也. 顔冉之學 其高下淺深 於此可見. 然學者誠能從事於敬恕之間 而有得焉 亦將無己之可克矣.

[_12_03_01_]
=== ○司馬牛問仁 (顔淵-12-03-01)

司馬牛 孔子弟子 名犁 向魋之弟.

[_12_03_02_]
=== 子曰 仁者其言也訒 (顔淵-12-03-02)

訒 忍也 難也. 仁者 心存而不放 故其言若有所忍而不易發. 蓋其德之一端也. 夫子以牛多言而躁 故告之以此 使其於此而謹之 則所以爲仁之方 不外是矣.

[_12_03_03_]
=== 曰 其言也訒 斯謂之仁矣乎 子曰 爲之難 言之得無訒乎 (顔淵-12-03-03)

牛意仁道至大 不但如夫子之所言 故夫子又告之以此. 蓋心常存 故事不苟 事不苟 故其言自有不得而易者 非强閉之而不出也. 楊氏曰 觀此及下章再問之語 牛之易其言可知. ○程子曰 雖爲司馬牛多言 故及此 然聖人之言 亦止此爲是. 愚謂牛之爲人如此 若不告之以其病之所切 而泛以爲仁之大槩語之 則以彼之躁 必不能深思以去其病 而終無自以入德矣. 故其告之如此. 蓋聖人之言 雖有高下大小之不同 然其切於學者之身 而皆爲入德之要 則又初不異也. 讀者其致思焉.

[_12_04_01_]
=== ○司馬牛問君子 子曰 君子不憂不懼 (顔淵-12-04-01)

向魋作亂 牛常憂懼. 故夫子告之以此.

[_12_04_02_]
=== 曰 不憂不懼 斯謂之君子矣乎 子曰 內省不疚 夫何憂何懼 (顔淵-12-04-02)

牛之再問 猶前章之意 故復告之以此. 疚 病也. 言由其平日所爲無愧於心 故能內省不疚而自無憂懼 未可遽以爲易而忽之也. ○晁氏曰 不憂不懼 由乎德全而無疵 故無入而不自得 非實有憂懼而强排遣之也.

[_12_05_01_]
=== ○司馬牛憂曰 人皆有兄弟 我獨亡 (顔淵-12-05-01)

牛有兄弟 而云然者 憂其爲亂而將死也.

[_12_05_02_]
=== 子夏曰 商聞之矣 (顔淵-12-05-02)

蓋聞之夫子.

[_12_05_03_]
=== 死生有命 富貴在天 (顔淵-12-05-03)

命 禀於有生之初 非今所能移. 天莫之爲而爲 非我所能必. 但當順受而已

[_12_05_04_]
=== 君子敬而無失 與人恭而有禮 四海之內 皆兄弟也 君子何患乎無兄弟也 (顔淵-12-05-04)

旣安於命 又當脩其在己者 故又言 苟能持己以敬而不間斷 接人以恭而有節文 則天下之人皆愛敬之如兄弟矣. 蓋子夏欲以寬牛之憂 而爲是不得已之辭 讀者不以辭害意可也. ○胡氏曰 子夏四海皆兄弟之言 特以廣司馬牛之意 意圓而語滯者也 唯聖人則無此病矣. 且子夏知此 而以哭子喪明 則以蔽於愛而昧於理 是以不能踐其言爾.

[_12_06_01_]
=== ○子張問明 子曰 浸潤之譖 膚受之愬 不行焉 可謂明也已矣 浸潤之譖 膚受之愬 不行焉 可謂遠也已矣 (顔淵-12-06-01)

浸潤 如水之浸灌滋潤漸漬而不驟也. 譖 毁人之行也. 膚受 謂肌膚所受利害切身 如易所謂剝床以膚 切近災者也. 愬 愬己之寃也. 毁人者漸漬而不驟 則聽者不覺其入 而信之深矣. 愬寃者急迫而切身 則聽者不及致詳 而發之暴矣. 二者難察而能察之 則可見其心之明 而不蔽於近矣. 此亦必因子張之失而告之 故其辭繁而不殺 以致丁寧之意云. ○楊氏曰 驟而語之 與利害不切於身者不行焉 有不待明者能之也. 故浸潤之譖 膚受之愬不行 然後謂指明 而又謂之遠 遠則明之至也. 書曰 視遠惟明.

[_12_07_01_]
=== ○子貢問政 子曰 足食 足兵 民信之矣 (顔淵-12-07-01)

言倉廩實 而武備脩 然後敎化行 而民信於我 不離叛也.

[_12_07_02_]
=== 子貢曰 必不得已而去 於斯三者何先 曰 去兵 (顔淵-12-07-02)

言食足而信孚 則無兵而守固矣.

[_12_07_03_]
=== 子貢曰 必不得已而去 於斯二者何先 曰 去食 自古皆有死 民無信不立 (顔淵-12-07-03)

民無食必死 然死者人之所必不免. 無信則雖生而無以自立 不若死之爲安 故寧死而不失信於民 使民亦寧死而不失信於我也. ○程子曰 孔門弟子善問 直窮到底. 如此章者 非子貢不能問 非聖人不能答也. 愚謂以人情而言 則兵食足而後吾之信可以孚於民. 以民德而言 則信本人之所固有 非兵食所得而先也. 是以爲政者 當身率其民而以死守之 不以危急而可棄也.

[_12_08_01_]
=== ○棘子成曰 君子質而已矣 何以文爲 (顔淵-12-08-01)

棘子成 衛大夫 疾時人文勝 故爲此言.

[_12_08_02_]
=== 子貢曰 惜乎 夫子之說君子也 駟不及舌 (顔淵-12-08-02)

言子成之言 乃君子之意 然言出於舌 則駟馬不能追之 又惜其失言也.

[_12_08_03_]
=== 文猶質也 質猶文也 虎豹之鞹 猶犬羊之鞹 (顔淵-12-08-03)

鞹 皮去毛者也. 言文質等耳 不可相無. 若必盡去其文 而獨存其質 則君子小人無以辨矣. 夫棘子成矯當時之弊 固失之過 而子貢矯子成之弊 又無本末輕重之差 胥失之矣.

[_12_09_01_]
=== ○哀公問於有若曰 年饑用不足 如之何 (顔淵-12-09-01)

稱有若者 君臣之詞. 用 謂國用. 公意蓋欲加賦以足用也.

[_12_09_02_]
=== 有若對曰 盍徹乎 (顔淵-12-09-02)

徹 通也 均也. 周制一夫受田百畝 而與同溝共井之人 通力合作 計畝均收. 大率民得其九 公取其一 故謂之徹. 魯自宣公稅畝 又逐畝什取其一 則爲什而取二矣. 故有若請但專行徹法 欲公節用以厚民也.

[_12_09_03_]
=== 曰 二 吾猶不足 如之何其徹也 (顔淵-12-09-03)

二 卽所謂什二也. 公以有若不喩其旨 故言此以示加賦之意.

[_12_09_04_]
=== 對曰 百姓足 君孰與不足 百姓不足 君孰與足 (顔淵-12-09-04)

民富則君不至獨貧 民貧則君不能獨富. 有若深言君民一體之意 以止公之厚斂. 爲人上者 所宜深念也. ○楊氏曰 仁政必自經界始. 經界正而後井地均 穀祿平 而軍國之須皆量是以爲出焉. 故一徹而百度擧矣 上下寧憂不足乎. 以二猶不足而敎之徹 疑若迂矣 然什一 天下之中正 多則桀 寡則貉 不可改也. 後世不究其本 而唯末之圖 故征斂無藝 費出無經 而上下困矣. 又惡知盍徹之當務而不爲迂乎.

[_12_10_01_]
=== ○子張問崇德 辨惑 子曰 主忠信 徙義 崇德也 (顔淵-12-10-01)

主忠信則本立 徙義則日新.

[_12_10_02_]
=== 愛之欲其生 惡之欲其死 旣欲其生 又欲其死 是惑也 (顔淵-12-10-02)

愛惡 人之常情也. 然人之生死有命 非可得而欲也. 以愛惡而欲其生死 則惑矣. 旣欲其生 又欲其死 則惑之甚也.

[_12_10_03_]
=== 誠不以富 亦祗以異 (顔淵-12-10-03)

此詩小雅我行其野之詞也. 舊說夫子引之以明欲其生死者 不能使之生死 如此詩所言不足以致富而適足以取異也. 程子曰 此錯簡 當在第十六篇齊景公有馬千駟之上 因此下文亦有齊景公字而誤也. ○楊氏曰 堂堂乎張也 難與並爲仁矣. 則非誠善補過不蔽於私者 故告之如此.

[_12_11_01_]
=== ○齊景公問政於孔子 (顔淵-12-11-01)

齊景公名杵臼. 魯昭公末年 孔子適齊.

[_12_11_02_]
=== 孔子對曰 君君 臣臣 父父 子子 (顔淵-12-11-02)

此人道之大經 政事之根本也. 是時景公失政 而大夫陳氏厚施於國 景公又多內嬖而不立太子 其君臣父子之間 皆失其道 故夫子告之以此.

[_12_11_03_]
=== 公曰 善哉 信如君不君 臣不臣 父不父 子不子 雖有粟 吾得而食諸 (顔淵-12-11-03)

景公善孔子之言 而不能用 其後果以繼嗣不定 啓陳氏弑君簒國之禍. ○楊氏曰 君之所以君 臣之所以臣 父之所以父 子之所以子 是必有道矣. 景公知善夫子之言 而不知反求其所以然 蓋悅而不繹者 齊之所以卒於亂也.

[_12_12_01_]
=== ○子曰 片言可以折獄者 其由也與 (顔淵-12-12-01)

片言 半言. 折 斷也. 子路忠信明決 故言出而人信服之 不待其辭之畢也.

[_12_12_02_]
=== 子路無宿諾 (顔淵-12-12-02)

宿 留也. 猶宿寃之宿. 急於踐言 不留其諾也. 記者因夫子之言而記此 以見子路之所以取信於人者 有其養之有素也. ○尹氏曰 小邾射以句繹奔魯 曰使季路要我 吾無盟矣. 千乘之國 不信其盟而信子路之一言 其見信於人可知矣. 一言而折獄者 信在言前 人自信之故也. 不留諾 所以全其信也.

[_12_13_01_]
=== ○子曰 聽訟 吾猶人也 必也使無訟乎 (顔淵-12-13-01)

范氏曰 聽訟者 治其末 塞其流也. 正其本淸其源 則無訟矣. ○楊氏曰 子路片言可以折獄 而不知以禮遜爲國 則未能使民無訟者也. 故又記孔子之言 以見聖人不以聽訟爲難 而以使民無訟爲貴.

[_12_14_01_]
=== ○子張問政 子曰 居之無倦 行之以忠 (顔淵-12-14-01)

居 謂存諸心. 無倦 則始終如一. 行 謂發於事. 以忠 則表裏如一. ○程子曰 子張少仁 無誠心愛民 則必倦而不盡心 故告之以此.

[_12_15_01_]
=== ○子曰 博學於文 約之以禮 亦可以弗畔矣夫 (顔淵-12-15-01)

[_12_16_01_]
=== ○子曰 君子成人之美 不成人之惡 小人反是 (顔淵-12-16-01)

成者 誘掖獎勸 以成其事也. 君子小人 所存旣有厚薄之殊 而其所好又有善惡之異 故其用心不同如此.

[_12_17_01_]
=== ○季康子問政於孔子 孔子對曰 政者 正也 子帥以正 孰敢不正 (顔淵-12-17-01)

范氏曰 未有己不正而能正人者. ○胡氏曰 魯自中葉 政由大夫. 家臣效尤 據邑背叛 不正甚矣 故孔子以是告之 欲康子以正自克 而改三家之故. 惜乎康子之溺於利欲 而不能也.

[_12_18_01_]
=== ○季康子患盜 問於孔子 孔子對曰 苟子之不欲 雖賞之不竊 (顔淵-12-18-01)

言子不貪欲 則雖賞民使之爲盜 民亦知恥而不竊. ○胡氏曰 季氏竊柄 康子奪嫡 民之爲盜 固其所也. 盍亦反其本邪 孔子以不欲啓之 其旨深矣. 奪嫡事 見春秋傳.

[_12_19_01_]
=== ○ 季康子問政於孔子曰 如殺無道 以就有道 何如 孔子對曰 子爲政 焉用殺 子欲善而民善矣 君子之德風 小人之德草 草上之風 必偃 (顔淵-12-19-01)

爲政者 民所視效 何以殺爲. 欲善則民善矣. 上 一作尙 加也. 偃 仆也. ○尹氏曰 殺之爲言 豈爲人上之語哉. 以身敎者從 以言敎者訟 而況於殺乎.

[_12_20_01_]
=== ○子張問士 何如斯可謂之達矣 (顔淵-12-20-01)

達者 德孚於人 而行無不得之謂.

[_12_20_02_]
=== 子曰 何哉 爾所謂達者 (顔淵-12-20-02)

子張務外 夫子蓋已知其發問之意 故反詰之 將以發其病而藥之也.

[_12_20_03_]
=== 子張對曰 在邦必聞 在家必聞 (顔淵-12-20-03)

言名譽著聞也.

[_12_20_04_]
=== 子曰 是聞也 非達也 (顔淵-12-20-04)

聞與達相似 而不同 乃誠僞之所以分 學者不可不審也. 故夫子旣明辨之 下文又詳言之.

[_12_20_05_]
=== 夫達也者 質直而好義 察言而觀色 慮以下人 在邦必達 在家必達 (顔淵-12-20-05)

內主忠信 而所行合宜 審於接物 而卑以自牧 皆自脩於內 不求人知之事. 然德脩於己 而人信之 則所行自無窒礙矣.

[_12_20_06_]
=== 夫聞也者 色取仁而行違 居之不疑 在邦必聞 在家必聞 (顔淵-12-20-06)

善其顔色 以取於仁 而行實背之. 又自以爲是 而無所忌憚 此不務實而專務求名者 故虛譽雖隆 而實德則病矣. ○程子曰 學者須是務實 不要近名. 有意近名 大本已失 更學何事. 爲名而學 則是僞也. 今之學者 大抵爲名. 爲名與爲利 雖淸濁不同 然其利心則一也. 尹氏曰 子張之學 病在乎不務實 故孔子告之 皆篤實之事充乎內而發乎外.者也 當時門人親受聖人之敎 而差失有如此者 況後世乎.

[_12_21_01_]
=== ○樊遲從遊於舞雩之下曰 敢問崇德 脩慝 辨惑 (顔淵-12-21-01)

胡氏曰 慝之字 從心從匿 蓋惡之匿於心者. 脩者 治而去之.

[_12_21_02_]
=== 子曰 善哉問 (顔淵-12-21-02)

善其切於爲己.

[_12_21_03_]
=== 先事後得 非崇德與 攻其惡 無攻人之惡 非脩慝與 一朝之忿 忘其身以及其親 非惑與 (顔淵-12-21-03)

先事後得 猶言先難後獲也. 爲所當爲而不計其功 則德日積而不自知矣. 專於治己而不責人 則己之惡無所匿矣. 知一朝之忿爲甚微 而禍及其親爲甚大 則有以辨惑而懲其忿矣. 樊遲麤鄙近利 故告之以此 三者 皆所以救其失也. ○范氏曰 先事後得 上義而下利也. 人惟有利欲之心 故德不崇. 惟不自省己過而知人之過 故慝不脩. 感物而易動者 莫如忿 忘其身以及其親 惑之甚者也. 惑之甚者必起於細微 能辨之於早 則不至於大惑矣. 故懲忿所以辨惑也.

[_12_22_01_]
=== ○樊遲問仁 子曰 愛人 問知 子曰 知人 (顔淵-12-22-01)

愛人 仁之施 知人 知之務.

[_12_22_02_]
=== 樊遲未達 (顔淵-12-22-02)

曾氏曰 遲之意 蓋以愛欲其周 而知有所擇 故疑二者之相悖耳.

[_12_22_03_]
=== 子曰 擧直錯諸枉 能使枉者直 (顔淵-12-22-03)

擧直錯枉者 知也. 使枉者直 則仁矣. 如此則二者不惟不相悖 而反相爲用矣.

[_12_22_04_]
=== 樊遲退 見子夏曰 鄕也吾見於夫子而問知 子曰 擧直錯諸枉 能使枉者直 何謂也 (顔淵-12-22-04)

遲 以夫子之言專爲知者之事 又未達所以能使枉者直之理.

[_12_22_05_]
=== 子夏曰 富哉言乎 (顔淵-12-22-05)

歎其所包者廣 不止言知.

[_12_22_06_]
=== 舜有天下 選於衆 擧皐陶 不仁者遠矣 湯有天下 選於衆 擧伊尹 不仁者遠矣 (顔淵-12-22-06)

伊尹 湯之相也. 不仁者遠 言人皆化而爲仁 不見有不仁者. 若其遠去爾. 所謂使枉者直也. 子夏蓋有以知夫子之兼仁知而言矣. ○程子曰 聖人之語 因人而變化. 雖若有淺近者 而其包含 無所不盡. 觀於此章可見矣. 非若他人之言 語近則遺遠 語遠則不知近也. 尹氏曰 學者之問也 不獨欲聞其說 又必欲知其方. 不獨欲知其方 又必欲爲其事. 如樊遲之問仁知也 夫子告之盡矣. 樊遲未達 故又問焉. 而猶未知其何以爲之也. 及退而問諸子夏 然後有以知之. 使其未喩 則必將復問矣. 旣問於師 又辨於友 當時學者之務實也如是.

[_12_23_01_]
=== ○子貢問友 子曰 忠告而善道之 不可則止 無自辱焉 (顔淵-12-23-01)

友所以輔仁 故盡其心以告之. 善其說以道之. 然以義合者也 故不可則止. 若以數而見疏 則自辱矣.

[_12_24_01_]
=== ○曾子曰 君子以文會友 以友輔仁 (顔淵-12-24-01)

講學以會友 則道益明. 取善以輔仁 則德日進.

論語集注大全卷之十三

[_13_]
== 子路第十三

凡三十章

[_13_01_01_]
=== ○子路問政 子曰 先之勞之 (子路-13-01-01)

蘇氏曰 凡民之行 以身先之 則不令而行. 凡民之事 以身勞之 則雖勤不怨.

[_13_01_02_]
=== 請益 曰 無倦 (子路-13-01-02)

吳氏曰 勇者喜於有爲 而不能持久 故以此告之. ○程子曰 子路問政 孔子旣告之矣. 及請益 則曰無倦而已. 未嘗復有所告 姑使之深思也.

[_13_02_01_]
=== ○仲弓爲季氏宰 問政 子曰 先有司 赦小過 擧賢才 (子路-13-02-01)

有司 衆職也. 宰兼衆職 然事必先之於彼而後考其成功 則己不勞而事畢擧矣. 過 失誤也. 大者於事或有所害 不得不懲. 小者赦之 則刑不濫 而人心悅矣. 賢 有德者 才 有能者. 擧而用之 則有司皆得其人 而政益脩矣.

[_13_02_02_]
=== 曰 焉知賢才而擧之 曰 擧爾所知 爾所不知 人其舍諸 (子路-13-02-02)

仲弓慮無以盡知一時之賢才 故孔子告之以此. 程子曰 人各親其親 然後不獨親其親. 仲弓曰 焉知賢才而擧之 子曰 擧爾所知 爾所不知人其舍諸 便見仲弓與聖人用心之大小. 推此義 則一心可以興邦 一心可以喪邦 只在公私之間爾. ○范氏曰 不先有司 則君行臣職矣. 不赦小過 則下無全人矣. 不擧賢才 則百職廢矣. 失此三者 不可以爲季氏宰 況天下乎.

[_13_03_01_]
=== ○子路曰 衛君待子而爲政 子將奚先 (子路-13-03-01)

衛君 衛出公輒也. 是時魯哀公之十年 孔子自楚反乎衛.

[_13_03_02_]
=== 子曰 必也正名乎 (子路-13-03-02)

是時出公不父其父 而禰其祖 名實紊矣 故孔子以正名爲先. 謝氏曰 正名雖爲衛君而言 然爲政之道 皆當以此爲先.

[_13_03_03_]
=== 子路曰 有是哉 子之迂也 奚其正 (子路-13-03-03)

迂 謂遠於事情 言非今日之急務也.

[_13_03_04_]
=== 子曰 野哉由也 君子於其所不知 蓋闕如也 (子路-13-03-04)

野 謂鄙俗. 責其不能闕疑而率爾妄對也.

[_13_03_05_]
=== 名不正 則言不順 言不順 則事不成 (子路-13-03-05)

楊氏曰 名不當其實 則言不順. 言不順 則無以考實而事不成.

[_13_03_06_]
=== 事不成 則禮樂不興 禮樂不興 則刑罰不中 刑罰不中 則民無所措手足 (子路-13-03-06)

范氏曰 事得其序之謂禮 物得其和之謂樂. 事不成則無序而不和. 故禮樂不興. 禮樂不興 則施之政事 皆失其道 故刑罰不中.

[_13_03_07_]
=== 故君子名之必可言也 言之必可行也 君子於其言 無所苟而已矣 (子路-13-03-07)

程子曰 名實相須 一事苟則其餘皆苟矣. ○胡氏曰 衛世子蒯聵 恥其母南子之淫亂 欲殺之不果而出奔. 靈公欲立公子郢 郢辭. 公卒 夫人立之 又辭. 乃立蒯聵之子輒 以拒蒯聵. 夫蒯聵欲殺母得罪於父 而輒據國以拒父 皆無父之人也. 其不可有國也明矣. 夫子爲政而以正名爲先 必將具其事之本末 告諸天王 請于方伯 命公子郢而立之 則人倫正 天理得 名正言順而事成矣. 夫子告之之詳如此 而子路終不喩也. 故事輒不去 卒死其難. 徒知食焉不避其難之爲義 而不知食輒之食爲非義也.

[_13_04_01_]
=== ○樊遲請學稼 子曰 吾不如老農 請學爲圃 曰 吾不如老圃 (子路-13-04-01)

種五穀曰稼 種蔬菜曰圃.

[_13_04_02_]
=== 樊遲出 子曰 小人哉 樊須也 (子路-13-04-02)

小人 謂細民. 孟子所謂小人之事者也.

[_13_04_03_]
=== 上好禮 則民莫敢不敬 上好義 則民莫敢不服 上好信 則民莫敢不用情 夫如是 則四方之民 襁負其子而至矣 焉用稼 (子路-13-04-03)

禮義信 大人之事也. 好義則事合宜. 情 誠實也. 敬服用情 蓋各以其類而應也. 襁 織縷爲之 以約小兒於背者. ○楊氏曰 樊須遊聖人之門 而問稼圃 志則陋矣. 辭而闢之可也. 待其出而後言其非何也. 蓋於其問也 自謂農圃之不如 則拒之者至矣. 須之學 疑不及此 而不能問 不能以三隅反矣 故不復. 及其旣出 則懼其終不喩也 求老農老圃而學焉 則其失愈遠矣. 故復言之 使知前所言者 意有在也.

[_13_05_01_]
=== ○子曰 誦詩三百 授之以政 不達 使於四方 不能專對 雖多 亦奚以爲 (子路-13-05-01)

專 獨也. 詩 本人情該物理 可以驗風俗之盛衰 見政治之得失 其言溫厚和平 長於風諭故誦之者必達於政而能言也. ○程子曰 窮經將以致用也. 世之誦詩者 果能從政而專對乎. 然則其所學者 章句之末耳. 此學者之大患也.

[_13_06_01_]
=== ○子曰 其身正 不令而行 其身不正 雖令不從 (子路-13-06-01)

[_13_07_01_]
=== ○子曰 魯衛之政 兄弟也 (子路-13-07-01)

魯 周公之後 衛 康叔之後 本兄弟之國 而是時衰亂 政亦相似 故孔子嘆之.

[_13_08_01_]
=== ○子謂衛公子荊善居室 始有 曰 苟合矣 少有 曰 苟完矣 富有 曰苟美矣 (子路-13-08-01)

公子荊 衛大夫. 苟 聊且粗略之意. 合 聚也. 完 備也. 言其循序而有節 不以欲速盡美 累其心. ○楊氏曰 務爲全美 則累物而驕吝之心生. 公子荊 皆曰苟而已 則不以外物爲心 其欲易足 故也.

[_13_09_01_]
=== ○子適衛 冉有僕 (子路-13-09-01)

僕 御車也.

[_13_09_02_]
=== 子曰 庶矣哉 (子路-13-09-02)

庶 衆也.

[_13_09_03_]
=== 冉有曰 旣庶矣 又何加焉 曰 富之 (子路-13-09-03)

庶而不富 則民生不遂 故制田里薄賦斂以富之.

[_13_09_04_]
=== 曰 旣富矣 又何加焉 曰 敎之 (子路-13-09-04)

富而不敎 則近於禽獸 故必立學校明禮義以敎之. ○胡氏曰 天生斯民 立之司牧 而寄以三事 然自三代之後 能擧此職者 百無一二. 漢之文明 唐之太宗 亦云庶且富矣. 西京之敎無聞焉. 明帝尊師重傅 臨雍拜老 宗戚子弟 莫不受學. 唐太宗大召名儒 增廣生員 敎亦至矣. 然而未知所以敎也. 三代之敎 天子公卿 躬行於上 言行政事 皆可師法. 彼二君者 其能然乎.

[_13_10_01_]
=== ○子曰 苟有用我者 朞月而已可也 三年有成 (子路-13-10-01)

朞月 謂周一歲之月也. 可者 僅辭言紀綱布也. 有成 治功成也. ○尹氏曰 孔子歎當時莫能用己也. 故云然. 愚按史記此蓋爲衛靈公不能用而發.

[_13_11_01_]
=== ○子曰 善人爲邦百年 亦可以勝殘去殺矣 誠哉是言也 (子路-13-11-01)

爲邦百年 言相繼而久也. 勝殘 化殘暴之人使不爲惡也. 去殺 謂民化於善 可以不用刑殺也. 蓋古有是言 而夫子稱之. 程子曰 漢自高惠至于文景 黎民醇厚 幾致刑措 庶乎其近之矣. ○尹氏曰 勝殘去殺 不爲惡而已. 善人之功如是. 若夫聖人則不待百年 其化亦不止此.

[_13_12_01_]
=== ○子曰 如有王者 必世而後仁 (子路-13-12-01)

王者 謂聖人受命而興也. 三十年爲一世. 仁 謂敎化浹也. 程子曰 周自文武至于成王 而後禮樂興 卽其效也. ○或問 三年必世 遲速不同何也. 程子曰 三年有成 謂法度紀綱有成 而化行也. 漸民以仁 摩民以義 使之浹於肌膚 淪於骨髓 而禮樂可興 所謂仁也. 此非積久何以能致.

[_13_13_01_]
=== ○子曰 苟正其身矣 於從政乎何 有不能正其身 如正人何 (子路-13-13-01)

[_13_14_01_]
=== ○冉子退朝 子曰 何晏也 對曰 有政 子曰 其事也 如有政 雖不吾以 吾其與聞之 (子路-13-14-01)

冉有時爲季氏宰 朝 季氏之私朝也. 晏 晩也. 政 國政. 事 家事. 以 用也. 禮 大夫雖不治事 猶得與聞國政. 是時季氏專魯 其於國政 蓋有不與同列議於公朝 而獨與家臣謀於私室者 故夫子爲不知者而言 此必季氏之家事耳. 若是國政 我嘗爲大夫 雖不見用 猶當與聞. 今旣不聞 則是非國政也. 語意與魏徵獻陵之對 略相似. 其所以正名分 抑季氏 而敎冉有之意深矣.

[_13_15_01_]
=== ○定公問一言而可以興邦 有諸 孔子對曰 言不可以若是其幾也 (子路-13-15-01)

幾 期也. 詩曰 如幾如式 言一言之間 未可以如此而必期其效.

[_13_15_02_]
=== 人之言曰 爲君難 爲臣不易 (子路-13-15-02)

當時有此言也.

[_13_15_03_]
=== 如知爲君之難也 不幾乎一言而興邦乎 (子路-13-15-03)

因此言而知爲君之難 則必戰戰兢兢 臨深履薄 而無一事之敢忽. 然則此言也 豈不可以必期於興邦乎. 爲定公言 故不及臣也.

[_13_15_04_]
=== 曰 一言而喪邦 有諸 孔子對曰 言不可以若是其幾也 人之言曰 予無樂乎爲君 唯其言而莫予違也 (子路-13-15-04)

言他無所樂 惟樂此耳.

[_13_15_05_]
=== 如其善而莫之違也 不亦善乎 如不善而莫之違也 不幾乎一言而喪邦乎 (子路-13-15-05)

范氏曰 如不善而莫之違 則忠言不至於耳. 君日驕而臣日諂 未有不喪邦者也. ○謝氏曰 知爲君之難 則必敬謹以持之. 唯其言而莫予違 則讒諂面諛之人至矣. 邦未必遽興喪也 而興喪之源分於此. 然此非識微之君子 何足以知之.

[_13_16_01_]
=== ○葉公問政 (子路-13-16-01)

[_13_16_02_]
=== 子曰 近者說 遠者來 (子路-13-16-02)

被其澤則說 聞其風則來. 然必近者說而後 遠者來也.

[_13_17_01_]
=== ○子夏爲莒父宰 問政 子曰 無欲速 無見小利 欲速則不達 見小利則大事不成 (子路-13-17-01)

莒父 魯邑名. 欲事之速成 則急遽無序 而反不達. 見小者之爲利 則所就者小而所失者大矣. ○程子曰 子張問政 子曰 居之無倦 行之以忠. 子夏問政 子曰 無欲速 無見小利. 子張常過高而未仁 子夏之病 常在近小 故各以切己之事告之.

[_13_18_01_]
=== ○葉公語孔子曰 吾黨有直躬者 其父攘羊 而子證之 (子路-13-18-01)

直躬 直身而行者 有因而盜曰攘.

[_13_18_02_]
=== 孔子曰 吾黨之直者異於是 父爲子隱 子爲父隱 直在其中矣 (子路-13-18-02)

父子相隱 天理人情之至也. 故不求爲直 而直在其中. ○謝氏曰 順理爲直. 父不爲子隱 子不爲父隱 於理順邪. 瞽瞍殺人 舜竊負而逃 遵海濱而處. 當是時 愛親之心勝 其於直不直 何暇計哉.

[_13_19_01_]
=== ○樊遲問仁 子曰 居處恭 執事敬 與人忠 雖之夷狄 不可棄也 (子路-13-19-01)

恭 主容. 敬 主事. 恭見於外 敬主乎中. 之夷狄不可棄 勉其固守而勿失也. ○程子曰 此是徹上徹下語 聖人初無二語也. 充之則睟面盎背 推而達之 則篤恭而天下平矣. 胡氏曰 樊遲問仁者三 此最先 先難次之 愛人其最後乎.

[_13_20_01_]
=== ○子貢問曰 何如斯可謂之士矣 子曰 行己有恥 使於四方 不辱君命 可謂士矣 (子路-13-20-01)

此其志有所不爲 而其材足以有爲者也. 子貢能言 故以使事告之. 蓋爲使之難 不獨貴於能言而已.

[_13_20_02_]
=== 曰 敢問其次 曰 宗族稱孝焉 鄕黨稱弟焉 (子路-13-20-02)

此本立而材不足者 故爲其次.

[_13_20_03_]
=== 曰 敢問其次 曰 言必信 行必果 硜硜然 小人哉 抑亦可以爲次矣 (子路-13-20-03)

果 必行也. 硜 小石之堅確者. 小人 言其識量之淺狹也. 此其本末皆無足觀 然亦不害其爲自守也. 故聖人猶有取焉. 下此則市井之人 不復可爲士矣.

[_13_20_04_]
=== 曰 今之從政者 何如 子曰 噫 斗筲之人 何足算也 (子路-13-20-04)

今之從政者 蓋如魯三家之屬. 噫 心不平聲 斗 量名 容十升. 筲 竹器 容斗二升. 斗筲之人 言鄙細也. 算 數也. 子貢之問每下 故夫子以是警之. ○程子曰 子貢之意 蓋欲爲皎皎之行聞於人者 夫子告之 皆篤實自得之事.

[_13_21_01_]
=== ○子曰 不得中行而與之 必也狂狷乎 狂者進取 狷者有所不爲也 (子路-13-21-01)

行 道也. 狂者 志極高而行不掩. 狷者 知未及而守有餘. 蓋聖人本欲得中道之人而敎之 然旣不可得 而徒得謹厚之人 則未必能自振拔而有爲也. 故不若得此狂狷之人 猶可因其志節而激厲裁抑之 以進於道 非與其終於此而已也. ○孟子曰 孔子豈不欲中道哉 不可必得 故思其次也. 如琴張曾晳牧皮者 孔子之所謂狂也. 其志嘐嘐然 曰古之人古之人 夷考其行 而不掩焉者也. 狂者又不可得 欲得不屑不潔之士而與之 是狷也 是又其次也.

[_13_22_01_]
=== ○子曰 南人有言曰 人而無恒 不可以作巫醫 善夫 (子路-13-22-01)

南人 南國之人. 恒 常久也. 巫 所以交鬼神. 醫 所以寄死生 故雖賤役 而尤不可以無常. 孔子稱其言而善之.

[_13_22_02_]
=== 不恒其德 或承之羞 (子路-13-22-02)

此易恒卦九三爻辭. 承 進也.

[_13_22_03_]
=== 子曰 不占而已矣 (子路-13-22-03)

復加子曰 以別易文也. 其義未詳. 楊氏曰 君子於易 苟玩其占 則知無常之取羞矣. 其爲無常也 蓋亦不占而已矣. 意亦略通.

[_13_23_01_]
=== ○子曰 君子和而不同 小人同而不和 (子路-13-23-01)

和者 無乖戾之心 同者 有阿比之意. ○尹氏曰 君子尙義 故有不同. 小人尙利 安得而和.

[_13_24_01_]
=== ○子貢問曰 鄕人皆好之 何如 子曰 未可也 鄕人皆惡之 何如 子曰未可也 不如鄕人之善者好之 其不善者惡之 (子路-13-24-01)

一鄕之人 宜有公論矣. 然其間亦各以類自爲好惡也. 故善者好之 而惡者不惡 則必其有苟合之行. 惡者惡之 而善者不好 則必其無可好之實.

[_13_25_01_]
=== ○子曰 君子易事而難說也 說之不以道 不說也 及其使人也 器之 小人難事而易說也 說之雖不以道 說也 及其使人也 求備焉 (子路-13-25-01)

器之 謂隨其材器而使之也. 君子之心公而恕 小人之心私而刻. 天理人欲之間 每相反而已矣.

[_13_26_01_]
=== ○子曰 君子泰而不驕 小人驕而不泰 (子路-13-26-01)

君子循理 故安舒而不矜肆. 小人逞欲 故反是.

[_13_27_01_]
=== ○子曰 剛毅木訥 近仁 (子路-13-27-01)

程子曰 木者質樸 訥者遲鈍. 四者質之近乎仁者也. 楊氏曰 剛毅則不屈於物欲 木訥則不至於外馳 故近仁.

[_13_28_01_]
=== ○子路問曰 何如斯可謂之士矣 子曰 切切偲偲 怡怡如也 可謂士矣 朋友 切切偲偲 兄弟怡怡 (子路-13-28-01)

胡氏曰 切切 懇到也. 偲偲 詳勉也. 怡怡 和悅也. 皆子路所不足 故告之. 又恐其混於所施 則兄弟有賊恩之禍 朋友有善柔之損 故又別而言之.

[_13_29_01_]
=== ○子曰 善人敎民七年 亦可以卽戎矣 (子路-13-29-01)

敎民者 敎之以孝弟忠信之行 務農講武之法. 卽 就也. 戎 兵也. 民知親其上 死其長 故可以卽戎. ○程子曰 七年云者 聖人度其時可矣. 如云朞月三年百年一世 大國五年 小國七年之類. 皆當思其作爲如何 乃有益.

[_13_30_01_]
=== ○子曰 以不敎民戰 是謂棄之 (子路-13-30-01)

以 用也. 言用不敎之民以戰 必有敗亡之禍 是棄其民也.

論語集註大全卷之十四

[_14_]
== 憲問第十四

胡氏曰 此篇疑原憲所記. 凡四十七章           .

[_14_01_01_]
=== ○憲問恥 子曰 邦有道穀 邦無道穀 恥也 (憲問-14-01-01)

憲 原思名. 穀 祿也. 邦有道不能有爲 邦無道不能獨善 而但知食祿 皆可恥也. 憲之狷介 其於邦無道穀之可恥 固知之矣. 至於邦有道穀之可恥 則未必知也. 故夫子因其問 而幷言之 以廣其志 使知所以自勉 而進於有爲也.

[_14_02_01_]
=== ○克伐怨欲 不行焉 可以爲仁矣 (憲問-14-02-01)

此亦原憲以其所能而問也. 克 好勝. 伐 自矜. 怨 忿恨. 欲 貪欲.

[_14_02_02_]
=== 子曰 可以爲難矣 仁則吾不知也 (憲問-14-02-02)

有是四者而能制之使不得行 可謂難矣. 仁則天理渾然 自無四者之累 不行不足以言之也. ○程子曰 人而無克伐怨欲 惟仁者能之. 有之而能制其情 使不行 斯亦難能也. 謂之仁 則未也. 此聖人開示之深 惜乎憲之不能再問也. 或曰 四者不行 固不得爲仁矣. 然亦豈非所謂克己之事 求仁之方乎. 曰 克去己私 以復乎禮 則私欲不留 而天理之本然者得矣. 若但制而不行 則是未有拔去病根之意 而容其潛藏隱伏於胸中也. 豈克己求仁之謂哉. 學者察於二者之間 則其所以求仁之功 益親切而無滲漏矣.

[_14_03_01_]
=== ○子曰 士而懷居 不足以爲士矣 (憲問-14-03-01)

居 謂意所便. 安 處也.

[_14_04_01_]
=== ○子曰 邦有道 危言危行 邦無道 危行言孫 (憲問-14-04-01)

危 高峻也. 孫 卑順也. 尹氏曰 君子之持身 不可變也. 至於言 則有時而不敢盡 以避禍也. 然則爲國者使士言孫 豈不殆哉.

[_14_05_01_]
=== ○子曰 有德者必有言 有言者不必有德 仁者必有勇 勇者不必有仁 (憲問-14-05-01)

有德者 和順積中 英華發外 能言者 或便佞口給而已. 仁者 心無私累 見義必爲. 勇者 或血氣之强而已. ○尹氏曰 有德者必有言 徒能言者 未必有德也. 仁者志必勇 徒能勇者 未必有仁也.

[_14_06_01_]
=== ○ 南宮适問於孔子曰 羿善射 奡盪舟 俱不得其死然 禹稷躬稼 而有天下 夫子不答 南宮适出 子曰 君子哉若人 尙德哉若人 (憲問-14-06-01)

南宮适 卽南容也. 羿 有窮之君 善射 滅夏后相 而簒其位. 其臣寒浞 又殺羿而代之. 奡春秋傳作澆 浞之子也. 力能陸地行舟 後爲夏后少康所誅. 禹平水土 曁稷播種 身親稼穡之事. 禹受舜禪而有天下 稷之後至周武王 亦有天下. 适之意 蓋以羿奡比當世之有權力者 而以禹稷比孔子也. 故孔子不答. 然适之言如此 可謂君子之人 而有尙德之心矣. 不可以不與. 故俟其出而贊美之.

[_14_07_01_]
=== ○子曰 君子而不仁者有矣夫 未有小人而仁者也 (憲問-14-07-01)

謝氏曰 君子志於仁矣 然毫忽之間 心不在焉 則未免爲不仁也.

[_14_08_01_]
=== ○子曰 愛之能勿勞乎 忠焉能勿誨乎 (憲問-14-08-01)

蘇氏曰 愛而勿勞 禽犢之愛也. 忠而勿誨 婦寺之忠也. 愛而知勞之 則其爲愛也深矣. 忠而知誨之 則其爲忠也大矣.

[_14_09_01_]
=== ○子曰 爲命 裨諶草創之 世叔討論之 行人子羽修飾之 東里子産潤色之 (憲問-14-09-01)

裨諶以下四人 皆鄭大夫. 草 略也. 創 造也. 謂造爲草藁也. 世叔 游吉也. 春秋傳作子大叔. 討 尋究也. 論 講議也. 行人 掌使之官. 子羽 公孫揮也. 修飾 謂增損之. 東里 地名 子産所居也. 潤色 謂加以文采也. 鄭國之爲辭命 必更此四賢之手而成 詳審精密 各盡所長 是以應對諸侯 鮮有敗事. 孔子言此 蓋善之也.

[_14_10_01_]
=== ○或問子産 子曰 惠人也 (憲問-14-10-01)

子産之政 不專於寬 然其心則一以愛人爲主 故孔子以爲惠人. 蓋擧其重而言也.

[_14_10_02_]
=== 問子西 曰 彼哉彼哉 (憲問-14-10-02)

子西 楚公子申 能遜楚國 立昭王 而改紀其政 亦賢大夫也. 然不能革其僣王之號. 昭王欲用孔子 又沮止之. 其後卒召白公 以致禍亂 則其爲人可知矣. 彼哉者 外之之詞.

[_14_10_03_]
=== 問管仲 曰 人也 奪伯氏騈邑三百 飯疏食 沒齒無怨言 (憲問-14-10-03)

人也 猶言此人也. 伯氏 齊大夫. 騈邑 地名. 齒 年也. 蓋桓公奪伯氏之邑以與管仲 伯氏自知其罪 而心服管仲之功 故窮約以終身而無怨言. 荀卿所謂與之書社三百 而富人莫之敢拒者 卽此事也. ○或問管仲子産孰優. 曰管仲之德 不勝其才 子産之才 不勝其德. 然於聖人之學 則槩乎其未有聞也.

[_14_11_01_]
=== ○子曰 貧而無怨難 富而無驕易 (憲問-14-11-01)

處貧難 處富易. 人之常情. 然人當勉其難而不可忽其易也.

[_14_12_01_]
=== ○子曰 孟公綽爲趙魏老 則優 不可以爲滕薛大夫 (憲問-14-12-01)

公綽 魯大夫. 趙魏 晉卿之家. 老 家臣之長. 大家勢重 而無諸侯之事. 家老望尊 而無官守之責. 優 有餘也. 滕薛 二國名. 大夫 任國政者 滕薛國小政繁 大夫位高責重. 然則公綽蓋廉靜寡欲 而短於才者也. ○楊氏曰 知之弗豫 枉其才而用之 則爲棄人矣. 此君子所以患不知人也. 言此則孔子之用人可知矣.

[_14_13_01_]
=== ○子路問成人 子曰 若臧武仲之知 公綽之不欲 卞莊子之勇 冉求之藝 文之以禮樂 亦可以爲成人矣 (憲問-14-13-01)

成人 猶言全人. 武仲 魯大夫 名紇. 莊子 魯卞邑大夫. 言兼此四子之長 則知足以窮理 廉足以養心 勇足以力行 藝足以泛應. 而又節之以禮 和之以樂 使德成於內 而文見乎外. 則材全德備 渾然不見一善成名之迹. 中正和樂 粹然無復偏倚駁雜之蔽. 而其爲人也 亦成矣. 然亦之爲言 非其至者. 蓋就子路之所可及而語之也. 若論其至 則非聖人之盡人道 不足以語㤞.

[_14_13_02_]
=== 曰 今之成人者 何必然 見利思義 見危授命 久要不忘平生之言 亦可以爲成人矣 (憲問-14-13-02)

復加曰字者 旣答而復言也. 授命 言不愛其生 持以與人也. 久要 舊約也. 平生 平日也. 有是忠信之實 則雖其才知禮樂有所未備 亦可以爲成人之次也. ○程子曰 知之明 信之篤 行之果 天下之達德也. 若孔子所謂成人 亦不出此三者. 武仲 知也. 公綽 仁也. 卞莊子 勇也. 冉求 藝也. 須是合此四人之能 文之以禮樂 亦可以爲成人矣. 然而論其大成 則不止於此. 若今之成人 有忠信而不及於禮樂 則又其次者也. 又曰 臧武仲之知 非正也. 若文之以禮樂 則無不正矣. 又曰 語成人之名 非聖人孰能之. 孟子曰 唯聖人然後可以踐形 如此方可以稱成人之名. 胡氏曰 今之成人以下 乃子路之言. 蓋不復聞斯行之之勇 而有終身誦之之固矣. 未詳是否.

[_14_14_01_]
=== ○子問公叔文子於公明賈曰 信乎 夫子不言不笑不取乎 (憲問-14-14-01)

公叔文子 衛大夫公孫枝也. 公明姓 賈名 亦衛人. 文子爲人 其詳不可知. 然必廉靜之士 故當時以三者稱之.

[_14_14_02_]
=== 公明賈對曰 以告者過也 夫子時然後言 人不厭其言 樂然後笑 人不厭其笑 義然後取 人不厭其取 子曰 其然 豈其然乎 (憲問-14-14-02)

厭者 苦其多而惡之之辭. 事適其可 則人不厭而不覺其有是矣. 是以稱之. 或過而以爲不言不笑不取也. 然此言也 非禮義充溢於中 得時措之宜者不能. 文子雖賢 疑未及此. 但君子與人爲善 不欲正言其非也. 故曰其然豈其然乎 蓋疑之也.

[_14_15_01_]
=== ○子曰 臧武仲以防求爲後於魯 雖曰不要君 吾不信也 (憲問-14-15-01)

防 地名 武仲所封邑也. 要 有挾而求也. 武仲得罪奔邾 自邾如防 使請立後而避邑 以示若不得請 則將據邑以叛 是要君也. ○范氏曰 要君者無上 罪之大者也. 武仲之邑 受之於君 得罪出奔 則立後在君 非己所得專也. 而據邑以請 由其好知而不好學也. 楊氏曰 武仲卑辭請後 其跡非要君者 而意實要之. 夫子之言 亦春秋誅意之法也.

[_14_16_01_]
=== ○子曰 晋文公譎而不正 齊桓公正而不譎 (憲問-14-16-01)

晉文公 名重耳. 齊桓公 名小白. 譎 詭也. 二公皆諸侯盟主 攘夷狄以尊周室者也. 雖其以力假仁 心皆不正. 然桓公伐楚 仗義執言 不由詭道 猶爲彼善於此. 文公則伐衛以致楚 而陰謀以取勝 其譎甚矣. 二君他事 亦多類此. 故夫子言此以發其隱.

[_14_17_01_]
=== ○子路曰 桓公殺公子糾 召忽死之 管仲不死 曰 未仁乎 (憲問-14-17-01)

按春秋傳 齊襄公無道 鮑叔牙奉公子小白奔莒. 及無知弑襄公 管夷吾召忽奉公子糾奔魯. 魯人納之未克 而小白入 是爲桓公. 使魯殺子糾 而請管召. 召忽死之 管仲請囚. 鮑叔牙言於桓公 以爲相. 子路疑管仲忘君事讐 忍心害理 不得爲仁也.

[_14_17_02_]
=== 子曰 桓公九合諸侯 不以兵車 管仲之力也 如其仁 如其仁 (憲問-14-17-02)

九 春秋傳作糾 督也. 古字通用. 不以兵車 言不假威力也. 如其仁 言誰如其仁者 又再言以深許之. 蓋管仲雖未得爲仁人 而其利澤及人 則有仁之功矣.

[_14_18_01_]
=== ○子貢曰 管仲非仁者與 桓公殺公子糾 不能死 又相之 (憲問-14-18-01)

子貢意不死猶可 相之則已甚矣.

[_14_18_02_]
=== 子曰 管仲相桓公 覇諸侯 一匡天下 民到于今受其賜 微管仲 吾其被髮左衽矣 (憲問-14-18-02)

覇與伯同 長也. 匡 正也. 尊周室 攘夷狄 皆所以正天下也. 微 無也 袵 衣衿也. 被髮左衽 夷狄之俗也.

[_14_18_03_]
=== 豈若匹夫匹婦之爲諒也 自經於溝瀆 而莫之知也 (憲問-14-18-03)

諒 小信也. 經 縊也. 莫之知. 人不知也. 後漢書引此文 莫字上有人字. ○程子曰 桓公兄也. 子糾弟也. 仲私於所事 輔之以爭國 非義也. 桓公殺之雖過 而糾之死實當. 仲始與之同謀 遂與之同死可也. 知輔之爭爲不義 將自免以圖後功 亦可也. 故聖人不責其死 而稱其功. 若使桓弟而糾兄 管仲所輔者正 桓奪其國而殺之 則管仲之與桓 不可同世之讐也. 若計其後功 而與其事桓 聖人之言 無乃害義之甚 啓萬世反覆不忠之亂乎. 如唐之王珪魏徵 不死建成之難 而從太宗 可謂害於義矣. 後雖有功 何足贖哉. 愚謂管仲有功而無罪 故聖人獨稱其功. 王魏先有罪而後有功 則不以相掩可也.

[_14_19_01_]
=== ○公叔文子之臣大夫僎 與文子同升諸公 (憲問-14-19-01)

臣 家臣. 公 公朝. 謂薦之與己同進爲公朝之臣也.

[_14_19_02_]
=== 子聞之曰 可以爲文矣 (憲問-14-19-02)

文者 順理而成章之謂. 諡法亦有所謂錫民爵位曰文者. ○洪氏曰 家臣之賤 而引之使 與己竝有三善焉. 知人 一也. 忘己 二也. 事君 三也.

[_14_20_01_]
=== ○子言衛靈公之無道也 康子曰 夫如是 奚而不喪 (憲問-14-20-01)

喪 失位也.

[_14_20_02_]
=== 孔子曰 仲叔圉治賓客 祝駝治宗廟 王孫賈治軍旅 夫如是 奚其喪 (憲問-14-20-02)

仲叔圉 卽孔文子也. 三人 皆衛臣 雖未必賢 而其才可用. 靈公用之 又各當其才. ○尹氏曰 衛靈公之無道 宜喪也. 而能用此三人 猶足以保其國 而況有道之君 能用天下之賢才者乎. 詩曰 無競維人 四方其訓之.

[_14_21_01_]
=== ○子曰 其言之不怍 則爲之也難 (憲問-14-21-01)

大言不慙 則無必爲之志. 而自不度其能否矣. 欲踐其言 豈不難哉.

[_14_22_01_]
=== ○陳成子弑簡公 (憲問-14-22-01)

成子 齊大夫 名恒. 簡公 齊君 名壬. 事在春秋哀公十四年.

[_14_22_02_]
=== 孔子沐浴而朝 告於哀公曰 陳恒弑其君 請討之 (憲問-14-22-02)

是時孔子致仕居魯 沐浴齊戒以告君 重其事而不敢忽也. 臣弑其君 人倫之大變 天理所不容 人人得而誅之 況鄰國乎, 故夫子雖已告老 而猶請哀公討之.

[_14_22_03_]
=== 公曰 告夫三子 (憲問-14-22-03)

三子 三家也. 時政在三家 哀公不得自專 故使孔子告之.

[_14_22_04_]
=== 孔子曰 以吾從大夫之後 不敢不告也 君曰 告夫三子者 (憲問-14-22-04)

孔子出而自言如此 意謂弑君之賊 法所必討. 大夫謀國 義所當告. 君乃不能自命三子 而使我告之邪.

[_14_22_05_]
=== 之三子告 不可 孔子曰 以吾從大夫之後 不敢不告也 (憲問-14-22-05)

以君命往告 而三子魯之强臣 素有無君之心 實與陳氏聲勢相倚 故沮其謀. 而夫子復以此應之 其所以警之者 深矣. ○程子曰 左氏記孔子之言曰 陳恒弑其君 民之不予者半. 以魯之衆 加齊之半 可克也. 此非孔子之言 誠若此言 是以力不以義也. 若孔子之志 必將正名其罪 上告天子 下告方伯 而率與國以討之. 至於所以勝齊者 孔子之餘事也. 豈計魯人之衆寡哉. 當是時天下之亂極矣. 因是足以正之 周室其復興乎. 魯之君臣 終不從之 可勝惜哉. 胡氏曰 春秋之法 弑君之賊 人人得而討之. 仲尼此擧 先發後聞可也.

[_14_23_01_]
=== ○子路問事君 子曰 勿欺也而犯之 (憲問-14-23-01)

犯 謂犯顔諫爭. ○范氏曰 犯非子路之所難也. 而以不欺爲難. 故夫子告以先勿欺 而後犯也.

[_14_24_01_]
=== ○子曰 君子上達 小人下達 (憲問-14-24-01)

君子循天理 故日進乎高明. 小人徇人欲 故日究乎汙下.

[_14_25_01_]
=== ○子曰 古之學者爲己 今之學者爲人 (憲問-14-25-01)

程子曰 爲己 欲得之於己也. 爲人 欲見知於人也. ○程子曰 古之學者爲己 其終至於成物. 今之學者爲人 其終至於喪己. 愚按聖賢論學者用心得失之際 其說多矣 然未有如此言之切而要者. 於此明辯而日省之 則庶乎其不昧於所從矣.

[_14_26_01_]
=== ○蘧伯玉使人於孔子 (憲問-14-26-01)

籧伯玉 衛大夫 名瑗. 孔子居衛 嘗主於其家. 旣而反魯 故伯玉使人來也.

[_14_26_02_]
=== 孔子與之坐而問焉 曰 夫子何爲 對曰 夫子欲寡其過而未能也 使者出 子曰 使乎使乎 (憲問-14-26-02)

與之坐 敬其主以及其使也. 夫子 指伯玉也. 言其但欲寡過 而猶未能 則其省身克己 常若不及之意可見矣. 使者之言 愈自卑約 而其主之賢益彰 亦可謂深知君子之心而善於詞令者矣. 故夫子再言使乎以重美之. 按莊周稱 伯玉行年五十而知四十九年之非. 又曰 伯玉行年六十而六十化. 蓋其進德之功 老而不倦 是以踐履篤實 光輝宣著 不惟使者知之 而夫子亦信之也.

[_14_27_01_]
=== ○子曰 不在其位 不謀其政 (憲問-14-27-01)

[_14_28_01_]
=== ○曾子曰 君子思不出其位 (憲問-14-28-01)

此艮卦之象辭也. 曾子蓋嘗稱之 記者因上章之語而類記之也. ○范氏曰 物各止其所 而天下之理得矣. 故君子所思不出其位 而君臣上下大小 皆得其職也.

[_14_29_01_]
=== ○子曰 君子恥其言而過其行 (憲問-14-29-01)

恥者 不敢盡之意. 過者 欲有餘之辭.

[_14_30_01_]
=== ○子曰 君子道者三 我無能焉 仁者不憂 知者不惑 勇者不懼 (憲問-14-30-01)

自責以勉人也.

[_14_30_02_]
=== 子貢曰 夫子自道也 (憲問-14-30-02)

道 言也. 自道 猶云謙辭. ○尹氏曰 成德以仁爲先 進學以知爲先. 故夫子之言 其序有不同者 以此.

[_14_31_01_]
=== ○子貢方人 子曰 賜也賢乎哉 夫我則不暇 (憲問-14-31-01)

方 比也. 乎哉 疑辭. 比方人物 而較其短長 雖亦窮理之事 然專務爲此 則心馳於外 而所以自治者疎矣. 故褒之而疑其辭 復自貶以深抑之. ○謝氏曰 聖人責人 辭不迫切 而意已獨至如此.

[_14_32_01_]
=== ○子曰 不患人之不己知 患其不能也 (憲問-14-32-01)

凡章指同而文不異者 一言而重出也. 文小異者 屢言而各出也. 此章凡四見 而文皆有異 則聖人於此一事 蓋屢言之. 其丁寧之意 亦可見矣.

[_14_33_01_]
=== ○子曰 不逆詐 不億不信 抑亦先覺者 是賢乎 (憲問-14-33-01)

逆 未至而迎之也. 億 未見而意之也. 詐 謂人欺己. 不信 謂人疑己. 抑 反語辭. 言雖不逆不億 而於人之情僞 自然先覺 乃爲賢也. ○楊氏曰 君子一於誠而已 然未有誠而不明者. 故雖不逆詐 不億不信 而常先覺也. 若夫不逆不億 而卒爲小人所罔焉 斯亦不足觀也已.

[_14_34_01_]
=== ○ 微生畝謂孔子曰 丘何爲是栖栖者與 無乃爲佞乎 (憲問-14-34-01)

微生姓 畝名也. 畝名呼夫子 而辭甚倨 蓋有齒德而隱者 栖栖 依依也. 爲佞 言其務爲口給以悅人也.

[_14_34_02_]
=== 孔子曰 非敢爲佞也 疾固也 (憲問-14-34-02)

疾 惡也. 固 執一而不通也. 聖人之於達尊 禮恭而言直如此 其警之亦深矣.

[_14_35_01_]
=== ○子曰 驥不稱其力 稱其德也 (憲問-14-35-01)

驥 善馬之名. 德 謂調良也. ○尹氏曰 驥雖有力 其稱在德. 人有才而無德 則亦奚足尙哉.

[_14_36_01_]
=== ○或曰 以德報怨 何如 (憲問-14-36-01)

或人所稱 今見老子書 德 謂恩惠也.

[_14_36_02_]
=== 子曰 何以報德 (憲問-14-36-02)

言於其所怨 旣以德報之矣 則人之有德於我者 又將何以報之乎.

[_14_36_03_]
=== 以直報怨 以德報德 (憲問-14-36-03)

於其所怨者 愛憎取舍 一以至公而無私 所謂直也. 於其所德者 則必以德報之 不可忘也. ○或人之言 可謂厚矣. 然以聖人之言觀之 則見其出於有意之私 而怨德之報 皆不得其平也. 必如夫子之言 然後二者之報 各得其所. 然怨有不讐 而德無不報 則又未嘗不厚也. 此章之言 明白簡約 而其指意 曲折反覆. 如造化之簡易易知 而微妙無窮 學者所宜詳玩也.

[_14_37_01_]
=== ○子曰 莫我知也夫 (憲問-14-37-01)

夫子自歎 以發子貢之問也.

[_14_37_02_]
=== 子貢曰 何爲其莫知子也 子曰 不怨天 不尤人 下學而上達 知我者其天乎 (憲問-14-37-02)

不得於天 而不怨天. 不合於人 而不尤人. 但知下學而自然上達 此但自言其反己自脩 循序漸進耳. 無以甚異於人而致其知也. 然深味其語意 則見其中自有人不及知 而天獨知之之妙. 蓋在孔門 唯子貢之智幾足以及此. 故特語以發之. 惜乎其猶有所未達也. ○程子曰 不怨天 不尤人 在理當如此. 又曰下學上達 意在言表. 又曰學者須守下學上達之語 乃學之要. 蓋凡下學人事 便是上達天理. 然習而不察 則亦不能以上達矣.

[_14_38_01_]
=== ○公伯寮愬子路於季孫 子服景伯以告曰 夫子固有惑志於公伯寮 吾力猶能肆諸市朝 (憲問-14-38-01)

公伯寮 魯人. 子服 氏. 景 諡. 伯 字. 魯大夫子服何也. 夫子 指季孫. 言其有疑於寮之言也. 肆 陳尸也. 言欲誅寮.

[_14_38_02_]
=== 子曰 道之將行也與 命也 道之將廢也與 命也 公伯寮其如命何 (憲問-14-38-02)

謝氏曰 雖寮之愬行 亦命也. 其實 寮無如之何. 愚謂言此以曉景伯 安子路而警伯寮耳. 聖人於利害之際 則不待決於命而後泰然也.

[_14_39_01_]
=== ○子曰 賢者辟世 (憲問-14-39-01)

天下無道而隱 若伯夷太公是也.

[_14_39_02_]
=== 其次辟地 (憲問-14-39-02)

去亂國 適治邦.

[_14_39_03_]
=== 其次辟色 (憲問-14-39-03)

禮貌衰而去.

[_14_39_04_]
=== 其次辟言 (憲問-14-39-04)

有違言而後去也. ○程子曰 四者雖以大小次第言之 然非有優劣也. 所遇不同耳.

[_14_40_01_]
=== ○子曰 作者七人矣 (憲問-14-40-01)

李氏曰 作 起也. 言起而隱去者 今七人矣. 不可知其誰何 必求其人以實之 則鑿矣.

[_14_41_01_]
=== ○子路宿於石門 晨門曰 奚自 子路曰 自孔氏 曰 是知其不可而爲之者與 (憲問-14-41-01)

石門 地名. 晨門 掌晨啓門. 蓋賢人隱於抱關者也. 自 從也. 問其何所從來也. 胡氏曰 晨門知世之不可而不爲 故以是譏孔子. 然不知聖人之視天下無不可爲之時也.

[_14_42_01_]
=== ○子擊磬於衛 有荷蕢而過孔氏之門者 曰 有心哉 擊磬乎 (憲問-14-42-01)

磬 樂器. 荷 擔也. 蕢 草器也. 此荷蕢者 亦隱士也. 聖人之心 未嘗忘天下. 此人聞其磬聲而知之 則亦非常人矣.

[_14_42_02_]
=== 旣而曰 鄙哉硜硜乎 莫己知也 斯已而已矣 深則厲 淺則揭 (憲問-14-42-02)

硜硜 石聲 亦專確之意. 以衣涉水曰厲 攝衣涉水曰揭. 此兩句衛風匏有苦葉之詩也. 譏孔子人不知己而不止 不能適淺深之宜.

[_14_42_03_]
=== 子曰 果哉 末之難矣 (憲問-14-42-03)

果哉 嘆其果於忘世也. 末 無也. 聖人心同天地 視天下猶一家 中國猶一人 不能一日忘也. 故聞荷蕢之言 而嘆其果於忘世 此言人之出處 若但如此 則亦無所難矣.

[_14_43_01_]
=== ○子張曰 書云高宗諒陰 三年不言 何謂也 (憲問-14-43-01)

高宗 商王武丁也. 諒陰 天子居喪之名. 未詳其義.

[_14_43_02_]
=== 子曰 何必高宗 古之人皆然 君薨 百官總己 以聽於冢宰 三年 (憲問-14-43-02)

言君薨 則諸侯亦然. 總己 謂總攝己職. 冢宰 大宰也. 百官聽於冢宰 故君得以三年不言也. ○胡氏曰 位有貴賤 而生於父母 無以異者. 故三年之喪 自天子達於庶人. 子張非疑此也 殆以爲人君三年不言 則臣下無所禀令 禍亂或由以起也. 孔子告以聽於冢宰 則禍亂非所憂矣.

[_14_44_01_]
=== ○子曰 上好禮 則民易使也 (憲問-14-44-01)

謝氏曰 禮達而分定 故民易使.

[_14_45_01_]
=== ○子路問君子 子曰 修己以敬 曰 如斯而已乎 曰 修己以安人 曰 如斯而已乎 曰 修己以安百姓 修己以安百姓 堯舜其猶病諸 (憲問-14-45-01)

脩己以敬 夫子之言至於盡矣. 而子路少之 故再以其充積之盛 自然及物者告之 無他道也. 人者對己而言 百姓則盡乎人矣. 堯舜猶病 言不可以有加於此 以抑子路 使反求諸近也. 蓋聖人之心無窮 世雖極治 然豈能必知四海之內 果無一物不得其所哉. 故堯舜猶以安百姓爲病. 若曰吾治已足 則非所以爲聖人矣. ○程子曰 君子脩己以安百姓 篤恭而天下平. 唯上下一於恭敬 則天地自位 萬物自育 氣無不和 而四靈畢至矣. 此體信達順之道 聰明睿知 皆由是出 以此事天饗帝.

[_14_46_01_]
=== ○原壤夷俟 子曰 幼而不孫弟 長而無述焉 老而不死 是爲賊 以杖叩其脛 (憲問-14-46-01)

原壤 孔子之故人. 母死而歌 蓋老氏之流 自放於禮法之外者. 夷 蹲踞也. 俟 待也. 言見孔子來 而蹲踞以待之也. 述 猶稱也. 賊者 害人之名. 以其自幼至老 無一善狀 而久生於世 徒足以敗常亂俗 則是賊而已矣. 脛 足骨也. 孔子旣責之 而因以所曳之杖 微擊其脛 若使勿蹲踞然.

[_14_47_01_]
=== ○闕黨童子將命 或問之曰 益者與 (憲問-14-47-01)

闕黨 黨名. 童子 未冠者之稱. 將命 謂傳賓主之言. 或人疑此童子學有進益 故孔子使之傳命以寵異之也.

[_14_47_02_]
=== 子曰 吾見其居於位也 見其與先生並行也 非求益者也 欲速成者也 (憲問-14-47-02)

禮 童子當隅坐隨行. 孔子言吾見此童子不循此禮 非能求益 但欲速成爾. 故使之給使令之役 觀長少之序 習揖遜之容. 蓋所以抑而敎之 非寵而異之也.

論語集註大全卷之十五

[_15_]
== 衛靈公第十五

凡四十一章

[_15_01_01_]
=== ○衛靈公問陳於孔子 孔子對曰 俎豆之事 則嘗聞之矣 軍旅之事 未之學也 明日遂行 (衛靈公-15-01-01)

陳 謂軍師行伍之列. 俎豆 禮器. 尹氏曰 衛靈公 無道之君也. 復有志於戰伐之事 故答以未學而去之.

[_15_01_02_]
=== 在陳絶糧 從者病 莫能興 (衛靈公-15-01-02)

孔子去衛適陳. 興 起也.

[_15_01_03_]
=== 子路慍見曰 君子亦有窮乎 子曰 君子固窮 小人窮斯濫矣 (衛靈公-15-01-03)

何氏曰 濫 溢也. 言君子固有窮時 不若小人窮則放溢爲非. 程子曰 固窮者 固守其窮 亦通. ○愚謂聖人當行而行 無所顧慮. 處困而亨 無所怨悔 於此可見. 學者宜深味之.

[_15_02_01_]
=== ○子曰 賜也 女以予爲多學而識之者與 (衛靈公-15-02-01)

子貢之學多而能識矣. 夫子欲其知所本也. 故問以發之.

[_15_02_02_]
=== 對曰 然 非與 (衛靈公-15-02-02)

方信而忽疑 蓋其積學功至 而亦將有得也.

[_15_02_03_]
=== 曰 非也 予一以貫之 (衛靈公-15-02-03)

說見第四篇. 然彼以行言 而此以知言也. ○謝氏曰 聖人之道大矣. 人不能遍觀而盡識 宜其以爲多學而識之也. 然聖人豈務博者哉. 如天之於衆形 匪物物刻而雕之也. 故曰予一以貫之. 德輶如毛 毛猶有倫 上天之載 無聲無臭 至矣. 尹氏曰 孔子之於曾子 不待其問而直告之以此. 曾子復深喩之曰 唯. 若子貢 則先發其疑而後告之 而子貢終亦不能如曾子之唯也. 二子所學之淺深 於此可見. 愚按夫子之於子貢 屢有以發之. 而他人不與焉. 則顔曾以下諸子所學之淺深 又可見矣.

[_15_03_01_]
=== ○子曰 由 知德者鮮矣 (衛靈公-15-03-01)

由 呼子路之名而告之也. 德 謂義理之得於己者 非己有之 不能知其意味之實也. ○自第一章至此 疑皆一時之言 此章蓋爲慍見發也 .

[_15_04_01_]
=== ○子曰 無爲而治者 其舜也與 夫何爲哉 恭己正南面而已矣 (衛靈公-15-04-01)

無爲而治者 聖人德盛而民化 不待其有所作爲也. 獨稱舜者 紹堯之後 而又得人以任衆職 故尤不見其有爲之迹也. 恭己者 聖人敬德之容. 旣無所爲 則人之所見如此而已.

[_15_05_01_]
=== ○子張問行 (衛靈公-15-05-01)

猶問達之意也.

[_15_05_02_]
=== 子曰 言忠信 行篤敬 雖蠻貊之邦行矣 言不忠信 行不篤敬 雖州里 行乎哉 (衛靈公-15-05-02)

子張意在得行於外 故夫子反於身而言之 猶答干祿問達之意也. 篤 厚也. 蠻 南蠻. 貊 北狄. 二千五百家爲州.

[_15_05_03_]
=== 立則見其參於前也 在輿 則見其倚於衡也 夫然後行 (衛靈公-15-05-03)

其者 指忠信篤敬而言. 參 讀如毋往參焉之參. 言與我相參也. 衡 軛也. 言其於忠信篤敬 念念不忘 隨其所在 常若有見. 雖欲頃刻離之 而不可得. 然後一言一行 自然不離於忠信篤敬 而蠻貊可行也.

[_15_05_04_]
=== 子張書諸紳 (衛靈公-15-05-04)

紳 大帶之垂者. 書之欲其不忘也. ○程子曰 學要鞭辟近裏 著己而已. 博學而篤志 切問而近思 言忠信 行篤敬 立則見其參於前 在輿則見其倚於衡 卽此是學. 質美者明得盡 査滓便渾化 却與天地同體. 其次惟莊敬以持養之 及其至 則一也.

[_15_06_01_]
=== ○子曰 直哉史魚 邦有道如矢 邦無道如矢 (衛靈公-15-06-01)

史 官名. 魚 衛大夫 名鰌. 如矢 言直也. 史魚自以不能進賢退不肖 旣死猶以尸諫. 故夫子稱其直 事見家語.

[_15_06_02_]
=== 君子哉蘧伯玉 邦有道則仕 邦無道則可卷而懷之 (衛靈公-15-06-02)

伯玉出處 合於聖人之道 故曰君子. 卷 收也. 懷 藏也. 如於孫林父寗殖 放弑之謀 不對而出 亦其事也. ○楊氏曰 史魚之直 未盡君子之道. 若籧伯玉然後可免於亂世. 若史魚之如矢 則雖欲卷而懷之 有不可得也.

[_15_07_01_]
=== ○子曰 可與言而不與之言 失人 不可與言而與之言 失言 知者不失人 亦不失言 (衛靈公-15-07-01)

[_15_08_01_]
=== ○子曰 志士仁人 無求生以害仁 有殺身以成仁 (衛靈公-15-08-01)

志士 有志之士. 仁人則成德之人也. 理當死 而求生 則於其心有不安矣. 是害其心之德也. 當死而死 則心安而德全矣. ○程子曰 實理得之於心 自別. 實理者 實見得是 實見得非也. 古人有捐軀隕命者 若不實見得 惡能如此 須是實見得生不重於義 生不安於死也. 故有殺身以成仁者 只是成就一箇是而已.

[_15_09_01_]
=== ○子貢問爲仁 子曰 工欲善其事 必先利其器 居是邦也 事其大夫之賢者 友其士之仁者 (衛靈公-15-09-01)

賢以事言 仁以德言. 夫子嘗謂子貢悅不若己者 故以是告之 欲其有所嚴憚切磋 以成其德也. ○程子曰 子貢問爲仁 非問仁也. 故孔子告之以爲仁之資而已.

[_15_10_01_]
=== ○顔淵問爲邦 (衛靈公-15-10-01)

顔子 王佐之才 故問治天下之道. 曰爲邦者 謙辭.

[_15_10_02_]
=== 子曰 行夏之時 (衛靈公-15-10-02)

夏時 謂以斗柄初昏建寅之月爲歲首也. 天開於子 地闢於丑 人生於寅 故斗柄建此三辰之月 皆可以爲歲首. 而三代迭用之. 夏以寅爲人正 商以丑爲地正 周以子爲天正也. 然時以作事 則歲月自當以人爲紀. 故孔子嘗曰 吾得夏時焉. 而說者以爲夏小正之屬. 蓋取其時之正 與其令之善 而於此又以告顔子也.

[_15_10_03_]
=== 乘殷之輅 (衛靈公-15-10-03)

商輅 木輅也 輅者 大車之名. 古者以木爲車而已. 至商而有輅之名 蓋始異其制也. 周人飾以金玉 則過侈而易敗 不若商輅之朴素渾堅 而等威已辨 爲質而得其中也.

[_15_10_04_]
=== 服周之冕 (衛靈公-15-10-04)

周冕有五 祭服之冠也. 冠上有覆 前後有旒. 黃帝以來 蓋已有之. 而制度儀等 至周始備. 然其爲物小 而加於衆體之上 故雖華而不爲靡 雖費而不及奢. 夫子取之 蓋亦以爲文而得其中也.

[_15_10_05_]
=== 樂則韶舞 (衛靈公-15-10-05)

取其盡善盡美.

[_15_10_06_]
=== 放鄭聲 遠佞人 鄭聲淫 佞人殆 (衛靈公-15-10-06)

放 謂禁絶之. 鄭聲 鄭國之音. 佞人 卑諂辨給之人. 殆 危也. ○程子曰 問政多矣 惟顔淵告之以此. 蓋三代之制 皆因時損益. 及其久也 不能無弊. 周衰 聖人不作 故孔子斟酌先王之禮 立萬世常行之道 發此以爲之兆耳. 由是求之 則餘皆可考也.  張子曰 禮樂 治之法也. 放鄭聲 遠佞人 法外意也. 一日不謹 則法壞矣. 虞夏君臣 更相戒飭 意蓋如此. 又曰 法立而能守 則德可久. 業可大 鄭聲佞人 能使人喪其所守 故放遠之. 尹氏曰 此所謂百王不易之大法 孔子之作春秋 蓋此意也. 孔顔雖不得行之於時 然其爲治之法 可得而見矣.

[_15_11_01_]
=== ○子曰 人無遠慮 必有近憂 (衛靈公-15-11-01)

蘇氏曰 人之所履者 容足之外 皆爲無用之地. 而不可廢也. 故慮不在千里之外 則患在几席之下矣.

[_15_12_01_]
=== ○子曰 已矣乎 吾未見好德如好色者也 (衛靈公-15-12-01)

已矣乎 歎其終不得而見之也.

[_15_13_01_]
=== ○子曰 臧文仲其竊位者與 知柳下惠之賢 而不與立也 (衛靈公-15-13-01)

竊位 言不稱其位而有愧於心 如盜得而陰據之也. 柳下惠 魯大夫展獲 字禽 食邑柳下 諡曰惠. 與立 謂與之竝立於朝. 范氏曰 臧文仲爲政於魯 若不知賢 是不明也 知而不擧 是蔽賢也. 不明之罪小 蔽賢之罪大. 故孔子以爲不仁 又以爲竊位.

[_15_14_01_]
=== ○子曰 躬自厚而薄責於人 則遠怨矣 (衛靈公-15-14-01)

責己厚 故身益脩. 責人薄 故人易從 . 所以人不得而怨之.

[_15_15_01_]
=== ○子曰 不曰如之何 如之何者 吾末如之何也已矣 (衛靈公-15-15-01)

如之何如之何者 熟思而審處之辭也. 不如是而妄行 雖聖人亦無如之何矣.

[_15_16_01_]
=== ○子曰 群居終日 言不及義 好行小慧 難矣哉 (衛靈公-15-16-01)

小慧 私智也. 言不及義 則放辟邪侈之心滋. 好行小慧 則行險僥倖之機熟 難矣哉者 言其無以入德 而將有患害也.

[_15_17_01_]
=== ○子曰 君子義以爲質 禮以行之 孫以出之 信以成之 君子哉 (衛靈公-15-17-01)

義者 制事之本 故以爲質幹. 而行之必有節文 出之必以退遜 成之必在誠實 乃君子之道也. ○程子曰 義以爲質 如質幹然. 禮行此 孫出此 信成此 此四句只是一事 以義爲本. 又曰 敬以直內 則義以方外. 義以爲質 則禮以行之 孫以出之 信以成之 .

[_15_18_01_]
=== ○子曰 君子病無能焉 不病人之不己知也 (衛靈公-15-18-01)

[_15_19_01_]
=== ○子曰 君子疾沒世而名不稱焉 (衛靈公-15-19-01)

范氏曰 君子學以爲己 不求人知. 然沒世而名不稱焉 則無爲善之實 可知矣.

[_15_20_01_]
=== ○子曰 君子求諸己 小人求諸人 (衛靈公-15-20-01)

謝氏曰 君子無不反求諸己 小人反是. 此君子小人所以分也. ○楊氏曰 君子雖不病人之不己知 然亦疾沒世而名不稱也. 雖疾沒世而名不稱 然所以求者 亦反諸己而已. 小人求諸人 故違道干譽 無所不至. 三者文不相蒙 而意實相足 亦記言者之意.

[_15_21_01_]
=== ○子曰 君子矜而不爭 羣而不黨 (衛靈公-15-21-01)

莊以持己 曰矜 然無乖戾之心 故不爭 和以處衆 曰羣 然無阿比之意 故不黨.

[_15_22_01_]
=== ○子曰 君子不以言擧人 不以人廢言 (衛靈公-15-22-01)

[_15_23_01_]
=== ○子貢問曰 有一言而可以終身行之者乎 子曰 其恕乎 己所不欲 勿施於人 (衛靈公-15-23-01)

推己及物 其施不窮 故可以終身行之. ○尹氏曰 學貴於知要. 子貢之問 可謂知要矣. 孔子告以求仁之方也. 推而極之 雖聖人之無我 不出乎此. 終身行之 不亦宜乎.

[_15_24_01_]
=== ○子曰 吾之於人也 誰毁誰譽 如有所譽者 其有所試矣  (衛靈公-15-24-01)

毁者 稱人之惡而損其眞. 譽者 揚人之善而過其實. 夫子無是也. 然或有所譽者 則必嘗有以試之 而知其將然矣. 聖人善善之速 而無所苟如此. 若其惡惡則已緩矣. 是以雖有以前知其惡 而終無所毁也.

[_15_24_02_]
=== 斯民也 三代之所以直道而行也 (衛靈公-15-24-02)

斯民者 今此之人也. 三代 夏商周也. 直道 無私曲也. 言吾之所以無所毁譽者 蓋以此民 卽三代之時 所以善其善惡其惡而無所私曲之民. 故我今亦不得而枉其是非之實也. ○尹氏曰 孔子之於人也 豈有意於毁譽之哉. 其所以譽之者 蓋試而知其美故也. 斯民也 三代所以直道而行 豈得容私於其間哉.

[_15_25_01_]
=== ○子曰 吾猶及史之闕文也 有馬者 借人乘之 今亡矣夫 (衛靈公-15-25-01)

楊氏曰 史闕文 馬借人 此二事 孔子猶及見之. 今亡矣夫 悼時之益偸也. 愚謂此必有爲而言 蓋雖細故 而時變之大者可知矣. ○胡氏曰 此章義疑 不可强解.

[_15_26_01_]
=== ○子曰 巧言亂德 小不忍 則亂大謀 (衛靈公-15-26-01)

巧言 變亂是非 聽之使人喪其所守. 小不忍 如婦人之仁 匹夫之勇 皆是.

[_15_27_01_]
=== ○子曰 衆惡之 必察焉 衆好之 必察焉 (衛靈公-15-27-01)

楊氏曰 惟仁者 能好惡人 衆好惡人而不察 則或蔽於私矣.

[_15_28_01_]
=== ○子曰 人能弘道 非道弘人 (衛靈公-15-28-01)

弘 廓而大之也. 人外無道 道外無人. 然人心有覺 而道體無爲. 故人能大其道 道不能大其人也. ○張子曰 心能盡性 人能弘道也. 性不知檢其心 非道弘人也.

[_15_29_01_]
=== ○子曰 過而不改 是謂過矣 (衛靈公-15-29-01)

過而能改 則復於無過. 唯不改 則其過遂成而將不及改矣.

[_15_30_01_]
=== ○子曰 吾嘗終日不食 終夜不寢 以思無益 不如學也 (衛靈公-15-30-01)

此爲思而不學者言之. 蓋勞心以必求 不如遜志而自得也. 李氏曰 夫子非思而不學者 特垂語以敎人爾.

[_15_31_01_]
=== ○子曰 君子謀道不謀食 耕也 餒在其中矣 學也 祿在其中矣 君子憂道不憂貧 (衛靈公-15-31-01)

耕 所以謀食 而未必得食. 學所以謀道 而祿在其中. 然其學也 憂不得乎道而已. 非爲憂貧之故 而欲爲是以得祿也. ○尹氏曰 君子治其本 而不卹其末 豈以自外至者爲憂樂哉.

[_15_32_01_]
=== ○子曰 知及之 仁不能守之 雖得之 必失之 (衛靈公-15-32-01)

知足以知此理 而私欲間之 則無以有之於身矣.

[_15_32_02_]
=== 知及之 仁能守之 不莊以涖之 則民不敬 (衛靈公-15-32-02)

涖 臨也. 謂臨民也. 知此理而無私欲以間之 則所知者在我 而不失矣. 然猶有不莊者 蓋氣習之偏 或有厚於內而不嚴於外者. 是以民不見其可畏 而慢易之 下句放此.

[_15_32_03_]
=== 知及之 仁能守之 莊以涖之 動之不以禮 未善也 (衛靈公-15-32-03)

動之 動民也. 猶曰鼓舞而作興之云爾. 禮 謂義理之節文. ○愚謂學至於仁 則善有諸己 而大本立矣. 涖之不莊 動之不以禮 乃其氣稟學問之小疵 然亦非盡善之道也. 故夫子歷言之 使知德愈全 則責愈備 不可以爲小節而忽之也.

[_15_33_01_]
=== ○子曰 君子不可小知 而可大受也 小人不可大受 而可小知也 (衛靈公-15-33-01)

此言觀人之法. 知 我知之也. 受 彼所受也. 蓋君子於細事未必可觀 而材德足以任重. 小人雖器量淺狹 而未必無一長可取.

[_15_34_01_]
=== ○子曰 民之於仁也 甚於水火 水火 吾見蹈而死者矣 未見蹈仁而死者也 (衛靈公-15-34-01)

民之於水火 所賴以生 不可一日無. 其於仁也 亦然. 但水火外物 而仁在己. 無水火 不過害人之身而不仁 則失其心. 是仁有甚於水火 而尤不可以一日無者也. 況水火或有時而殺人 仁則未嘗殺人 亦何憚而不爲哉. 李氏曰 此夫子勉人爲仁之語. 下章放此.

[_15_35_01_]
=== ○子曰 當仁 不讓於師 (衛靈公-15-35-01)

當仁 以仁爲己任也. 雖師亦無所遜 言當勇往而必爲也. 蓋仁者人所自有 而自爲之 非有爭也. 何遜之有. ○程子曰 爲仁在己 無所與遜. 若善名在外 則不可不遜.

[_15_36_01_]
=== ○子曰 君子貞而不諒 (衛靈公-15-36-01)

貞 正而固也 諒則不擇是非而必於信.

[_15_37_01_]
=== ○子曰 事君敬其事而後其食 (衛靈公-15-37-01)

後 與後獲之後同. 食 祿也. 君子之仕也 有官守者 脩其職. 有言責者 盡其忠. 皆以敬吾之事而已 不可先有求祿之心也.

[_15_38_01_]
=== ○子曰 有敎無類 (衛靈公-15-38-01)

人性皆善 而其類有善惡之殊者 氣習之染也. 故君子有敎 則人皆可以復於善 而不當復論其類之惡矣.

[_15_39_01_]
=== ○子曰 道不同 不相爲謀 (衛靈公-15-39-01)

不同 如善惡邪正之類.

[_15_40_01_]
=== ○子曰 辭達而已矣 (衛靈公-15-40-01)

辭 取達意而止 不以富麗爲工.

[_15_41_01_]
=== ○師冕見 及階 子曰 階也 及席 子曰席也 皆坐 子告之曰 某在斯 某在斯 (衛靈公-15-41-01)

師 樂師 瞽者. 冕 名. 再言某在斯 歷擧在坐之人以詔之.

[_15_41_02_]
=== 師冕出 子張問曰 與師言之道與 (衛靈公-15-41-02)

聖門學者 於夫子之一言一動 無不存心省察如此.

[_15_41_03_]
=== 子曰 然 固相師之道也 (衛靈公-15-41-03)

相 助也. 古者瞽必有相 其道如此. 蓋聖人於此 非作意而爲之 但盡其道而已. ○尹氏曰 聖人處己爲人 其心一致 無不盡其誠故也. 有志於學者 求聖人之心 於斯亦可見矣. 范氏曰 聖人不侮鰥寡 不虐無告 可見於此. 推之天下 無一物不得其所矣.

論語集註大全第十六

[_16_]
== 季氏第十六

洪氏曰 此篇或以爲齊論. 凡十四章.

[_16_01_01_]
=== ○季氏將伐顓臾 (季氏-16-01-01)

顓臾 國名. 魯附庸也.

[_16_01_02_]
=== 冉有季路見於孔子曰 季氏將有事於顓臾 (季氏-16-01-02)

按左傳史記 二子仕季氏不同時. 此云爾者 疑子路嘗從孔子 自衛反魯 再仕季氏 不久而復之衛也.

[_16_01_03_]
=== 孔子曰 求 無乃爾是過與 (季氏-16-01-03)

冉求爲季氏聚斂 尤用事 故夫子獨責之.

[_16_01_04_]
=== 夫顓臾 昔者先王以爲東蒙主 且在邦域之中矣 是社稷之臣也 何以伐爲 (季氏-16-01-04)

東蒙 山名. 先王封顓臾於此山之下 使主其祭. 在魯地七百里之中. 社稷 猶云公家. 是時四分魯國 季氏取其二. 孟孫叔孫各有其一. 獨附庸之國 尙爲公臣. 季氏又欲取以自益. 故孔子言 顓臾乃先王封國 則不可伐. 在邦域之中 則不必伐 是社稷之臣 則非季氏所當伐也. 此事理之至當 不易之定體 而一言盡其曲折如此 非聖人不能也.

[_16_01_05_]
=== 冉有曰 夫子欲之 吾二臣者 皆不欲也 (季氏-16-01-05)

夫子 指季孫. 冉有實與謀 以夫子非之 故歸咎於季氏.

[_16_01_06_]
=== 孔子曰 求 周任有言曰 陳力就列 不能者止 危而不持 顚而不扶 則將焉用彼相矣 (季氏-16-01-06)

周任 古之良史. 陳 布也. 列 位也. 相 瞽者之相也. 言二子不欲則當諫 諫而不聽則當去也.

[_16_01_07_]
=== 且爾言過矣 虎兕出於柙 龜玉毁於櫝中 是誰之過與 (季氏-16-01-07)

兕 野牛也. 柙 檻也. 櫝 匱也. 言在柙而逸 在櫝而毁 典守者不得辭其過. 明二子居其位而不去 則季氏之惡 己不得不任其責也.

[_16_01_08_]
=== 冉有曰 今夫顓臾 固而近於費 今不取 後世必爲子孫憂 (季氏-16-01-08)

固 謂城郭完固. 費 季氏之私邑. 此則冉有之飾辭 然亦可見其實與季氏之謀矣.

[_16_01_09_]
=== 孔子曰 求 君子疾夫 舍曰欲之 而必爲之辭 (季氏-16-01-09)

欲之 謂貪其利.

[_16_01_10_]
=== 丘也聞 有國有家者 不患寡而患不均 不患貧而患不安 蓋均無貧 和無寡 安無傾 (季氏-16-01-10)

寡 謂民少. 貧 謂財乏. 均 謂各得其分. 安 謂上下相安. 季氏之欲取顓臾 患寡與貧耳. 然是時季氏據國 而魯君無民 則不均矣. 君弱臣强 互生嫌隙 則不安矣. 均則不患於貧而和 和則不患於寡而安 安則不相疑忌而無傾覆之患.

[_16_01_11_]
=== 夫如是 故遠人不服 則修文德以來之 旣來之 則安之 (季氏-16-01-11)

內治脩 然後遠人服. 有不服 則脩德以來之. 亦不當勤兵於遠.

[_16_01_12_]
=== 今由與求也 相夫子 遠人不服 而不能來也 邦分崩離析 而不能守也 (季氏-16-01-12)

子路雖不與謀 而素不能輔之以義 亦不得爲無罪. 故倂責之 遠人 謂顓臾. 分崩離析 謂四分公室 家臣屢叛.

[_16_01_13_]
=== 而謀動干戈於邦內 吾恐季孫之憂 不在顓臾 而在蕭墻之內也 (季氏-16-01-13)

干 楯也. 戈 戟也. 蕭牆 屛也. 言不均不和. 內變將作. 其後哀公 果欲以越伐魯 而去季氏. ○謝氏曰 當是時 三家强 公室弱 冉求又欲伐顓臾以附益之 夫子所以深罪之 爲其瘠魯以肥三家也. 洪氏曰 二子仕於季氏 凡季氏所欲爲 必以告於夫子. 則因夫子之言而救止者 宜亦多矣. 伐顓臾之事 不見於經傳 其以夫子之言而止也與.

[_16_02_01_]
=== ○孔子曰 天下有道 則禮樂征伐 自天子出 天下無道 則禮樂征伐 自諸侯出 自諸侯出 蓋十世希不失矣 自大夫出 五世希不失矣 陪臣執國命 三世希不失矣 (季氏-16-02-01)

先王之制 諸侯不得變禮樂 專征伐. 陪臣 家臣也. 逆理愈甚 則其失之愈速. 大約世數不過如此.

[_16_02_02_]
=== 天下有道 則政不在大夫 (季氏-16-02-02)

言不得專政.

[_16_02_03_]
=== 天下有道 則庶人不議 (季氏-16-02-03)

上無失政 則下無私議 非箝其口使不敢言也. ○此章通論天下之勢.

[_16_03_01_]
=== ○孔子曰 祿之去公室 五世矣 政逮於大夫 四世矣 故夫三桓之子孫微矣 (季氏-16-03-01)

魯自文公薨 公子遂殺子赤 立宣公 而君失其政. 歷成襄昭定 凡五公. 逮 及也. 自季武子始專國政 歷悼平桓子 凡四世 而爲家臣陽虎所執. 三桓 三家皆桓公之後 此以前章之說推之 而知其當然也. ○此章專論魯事 疑與前章皆定公時語. 蘇氏曰 禮樂征伐自諸侯出 宜諸侯之强也. 而魯以失政 政逮於大夫 宜大夫之强也. 而三桓以微 何也. 强生於安 安生於上下之分定. 今諸侯大夫 皆陵其上 則無以令其下矣. 故皆不久而失之也.

[_16_04_01_]
=== ○孔子曰 益者三友 損者三友 友直 友諒 友多聞 益矣 友便辟 友善柔 友便佞 損矣 (季氏-16-04-01)

友直 則聞其過. 友諒 則進於誠. 友多聞 則進於明. 便 習熟也. 便辟 謂習於威儀而不直. 善柔 謂工於媚悅而不諒. 便佞 謂習於口語 而無聞見之實. 三者損益正相反也. ○尹氏曰 自天子以至於庶人 未有不須友以成者. 而其損益有如是者 可不謹哉.

[_16_05_01_]
=== ○孔子曰 益者三樂 損者三樂 樂節禮樂 樂道人之善 樂多賢友 益矣 樂驕樂 樂佚遊 樂宴樂 損矣 (季氏-16-05-01)

節 謂辨其制度聲容之節. 驕樂 則侈肆而不知節. 佚遊 則惰慢而惡聞善. 宴樂 則淫溺而狎小人. 三者損益亦相反也. ○尹氏曰 君子之於好樂 可不謹哉.

[_16_06_01_]
=== ○孔子曰 侍於君子有三愆 言未及之而言 謂之躁 言及之而不言 謂之隱 未見顔色而言 謂之瞽 (季氏-16-06-01)

君子 有德位之通稱. 愆 過也. 瞽 無目 不能察言觀色. ○尹氏曰 時然後言 則無三者之過矣.

[_16_07_01_]
=== ○孔子曰 君子有三戒 少之時 血氣未定 戒之在色 及其壯也 血氣方剛 戒之在鬪 及其老也 血氣旣衰 戒之在得 (季氏-16-07-01)

血氣 形之所待以生者. 血陰而氣陽也. 得 貪得也. 隨時知戒 以理勝之 則不爲血氣所使也. ○范氏曰 聖人同於人者 血氣也. 異於人者 志氣也. 血氣有時而衰 志氣則無時而衰也. 少未定 壯而剛 老而衰者 血氣也. 戒於色 戒於鬪 戒於得者 志氣也. 君子養其志氣 故不爲血氣所動. 是以年彌高而德彌邵也.

[_16_08_01_]
=== ○孔子曰 君子有三畏 畏天命 畏大人 畏聖人之言 (季氏-16-08-01)

畏者 嚴憚之意也. 天命者 天所賦之正理也. 知其可畏 則其戒謹恐懼 自有不能已者. 而付畀之重 可以不失矣. 大人聖言 皆天命所當畏. 知畏天命 則不得不畏之矣.

[_16_08_02_]
=== 小人不知天命而不畏也 狎大人 侮聖人之言 (季氏-16-08-02)

侮 戱玩也. 不知天命 故不識義理 而無所忌憚如此. ○尹氏曰 三畏者 脩己之誠當然也. 小人不務修身誠己 則何畏之有.

[_16_09_01_]
=== ○孔子曰 生而知之者上也 學而知之者次也 困而學之 又其次也 困而不學 民斯爲下矣 (季氏-16-09-01)

困 謂有所不通. 言人之氣質不同 大約有此四等. ○楊氏曰 生知學知 以至困學 雖其質不同 然及其知之一也. 故君子惟學之爲貴 困而不學 然後爲下.

[_16_10_01_]
=== ○孔子曰 君子有九思 視思明 聽思聰 色思溫 貌思恭 言思忠 事思敬 疑思問 忿思難 見得思義 (季氏-16-10-01)

視無所蔽 則明無不見. 聽無所壅 則聰無不聞. 色 見於面者. 貌 擧身而言. 思問 則疑不蓄. 思難 則忿必懲. 思義 則得不苟. ○程子曰 九思各專其一. 謝氏曰 未至於從容中道 無時而不自省察也. 雖有不存焉者 寡矣 此之謂思誠.

[_16_11_01_]
=== ○孔子曰 見善如不及 見不善如探湯 吾見其人矣 吾聞其語矣 (季氏-16-11-01)

眞知善惡 而誠好惡之 顔曾冉閔之徒 蓋能之矣. 語 蓋古語也.

[_16_11_02_]
=== 隱居以求其志 行義以達其道 吾聞其語矣 未見其人也 (季氏-16-11-02)

求其志 守其所達之道也. 達其道 行其所求之志也. 蓋惟伊尹太公之流 可以當之. 當時若顔子 亦庶乎此. 然隱而未見 又不幸而蚤死 故夫子云然.

[_16_12_01_]
=== ○齊景公有馬千駟 死之日 民無德而稱焉 伯夷叔齊 餓于首陽之下 民到于今稱之 (季氏-16-12-01)

駟 四馬也. 首陽 山名.

[_16_12_02_]
=== 其斯之謂與 (季氏-16-12-02)

胡氏曰 程子以爲 第十二篇錯簡 誠不以富亦祗以異 當在此章之首. 今詳文勢 似當在此句之上. 言人之所稱 不在於富 而在於異也. 愚謂此說近是 而章首當有孔子曰字 蓋闕文耳. 大抵此書 後十篇多闕誤.

[_16_13_01_]
=== ○陳亢問於伯魚曰 子亦有異聞乎 (季氏-16-13-01)

亢 以私意窺聖人 疑必陰厚其子.

[_16_13_02_]
=== 對曰 未也 嘗獨立 鯉趨而過庭 曰 學詩乎 對曰 未也 不學詩 無以言 鯉退而學詩 (季氏-16-13-02)

事理通達 而心氣和平 故能言.

[_16_13_03_]
=== 他日又獨立 鯉趨而過庭 曰 學禮乎 對曰 未也 不學禮 無以立 鯉退而學禮 (季氏-16-13-03)

品節詳明 而德性堅定 故能立.

[_16_13_04_]
=== 聞斯二者 (季氏-16-13-04)

當獨立之時 所聞不過如此 其無異聞可知.

[_16_13_05_]
=== 陳亢退而喜曰 問一得三 聞詩聞禮 又聞君子之遠其子也 (季氏-16-13-05)

尹氏曰 孔子之敎其子 無異於門人. 故陳亢以爲遠其子.

[_16_14_01_]
=== ○邦君之妻 君稱之曰夫人 夫人自稱 曰小童 邦人稱之 曰君夫人 稱諸異邦 曰寡小君 異邦人稱之 亦曰君夫人 (季氏-16-14-01)

寡 寡德謙辭. ○吳氏曰 凡語中所載如此類者 不知何謂. 或古有之 或夫子嘗言之 不可考也.

論語集註大全卷之十七

[_17_]
== 陽貨第十七

凡二十六章

[_17_01_01_]
=== ○陽貨欲見孔子 孔子不見 歸孔子豚  孔子時其亡也 而往拜之 遇諸途 (陽貨-17-01-01)

陽貨 季氏家臣 名虎 嘗囚季桓子而專國政. 欲令孔子來見己 而孔子不往 貨以禮 大夫有賜於士 不得受於其家 則往拜其門. 故瞰孔子之亡 而歸之豚. 欲令孔子來拜 而見之也.

[_17_01_02_]
=== 謂孔子曰 來 予與爾言 曰 懷其寶而迷其邦 可謂仁乎 曰 不可 好從事而亟失時 可謂知乎 曰 不可 日月逝矣 歲不我與 孔子曰 諾 吾將仕矣 (陽貨-17-01-02)

懷寶迷邦 謂懷藏道德 不救國之迷亂. 亟 數也. 失時 謂不及事幾之會. 將者 且然而未必之辭. 貨語皆譏孔子 而諷使速仕. 孔子固未嘗如此 而亦非不欲仕也. 但不仕於貨耳. 故直據理答之 不復與辯 若不諭其意者. ○陽貨之欲見孔子 雖其善意 然不過欲使助己爲亂耳. 故孔子不見者 義也. 其往拜者 禮也. 必時其亡而往者 欲其稱也. 遇諸塗而不避者 不終絶也. 隨問而對者 理之直也. 對而不辨者 言之孫 而亦無所詘也. 楊氏曰 揚雄謂孔子於陽貨也 敬所不敬 爲詘身以信道 非知孔子者. 蓋道外無身 身外無道. 身詘矣 而可以信道 吾未之信也.

[_17_02_01_]
=== ○子曰 性相近也 習相遠也 (陽貨-17-02-01)

此所謂性 兼氣質而言者也. 氣質之性 固有美惡之不同矣. 然以其初而言 則皆不甚相遠也. 但習於善則善 習於惡則惡 於是始相遠耳. ○程子曰 此言氣質之性 非言性之本也. 若言其本 則性卽是理 理無不善 孟子之言性善是也. 何相近之有哉.

[_17_03_01_]
=== ○子曰 唯上知與下愚 不移 (陽貨-17-03-01)

此承上章而言 人之氣質相近之中 又有美惡一定 而非習之所能移者. ○程子曰 人性本善 有不可移者何也. 語其性 則皆善也. 語其才 則有下愚之不移. 所謂下愚 有二焉 自暴自棄也. 人苟以善自治 則無不可移. 雖昏愚之至 皆可漸磨而進也. 惟自暴者拒之以不信 自棄者絶之以不爲. 雖聖人與居 不能化而入也. 仲尼之所謂下愚也. 然其質非必昏且愚也 往往强戾而才力有過人者 商辛是也. 聖人以其自絶於善 謂之下愚. 然考其歸 則誠愚也 或曰 此與上章當合爲一 子曰二字 蓋衍文耳.

[_17_04_01_]
=== ○子之武城 聞弦歌之聲 (陽貨-17-04-01)

弦 琴瑟也. 時子遊爲武城宰 以禮樂爲敎 故邑人皆弦歌也.

[_17_04_02_]
=== 夫子莞爾而笑曰 割鷄 焉用牛刀 (陽貨-17-04-02)

莞爾 小笑貌. 蓋喜之也. 因言其治小邑 何必用此大道也.

[_17_04_03_]
=== 子游對曰 昔者偃也聞諸夫子曰 君子學道則愛人 小人學道則易使也 (陽貨-17-04-03)

君子小人 以位言之. 子遊所稱 蓋夫子之常言. 言君子小人 皆不可以不學 故武城雖小 亦必敎以禮樂.

[_17_04_04_]
=== 子曰 二三子 偃之言是也 前言戱之耳 (陽貨-17-04-04)

嘉子遊之篤信 又以解門人之惑也. ○治有大小 而其治之必用禮樂 則其爲道一也. 但衆人多不能用 而子游獨行之 故夫子驟聞而深喜之 因反其言以戱之. 而子游以正對 故復是其言 而自實其戱也.

[_17_05_01_]
=== ○公山弗擾以費畔 召 子欲往 (陽貨-17-05-01)

弗擾 季氏宰 與陽虎共執桓子 據邑以叛.

[_17_05_02_]
=== 子路不說曰 末之也已 何必公山氏之之也 (陽貨-17-05-02)

末 無也. 言道旣不行 無所往矣. 何必公山氏之往也.

[_17_05_03_]
=== 子曰 夫召我者 而豈徒哉 如有用我者 吾其爲東周乎 (陽貨-17-05-03)

豈徒裁 言必用我也. 爲東周 言興周道於東方. ○程子曰 聖人以天下無不可有爲之人 亦無不可改過之人 故欲往. 然而終不往者 知其必不能改故也.

[_17_06_01_]
=== ○子張問仁於孔子 孔子曰 能行五者於天下 爲仁矣 請問之 曰 恭 寬 信 敏 惠 恭則不侮 寬則得衆 信則人任焉 敏則有功 惠則足以使人 (陽貨-17-06-01)

行是五者 則心存而理得矣. 於天下言無適而不然. 猶所謂雖之夷狄 不可棄者. 五者之目 蓋因子張所不足而言耳. 任 倚仗也. 又言其效如此. ○張敬夫曰 能行此五者於天下 則其心公平而周遍可知矣. 然恭其本與. 李氏曰 此章與六言六蔽五美四惡之類 皆與前後文體大不相似.

[_17_07_01_]
=== ○佛肹召 子欲往 (陽貨-17-07-01)

拂肹 晉大夫 趙氏之中牟宰也.

[_17_07_02_]
=== 子路曰 昔者由也聞諸夫子曰 親於其身爲不善者 君子不入也 佛肹以中牟畔 子之往也 如之何 (陽貨-17-07-02)

子路恐佛肹之浼夫子 故問此而止夫子之行. 親 猶自也. 不入 不入其黨也.

[_17_07_03_]
=== 子曰 然 有是言也 不曰堅乎 磨而不磷 不曰白乎 涅而不緇 (陽貨-17-07-03)

磷 薄也. 涅 染皂物. 言人之不善 不能浼己. 楊氏曰 磨不磷 涅不緇而後無可無不可. 堅白不足 而欲自試於磨涅 其不磷緇也者幾希.

[_17_07_04_]
=== 吾豈匏瓜也哉 焉能繫而不食 (陽貨-17-07-04)

匏 瓠也. 匏瓜 繫於一處而不能飮食 人則不如是也. ○張敬夫曰 子路昔者之所聞 君子守身之常法. 夫子今日之所言 聖人體道之大權也. 然夫子於公山佛肹之召 皆欲往者 以天下無不可變之人 無不可爲之事也. 其卒不往者 知其人之終不可變 而事之終不可爲耳. 一則生物之仁 一則知人之智也.

[_17_08_01_]
=== ○子曰 由也 女聞六言六蔽矣乎 對曰 未也 (陽貨-17-08-01)

蔽 遮掩也.

[_17_08_02_]
=== 居 吾語女 (陽貨-17-08-02)

禮 君子問 更端 則起而對. 故夫子諭子路 使還坐而告之.

[_17_08_03_]
=== 好仁不好學 其蔽也愚 好知不好學 其蔽也蕩 好信不好學 其蔽也賊 好直不好學 其蔽也絞 好勇不好學 其蔽也亂 好剛不好學 其蔽也狂 (陽貨-17-08-03)

六言 皆美德 然徒好之而不學以明其理 則各有所蔽. 愚 若可陷可罔之類. 蕩 謂窮高極廣而無所止. 賊 謂傷害於物. 勇者 剛之發. 剛者 勇之體. 狂 躁率也. 范氏曰 子路勇於爲善 其失之者 未能好學以明之也. 故告之以此 曰勇 曰剛 曰信 曰直 又皆所以救其偏也.

[_17_09_01_]
=== ○子曰 小子 何莫學夫詩 (陽貨-17-09-01)

小子 弟子也.

[_17_09_02_]
=== 詩可以興 (陽貨-17-09-02)

感發志意.

[_17_09_03_]
=== 可以觀 (陽貨-17-09-03)

考見得失,

[_17_09_04_]
=== 可以群 (陽貨-17-09-04)

和而不流.

[_17_09_05_]
=== 可以怨 (陽貨-17-09-05)

怨而不怒.

[_17_09_06_]
=== 邇之事父 遠之事君 (陽貨-17-09-06)

人倫之道 時無不備. 二者擧重而言.

[_17_09_07_]
=== 多識於鳥獸草木之名 (陽貨-17-09-07)

其緖餘又足以資多識. ○學詩之法 此章盡之. 讀是經者 所宜盡心也.

[_17_10_01_]
=== ○子謂伯魚曰 女爲周南召南矣乎 人而不爲周南召南 其猶正牆面而立也與 (陽貨-17-10-01)

爲 猶學也. 周南召南 詩首篇名. 所言皆修身齊家之事. 正牆面而立 言卽其至近之地 而一物無所見 一步不可行.

[_17_11_01_]
=== ○子曰 禮云禮云 玉帛云乎哉 樂云樂云 鐘鼓云乎哉 (陽貨-17-11-01)

敬而將之以玉帛 則爲禮. 和而發之以鐘鼓 則爲樂. 遺其本而專事其末 則豈禮樂之謂哉. ○程子曰 禮只是一箇序 樂只是一箇和 只此兩字含蓄多少義理. 天下無一物無禮樂 且如置此兩椅 一不正便是無序. 無序便乖 乖便不和. 又如盜賊 至爲不道 然亦有禮樂. 蓋必有總屬 必相聽順 乃能爲盜. 不然則叛亂無統 不能一日相聚而爲盜也. 禮樂無處無之 學者要須識得.

[_17_12_01_]
=== ○子曰 色厲而內荏 譬諸小人 其猶穿窬之盜也與 (陽貨-17-12-01)

厲 威嚴也. 荏 柔弱也. 小人 細民也. 穿 穿壁. 窬 踰牆. 言其無實盜名 而常畏人知也.

[_17_13_01_]
=== ○子曰 鄕原 德之賊也 (陽貨-17-13-01)

鄕者 鄙俗之意. 原 與愿同. 荀子原慤註 讀作愿是也. 鄕原 鄕人之愿者也. 蓋其同流合汙 以媚於世 故在鄕人之中 獨以愿稱. 夫子以其似德非德 而反亂乎德 故以爲德之賊 而深惡之. 詳見孟子末篇.

[_17_14_01_]
=== ○子曰 道聽而塗說 德之棄也 (陽貨-17-14-01)

雖聞善言 不爲己有 是自棄其德也 ○王氏曰 君子多識前言往行 以畜其德. 道聽塗說 則棄之矣.

[_17_15_01_]
=== ○ 子曰 鄙夫 可與事君也與哉 (陽貨-17-15-01)

鄙夫 庸惡陋劣之稱.

[_17_15_02_]
=== 其未得之也 患得之 旣得之 患失之 (陽貨-17-15-02)

何氏曰 患得之 謂患不能得之.

[_17_15_03_]
=== 苟患失之 無所不至矣 (陽貨-17-15-03)

小則吮癰舐痔 大則弑父與君 皆生於患失而已. ○胡氏曰 許昌靳裁之有言曰 士之品 大槩有三 志於道德者 功名不足以累其心. 志於功名者 富貴不足以累其心. 志於富貴而已者 則亦無所不至矣. 志於富貴 卽孔子所謂鄙夫也.

[_17_16_01_]
=== ○子曰 古者民有三疾 今也或是之亡也 (陽貨-17-16-01)

氣失其平 則爲疾. 故氣稟之偏者 亦謂之疾. 昔所謂疾 今亦亡之 傷俗之益偸也.

[_17_16_02_]
=== 古之狂也肆 今之狂也蕩 古之矜也廉 今之矜也忿戾 古之愚也直 今之愚也詐而已矣 (陽貨-17-16-02)

狂者 志願太高. 肆 謂不拘小節. 蕩 則踰大閑矣. 矜者 持守太嚴. 廉 謂稜角峭厲. 忿戾 則至於爭矣. 愚者 暗昧不明. 直 謂徑行自遂. 詐 則挾私妄作矣. ○范氏曰 末世滋僞 豈惟賢者不如古哉. 民性之蔽 亦與古人異矣.

[_17_17_01_]
=== ○子曰 巧言令色 鮮矣仁 (陽貨-17-17-01)

[_17_18_01_]
=== ○子曰 惡紫之奪朱也 惡鄭聲之亂雅樂也 惡利口之覆邦家者 (陽貨-17-18-01)

朱 正色. 紫 間色. 雅 正也. 利口 捷給. 覆 傾敗也. ○范氏曰 天下之理 正而勝者常少. 不正而勝者常多. 聖人所以惡之也. 利口之人 以是爲非 以非爲是 以賢爲不肖 以不肖爲賢. 人君苟悅而信之 則國家之覆也 不難矣.

[_17_19_01_]
=== ○子曰 予欲無言 (陽貨-17-19-01)

學者多以言語觀聖人 而不察其天理流行之實 有不待言而著者. 是以徒得其言 而不得其所以言 故夫子發此以警之.

[_17_19_02_]
=== 子貢曰 子如不言 則小子何述焉 (陽貨-17-19-02)

子貢 正以言語 觀聖人者 故疑而問之.

[_17_19_03_]
=== 子曰 天何言哉 四時行焉 百物生焉 天何言哉 (陽貨-17-19-03)

四時行 百物生 莫非天理發見流行之實 不待言而可見. 聖人一動一靜 莫非妙道精義之發 亦天而已. 豈待言而顯哉. 此亦開示子貢之切 惜乎其終不喩也. ○程子曰 孔子之道 譬如日星之明 猶患門人未能盡曉. 故曰予欲無言 若顔子 則便黙識. 其他則未免疑問. 故曰小子何述 又曰 天何言哉 四時行焉 百物生焉. 則可謂至明白矣. 愚按此與前篇無隱之意相發 學者詳之.

[_17_20_01_]
=== ○孺悲欲見孔子 孔子辭以疾 將命者出戶 取瑟而歌 使之聞之 (陽貨-17-20-01)

孺悲 魯人 嘗學士喪禮於孔子. 當是時必有以得罪者 故辭以疾 而又使知其非疾以警敎之也. 程子曰 此孟子所謂不屑之敎誨 所以深敎之也.

[_17_21_01_]
=== ○宰我問三年之喪 期已久矣 (陽貨-17-21-01)

期 周年也.

[_17_21_02_]
=== 君子三年不爲禮 禮必壞 三年不爲樂 樂必崩 (陽貨-17-21-02)

恐居喪不習而崩壞也.

[_17_21_03_]
=== 舊穀旣沒 新穀旣升 鑽燧改火 期可已矣 (陽貨-17-21-03)

沒 盡也. 升 登也. 燧 取火之木也. 改火 春取楡柳之火 夏取棗杏之火 夏季取桑柘之火 秋取柞楢之火 冬取槐檀之火 亦一年而周也. 已 止也. 言期年則天運一周 時物皆變 喪至此可止也. 尹氏曰 短喪之說 下愚且恥言之. 宰我親學聖人之門 而以是爲問者 有所疑於心 而不敢强焉爾.

[_17_21_04_]
=== 子曰 食夫稻 衣夫錦 於女安乎 曰安 (陽貨-17-21-04)

禮 父母之喪 旣殯食粥麤衰. 旣葬 疏食水飮 受以成布. 期而小祥 始食菜果 練冠縓緣 要絰不除. 無食稻衣錦之理. 夫子欲宰我反求諸心 自得其所以不忍者. 故問之以此 而宰我不察也.

[_17_21_05_]
=== 女安則爲之 夫君子之居喪 食旨不甘 聞樂不樂 居處不安 故不爲也 今女安則爲之 (陽貨-17-21-05)

此夫子之言也. 旨 亦甘也. 初言女安則爲之 絶之之辭. 又發其不忍之端 以警其不察 而再言女安則爲之 以深責之.

[_17_21_06_]
=== 宰我出 子曰 予之不仁也 子生三年然後 免於父母之懷 夫三年之喪 天下之通喪也 予也有三年之愛於其父母乎 (陽貨-17-21-06)

宰我旣出 夫子懼其眞以爲可安而遂行之 故深探其本而斥之. 言由其不仁 故愛親之薄 如此也. 懷 抱也. 又言君子所以不忍於親 而喪必三年之故 使之聞之 或能反求而終得其本心也. ○范氏曰 喪雖止於三年 然賢者之情則無窮也. 特以聖人爲之中制 而不敢過 故必俯而就之 非以三年之喪爲足以報其親也. 所謂三年然後免於父母之懷 特以責宰我之無恩 欲其有以跂而及之耳.

[_17_22_01_]
=== ○子曰 飽食終日 無所用心 難矣哉 不有博奕者乎 爲之猶賢乎已 (陽貨-17-22-01)

博 局戱也. 弈 圍棊也. 已 止也. 李氏曰 聖人非敎人博弈也. 所以甚言無所用心之不可爾.

[_17_23_01_]
=== ○子路曰 君子尙勇乎 子曰 君子義以爲上 君子有勇而無義 爲亂 小人有勇而無義 爲盜 (陽貨-17-23-01)

尙 上之也. 君子爲亂 小人爲盜 皆以位而言者也. 尹氏曰 義以爲尙 則其爲勇也大矣. 子路好勇 故夫子以此救其失也. 胡氏曰 疑此子路初見孔子時問答也.

[_17_24_01_]
=== ○子貢曰 君子亦有惡乎 子曰 有惡 惡稱人之惡者 惡居下流而訕上者 惡勇而無禮者 惡果敢而窒者 (陽貨-17-24-01)

訕 謗毁也. 窒 不通也. 稱人惡 則無仁厚之意 下訕上則無忠敬之心 勇無禮則爲亂 果而窒則妄作 故夫子惡之.

[_17_24_02_]
=== 曰 賜也 亦有惡乎 惡徼以爲知者 惡不孫以爲勇者 惡訐以爲直者 (陽貨-17-24-02)

惡徼以下 子貢之言也. 徼 伺察也. 訐 謂攻發人之陰私. ○楊氏曰 仁者無不愛 則君子疑若無惡矣 子貢之有是心也 故問焉以質其是非. 侯氏曰 聖賢之所惡如此 所謂惟仁者 能惡人也.

[_17_25_01_]
=== ○子曰 唯女子與小人 爲難養也 近之則不孫 遠之則怨 (陽貨-17-25-01)

此小人 亦謂僕隸下人也. 君子之於臣妾 莊以涖之 慈以畜之 則無二者之患矣.

[_17_26_01_]
=== ○子曰 年四十而見惡焉 其終也已 (陽貨-17-26-01)

四十 成德之時 見惡於人 則止於此而已. 勉人及時遷善改過也. 蘇氏曰 此亦有爲而言 不知其爲誰也.

論語集註大全卷之十八

[_18_]
== 微子第十八

此篇多記聖賢之出處. 凡十一章.

[_18_01_01_]
=== ○微子去之 箕子爲之奴 比干諫而死 (微子-18-01-01)

微.箕 二國名. 子 爵也. 微子 紂庶兄. 箕子 比干 紂諸父. 微子見紂無道 去之以存宗祀. 箕子.比干皆諫 紂殺比干 囚箕子以爲奴. 箕子因佯狂而受辱.

[_18_01_02_]
=== 孔子曰 殷有三仁焉 (微子-18-01-02)

三人之行不同 而同出於至誠惻怛之意 故不咈乎愛之理 而有以全其心之德也. 楊氏曰 此三人者 各得其本心 故同謂之仁.

[_18_02_01_]
=== ○柳下惠爲士師 三黜 人曰 子未可以去乎 曰直道而事人 焉往而不三黜 枉道而事人 何必去父母之邦 (微子-18-02-01)

士師 獄官. 黜 退也. 柳下惠三黜不去 而其辭氣雍容如此 可謂和矣. 然其不能枉道之意 則有確乎不可拔者 是則所謂必以其道而不自失焉者也. ○胡氏曰 此必有孔子斷之之言 而亡之矣.

[_18_03_01_]
=== ○齊景公待孔子曰 若季氏 則吾不能 以季孟之間待之 曰 吾老矣 不能用也 孔子行 (微子-18-03-01)

魯三卿 季氏最貴 孟氏爲下卿. 孔子去之事 見世家. 然此言必非面語孔子 蓋自以告其臣 而孔子聞之爾. ○程子曰 季氏强臣 君待之之禮極隆 然非所以待孔子也. 以季孟之間待之 則禮亦至矣. 然復曰吾老矣 不能用也. 故孔子去之. 蓋不繫待之輕重 特以不用而去爾.

[_18_04_01_]
=== ○齊人歸女樂 季桓子受之 三日不朝 孔子行 (微子-18-04-01)

季桓子 魯大夫 名斯. 按史記定公十四年孔子爲魯司寇 攝行相事. 齊人懼 歸女樂以沮之. 尹氏曰 受女樂而怠於政事如此 其簡賢棄禮 不足與有爲可知矣. 夫子所以行也. 所謂見幾而作 不俟終日者與. ○范氏曰 此篇記仁賢之出處 而折中以聖人之行 所以明中庸之道也.

[_18_05_01_]
=== ○楚狂接輿歌而過孔子曰 鳳兮鳳兮 何德之衰 往者不可諫 來者猶可追 已而已而 今之從政者殆而 (微子-18-05-01)

接輿 楚人. 佯狂避世. 夫子時將適楚 故接與歌而過其車前也. 鳳 有道則見 無道則隱. 接輿以比孔子 而譏其不能隱 爲德衰也. 來者可追 言及今尙可隱去. 已 止也. 而 語助辭. 殆 危也. 接輿 蓋知尊夫子而趨不同者也.

[_18_05_02_]
=== 孔子下 欲與之言 趨而辟之 不得與之言 (微子-18-05-02)

孔子下車 蓋欲告之以出處之意. 接輿自以爲是 故不欲聞而辟之也.

[_18_06_01_]
=== ○長沮桀溺 耦而耕 孔子過之 使子路問津焉 (微子-18-06-01)

二人 隱者. 耦 並耕也. 時孔子自楚反乎蔡. 津 濟渡處.

[_18_06_02_]
=== 長沮曰 夫執輿者爲誰 子路曰 爲孔丘 曰是魯孔丘與 曰 是也 曰 是知津矣 (微子-18-06-02)

執輿 執轡在車也. 蓋本子路御而執轡 今下問津 故夫子代之也. 知津 言數周流 自知津處.

[_18_06_03_]
=== 問於桀溺 桀溺曰 子爲誰 曰 爲仲由 曰 是魯孔丘之徒與 對曰然 曰 滔滔者 天下皆是也 而誰以易之 且而與其從辟人之士也 其若從辟世之士哉 耰而不輟 (微子-18-06-03)

滔滔 流而不反之意. 以 猶與也. 言天下皆亂 將誰與變易之. 而 汝也. 辟人 謂孔子. 辟世 桀溺自謂. 耰 覆種也. 亦不告以津處.

[_18_06_04_]
=== 子路行以告 夫子憮然曰 鳥獸不可與同群 吾非斯人之徒與而誰與 天下有道 丘不與易也 (微子-18-06-04)

憮然 猶悵然 惜其不喩己意也. 言所當與同羣者 斯人而已 豈可絶人逃世以爲潔哉. 天下若已平治 則我無用變易之. 正爲天下無道 故欲以道易之耳. ○程子曰 聖人不敢有忘天下之心 故其言如此也. 張子曰 聖人之仁不以無道必天下而棄之也.

[_18_07_01_]
=== ○子路從而後 遇丈人以杖荷蓧 子路問曰 子見夫子乎 丈人曰 四體不勤 五穀不分 孰爲夫子 植其杖而芸 (微子-18-07-01)

丈人 亦隱者. 蓧 竹器. 分 辨也. 五穀不分 猶言不辨菽麥爾. 責其不事農業 而從師遠遊也. 植 立之也. 芸 去草也.

[_18_07_02_]
=== 子路拱而立 (微子-18-07-02)

知其隱者 敬之也.

[_18_07_03_]
=== 止子路宿 殺鷄爲黍而食之 見其二子焉 明日 子路行以告 子曰 隱者也 使子路反見之 至則行矣 (微子-18-07-03)

孔子使子路反見之 蓋欲告之以君臣之義. 而丈人意子路必將復來 故先去之以滅其跡. 亦接輿之意也.

[_18_07_04_]
=== 子路曰 不仕無義 長幼之節 不可廢也 君臣之義 如之何其廢之 欲潔其身 而亂大倫 君子之仕也 行其義也 道之不行 已知之矣 (微子-18-07-04)

子路述夫子之意如此 蓋丈人之接子路甚倨 而子路益恭. 丈人因見其二子焉 則於長幼之節 固知其不可廢矣. 故因其所明以曉之. 倫 序也. 人之大倫有五 父子有親 君臣有義 夫婦有別 長幼有序 朋友有信是也. 仕所以行君臣之義. 故雖知道之不行 而不可廢. 然謂之義 則事之可否 身之去就 亦自有不可苟者. 是以雖不潔身以亂倫 亦非忘義以徇祿也. 福州有國初時寫本 路下有反子二字. 以此爲子路反而夫子言之也. 未知是否. ○范氏曰 隱者爲高 故往而不返. 仕者爲通 故溺而不止. 不與鳥獸同羣 則決性命之情以饕富貴 此二者皆惑也. 是以依乎中庸者爲難. 惟聖人不廢君臣之義 而必以其正. 所以或出或處 而終不離於道也.

[_18_08_01_]
=== ○逸民 伯夷.叔齊.虞仲.夷逸.朱張.柳下惠.少連 (微子-18-08-01)

逸 遺. 逸民者 無位之稱. 虞仲 卽仲雍 與泰伯同竄荊蠻者. 夷逸 朱張 不見經傳. 少連 東夷人.

[_18_08_02_]
=== 子曰 不降其志 不辱其身 伯夷叔齊與 (微子-18-08-02)

[_18_08_03_]
=== 謂柳下惠.少連 降志辱身矣 言中倫 行中慮 其斯而已矣 (微子-18-08-03)

柳下惠事見上 倫 義理之次第也. 慮 思慮也. 中慮 言有意義 合人心. 少連事不可考. 然記稱其善居喪 三日不怠 三月不懈 朞悲哀 三年憂 則行之中慮 亦可見矣.

[_18_08_04_]
=== 謂虞仲夷逸 隱居放言 身中淸 廢中權 (微子-18-08-04)

仲雍居吳 斷髮文身 裸以爲飾. 隱居獨善 合乎道之淸. 放言自廢 合乎道之權.

[_18_08_05_]
=== 我則異於是 無可無不可 (微子-18-08-05)

孟子曰 孔子可以仕則仕 可以止則止 可以久則久 可以速則速. 所謂無可無不可也. ○謝氏曰 七人隱遯不汙則同. 其立心造行則異. 伯夷叔齊 天子不得臣 諸侯不得友 蓋已遯世離羣矣. 下聖人一等 此其最高與. 柳下惠少連 雖降志而不枉已 雖辱身而不求合 其心有不屑也. 故言能中倫 行能中慮. 虞仲夷逸 隱居放言 則言不合先王之法者多矣. 然淸而不汙也 權而適宜也. 與方外之士害義傷敎而亂大倫者殊科. 是以均謂之逸民. 尹氏曰 七人各守其一卽 而孔子則無可無不可 所以常適其可而異於逸民之徒也. 揚雄曰 觀乎聖人 則見賢人. 是以孟子語夷惠 亦必以孔子斷之.

[_18_09_01_]
=== ○大師摯 適齊 (微子-18-09-01)

大師 魯樂官之長. 摯 其名也.

[_18_09_02_]
=== 亞飯干 適楚 三飯繚 適蔡 四飯缺 適秦 (微子-18-09-02)

亞飯以下 以樂侑食之官. 干 繚 缺 皆名也.

[_18_09_03_]
=== 鼓方叔 入於河 (微子-18-09-03)

鼓 擊鼓者. 方叔 名. 河 河內.

[_18_09_04_]
=== 播鼗武 入於漢 (微子-18-09-04)

播 搖也. 鼗 小鼓 兩方有耳 持其柄而搖之 則旁耳還自擊. 武 名也. 漢 漢中.

[_18_09_05_]
=== 小師陽擊磬襄入於海 (微子-18-09-05)

少師 樂官之佐. 陽襄 二人名. 襄 卽孔子所從學琴者. 海 海島也. ○此記賢人之隱遁 以附前章. 然未必夫子之言也. 末章放此. 張子曰 周衰樂廢 夫子自衛反魯 一嘗治之. 其後伶人賤工識樂之正. 及魯益衰 三桓僣妄 自大師以下 皆知散之四方. 逾河蹈海以去亂 聖人俄頃之助 功化如此. 如有用我 期月而可 豈虛語哉.

[_18_10_01_]
=== ○周公謂魯公曰 君子不施其親 不使大臣怨乎不以 故舊無大故 則不棄也 無求備於一人 (微子-18-10-01)

施 陸氏本作弛 福本同. ○魯公 周公子伯禽也. 弛 遺棄也. 以 用也. 大臣非其人則去之. 在其位 則不可不用. 大故 謂惡逆. 李氏曰 四者皆君子之事 忠厚之至也. ○胡氏曰 此伯禽受封之國 周公訓戒之辭. 魯人傳誦久而不忘也. 其或夫子嘗與門弟子言之歟.

[_18_11_01_]
=== ○周有八士 伯達 伯适 仲突 仲忽 叔夜 叔夏 季隨 季騧 (微子-18-11-01)

或曰 成王時人 或曰 宣王時人 蓋一母四乳而生八子也. 然不可考矣. ○張子曰 記善人之多也. 愚按此篇 孔子於三仁逸民師摯八士 旣皆稱贊而品列之 於接輿沮溺丈人 又每有惓惓接引之意 皆衰世之志也. 其所感者深矣. 在陳之歎 蓋亦如此. 三仁則無間然矣. 其餘數君子者 亦皆一世之高士. 若使得聞聖人之道 以裁其所過 而勉其所不及 則其所立 豈止於此而已哉.

論語集註大全卷之十九

[_19_]
== 子張第十九

此篇皆記弟子之言 而子夏爲多. 子貢次之. 蓋孔門自顔子以下 穎悟莫若子貢 自曾子以下 篤實無若子夏. 故特記之詳焉. 凡二十五章.

[_19_01_01_]
=== ○子張曰 士見危致命 見得思義 祭思敬 喪思哀 其可已矣 (子張-19-01-01)

致命 謂委致其命 猶言授命也. 四者立身之大節 一有不至 則餘無足觀. 故言士能如此 則庶乎其可矣.

[_19_02_01_]
=== ○子張曰 執德不弘 信道不篤 焉能爲有 焉能爲亡 (子張-19-02-01)

有所得而守之太狹 則德孤. 有所聞而信之不篤. 則道廢 焉能爲有亡 猶言不足爲輕重.

[_19_03_01_]
=== ○子夏之門人 問交於子張 子張曰 子夏云何 對曰 子夏曰 可者與之 其不可者拒之 子張曰 異乎吾所聞 君子尊賢而容衆 嘉善而矜不能 我之大賢與 於人何所不容 我之不賢與 人將拒我 如之何其拒人也 (子張-19-03-01)

子夏之言迫狹 子張譏之 是也. 但其所言 亦有過高之弊. 蓋大賢雖無所不容 然大故亦所當絶. 不賢固不可以拒人 然損友亦所當遠. 學者不可不察.

[_19_04_01_]
=== ○子夏曰 雖小道 必有可觀者焉 致遠恐泥 是以君子不爲也 (子張-19-04-01)

小道 如農圃醫卜之屬. 泥 不通也. ○楊氏曰 百家衆技 猶耳目鼻口 皆有所明而不能相通 非無可觀也. 致遠則泥矣 故君子不爲也.

[_19_05_01_]
=== ○子夏曰 日知其所亡 月無忘其所能 可謂好學也已矣 (子張-19-05-01)

亡 無也. 謂己之所未有. ○尹氏曰 好學者 日新而不失.

[_19_06_01_]
=== ○子夏曰 博學而篤志 切問而近思 仁在其中矣 (子張-19-06-01)

四者 皆學問思辨之事耳 未及乎力行而爲仁也. 然從事於此 則心不外馳 而所存自熟. 故曰仁在其中矣. ○程子曰 博學而篤志 切問而近思 可以言仁在其中矣. 學者要思得之 了此便是徹上徹下之道. 又曰 學不博 則不能守約. 志不篤 則不能力行. 切問近思在己者 則仁在其中矣. 又曰 近思者 以類而推. 蘇氏曰 博學而志不篤 則大而無成. 泛問遠思 則勞而無功.

[_19_07_01_]
=== ○子夏曰 百工居肆以成其事 君子學以致其道 (子張-19-07-01)

肆 謂官府造作之處. 致 極也. 工不居肆 則遷於異物 而業不精. 君子不學 則奪於外誘 而志不篤. 尹氏曰 學所以致其道也. 百工居肆 必務成其事 君子之於學 可不知所務哉. 愚按二設相須 其義始備.

[_19_08_01_]
=== ○子夏曰 小人之過也必文 (子張-19-08-01)

文 飾之也. 小人憚於改過 而不憚於自欺 故必文以重其過.

[_19_09_01_]
=== ○子夏曰 君子有三變 望之儼然 卽之也溫 聽其言也厲 (子張-19-09-01)

儼然者 貌之莊. 溫者 色之和. 厲者 辭之確. ○程子曰 他人儼然則不溫 溫則不厲. 惟孔子全之. 謝氏曰 此非有意於變 蓋並行而不相悖也. 如良玉溫潤而栗然.

[_19_10_01_]
=== ○子夏曰 君子信而後勞其民 未信 則以爲厲己也 信而後諫 未信 則以爲謗己也 (子張-19-10-01)

信 謂誠意惻怛 而人信之也. 厲 猶病也. 事上使下 皆必誠意交孚 而後可以有爲.

[_19_11_01_]
=== ○子夏曰 大德不踰閑 小德出入可也 (子張-19-11-01)

大德小德 猶言大節小節. 閑 闌也. 所以止物之出入. 言人能先立乎其大者 則小節雖或未盡合理 亦無害也. ○吳氏曰 此章之言 不能無弊 學者詳之.

[_19_12_01_]
=== ○子游曰 子夏之門人小子 當灑掃應對進退 則可矣 抑末也 本之則無 如之何 (子張-19-12-01)

子遊譏子夏弟子 於威儀容節之間 則可矣. 然此小學之末耳. 推其本 如大學正心誠意之事 則無有.

[_19_12_02_]
=== 子夏聞之曰 噫 言游過矣 君子之道 孰先傳焉 孰後倦焉 譬諸草木 區以別矣 君子之道 焉可誣也 有始有卒者 其惟聖人乎 (子張-19-12-02)

倦 如誨人不倦之倦. 區 猶類也. 言君子之道 非以其末爲先而傳之 非以其本爲後而倦敎. 但學者所至 自有淺深. 如草木之有大小 其類固有別矣. 若不量其淺深 不問其生熟 而槩以高且遠者 强而語之 則是誣之而已. 君子之道 豈可如此. 若夫始終本末 一以貫之 則惟聖人爲然 豈可責之門人小子乎. ○程子曰 君子敎人有序 先傳以小者近者 而後敎以大者遠者 非先傳以近小 而後不敎以遠大也. 又曰 洒掃應對便是形而上者 理無大小故也. 故君子只在謹獨. 又曰 聖人之道 更無精粗. 從洒掃應對 與精義入神貫通只一理. 雖洒掃應對 只看所以然如何. 又曰 凡物有本末 不可分本末爲兩段事. 洒掃應對是其然 必有所以然. 又曰 自洒掃應對上 便可到聖人事. 愚按程子第一條說此章 文意最爲詳盡. 其後四條 皆以明精粗本末 其分雖殊 而理則一. 學者當徇序而漸進 不可厭末而求本. 蓋與第一條之意 實相表裏 非謂末卽是本 但學其末而本便在此也.

[_19_13_01_]
=== ○子夏曰 仕而優則學 學而優則仕 (子張-19-13-01)

優 有餘力也. 仕與學理同而事異 故當其事者 必先有以盡其事而後可及其餘. 然仕而學則所以資其仕者益深. 學而仕 則所以驗其學者益廣.

[_19_14_01_]
=== ○子游曰 喪致乎哀而止 (子張-19-14-01)

致極其哀 不尙文飾也. 楊氏曰 喪與其易也寧戚. 不若禮不足而哀有餘之意 愚按 而止二字 亦微有過於高遠而簡略細微之弊 學者詳之.

[_19_15_01_]
=== ○子游曰 吾友張也 爲難能也 然而未仁 (子張-19-15-01)

子張行過高 而少誠實側怛之意.

[_19_16_01_]
=== ○曾子曰 堂堂乎張也 難與竝爲仁矣 (子張-19-16-01)

堂堂 容貌之盛. 言其務外自高 不可輔而爲仁 亦不能有以輔仁之仁也. ○范氏曰 子張外有餘而內不足 故門人皆不與其爲仁. 子曰 剛毅木訥近仁. 寧外不足而內有餘 庶可以爲仁矣.

[_19_17_01_]
=== ○曾子曰 吾聞諸夫子 人未有自致者也 必也親喪乎 (子張-19-17-01)

致 盡其極也. 蓋人之眞情所不能自已者. ○尹氏曰 親喪固所自盡也. 於此不用其誠 惡乎用其誠.

[_19_18_01_]
=== ○曾子曰 吾聞諸夫子 孟莊子之孝也 其他可能也 其不改父之臣與父之政 是難能也 (子張-19-18-01)

孟莊子 魯大夫 名速. 其父獻子 名蔑. 獻子有賢德 而莊子能用其臣 守其政 故其他孝行雖有可稱 而皆不若此事之爲難.

[_19_19_01_]
=== ○孟氏使陽膚爲士師 問於曾子 曾子曰 上失其道 民散久矣 如得其情 則哀矜而勿喜 (子張-19-19-01)

陽膚 曾子弟子. 民散 謂情義乖離 不相維繫. 謝氏曰 民之散也 以使之無道 敎之無素 故其犯法也. 非迫於不得已 則陷於不知也. 故得其情則哀矜而勿喜.

[_19_20_01_]
=== ○子貢曰 紂之不善 不如是之甚也 是以君子惡居下流 天下之惡皆歸焉 (子張-19-20-01)

下流 地形卑下之處 衆流之所歸. 喩人身有汙賤之實 亦惡名之所聚也. 子貢言此欲人常自警省 不可一置其身於不善之地. 非謂紂本無罪 而虛被惡名也.

[_19_21_01_]
=== ○子貢曰 君子之過也 如日月之食焉 過也 人皆見之 更也 人皆仰之 (子張-19-21-01)

[_19_22_01_]
=== ○衛公孫朝問於子貢曰 仲尼焉學 (子張-19-22-01)

公孫朝 衛大夫.

[_19_22_02_]
=== 子貢曰 文武之道 未墜於地 在人 賢者識其大者 不賢者識其小者 莫不有文武之道焉 夫子焉不學 而亦何常師之有 (子張-19-22-02)

文武之道 謂文王武王之謨訓功烈 與凡周之禮樂文章 皆是也. 在人 言人有能記之者. 識 記也.

[_19_23_01_]
=== ○叔孫武叔語大夫於朝曰 子貢賢於仲尼 (子張-19-23-01)

武叔 魯大夫 名州仇.

[_19_23_02_]
=== 子服景伯以告子貢 子貢曰 譬之宮牆 賜之牆也及肩 窺見室家之好 (子張-19-23-02)

牆卑 室淺.

[_19_23_03_]
=== 夫子之牆數仞 不得其門而入 不見宗廟之美 百官之富 (子張-19-23-03)

七尺曰仞 不入其門 則不見其中之所有. 言牆高而宮廣也

[_19_23_04_]
=== 得其門者或寡矣 夫子之云 不亦宜乎 (子張-19-23-04)

此夫子 指武叔.

[_19_24_01_]
=== ○叔孫武叔毁仲尼 子貢曰 無以爲也 仲尼不可毁也 他人之賢者 丘陵也 猶可踰也 仲尼 日月也 無得而踰焉 人雖欲自絶 其何傷於日月乎 多見其不知量也 (子張-19-24-01)

無以爲 猶言無用爲此. 土高曰丘 大阜曰陵. 日月 喩其至高. 自絶 謂以毁謗自絶於孔子. 多 與祗同 適也. 不知量 謂不自知其分量也.

[_19_25_01_]
=== ○陳子禽謂子貢曰 子爲恭也 仲尼豈賢於子乎 (子張-19-25-01)

爲恭 謂爲恭敬推遜其師也.

[_19_25_02_]
=== 子貢曰 君子一言以爲知 一言以爲不知 言不可不愼也 (子張-19-25-02)

責子禽不謹言.

[_19_25_03_]
=== 夫子之不可及也 猶天之不可階而升也 (子張-19-25-03)

階 梯也. 大可爲也 化不可爲也. 故曰不可階而升也.

[_19_25_04_]
=== 夫子之得邦家者 所謂立之斯立 道之斯行 綏之斯來 動之斯和 其生也榮 其死也哀 如之何其可及也 (子張-19-25-04)

立之 謂植其生也. 道 引也. 謂敎之也. 行 從也. 綏 安也. 來 歸附也. 動 謂鼓舞之也. 和 所謂於變時雍. 言其感應之妙 神速如此. 榮 謂莫不尊親. 哀則如喪考妣. 程子曰 此聖人之神化 上下與天地同流者也. ○謝氏曰 觀子貢稱聖人語 乃知晩年進德 蓋極於高遠也. 夫子之得邦家者 其鼓舞羣動 捷於桴鼓影響. 人雖見其變化而莫窺其所以變化也. 蓋不離於聖 而有不可知者存焉. 聖而進於不可知之之神矣. 此殆難以思勉及也.

論語集註大全卷之二十

[_20_]
== 堯曰第二十

凡三章

[_20_01_01_]
=== ○堯曰 咨 爾舜 天之曆數在爾躬 允執厥中 四海困窮 天祿永終 (堯曰-20-01-01)

此堯命舜 而禪以帝位之辭. 咨 嗟歎聲. 曆數 帝王相繼之次第. 猶歲時氣節之先後也. 允 信也. 中者 無過不及之名. 四海之人困窮 則君祿亦永絶矣. 戒之也.

[_20_01_02_]
=== 舜亦以命禹 (堯曰-20-01-02)

舜後遜位於禹 亦以此辭命之. 今見於虞書大禹謨. 比此加詳.

[_20_01_03_]
=== 曰 予小子履 敢用玄牡 敢昭告于皇皇后帝 有罪不敢赦 帝臣不蔽 簡在帝心 朕躬有罪 無以萬方 萬方有罪 罪在朕躬 (堯曰-20-01-03)

此引商書湯誥之辭. 蓋湯旣放桀 而告諸侯也. 與書文大同小異. 曰上當有湯字. 履 蓋湯名. 用玄牡 夏尙黑 未變其禮也. 簡 閱也. 言桀有罪 己不敢赦 而天下賢人皆上帝之臣 己不敢蔽. 簡在帝心 惟帝所命. 此述其初請命而伐桀之詞也. 又言君有罪 非民所致. 民有罪 實君所爲. 見其厚於責己 薄於責人之意. 此其告諸侯之辭也.

[_20_01_04_]
=== 周有大賚 善人是富 (堯曰-20-01-04)

此以下 述武王事. 賚 予也. 武王克商 大賚于四海. 見周書武成篇. 此言其所富者 皆善人也. 詩序曰 賚所以錫予善人 蓋本於此.

[_20_01_05_]
=== 雖有周親 不如仁人 百姓有過 在予一人 (堯曰-20-01-05)

此周書泰誓之辭. 孔氏曰 周 至也. 言紂至親雖多 不如周家之多仁人.

[_20_01_06_]
=== 謹權量 審法度 修廢官 四方之政行焉 (堯曰-20-01-06)

權 稱錘也. 量 斗斛也. 法度 禮樂制度皆是也.

[_20_01_07_]
=== 興滅國 繼絶世 擧逸民 天下之民歸心焉 (堯曰-20-01-07)

興滅繼絶 謂封黃帝堯舜夏商之後. 擧逸民 謂釋箕子之囚 復商容之位 三者皆人心之所欲也.

[_20_01_08_]
=== 所重民食喪祭 (堯曰-20-01-08)

武成曰 重民五敎 惟食喪祭.

[_20_01_09_]
=== 寬則得衆 信則民任焉 敏則有功 公則說 (堯曰-20-01-09)

此於武王之事無所見 恐或泛言帝王之道也. ○楊氏曰 論語之書 皆聖人微言而其徒傳守之 以明斯道者也. 故於終篇 具載堯舜咨命之言 湯武誓師之意 與夫施諸政事者 以明聖學之所傳者 一於是而已. 所以著明二十篇之大旨也. 孟子於終篇亦歷叙堯舜湯文孔子相承之次 皆此意也.

[_20_02_01_]
=== ○子張問於孔子曰 何如斯可以從政矣 子曰 尊五美 屛四惡 斯可以從政矣 子張曰 何謂五美 子曰 君子惠而不費 勞而不怨 欲而不貪 泰而不驕 威而不猛 子張曰 何謂惠而不費 子曰 因民之所利而利之 斯不亦惠而不費乎 擇可勞而勞之 又誰怨 欲仁而得仁 又焉貪 君子無衆寡 無小大 無敢慢 斯不亦泰而不驕乎 君子正其衣冠 尊其瞻視 儼然人望而畏之 斯不亦威而不猛乎 (堯曰-20-02-01)

[_20_02_02_]
=== 子張曰 何謂四惡 子曰 不敎而殺 謂之虐 不戒視成 謂之暴 慢令致期 謂之賊 猶之與人也 出納之吝 謂之有司 (堯曰-20-02-02)

虐 謂殘酷不仁. 暴 謂卒遽無漸. 致期 刻期也. 賊者 切害之意. 緩於前而急於後 以誤其民而必刑之 是賊害之也. 猶之 猶言均之也. 均之以物與人 而於其出納之際 乃或吝而不果. 則是有司之事 而非爲政之體. 所與雖多 人亦不懷其惠矣. 項羽使人有功當封 刻印刓 忍弗能予 卒以取敗 亦其驗也. ○尹氏曰 告問政者多矣 未有如此之備者也. 故記之以繼帝王之治. 則夫子之爲政可知也.

[_20_03_01_]
=== ○子曰 不知命 無以爲君子也 (堯曰-20-03-01)

程子曰 知命者 知有命而信之也. 不知命則見害必避 見利必趨 何以爲君子.

[_20_03_02_]
=== 不知禮 無以立也 (堯曰-20-03-02)

不知禮 則耳目無所加 手足無所措.

[_20_03_03_]
=== 不知言 無以知人也 (堯曰-20-03-03)

言之得失 可以知人之邪正. ○尹氏曰 知斯三者 則君子之事備矣. 弟子記此以終篇 得無意乎. 學者少而讀之 老而不知一言爲可用 不幾於侮聖言者乎. 夫子之罪人也 可不念哉.
