[[_0_]]
= Ökologische Kommunikation
Joy <arbago@gmail.com>
v1.0, 2015-5-6
:icons: font
:sectanchors:
:imagesdir: images
:homepage: http://arbago.com
:toc: macro

toc::[]

[preface]
== Environmental Communications

Ökologische Kommunikation: Kann die moderne Gesellschaft sich auf ökologische Gefährdungen einstellen? +
by Niklas Luhmann, 1981

Can modern society adapt to environmental hazards?

[quote, 미셀 드 몽테뉴, Apologie de Raimond Sebond]
____
우리말에는 약점과 결함이 있다 다른 모든 것들처럼 +
세계 혼란의 대부분은 문법학자들로 말미암는다
____

근대사회의 가장 중요한 기능체계

기본 구조에서는 매우 류사한 그림이 한개 나타난다 +
환경문제는 정치, 경제, 륜리 등만이 관련돈 것이 아니라, *사회체제*와 련관되어 있다

무분별한 어휘 선택과 큰 파급효과를 갖는 리론을 결정하는데 따른 직감력 부족은 환경문헌의 가장 뚜렷한 특징 중 하나다 마치 환경을 념려하는 것이 환경에 대한 경솔한 견해를 정당화할 수 있다는 듯이

문제는 좀더 근본에서 기능체계들의 분화에 있다

[[hayje]]
== 해제

1차식 관찰이 아니라, 사회에서 커뮤니케이션을 어떻게 하고 있는가를 다루는 2차식 관찰, 곧 [big blue underline]'`관찰의 관찰`'이다

사회가 환경문제에 어떻게 반응해야만 하는가가 아니라 +
사회가 환경문제에 어떻게 반응하는가이다

의식의 변화를 강조하거나 도덕에 호소해봐야 소용이 없다

환경은 환경으로서가 아니라 +
사회문제가 될 때, 즉 의사소통의의 대상이 될 때만 다룰 수 있는 '`사회내부`' 문제다 +
그래서 *사회 작동*을 파악해야 한다

처방전을 람발하기보다는 현실을 꿰뚫어보는 리론이 필요하다

기능으로 분화한 사회는 정점도 중심도 없이 작동한다 +
그래서 반향은 쪼개어 나타나며, 그리고 너무 적다

체계리론 System Theory::
체계는 분석용 도구가 아니라 실존하는 것이다

루만은 근대사회의 근본특징으로 기능분화를 꼽는다

기능마다 고유 커뮤니케이션만 생성하고 류통한다 +
이런 현상을 *분화독립화*로 부른다 +
정치는 정치얘기만, 경제는 경제얘기만 한다

이원코드::
사회의 모든 커뮤니케이션은 각 기능별로 고유한 코드로 기능특화 커뮤니케이션으로 축소된다 +
정치는 환경을 정치로만 다루고, 경제는 환경을 경제식으로만 다룬다

그래서 각 기능은 가지준거식-폐쇄식 체계다

루만의 체계리론은 체계에만 관한 것이 아니라 체계-환경의 차이에 관한 것이다 +
환경이 없으면 체계도 없고, 체계는 끝없이 환경과 접촉한다

환경은 체계 내에서만 구성된다::
환경은 타자준거정보처리의 전체지평이다 +
환경정보는 소음 또는 혼선이다가 체계 내부로 전환되야 그 체계의 구성요소가 된다

코드와 프로그램::
밥과 반찬

사회는 인간들로 구성되어 있지 않고, 커뮤니케이션으로 구성되어 있다::
체계가 살아있다고 가정하는 순간, 인간은 배제된 것임을 눈치챘어야 한다 +
인간은 심리고, 의식이 구성요소다

의식변화만으로 사회사실인 환경문제를 바꿀 수는 없다 +
오직 커뮤니케이션이 될 때만 효과가 있다

사회전체가 환경에 대응하는 것은 가치의 인플레이션을 부르고, 따라서 자칫 이데올로기편향으로 빠질 가능성이 높다 +
스스로 끝없이 *계몽*해야 한다 +
루만의 론문모음집시리즈의 제목이 *사회학식계몽*이다

반향::
한 기능의 변화가 다른 기능의 변화를 초래하는 상황 +
기능은 각기 독자로 작동하지만 상호의존하는 관계다

[[_1_0_1_]]
== 01 사회학식 금욕

[[_2_0_2_]]
== 02 원인과 책임?

[[_3_0_3_]]
== 03 복잡성과 진화

[[_4_0_4_]]
== 04 반향

[[_5_0_5_]]
== 05 관찰의 관찰

[[_6_0_6_]]
== 06 사회 작동으로서 커뮤니케이션

[[_7_0_7_]]
== 07 생태 지식과 사회 커뮤니케이션

[[_8_0_8_]]
== 08 이원 코드화

[[_9_0_9_]]
== 09 코드, 기준, 프로그램

[[_10_0_10_]]
== 10 경제

[[_11_0_11_]]
== 11 법

[[_12_0_12_]]
== 12 학문

[[_13_0_13_]]
== 13 정치

[[_14_0_14_]]
== 14 종교

[[_15_0_15_]]
== 15 교육

[[_16_0_16_]]
== 16 기능 분화

[[_17_0_17_]]
== 17 제한과 강화: 너무나 적은 그리고 너무나 많은 반향

[[_18_0_18_]]
== 18 대표와 자기관찰: '새로운 사회 운동'

[[_19_0_19_]]
== 19 두려움, 도덕 그리고 리론

[[_20_0_20_]]
== 20 생태 커뮤니케이션의 합리성에 대하여

[[_21_0_21_]]
== 21 환경륜리학
