[[_0_]]
= 탄소문명
Joy <arbago@gmail.com>
:icons: font
:sectanchors:
:toc: macro

toc::[]

[preface]
== 서론 원소의 절대 왕자

=== 보이지 않는 영웅

=== 왕자의 민낯

생명은 자연계에 존재하는 얼마 되지 않는 탄소를 긁어모아서 간신히 만들어졌다고 할 수 있다

탄소는 플러스와 마이너스를 가리지 않는, 불편부당한 존재이며, 이것이 결정히 중요한 요인이다

탄소는 수백만 개가 결합해도 서로 반발하지 않는다. 이로 인해서 길게 련결하여 안정하고 다양한 탄소화합물을 만드는 것이 가능하다

또한 탄소는 가장 작은 부류의 원소다. 그렇기 때문에 탄소로는 짧고 긴밀한 결합을 만들 수 있다. 결합의 팔 4개를 전부 사용하여 단일결합, 이중결합, 삼중결합 등으로 부르는 다채로운 련결방법을 채택할 수 있다.

[big blue yellow-background underline]#탄소는 작고 평범하지만, 이런 특성 때문에 *원소의 절대 왕자*의 자리에 오를 수 있었다#

=== 다양해진 세계

현재 '`유기화합물`'이라는 말은 탄소를 기본으로 한 화합물이라는 의미로 사용되고 있다. 생명이 만든 화합물들인 유기화합물의 많은 부분이 _탄소를 바탕_으로 만들어졌기 때문이다

그렇다면, 유기화합물과 무기화합물의 차이는 도대체 무엇일까? 언뜻 알 수 있는 것은 전자는 부드럽고 유연하며, 후자는 딱딱하고 변형하기 어려운 것이라는 점이다. 이런 차이는 _분자 구조_의 차이에서 유래한다

금속과 암석을 원자 수준에서 보면, 마치 성의 석벽처럼 원자들이 같은 구조로 쌓여 있다. 이런 동일한 패턴의 반복을 과학자는 "`*결정(crystal)*`"이라고 부른다 (반복련습의 루적으로 얻은 성과를 "`노력의 결정`"이라고 말하는 것은 상당히 합당한 표현이다). 결정 속에는 원자들이 빈틈없이 꽉 들어차 있기 때문에 원자들은 조금도 움직일 수 없고, 이로 인해서 전체로서의 결정은 단단하고 변형하기 어려운 물질이 된다

탄소도 극히 드물게 이러한 단단한 결정을 만들 수 있다. 순수한 탄소가 단단하게 결합하여 빽빽하게 속을 가득 채우고 있는 구조를 만들기 때문에 매우 단단한 물질이 되어 빛을 굴절함으로써 아름다운 빛을 발하는 탄소 결정이 있다. 바로 *다이아몬드*다

탄소가 단단한 골조를 만들고 수소가 칸막이를 제공함으로써 유기화합물에는 놀라울 정도로 풍부한 가능성이 생기는 것이다

탄소와 수소의 결합은 알려진 것만 해도 수백만이고, 가능성으로 보면 실제로 화합물을 무한정 만들 수 있다

=== 일상생활 속의 탄소

탄소의 비률 0.08퍼센트

눈에 보이는 물질들 중에서 탄소가 들어 있지 않은 것: 금속, 유리, 돌

셀룰로오스::
목재 등 식물의 몸체를 구성 +
탄소화합물 +
종이, 마, 면, 채소의 식물 섬유

인공 탄소화합물: 플라스틱, 고무

플라스틱::
폴리에틸렌: 단순한 탄화수소(hydrocarbon)의 련쇄 +
폴리프로필렌: 하나 간격으로 탄소의 가지가 붙은 구조

고무::
탄소의 사슬에 규칙히 이중결합이 포함됨

의약품::
분자설계의 궁극 +
신체의 단백질에 결합하여 그 움직임을 조절하여 약효를 발휘함

=== 탄소화합물과 력사

그렇다면 인류의 력사가 이들 탄소화합물에 크게 좌우되었던 것은 당연한 일이라고 할 수 있다 +
석유를 둘러싸고 벌어지는 일들

세계의 력사는 탄소화합물의 장대한 리합집산의 반복이었다고 할 수 있다

이것은 인류가 여러 형태로 탄소화합물을 생산하는 기술을 습득함으로써 변화에 크게 기여했기 때문이다

천연으로부터 얻은 하합물의 구조를 인공으로 변환하는 기술::
설탕의 구조를 일부 변환하여 칼로리가 없는 감미료를 만듦 +
설탕을 아세트산과 결합하면 쓴맛이 되고 +
황산과 결합하면 위 점막을 보호하는 의약품이 되고 +
질산과 결합하면 폭약이 된다

=== 력사를 움직인 모르핀

양귀비의 덜 익은 열매에 상처를 내서 얻은 유액(乳液)을 말려서 굳힌 것이 아편이다

阿片::
양귀비의 채 익지 않은 열매에 상처(傷處)를 내어서 뽑아낸 진을 말려서 굳힌 갈색(褐色) 가루. 모르핀 등(等)을 주(主) 성분(成分)으로 하는 마약으로서, 진통제(鎭痛劑)나 설사약(泄瀉藥) 등(等)에 쓰임

16세기에는 인도로부터 동남아시아 각지에 거대한 양귀비 밭이 만들어졌다

[W] morphine (môr′fēn′)::
An alkaloid, C17H19NO3, extracted from opium and used in the form of its hydrated sulfate or hydrochloride salt to relieve moderate to severe pain. Also called morphia. +
[French, from Morphée, Morpheus, from Latin Morpheus.] +
morphine - an alkaloid narcotic drug extracted from opium; a powerful, habit-forming narcotic used to relieve pain
* =morphia
* <>analgesic, anodyne, pain pill, painkiller - a medicine used to relieve pain
* <>apomorphine - a morphine derivative that is not as strong as morphine; used as an emetic and in small doses as a sedative
* <>opiate - a narcotic drug that contains opium or an opium derivative

모르핀::
1803년 서른 살의 독일인 약제사 프리드리히 제르튀르너 (Friedrich Sertürner) +
잘게 갈아서 으깬 아편을 산 (酸)으로 추출하여 암모니아를 리용하여 알칼리성으로 되돌리면 고체가 침전된다 +
이것을 다시 알코올로 재결정하고 정제하여 순수결정을 얻었다 +
그리스 신화의 잠의 신 모르페우스의 이름을 따서 이 성분을 "`모르핀(morphine)`"이라고 불렀다 +
모르핀은 식물로부터 약효성분을 순수하게 분리한 최초의 례에 해당한다

순수한 모르핀을 얻게 되자 유효성분을 정확하게 계산하여 투약하는 일이 가능해졌고 +
의약의로 사용하는 것이 대폭 늘어났다 +
"`눈대중`", "`어림짐작`"이 아니라, 데이타를 토대로 한 의학의 길이 열렸다고 할 수 있다

1896년 바이엘의 기침약::
1874년에 모르핀에 아세틸기라고 불리는 원자단 (原子團)을 더해서 체내의 흡수성을 높임 +
이 화합물을 1896년에 독일의 바이엘 사에서 기침약으로 발매

판도라의 상자, 헤로인::
모르핀은 생각지도 않게 판도라의 상자를 연 꼴이 되었다 +
이 화합물을 복용하는 대신에 정맥주사로 맞으면, 엄청난 행복감을 느끼고 +
약을 끊은 후에는 지옥 같은 금단증상이 찾아온다 +
이 약이 바로 헤로인이다

1840년 아편전쟁

=== 화합물 리용의 력사

탄소라는 미시의 관점으로 본 세계사

* 제1부: 인간의 생명을 지탱하는 물질군 +
칼로리를 제공하고 미각을 풍성하게 하며 식물의 안정성을 확보하는 것

** 향신료, 글루탐산 (glutamic acid)
* 제2부: 인간의 감정을 고조케하고 감동케 하여 훌륭한 문화를 구축한다
** 카페인, 뇨산, 니코틴, 에탄올
* 제3부: 사회를 움직이는 원동력이 된 에너지를 낳는 화합물
** 니트로 화합물, 암모니아, 석유

암모니아는 탄소를 포함하지 않는 무기화합물이지만 생체 내에서 탄소와 결합하여 중요한 역할을 하기 때문에 선택하였다

[big blue yellow-background underline]"`21세기는 탄소의 세기`"

탄소는 지구에서 얼마 되지 않는 자원이고, 그 *쟁탈전*은 이미 시작되었다 +
그것을 손에 넣지 않고는 "`22세기의 새벽`"을 볼 수 없을 것이다

[[_1_0_0_]]
== 제1부 인류의 생명을 지탱해준 물질들

[[_1_1_1_]]
=== 1. 문명사회를 만든 물질─록말

[[_1_1_2_]]
==== “인류”를 창조한 물질

녹말 綠末 전분 澱粉 starch

3대 작물: 쌀, 밀, 옥수수

우리의 몸을 움직이는 것은 탄소화합물이 산화되면서 이산화탄소와 물로 변할 때의 화학에너지다

포도당의 하이드록시기(Hydroxy기, OH)는 물 분자에 쉽게 끌리기 때문에 물에 녹아서 쉽게 흘러나간다. 에너지원으로서 쉽게 산화되는 것은 좋지만, 저장에는 그다지 적당하지 않다. 따라서 식물은 포도당을 많이 련결하여 다발로 보존하는 수단을 고안했다. 이것이 록말의 정체다

밥::
록말에 물을 넣어 가열한 후에 포도당 사이에 물분자가 들어가서 팽윤膨潤된(겔화, 호화糊化) 상태 +
록말의 결합이 느슨해지면서 소화분해가 용이해지고, 흡수가 좋아져서 섭취 칼로리도 늘어 식사에 필요한 시간이 대폭 단축된다

팽윤 膨潤::
용매(溶媒) 속에 담근 젤라틴이나 고무 따위의 고분자(高分子) 화합물(化合物)이 용매(溶媒)를 흡수(吸收)하여 차차 그 용적(容積)이 늘어 가는 현상(現象)

호화 糊化::
호화전분(糊化澱粉) 풀처럼 끈적끈적하게 된 상태(狀態)의 전분

인간은 겔화되지 않은 록말을 소화하는 능력을 잃게 되었다. 도토리 등을 생으로 먹으면 배탈이 난다. 체내에서 행해야 하는 소화의 기능을 불에 "`외부 위탁`"을 함으로써 칼로리와 시간, 그리고 높은 지능을 가지게 되었다고 볼 수 있다. 록말의 가열 조리는 인류에게 매우 중요한 전환점이 되었다

[[_1_1_3_]]
==== 농경 개시의 수수께끼

약 1만 년전의 비슷한 시기에 세계각제에서 서로 약속이라도 한 것처럼 농경을 시작했다

농경으로 해서 인류의 생활이 개선된 것은 아니다. 수렵생활 당시보다 키가 178센티에서 160센티로 작아졌고, 충치나 감염증의 위험이 높아져서 평균수명이 35.4세에서 30세로 줄었다

로동시간은 수렵시대의 하루 3시간보다 하루종일로동으로 훨씬 늘어났다

이런 사정만 보면 농경의 시작은 풍부한 식재료를 얻기 위한 획기한 신기술이 아니라 어떤 사정에 쫓겨 부득이하게 선택한 길이라고 생각하는 것도 당연하다

[[_1_1_4_]]
==== 사회의탄생

#`'富`'#라는 개념이 생겼다

부패와 변질이 잘 되지 않는다는 록말의 성질이, 그 촉진제가 되었다고 할 수 있다

록말 확보를 위해서 초기에는 다양한 작물들의 재배가 시도되었으나 결국 쌀, 밀, 옥수수를 비롯하여 몇몇 종으로 결정되었다. 이들 작물의 유전자가 변이를 일으키기 쉬웠다는 것이 선택의 큰 원인으로 생각되고 있다.

[CAUTION]
====
정말?
====

이곳에서 인류 력사의 막이 올랐다

[WARNING]
====
수렵시대의 기록은 련속되지 않고 새로운 문명만이 존재하게 되었다는 것인가?
====

[[_1_1_5_]]
==== 기후 변화와 력사

력사책을 살펴볼 때, 불가사의한 것이 있다 ... +
지도자의 그릇이 중요하지만, 력사를 움지이는 요인은 결코 그것뿐만은 아닐 것이다

그것이 바로 #기후#다

기후가 좋지 못해 수확이 충분하지 못하면 아무리 훌륭한 군주라도 민란이 일어난다. 그 반대로, 배부르면 정치가 다소 이상하더라도 세상은 평화롭고, 먹지 못하면 세상은 혼란스러워진다

그 중에서 사람들을 먹이는 일에 성공한 사람이 영웅이 되고, 최종에 모든 사람들에게 밥을 준 사람이 패자覇者가 된다

2세기 중반의 세계는 홍수와 가뭄이 많아 흉작이 이어졌고, 전란을 발생하였다. 대륙에서는 통일국가가 없었던 3국시대 220~280 였고, 로마에서는 군인황제가 란립한 위기의 3세기 235~284 였다 ··· 농경의 인구증가는 이런 거대전란의 씨앗을 키우는 원인이기도 했다

[[_1_1_6_]]
==== 기후 변화와 고대의 종언

민족이동 +
게르만의 로마 침입으로 인한 서로마의 붕괴 +
5호16국시대 304~439

중앙아시아가 건조하게 된 결과

535년에서부터 2년가 전지구에 이변이 일어나 햇빛이 약하고 흐려 추운 날이 계속되자 식량이 부족하게 되었다는 사실이 세계 여러 곳의 문헌에 남아 있다

이런 급격한 한랭화 현상은 세계 각지에 있는 나무의 나이테의 흔적으로 뒷받침된다

거대한 분화噴火로 인한 화산재가 태양빛을 가려서 일어난 현상으로 보이며 인도네시아의 크라카타우 섬을 지목하고 있다

이 한랭기후는 십수년간 계속됐고 결국 고대가 종언했다

[[_1_1_7_]]
==== 일본과 쌀

쌀에는 록말도 들어 있지만 량질의 단백질과 미네랄을 적당하게 들어 있다

비타민 B~1~은 쌀겨에서 발견되었기 때문에 쌀의 학명으로부터 따온 oryzanine이라고 명명되었다

논은 토지를 수평하게 만들어 물을 끌어와서 머물게 해야 한다

렬도는 록말 생산을 위해서 개조된 섬이라고 해도 과언이 아니다

.록말
* amylose: 포도당분자가 라선모양으로 길게 이어진 것
* amylopectin: 중간에 갈라진 것

amylopectin이 많으면 록말의 사슬이 뒤얽혀서 찰기가 좋아지는데, 100퍼센트인 것이 찹쌀이다.

amylose가 16퍼센트 인 것이 황금비률인 것 같다

[W] amylose (ăm′ə-lōs′, -lōz′)::
The inner portion of a starch granule, consisting of relatively soluble polysaccharides having an unbranched, linear, or spiral structure.

[W] amylopectin (ăm′ə-lō-pĕk′tĭn)::
The outer portion of a starch granule consisting of insoluble, highly branched polysaccharides of high molecular weight.

동아시아나 동남아시아의 인구밀도가 높은 것은 쌀 때문이다

일본에서 석石은 어른이 1년간 먹는 쌀량이다

[W] 석石::
섬(10말. 용량 단위)

[[_1_1_8_]]
==== 세계를 구한 작물

이 혹독한 시기를 지탱해준 작물이 바로 감자다

안데스 산맥의 티티카카 호수 부근에서 자라는 작물이었는데

4천미터 가까운 고지대가 원산지였기 때문에 감자는 한랭한 기후에서도 잘 자라고..., 여름이 없던 한랭한 시대를 견뎌내기 위해서 감자는 확실히 안성맞춤인 작물이었다

장기 지속한 한랭기를 감자로 넘길 수 있었던 것은 독일만이 아니었다. 안데스에서 온 이 볼품없는 작물이 없었다면 유럽 국가들은 붕괴되었을지도 모른다

[[_1_1_9_]]
==== 감자 기근

아메리카의 아일랜드계 이민의 많은 부분은 이 시기에 탈출할 사람들이다. 이민자들은 역경 속에서도 서서히 세력을 구축하여 최근에는 케네디, 레이건, 클린터 등의 대통령을 배출하였고, 현재의 오바마 대통령, 바이든 부통령도 아일랜드 혈통을 이어받았다는 점을 생각해보면, 대기근이 력사에 미친 영향이 지대한 것을 알 수 있다

아일랜드에서는 다른 작물이 자라지 않았다는 사정이 있었다고 하더라도, 모노컬처 monoculture (단일작물재배)가 실패하면, 결과는 비참하다. 식량, 에너지 등 생존이 불가결한 것에 대해서는 이중삼중의 수단을 갖추고 있어야 한다

[[_1_1_10_]]
==== 록말의 미래

.식량부족문제
* 급격한 세계 인구의 증가
* 개발도상국의 생활수준 향상
* 물부족으로 인한 식량 생산의 어려움

.물과 생산
* 찻잔 하나 분량의 쌀을 재배하려면 3백~4백 킬로그램의 물이 필요하다
* 100그램의 소고기 스테이크를 만들려면 2.5킬로그램의 골물과 2톤의 물이 필요하다
* 고기를 먹는 것은 수자원의 관점에서 보면 무서울 정도로 사치스런 행위다

지구는 *"`물의 행성`"*이다

.물
* 97퍼센트는 바닷물
* 2퍼센트는 남극과 그린랜드의 빙하
* 0.7퍼센터 이하만 경작에 리용 가능

중국 황하도 1970년 이후 때때로 물의 흐름이 끊겨서 물이 하류까지 흐르지 않는다

해수의 담수화::
Desalination +
전세계에서 하루 6,700만톤 담수 생산 (2011년 기준)

그러나 현재 지구에는 경작에 적당한 대규모의 미개발지는 남아 있지 않고, 이주할 수 있는 외부 세계도 더 이상 존재하지 않는다

[[_1_2_11_]]
=== 2. 인류가 빠진 “달콤한 함정”─설탕

[[_1_2_12_]]
==== 저항하기 힘든유혹

"`달콤한 생활`", "`달콤한 함정`" 등 "`달콤하다`"라는 말에는 어딘가 어두운 이면의 쾌락의 이미지가 따른다

.단맛::
당류 糖 엿 당, 엿 탕 +
saccharides

링게르::
포도당 + 아미노산 + 비타민

공복감::
혈중 포도당 농도 즉 혈당이 낮아지면 뇌는 생명유지에 위험이 림박했다고 판단하여 음식을 섭취하라는 신호를 보낸다 +
당류야말로 생명 유지의 기본 물질이라는 것을 이 현상으로 알 수 있다

세계의 어느 곳에 가져가도 반드시 팔리는 것이 설탕이다 +
이처럼 문화와 기호의 벽을 넘어서 모두가 갈구하는 상품은 매우 드물다

단맛 생산 식물::
사탕수수 +
사탕무: 19세기에 품종개량에 의해 등장

사탕수수::
한랭한 지역에서 재배 불능 +
토지 지력 급감하여 새로운 토지로 이동 +
사탕수수의 재배 및 설탕의 제조는 많은 인력을 필요로 하는 중노동이다

[[_1_2_13_]]
==== 사탕수수, 서쪽으로

사탕수수의 원산지는 확실하지 않고, 기원전 2천년경에 인도에서 설탕이 생산된 것 같다

설탕을 처음으로 접한 유럽인은 알렉산드로스 대왕의 동방원정 부대였다

설탕은 이슬람교와 함께 서쪽으로 확대되었다

탄소화합물을 순수하게 선별하여 사용한 가장 초기의 례라고 할 수 있다. 인류의 화합물 리용이라는 면에서 보아도 백설탕의 제조는 일대확기한 사건이었다

[[_1_2_14_]]
==== 설탕은 만병통치약

영양 상태가 좋지 않았던 그 시대에는 칼로리가 높은 설탕을 먹는 것 자체로 환자가 건강을 회복하는 사례가 많았을 것이다. 무엇보다 순수한 설탕의 희고 아름다운 빛, 그리고 미혹迷惑한 달콤한 맛은 신비했을 것이며, 플라시보효과 (placebo effect, 위약 僞藥)를 내기 위해서는 설탕 이상의 것은 없었을 것이다

[[_1_2_15_]]
==== 두 번의 계기

문제의 초점은 기독교의 단식일에 설탕을 먹는 것을 허용할 것인가에 맞추어졌다. 이 문제에 결단을 내린 인물은 중세 최고의 신학자 토마스 아퀴나스였는데, "`설탕은 소화를 돕는 약이므로 설탕을 입에 넣는다고 해도 단식을 그만두는 것은 아니다`"라고 했다

식품이 아니라는 판정이 식품으로서의 보급에 결정한 역할을 했다는 것은 아주 아이러니하다

설탕의 수요는 늘어났지만 사탕수수는 한랭한 지역에서는 재배되지 않고 지력을 금세 고갈시킨다. 콜럼버스에 의한 아메리카 대륙의 발견은 엄청난 소식이었다. 신대륙은 행운인지 불운인지 사탕수수의 재배에 적합한 환경이었다. 아메리카 대륙 발견으로부터 15년 후에는 본격으로 사탕수수 플랜테이션이 가동되기 시작했다

설탕과 카페인, 당시 이 2개의 쾌락물질의 조합은 부유층의 신분을 보여주는 상징물이 되었고 진정한 미각의 혁명이었다

삼각무역::
유럽에서 아프리카로 무기와 섬유제품이 갔고, 그 무기의 힘으로 포획한 노예를 아메리카로 보내서 생산한 설탕을 유럽으로 수출한다 +
사람, 물건, 돈이 전세계로 이동하는 시스템이 력사상 처음으로 출현했다 +
현재까지 계속되는 인종차별, 환경파괴, 남북문제 등은 설탕에 대한 욕망에서 비롯되었다고 해도 된다

영국은 오늘날에도 칼로리의 20퍼센트를 설탕에서 섭취한다

설탕으로 얻은 부::
산업혁명의 자원 +
세계지배의 원동력 +
런던의 테이트 갤러리 (헨리 테이트의 소장품)

[[_1_2_16_]]
==== 당뇨병의 시대

당뇨병의 발병 조건::
과식, 비만, 스트레스

혈액에 넘치는 당은 체내의 각종 단백질과 결합하여 인체 기능을 파괴한다

선진국의 최대위험은 비만이고, 후진국은 영양실조

설탕도 니코틴과 같이 과잉섭취를 억제하기 위해 세금을 무겁게 해야한다는 주장도 있다

모든 물질은 과잉섭취하면 독이 되는데, 특히 설탕이 그러하다

[[_1_2_17_]]
==== 진화하는 단맛

사카린 saccharin C~7~H~5~NO~3~S::
1879년 존즈 홒킨즈 대학의 콘스탄틴 팔버그 +
콜타르를 연구하다 우연히 맛보면서 발결하게 됨 +
감미는 설탕의 300배, 체내에 흡수되지 않음

기타 합성 감미료::
dulcin +
Zyclo +
1960년대에 사용 금지됨 +
식품첨가물 위험 인식의 계기가 됨

aspartame::
미국 Searle사가 개발 +
감미는 설탕의 200배, 칼로리는 지극히 저량 +
phenylalanine 함유라는 표시를 전제로 FDA에서 16년만에 승인을 받음

sucralose::
감미는 설탕의 600배 +
1976년에 처음으로 합성 +
테스트해보게가 맛보게로 오해되어 탄생

감미료::
혀의 단맛 수용체를 속여 결합하기 때문에 뇌는 단맛을 느낀다 +
하지만 위장은 당이 아니므로 흡수하지 않으니까 칼로리는 없다

제로칼로리음료::
수크랄로스, 아스파탐, acesulfame K 등을 리용

neotame::
감미는 설탕의 1만배 +
미국에서 개발되어 일본은 2007년에 식품첨가물로 승인

lugduname::
감미는 설탕의 22만배 +
프랑스 개발 +
5만분의 1그램이 각설탕 1개에 해당 +
아직 식품용으로 승인 안됨

[[_1_2_18_]]
==== 깊어가는 단맛의 불가사의

단맛을 느끼는 구조는 지금도 수수께끼다 +
화학식의 구조가 하나도 서로 닮지 않다 +
chloroform, nitroglycerin 등도 강한 단맛을 낸다

어떤 분자가 단맛을 느끼게 하는지, 아무리 구조식을 들여다보아도 짐작할 수 없다 +
당뇨병의 발병 메커니즘, 체내에서 당이 맡고 있는 역할 등에 대해서도 아직 해명되지 않다 +
당은 생화학에서 중요한 미개척 분야다

[big blue yellow-background underline]"`세계를 뒤흔드는 마성의 미각인 단맛은 도대체 무엇일까?`"

[[_1_3_19_]]
=== 3. 대항해 시대를 낳은 향기─방향족 화합물

[[_1_3_20_]]
==== 항신료는 보석

[[_1_3_21_]]
==== 파라오의 비밀

열대지역에서만 수확되는 작물을 북방의 사람들이 찾아나면서부터 세계는 뒤흔들려 력사가 움직이기 시작했다

향신료는 인류 최초의 국제상품이었다

우선 왕의 유체는 심장과 신장을 남겨두고 장기를 제거한다

[[_1_3_22_]]
==== 식물의 화학무기

향신료가 방부제로서 역할을 하는 것은 향신료가 식물이 만드는 화학무기이기 때문이다 +
외부의 적으로부터 도망칠 수 없는 식물들은 세균을 죽이고, 곤충이 접근하지 못하게 하는 성분을 만들어 자신을 지켜왔다 +
이것을 인간이 채취하여 활용하고 있는 것이다

벤젠고리 (benzene ring: 거북의 등껍질 모양, 육각형의 고리 모양) +
페놀 (phenol): 벤젠고리 + 산소원자 +
cresol: 소독약. 부분구조가 페놀과 비슷 +
향신료가 어느 정도의 살균력을 가진 리유가 되기도 한다

고기는 장기보관이 불가능하다 +
말리거나 염장하는 방법도 있지만 풍미를 크게 해친다 +
향신료는 고기의 맛을 살려줄 뿐만 아니라 보존성을 높여준다 +
다소 상한 고기의 맛과 냄새를 속이기 위해서도 향신료의 향은 유용했을 것이다

그들은 가열 전부터 후추를 뿌려서 고유의 향을 날려버리게 되는 조리를 했던 듯하다

귀족들의 위장에서 소비된 후추의 비용을 좀더 일찍부터 이민족 방비에 충당했더라면 로마 략탈이라는 쓰라린 패배를 당하지 않았을지도 모른다

고기를 맛있게 먹기 위해서 쓰이던 향신료가 고기 그 자체보다 훨씬 더 고가였던 것이다

중세때는 향신료는 악마를 물리치는 신비한 령약으로 비쳐졌음이 분명하다

[[_1_3_23_]]
==== 대항해 시대의 발소리

1496년 포르투갈의 바스쿠 다 가마가 아프리카 대륙을 돌아 인도에 도착했다 +
이로써 유렆 최서단의 작은 나라인 포르투갈은 세계를 제패하는 거대 제국으로의 길을 걷는다

[[_1_3_24_]]
==== 신대륙의 붉은 열매

1492년 콜럼부스는 포르투갈과는 반대로 서쪽으로 출항했다 +
2개월 후에 아메리카에 도착해서 새빨간 열매가 열린 식물을 보았다 +
그때까지 향신료의 녀왕이라고 하던 후추의 지위를 위협하게 되는 향신료인 고추의 발견이었다

고추::
유렆에서는 류행하지 못했다 +
아시아에서 열렬히 받아들였다 +
아시아의 료리라고 하면 우선 맵다는 이미지가 있다 +
16세기 이후 고추가 도입된 이후의 일이다 +
인도의 카레, 한국의 김치, 타이의 똠양꿍도 포르투갈인이 고추를 가져오기 전까지는 우리가 지금 알고 있는 맛이 아니었다

capsaicin::
체내에서 TRPV1이라고 불리는 수용체 단백질과 결합하여 스위치를 켠다 +
그러면 우리 몸은 아프지도 않고 온도도 상승하지 않았는데도 열을 느끼고 땀이 난다 +
고추의 매운맛은 미각이 아니라 통각痛覺과 온각溫覺이고, 영어로 hot이다

캪사이신으로 통증을 느끼면 뇌는 치유하기 위해 엔돌핀과 같은 뇌의 마약을 방출한다 +
매운 음식을 먹는 것은 괴로운 일인데도 식후에는 불가사의한 만족을 느끼는 것이다 +
마라톤에서 Runners' High와 닮았다

'`먹는 마조히즘`'이지만 이것을 받아들이는 방식에 아시아와 유렆이 차이를 크게 보이는 것은 흥미롭다 +
엄격한 수행 끝에 보살의 경지에 이르는 불교가 영향력을 가진 지역과 +
고추 문화를 받아들인 지역이 중첩되는 것은 과연 우연이었을까?

[[_1_3_25_]]
==== 목표는 몰루카 제도

몰루카(Moluccas, Maluku Islands)::
스페인의 마젤란이 1519년 스페인을 떠나 남아메리카 대륙 남단을 돌아 태평양을 건너 필리핀을 거쳐 몰루카 제도에 도착하고 1522년 스페인으로 귀국 +
력사상 최초의 세계일주 +
5척에서 1척만 남고, 270명의 선원은 18명만 남았다 +
17세기에는 영국도 이 섬을 노렸으나 +
네덜란드가 차지 하여 동인도 회사를 설립 하였고 력사상 최초의 주식회사가 되었으니 +
근대 자본주의 성립에 향신료는 한몫을 담당했다 +
현재 세계에 퍼져 있는 스페인어권과 포르투갈어권은 향신료와 금은 등의 보물 획득을 위해 세계를 돌아다닌 모험가들의 흔적이다 +

Manhattan::
1665년 영국에 이긴 네덜란드는 몰루카제도의 작은 섬인 란 섬을 얻었고 +
북아메리카의 한 구석인 허드슨 강의 하구에 있는 가늘고 긴 섬을 영국에 할양했는데 +
지금의 맨해튼 섬이다 +
네덜란드가 향신료에 집착하지 않았다면 뉴욕은 지금도 "`뉴암스텔담`"이었을 것이다


[[_1_3_26_]]
==== 항신료는 마약인가

일본 음식에는 된장 간장 등 발효조미료가 맛의 기본을 이루고 있었기 때문에 자극한 향신료가 들어올 여지가 적았다

일본은 냄새에 대한 관심이 낮은 민족인 듯하다

일본어::
におい[匂い] (좋은) 냄새; 향내; 향기.(=かおり)

영어::
* smell: 냄새 전반
* perfume: 향료의 방향芳香
* odor: 물체의 특이한 냄새
* stench: 악취
* stink: 악취
* scent: 향기
* fragrance: 화장품의 방향
* bouquet: 술 냄새 (특히 포도주의) 향미
* aroma: 커피, 카레 등의 냄새
* flavor: 맛과 냄새의 혼합

문자::
* 匂: 향내 내
* 臭: 냄새 취, 맡을 후
* 香: 향기 향
* 芳: 꽃다울 방
* 馥: 향기 복, 화살 꽂히는 소리 벽
* 郁: 성할 욱
* 薰: 향풀 훈
* 馨: 꽃다울 형
* 䭰: 향기 성할 봉
* 腥: 비릴 성
* 嗅覺: 후각

[[_1_3_27_]]
==== 끝나지 않은 항신료의 시대

18세기에 들어서 향신료에 대한 리권다툼은 한풀 꺾였다 +
농업혁명이 원인이었다 +
가축을 일 년 내내 키울 수 있게 되었다 +
순무 등 겨울에도 자라는 작물의 개발 +
지력을 고갈하지 않는 륜작법의 정착

19세기에 랭장기법이 개발되어 향신료에 대한 수요는 격감한다

오늘날 향신료는 단순히 미각을 즐겁게 해주기 위한 기호품이 되었다

향기를 디자인하는 일이 가능해졌다

"`액체의 보석`"이라고도 불리며 고급 브랜드의 주력 상품인 향수는 바로 이들 향기물질을 브랜드화한 것이다

캪사이신과 닮은 화합물을 리용하여 수용체受容體를 막아버리면 통증을 못느끼게 된다 +
의약 중에서도 진통제는 거대시장이다

[[_1_4_28_]]
=== 4. 세계를 이등분한 “감칠맛” 론쟁─글루탐산

[[_1_4_29_]]
==== 미각의홈그라운드

일본인에게 라면은 며칠 먹지 못하면 그리워하게 되는 미각의 홈그라운드와 같은 위치를 차지하고 있는 것 같다

sodium glutamate 글루타민산나트륨(~酸~)::
글루탐산 소듐 +
다시마와 가다랑어포 (가쓰오부시)의 국물 +
순수 추출물이 "`감칠맛 조미료`"다 +
글루탐산의 감칠맛은 약하고, 소듐이온과 결합해야 강한 맛이 난다

うまみ[うまみ·うま味·旨味·甘味] 감칠맛 savory taste::
서구의 향신료에 대한 열광을 일본인들이 리해하지 못하듯이 +
일본의 감칠맛에 대한 인기도 서구인들은 납득하지 못한다

[[_1_4_30_]]
==== 단백질 센서

생명유지에 자강 중요한 물질

DNA의 형태로 조상으로부터 물려받은 유전정보는 "`이러한 단백질을 만들어라`"라는 지령의 집합체다

단백질의 수명은 며칠이어서 +
동물은 생존에 꼭 필요한 단백질을 계속 섭취할 필요가 있다

세계를 가득 채운 생명들의 행위는 아미노산 재순환의 장대한 반복으로 지탱된다

단백질이 있는 곳에서는 반드시 그것이 분해되면서 생긴 글루탐산이 존재하고 +
이 "`단백질 표지`"를 섭취했을 때에 쾌락을 느끼도록 인간의 몸은 되어 있다

인간의 모유에 있는 아미노산에는 글루탐산이 절반이다 +
우리는 태어나자마자 감칠맛을 찾게 되어 있다 +
라면가게 앞에 줄선 사람들은 어머니의 젖을 찾는 것과 같은 심리의 지배를 밭는 것이다

[[_1_4_31_]]
==== 제호의 맛

rennet (rĕn′ĭt) 레닛(우유를 치즈로 만들 때 사용되는 응고 효소)::
An extract made from the inner lining of the fourth stomach of a calf or other young ruminant, used in cheesemaking to curdle milk.
* [C15: related to Old English gerinnan to curdle, run]

게다가 숙성 과정에서도 단백질이 계속 분해되면서 맛이 보다 깊어진다 +
소와 대지를 도축한 후에 바로 먹는 것보다는 어느 정도 지난 후에 조리하는 것이 더 맛있는 것과 마찬가지다

* 酥 [sū] 연유 소, 치즈. 유지(乳脂)식품.
* 酪 [lào] 쇠젖 락, 타락(駝酪: 우유 또는 양유를 끓여 만든 음료)
* 酪酥 [làosū] 소·양·말 등의 젖으로 만든 둥글넓적한 식품, 가지. [‘酪酥’의 맛이 가지와 비슷하다 하여 붙여진 이름임]
* 醍醐 [tíhú]: 醍 맑은 술 제, 醐 우락 더껑이 호, 우유(牛乳)에 갈분(葛粉)을 타서 미음(米飮)같이 쑨 죽(粥)

Glutamic acid 글루탐산::
글루탐산이라는 이름도 밀가루의 끈기 성분이 '`글루텐(gluten)`'에서 따왔다

gluten (glo͞ot′n)::
The mixture of proteins, including gliadins and glutelins, found in wheat grains, which are not soluble in water and which give wheat dough its elastic texture.
* [French, from Latin glūten, glue.]

[[_1_4_32_]]
==== 막부를 쓰러뜨린 다시마

[[_1_4_33_]]
==== 일본인의 체격을 향상시킨 남자

[[_1_4_34_]]
==== 고난의 길

[[_1_4_35_]]
==== 떤리함이라는 공포

[[_2_0_36_]]
== 제2부 인류의 정신을 움직인 물질들

[[_2_1_37_]]
=== 5. 세계를 사로잡은 합법한 약물─니코틴

[[_2_1_38_]]
==== 매력한 사기꾼

[[_2_1_39_]]
==== 인간, 담배를 만나다

[[_2_1_40_]]
==== 니코틴이란 무엇인가

[[_2_1_41_]]
==== 콜럼버스의 선물

[[_2_1_42_]]
==== 세계를 사로잡은 알칼로이드

[[_2_1_43_]]
==== 담배 탄압

[[_2_1_44_]]
==== 담배와 문화

[[_2_1_45_]]
==== 담배는 없어질까

[[_2_2_46_]]
=== 6. 력사를 흥분시킨 물질─카페인

[[_2_2_47_]]
==== 펀애를 받은 비밀

[[_2_2_48_]]
==== 차의기원

[[_2_2_49_]]
==== 카떼인의 약리

[[_2_2_50_]]
==== 카페인의 정신고양

[[_2_2_51_]]
==== 일본과 차

[[_2_2_52_]]
==== 서앙으로의 침투

[[_2_2_53_]]
==== 커피의 등장

[[_2_2_54_]]
==== 카페에서 시작된 혁명

[[_2_2_55_]]
==== 홍차와 영국 신사

[[_2_2_56_]]
==== 지배자는 가도 카페인은 남는다

[[_2_3_57_]]
=== 7. “천재 물질”은 존재하는가─뇨산

[[_2_3_58_]]
==== 통증의 결정

[[_2_3_59_]]
==== 사이안산으로부터 태어난 생명 분자

[[_2_3_60_]]
==== 백악기의 통풍 환자

[[_2_3_61_]]
==== 통풍으로 괴로워한 영웅들

[[_2_3_62_]]
==== 유전 요인과 성격 요인

[[_2_3_63_]]
==== 천재 물질성의 부상

[[_2_3_64_]]
==== 통풍과 뇌과학

[[_2_4_65_]]
=== 8. 인류 최고의 친구가 된 물질─에탄올

[[_2_4_66_]]
==== 바쿠스의 올가미

[[_2_4_67_]]
==== 인류,  솔과 만나다

[[_2_4_68_]]
==== 만취의 과학

[[_2_4_69_]]
==== 종교와 술

[[_2_4_70_]]
==== 증류주의 등장

[[_2_4_71_]]
==== 미국을 세운 술

[[_2_4_72_]]
==== 금주법의 시대

[[_2_4_73_]]
==== 에탄올 연료의 시대

[[_3_0_74_]]
== 제3부 세계를 움직이는 에너지

[[_3_1_75_]]
=== 9. 왕조를 날려버린 물질─니트로

[[_3_1_76_]]
==== 에너지를 장악한 동물

[[_3_1_77_]]
==== 폭발에 대한 충동

[[_3_1_78_]]
==== 화약의 등장

[[_3_1_79_]]
==== 화약의 화학

[[_3_1_80_]]
==== 진화하는 비행물체

[[_3_1_81_]]
==== 고도의 락성(落成)

[[_3_1_82_]]
==== 초석을 확보하라

[[_3_1_83_]]
==== 노벨이라는 남자

[[_3_1_84_]]
==== 총력전의 시대로

[[_3_2_85_]]
=== 10. 공기로부터 태어난 빵과 폭약─암모니아

[[_3_2_86_]]
==== 유일한 무기화합물

[[_3_2_87_]]
==== 100년 전의 원소 위기

[[_3_2_88_]]
==== 질소를 보급하라

[[_3_2_89_]]
==== 구아노의 섬

[[_3_2_90_]]
==== 초석의 시대

[[_3_2_91_]]
==== 크룩스의 예언

[[_3_2_92_]]
==== 하버의 등장

[[_3_2_93_]]
==== 초연의 시대

[[_3_2_94_]]
==== 하버의 유산은 지금은

[[_3_2_95_]]
==== 끝나지 않는 원소 위기

[[_3_3_96_]]
=== 11. 력사상 최강의 에너지─석유

[[_3_3_97_]]
==== 석탄과석유

[[_3_3_98_]]
==== 산업혁명을 떠받친 불

[[_3_3_99_]]
==== 공해 문제

[[_3_3_100_]]
==== 결정한 수단의 등장

[[_3_3_101_]]
==== 드레이크의 어리석은 행동

[[_3_3_102_]]
==== 석유제국의 출현

[[_3_3_103_]]
==== 석유란 무엇인가

[[_3_3_104_]]
==== 석유의 기원에 대한 수수께끼

[[_3_3_105_]]
==== 석유와의 전쟁

[[_3_3_106_]]
==== 화석연료는 어디로

[[_4_0_107_]]
== 결론

[[_4_1_108_]]
=== 탄소는어디로

[[_4_2_109_]]
=== 탄소의축구공

[[_4_3_110_]]
=== 탄소 나노튜브의 충격

[[_4_4_111_]]
=== 탄소 쟁탈전의 시대

[[_4_5_112_]]
=== 기후 변화의 숙명

[[_4_6_113_]]
=== 인공 광합성의 실현

[[_4_7_114_]]
=== 석유를 만드는 수초

[[_4_8_115_]]
=== 지속 가능한 지구를 향해서
