[[_0_]]
= 뼈운동
Joy <arbago@gmail.com>
v1.0, 2015-4-27
:icons: font
:sectanchors:
:toc: macro

toc::[]

[preface]
== 머릿말
Honekakumei Kintoreyorimo '`Honekokyu de Ashikoshiga Tsuyokunaru`', Wakagaeru
(C)Yoshio Yuzaki 2013

[quote, 제아미]
____
숨(息)은 뼈(骨)다
____

동물의 진화는 곧 뼈의 진화 - 미끼 시게오

바다에서 땅으로 올라온 상륙극은 생명 력사의 최대 드라마

상륙극::
* 폐호흡
* 중력 (땅은 물의 6배) -> 뼈의 발달

Andreas Vesalius::
벨기에의 해부학자
+
뼈를 비롯한 모든 신체 부위에 이름을 붙여서 구분함
+
현대 해부학의 창시자

뼈운동::
모든 뼈를 하나하나 분리한 후에 통합하는 방식을 씀

[[_0_0_0_]]
== PROLOGUE: "`근육 신화로`" 건강을 해치는 현대인

[[_0_1_1_]]
=== ‘메타보’에서 ‘로코모’로 점차 바뀌는 성인병

메타보::
Metabolic Syndrome +
단순 비만을 넘어 내장에 지방이 축적된 내장비만에 고혈압, 고혈당, 이상지질혈증 중 둘 이상이 추가된 대사증후근 +
내장지방증후군

로코모::
Locomotive Syndrome +
운동기능저하증후군 +
사지가 약해진 상태

[[_0_2_2_]]
=== 근육강화를 통한 운동 기능 개선의 오류

80년쯤 전의 역학 전성시대에 성립된 서양운동학, 즉 '`운동은 근육의 작용으로 이루어진다`'는 전제에 기초한 방식이기 때문이다

동양의 신체문화는 근육을 단순히 부분으로 강화하는 것보다 몸을 전체로 강화하는 데 중점을 둔다

근육은 중요하지만 인간은 다른 동물과 달리 '`직립보행`'이라는 곡예에 가까운 자세(구조)를 유지하기 때문에 몸을 직접 지탱하는 뼈가 특히 중요하다

근육신화::
근육을 붙이면 운동능력이 향상되고 심신이 건강하게 된다고 믿는 것은 진실과 다르다

무엇이든 지나치면 그나마 있던 장점까지 상쇄되고 만다 +
쓸데없이 근육을 붙이면 어떤 폐해가 있는지부터 우선 알아 두기 바란다

[[_0_3_3_]]
=== 근육맨 전사에 대한 알렉산더 대왕의 깨달음

[[_0_4_4_]]
=== 스모 선수의 부드럽고 유연한 근육

[quote, 와까노하나]
____
스모선수에게 필요한 랑창한 근육은 뎃뽀(鉄砲)훈련으로만 얻을 수 있다. 몸을 경직하게 하는 근육훈련은 좋지 않다

무뎃포(무데뽀)와 뎃포(데뽀)의 싸움::
‘무뎃포’란 단어는 일본어 ‘無鐵砲’에서 나왔다고 하는데 말 그대로 “총(철포)도 안 들고 총을 든 놈에게 덤비는 격”이란 뜻이라고 한다.
http://blog.naver.com/maximilian1/110188862574[김동욱 기자의 역사책 읽기^]
____

[W] 낭창-거리다::
가늘고 긴 막대기나 줄 따위가 탄력 있게 자꾸 흔들리다. [비슷한 말] 낭창대다.

* 수양버들이 낭창거리며 흔들리다
* 낚싯대를 잡아채자 낭창거리는 대를 통해 힘찬 붕어의 몸놀림이 전해져 왔다.

[[_0_5_5_]]
=== 50대 이후와 녀성의 과도한 근육 단련은 금물

체지방률이 한자릿수밖에 되지 않는 몸에 복근을 붙여 놓으면 치골이 피로골절을 일으키기 쉽다. 어쨌든 녀자는 복근을 붙이지 않는 것이 좋다

[[_0_6_6_]]
=== 근육이 호흡을 방해한다

근육운동은 때때로 숨을 참는 무호흡(무산소) 운동이 되어 버린다. 게다가 몸에 붙은 근육은 깊고 매끄러운 호흡을 방해한다.

[[_0_7_7_]]
=== 근육 때문에 실패한 메이저리그의 일본 선수들

라커룸쇼크::
라커룸에서 백인, 흑인, 중남미 카리브계의 선수들이 옷을 갈아입다 벌거벗은 채로 근육을 뽐내는 모습을 보면 일본인 선수는 그만 기가 죽는다는 것이다
+
그래서 그들을 따라잡으려고 근육단련을 하다 보면 관절, 특히 무릎에 큰 부담을 주게 된다
+
식생활 패턴이 전혀 다른 백인과 흑인의 근육은 일본인의 근육보다 훨씬 부드러워서 일본인처럼 근육 때문에 몸을 혹사하거나 부상당할 위험이 거의 없다

[[_0_8_8_]]
=== 식을 줄 모르는 머슬카(MUSCLE CAR)의 인기

머슬카 (Muscle Car)::
크지 않은 차체에 배기량은 7,000~8,000CC, 엔진출력은 400마력에 달한다. 시동을 걸고 4~5초 만에 시속 100km까지 올라가는 대단한 힘을 자랑하는 스포츠카로 '`머스탱 마하 원`'과 '`AC 코브라`' 등이 대표다
+
머슬카는 연비가 낮고 고장이 잦으며 승차감도 별로이고 운전하기도 불편하다

승용차는 150마력 정도가 가장 좋다

그만큼 미국 사회의 근육신화는 뿌리가 깊다

[[_0_9_9_]]
=== 사자와 치타는 근육 단련을 하지 않는다

인간세계에서도 근육단련은 선진국으로 불리는 곳에서 사는 사람들 뿐이다

근육을 단련하면 체력이 좋게 된다는 주장은 과연 진실일까? +
부분부분 근육을 억지로 강화하다 보면 인간의 몸에 과연 어떤 일이 일어날까?

근육단련::
수의근을 단련하는 것인데, 수의근이 늘어나면 뇌가 몸의 움직임을 더 많이 통제하게 된다. 즉 몸 전체에 대한 뇌의 지배가 더 강해진다 +
내가 다른 책에서 썼듯 '`현대는 뇌가 몸을 잊고 독주하는 시대`'임을 깨닫는다

생명을 지키려는 순간, 반사 행동은 뇌의 명령 없이 무의식으로 일어난다. 뇌의 통제를 받는 근육을 늘리는 일은 사실은 몸을 더욱 '`부자연스럽고`' '`부자유하게`' 만들 뿐이다

[[_0_10_10_]]
=== ‘근육 신화’에서 벗어나자

나는 철학이라는 학문을 공부했지만, 철학보다 오히려 인류학, 그리고 원숭이, 도둑고양이 같은 동물에게서 더 많이 배웠다

몸에 관해서는 동물과 공통되는 점이 많다. 게다가 몸은 인간보다 동물이 더 잘 활용하고 있으므로, 몸에 관련해서는 동물에게 배워야 한다

[quote, Walter B. Canon]
____
몸은 뼈의 지렛대 원리로 움직인다
____

근육이 지나치면 근육이 이 지렛대 원리를 무시하고 제멋대로 움직이려 하게 된다

근육이 주도하는 동작은 숨을 멈춘 채 이루어진다.

현대인에게 가장 필요한 것은 뼈의 지렛대원리를 최소한의 에너지로 지탱할 수 있는 에너지절약형근육이다

[[_1_0_11_]]
== 1.  뼈가 가장 중요한 리유

[[_1_1_12_]]
=== 뼈의 특성은 강인함

이렇게 모든 것이 소멸된 뒤에도 남는 뼈를 특별히 여겨 그 속에 령혼이 깃들어 있다고 믿는 민족과 종교가 많은 것도 당연하다

[[_1_2_13_]]
=== 우리 몸속의 식물성과 동물성 특질

'`건전한 정신은 건전한 몸에 깃든다`'는 말도 있는데, 사실 이 말은 원래 고대 로마 시인이 '`건전한 정신이 건전한 몸에 깃들게 하소서`'라고 기도한 것이 잘못 전해졌다고 한다

인간을 정신과 육체로 나누는 것과는 달리, 인간의 몸을 식물성신체와 동물성신체로 나누는 견해도 예전부터 존재했다

식물성신체::
동물과 식물에 공통으로 있는 기관 +
식도, 위, 대장, 소장 등의 소화관 (장관) +
내장계(內臟界)
+
식물의 뿌리는 사실 동물의 소화기관과 똑같은 기능을 한다 +
장갑을 뒤집으면 털이 돋은 부분이 밖으로 나오게 되는데, 이것은 수염뿌리가 부숭부숭한 식물의 뿌리를 련상하게 한다

동물성신체::
피부, 근육, 신경, 뇌 +
식물에는 없고 동물에는 있는 '`움직이기 위한 기관`' +
체벽계(體壁界)

[[_1_3_14_]]
=== 뼈는 내장계와 체벽계를 연결하는 ‘제3의 신체’

엄밀히 말해 뼈가 있는 동물이란 응뼈(척추)가 있는 동물만을 가리킨다 +
어류, 량서류, 파충류, 조류, 인간을 포함한 포유류 +
동물계 전체종류에서 5%

뼈는 식물성신체와 동물성신체의 련결기관을로 생각하는 것이 옳다

식물성기관인 장관은 수정된 세포의 내배엽에서 생겨나고 +
동물성기관인 피부와 신경은 외배엽에서 생겨나는데 +
뼈는 그 중간이 중배엽에서 생겨난다

뼈는 눈에 보이는 피부와 근육으로 덮인 채 다양한 동작을 취하는 동물성 신체도 아니고 +
매일 음식과 스트레스에 민감하게 반응하며 생명을 유지하는 소화관 같은 식물성신체도 아니다

##뼈는 몸 내부에서 쌍방을 지탱하는 '`제3의 신체`'다##

[[_1_4_15_]]
=== 뼈는 체액의 바다에 떠 있는 ‘산호’와 같은 존재

[quote, 하야시 야스후미, 뼈의 건강학]
____
뼈는 체액의 바다에 떠 있는 산호와 같다
____

[[_1_5_16_]]
=== 뼈의 중요한 2가지 역할

60조 개쯤 되는 전신의 세포에 칼슘을 공급한다

심장근육은 칼슘이 없이는 움직일 수 없다

[quote, 하야시 야스후미]
____
칼슘은 생명의 불꽃
____

[[_1_6_17_]]
=== 나이에 상관없이 뼈는 100% 재생된다

한번 부러져도, 적절한 위치에만 고정해 두면 뼈는 저절로 회복된다. 약물이나 광선 치료도 필요 없다. 게다가 부러진 자국도 전혀 남지 않는다.

뼈는 년령에 관계없이 완전히 재생된다 +
년령과 부위에 따라 회복속도에 차이가 있을 뿐이다

뼈 대사는 인간이 살아있는 한 지속되며, 조직이 새것으로 차례차례 교체된다는 점에서는 모발이나 손톱보다 오히려 피부나 위장과 류사한 특성을 지닌다

뼈를 별로 쓰지 않거나 뼈에 중력이 충분히 걸리지 않게 되면, 뼈 스스로 강해질 필요가 없다고 판단하여 파골세포(破骨細胞)를 활성화한다 +
뼈가 부러졌을 때처럼 새로운 뼈를 만드는 것이 아니라 뼈를 녹이는 방향으로 대사가 진행된다

병이나 부상으로 여러 날 누워 지내고 나면 제대로 서고 걷기가 어려워지는데, 이 역시 파골세포의 작용으로 뼈가 녹아서 약해졌기 때문이다

[[_1_7_18_]]
=== ‘물고기의 뼈’에서 ‘사람의 뼈’로 진화한 려정

[[_1_8_19_]]
=== 입덧은 태아의 인류 진화의 간접 체험

입덧(임신오조 姙娠惡阻)::
Hyperemesis gravidarum, Morning Sickness of Pregnancy

[W] Hyperemesis gravidarum (hī′pər-ĕm′ĭ-sĭs grăv′ĭ-dâr′əm)::
hyperemesis gravidarum - hyperemesis during pregnancy; if severe it can result in damage to the brain and liver and kidney
* <>hyperemesis - severe and excessive vomiting

[[_1_9_20_]]
=== 뼈를 잊고 근육에만 집착하는 현대인

筋骨, 氣骨, 强骨, 弱骨, 反骨, 骨格, 骨子

膂力 려력::
육체(肉體)의 힘, 등뼈의 힘, 몸의 근저에서 나오는 힘

* 膂 등골뼈 려 (등뼈와 근골)

[[_1_10_21_]]
=== 등뼈로 바이올린을켜라

[quote, Robert Lakatos, 벨기에의 바이올린 연주자]
등뼈를 느끼며 등뼈로 케세요

[[_1_11_22_]]
=== 뼈는 감각기관, 등뼈는 그 중추

멋진 음악을 만들어 내는 그들에게는 몇 가지 공통점이 있는데, 악보에 의존하지 않으며, 연주할 때는 몸을 좌우로 흔든다. 그리고 그 흔들림은 목만 좌우로 까딱까딱할 때와는 달리, 마치 등뼈에서 발산되는 것처럼 보인다

척추동물에게만 있는 등뼈는 그야말로 '`뼈 중의 뼈`'다. 섬세하게 움직이는 손가락도, 발의 발꿈치와 발톱까지도, 수많은 관절을 통해 등뼈에 련결되어 있다. 근육은 개별히 움직이지만, 뼈는 서로 련동하여 움직인다. 각 부위의 뼈는 마치 식물의 땅속뿌리처럼 보이지 않는 곳에서 모두 이어져 있다

우리의 등뼈는 에너지의 근원일 뿐 아니라, 뼈가 감각기관으로 기능하는 데에 중추역할을 한다 +
눈에 보이지않는, 귀에 들리지 않는, 코로 냄새 맡을 수 없는 무언가를 느끼려 할 때마다 뼈 중의 뼈인 등뼈가 진동하는 것을 보면 알 수 있다

시각이 정상이 일류 운동선수들도 결정의 순간에는 몸이 진동하는데, 특히 손끝, 턱(아래턱), 무릎 등의 뼈가 감각기관으로 가능하는 것으로 보인다

그들은 상대 서버나 공을 차기 직전의 공격수, 투구 동작에 들어간 투수의 움직임을 하나라도 놓칠세라 눈을 번뜩이는 동시에 시각을 넘어선 어떤 기운을 읽어 내기 위해 몸을 흔들고 있다. 몸의 이런 움직임은 검도나 레슬링 등의 격투기에서, 그리고 말 그대로 목숨을 건 동물의 싸움에서도 흔히 볼 수 있다

[[_1_12_23_]]
=== 직립하면서 등뼈가 몸의 중심축이 되다

[[_1_13_24_]]
=== ‘깊은 호흡’은 ‘뼈 호흡’

뼈중의 의 뼈인 등뼈까지 도달할 정도의 깊은 호흡, 그것이 '`뼈호흡`'이다. 등뼈를 의식하면서 호흡하는 습관이 몸에 배면 등뼈로 호흡하는 느낌을 알게 될 것이다. 그리고 기것이 바로 진정한 '`뼈호흡`'이다

[[_2_0_25_]]
== 2.  뼈운동 1단계 틀어진 몸을 바로잡고 약해진 뼈를 강하게

[[_2_2_27_]]
=== 근육보다는 뼈를 강화하는 일이 훨씬 간단하다

근육 붙이기::
계속 큰 부하를 걸지 않으면 근육은 금세 원래대로 돌아간다 +
즉 파괴와 복구를 반복해야만 근육질 몸을 유지할 수 있다

근섬유를 키우기 위해서 일시지만 조직을 파괴하는 것은 체벌이나 폭력과 다름없는 행위이고 심신의 평온함을 해친다고 할 수 있다 +
필요 이상으로 붙인 근육이 몸 뿐 아니라 정신도 딱딱하게 만든다

뼈를 강화하는 데는 근육처럼 부자연스러운 파괴의 과정이 없다 +
그저 자기 체중에 맞는 적당한 중력을 걸기만 하면 된다

발꿈치뼈::
뼈에는 중력을 감지하는 센서가 있는데, 특히 발꿈치뼈가 민감하다



[[_2_4_29_]]
=== Ⅰ. 손뼈에 자극을 주자

[[_2_4_30_]]
==== ① 양손 털기

[[_2_4_31_]]
==== ② 손가락 하나씩 비비기

[[_2_4_32_]]
==== ③ 손바닥으로 무릎 문지르고 두드리기

[[_2_4_33_]]
==== ④ 손바닥으로 팔꿈치 지탱하며 손 털기

[[_2_4_34_]]
==== ⑤ 팔꿈치 안쪽으로 갈비뼈 두드리기

[[_2_4_35_]]
==== ⑥ 팔을 늘어뜨린 채 손 털고 돌리기

[[_2_4_36_]]
==== ⑦ 손등과 손가락을 튕겨 올리듯 흔들기

[[_2_5_37_]]
=== Ⅱ. 발뼈에 자극을 주자

[[_2_5_38_]]
==== ① 발가락 풀기

[[_2_5_39_]]
==== ② 뒤꿈치 맞대고 발끝 세우기

[[_2_5_40_]]
==== ③ 발 태핑(다리 진동시키기)

[[_2_5_41_]]
==== ④ X자 다리 태핑

[[_2_5_42_]]
==== ⑤ 사지와 등뼈를 연결하는 ‘콩코드’ 자세

[[_2_6_43_]]
=== Ⅲ. 등뼈를 호흡시키자

[[_2_6_44_]]
==== A. 앉아서 하는 등뼈 호흡 운동

[[_2_6_45_]]
===== ① 양손 뻗어 깍지 끼기

[[_2_6_46_]]
===== ②두 손, 팔, 어깨로 직사각형 만들기

[[_2_6_47_]]
===== ③ 숨을 들이쉬면서 턱을 든다

[[_2_6_48_]]
===== ④갈비뼈 사이를 문지르고 두드리고 움켜쥐기

[[_2_6_49_]]
==== B. 서서 하는 등뼈 호흡 운동

[[_2_6_50_]]
===== ① 손발을 털고 금강합장하기

[[_2_6_51_]]
===== ②꼬리 튕기기

[[_2_6_52_]]
===== ③ 숨을 들이쉬며 하복부부터 손을 회전시켜 올라가기

[[_2_6_53_]]
===== ④손끝으로 가슴 훑으며 올라가기

[[_2_6_54_]]
===== ⑤ 숨을 내쉬면서 손 내리기

[[_2_7_55_]]
=== 2의 정리

[[_3_0_56_]]
== 3. 발뼈의 놀라운 저력

[[_3_1_57_]]
=== 의자에 오래 앉아 있으면 발이 굳어진다

[[_3_2_58_]]
=== 사람은 발로 사람이 되었다

[[_3_3_59_]]
=== ‘이상적인 발’에서 ‘허약한 발’로 쇠퇴한 일본인

[[_3_4_60_]]
=== ‘이상적인 발’의 환경

[[_3_5_61_]]
=== 쭈그려 앉는 자세가 사지를 강하게 만든다

[[_3_6_62_]]
=== 꿇어앉기는커녕, 의자도 올바르게 사용하지 못하는 현대인

[[_3_7_63_]]
=== 워킹화나 발가락 양말보다, 맨발로 지내라

[[_3_8_64_]]
=== 맨발로 지내며 발로 물건을 잡는 련습을 하라

[[_3_9_65_]]
=== 발호흡 운동은 최고의 건강법

[[_3_10_66_]]
=== 깊은 들숨이 건강에 좋다

[[_4_0_67_]]
== 4. 뼈운동 2단계

[[_4_1_68_]]
=== 근육의 긴장을 풀고 손, 발, 등뼈를 함께

[[_4_2_69_]]
=== 진동시켜 활력을 비약적으로 증진

[[_4_3_70_]]
=== 뼈는 두가지 측면에서 호흡과

[[_4_4_71_]]
=== 밀접한 관련이 있다

[[_4_5_72_]]
=== Ⅰ. 사지 만(卍)자 뼈운동

[[_4_5_73_]]
==== ① 손발 깍지

[[_4_5_74_]]
==== ② 손발을 서로 흔들기

[[_4_5_75_]]
==== ③ 등 울리기

[[_4_5_76_]]
==== ④ 사지 만(卍)자

[[_4_6_77_]]
=== Ⅱ. 꽈배기 뼈운동

[[_4_6_78_]]
==== ① 발 안쪽으로 반대쪽 발 발바닥 치기

[[_4_6_79_]]
==== ② 발등과 발등 부딪치기

[[_4_6_80_]]
==== ③ 발꿈치로 발가락 누르고 두드리기

[[_4_6_81_]]
==== ④ 꽈배기

[[_4_6_82_]]
==== ⑤ 꽈배기 플러스(응용편)

[[_4_7_83_]]
=== Ⅲ. 업다운 뼈호흡 운동

[[_4_7_84_]]
==== ① 발의 업다운

[[_4_7_85_]]
==== ② 업과 동시에 5단계 들이쉬기

[[_4_7_86_]]
==== ③ 업다운으로 조정하며 길게 내쉬기

[[_4_8_87_]]
=== Ⅳ. 날개 뼈호흡 운동

[[_4_8_88_]]
==== ① 손 털기

[[_4_8_89_]]
==== ② 갈비뼈 두드리기

[[_4_8_90_]]
==== ③ 양팔을 내려 손 털기

[[_4_8_91_]]
==== ④ 양팔을 들어 손 털기

[[_4_8_92_]]
==== ⑤ 양팔을 가슴에 두른 다음 잠시 정지

[[_4_9_93_]]
=== 5.  ‘뼈운동’으로 새롭게 젊음을 되찾다

[[_4_9_94_]]
==== 요통, 무릎 통증에 시달리던 삶에서 려행을 즐기며 사는 삶으로 (U. M. 씨 / 녀성 67세)

[[_4_9_95_]]
==== ● 요통에 시달리다, 2년 전부터는 무릎 통증까지

[[_4_9_96_]]
==== ● 발을 질질 끌며 걷던 무릎 통증이 나도 모르게 해소

[[_4_9_97_]]
==== ● 아직 건강할 때 몸을 잘 움직이게 만들어야 한다

[[_4_9_98_]]
==== 무술 단련으로 딱딱해졌던 몸이 낭창낭창한 몸으로 (H. D. 씨 / 남성 70세)

[[_4_9_99_]]
==== ● 온갖 무술훈련으로 덧붙여진 갑옷 같은 근육

[[_4_9_100_]]
==== ● 각각의 관절이 부드럽게 움직이자 불가능했던 동작이 가능

[[_4_9_101_]]
==== ● 마지막까지 간병인 없이 살고 싶다

[[_4_9_102_]]
==== 뼈를 새롭게 강화해 얻은, 날씬한 몸매와 건강- (T. M. 씨 / 녀성 49세)

[[_4_9_103_]]
==== ● 근육 통증이 아니라 뼈와 관절의 통증

[[_4_9_104_]]
==== ● 군살이 빠지고 가사 시간이 줄다

[[_4_9_105_]]
==== 뇌경색을 극복하다 (T. K. 씨 / 남성 62세)

[[_4_9_106_]]
==== ● 주말부부 시절 발생한 뇌경색

[[_4_9_107_]]
==== ● 반복되는 뼈운동으로 마비에서 점차 회복되다

[[_4_9_108_]]
==== 20대임에도 40대의 뼈 연령인 나: (T. H. 씨 / 녀성 29세)

[[_4_9_109_]]
==== ● 80대 할머니의 동작도 따라 하지 못하다

[[_4_9_110_]]
==== ● 다리와 허리가 가늘어졌다 걸음걸이가 예뻐졌다

[[_5_0_111_]]
== EPILOGUE

[[_5_1_112_]]
=== 86은 숫자일 뿐이다. 86세의 디나씨와의 대담

[[_5_2_113_]]
=== 5년 전에는 지팡이를 짚고 다녔지만, 86세인 지금 엘리베이터가 아닌 계단을 리용하다

[[_5_3_114_]]
=== ● 발이 퉁퉁 부어올라 코끼리 발이 되었던 시절

[[_5_4_115_]]
=== ● 지금은 최소 한 시간은 걸을 수 있고, 2~3층 정도는 계단으로 올라간다

[[_5_5_116_]]
=== ● 잘 걷게 되니 몸도 마음도 젊어졌다
