[[_0_]]
= 소금 오해를 풀면 건강이 보인다
Joy <arbago@gmail.com>
v1.0, 2015-05-27
:icons: font
:sectanchors:
:imagesdir: images
:homepage: http://arbago.com
:toc: macro

toc::[]

[preface]
== 책

소금 오해를 풀면 건강이 보인다, 윤태호, 2014

[preface]
== 머릿말: 소금에 대한 오해로 많은 사람이 건강을 잃고 있다

효능을 대체하지 못하는 요소들::
* 산소
* 물
* 소금

의학계에서는 근거없이 저염식을 강조하고, 심지어는 무염식을 주장한다

근거없는 주장이라도 의학계에서 말하면 대중에게로 쉽게 퍼져 나간다

아이러니하게도 그러한 잘못된 정보를 제공하는 사람 혹은 집단이 엄청난 리득을 보고 있다

소금에 대한 오해를 바로잡으면 국민 건강은 자연스럽게 증진될 것이다

[[_1_0_0_]]
== 1. 소금으로 건강을 회복하다

[[_1_1_1_]]
=== 끝도 없이 재발하는 병원치료

후에 알고 보니 '`통증클리닉`'의 치료는 +
질병의 원인을 그대로 두고 신경을 파괴하여 (신경파괴술, 신경응고술) +
뇌가 위험 신호를 느끼지 못하도록 만드는, +
구조면에서 인지 능력을 마비시키는 또 하나의 장애를 만든는 방법이었다

수술방법은 튀어나온 디스크를 잘라내고 목뼈에 쇠(티타늄) 조각을 박아서 목을 들어 올린다

결국 수술을 받지 않았고, +
단언컨대 그 결정은 정말 내 인생에서 가장 현명한 판단이었다

후에 통증에 대해 나름대로 분석해 본바, +
(목디스크와는 전혀 상관없이) 팔 부위의 세포가 산소를 공급해 달라고 호소하는 것이 '`통증`'이라는 사실을 았게 되었다

[[_1_2_2_]]
=== 본질 원인을 찾다

진통소염제와 항생제에 의해 병균도 죽지만 병균과 대항하는 백혈구까지도 죽어 +
그 사체가 대사 부산물과 함께 신장 혈관에 쌓여서 리뇨利尿를 방해했을 것이라는 추측을 하게 되었다

그때부터 '`물을 적게 마시면 각종 질병이 생기며, 물을 많이 마심으로써 많은 질병이 치료된다`'는 정보가 눈에 들어오기 시작했다

하지만 물을 먹으려고 하면 도로 넘어올 것 같았고 한 컾 마시는 것조차 너무 힘에 겨웠다 +
그 부드러운 물이 목에서 넘어가지 않다니

[[_1_3_3_]]
=== 물을 끌어당기는 소금

나는 비로소 그동안 물을 충분히 먹을 수 없었던 원인이 저염식 때문임을 알게 되었다

나는 '`짜게 먹으면 물을 많이 섭취할 수 있지만 고혈압에 걸리게 되고, +
싱겁게 먹으면 물을 못 먹어 피가 점점 탁해져 신장이 막힌다`'는 딜레마에 빠졌다

그렇다면 소금을 먹었을 때 통증이 사라진 리유는 무엇일까? +
그것은 바로 소금의 강력한 항산화 작용 때문이었다

소금을 충분히 섭취하자 소금의 환원 작용으로 활성산소의 발생이 억제되고 +
로폐물 老廢物이 몸 밖으로 배출된 것이다 +
따라서 막혔던 혈관이 열리고 세포에 산소공급이 원활해지므로 혈압도 정상화된 것이다

[[_2_0_3_]]
== 2. 소금의 오해

[[_2_1_4_]]
=== 론리가 없다

* 장병두: 약초를 리용하여 난치병 환자를 고침
* 최원철: 넥시아 (옻나무 추출물, 항암제, 경희대교수)
* 김남수: 뜸

그들이 의료법을 위반하여 활동을 제한받게 되었지만 +
결국 치료결과에 대한 메커니즘을 밝히지 못했기 때문이다

론리가 없으면 좋은 치료제를 발견하고도 끝없는 론란만 생긴다

옥수수수염에는 강력한 리뇨제인 칼륨이 다량 들어 있다 +
소금은 칼륨을 배출해 주는 물질로 +
칼륨을 섭취하면 소금이 칼륨을 배출하면서 물이 함께 빠져나가는 것이 리뇨의 원리이다 +
그 결과 체내에 나트륨의 량이 부족하게 되는데 +
나트륨과 같은 전해질이 부족하면 물을 보유하지 못해 +
심장에는 산소와 영양 공급량이 줄어 심장은 제 기능을 다 하지 못하게 된다 +
그래서 체내에는 칼륨과 나트륨의 비률이 일정하게 유지되어야 한다

나트륨을 제한하고 칼륨을 많이 섭취하면 +
저나트륨 증으로 심장의 수축력이 떨어져 +
부정맥이나 빠른 맥, 저혈압으로 위험하게 된다

이를 해결하려면 리뇨를 위해 +
칼륨을 더 섭취하되 +
그에 맞춰 나트륨도 섭취해야 한다

리뇨능력이 떨어진다고 해서 소금과 물을 지나치게 제한하면 +
물 부족으로 혈액은 탁해져 신장의 사구체는 점점 더 막힐 것이다

체내에 물이 충분해야 함에도 불구하고 +
리뇨만을 목적으로 칼륨 섭취를 강조하면 +
염분과 함께 수분이 빠져나가 탈수상태가 된다

[[_2_2_5_]]
=== 실험 오류와 맹종

아직 의학계에서는 고혈압의 원인을 모른다

과학정보는 믿음의 대상이 아니고 지식의 대상이다

1953년 미국 하버드대의 메네레가 고혈압의 원인을 찾던 중 소금이 고혈압의 주범이라는 실험 결과를 발표한다

소금은 고혈압의 원인이 아니라 오히려 치료하는 식품이다

[[_2_3_6_]]
=== 잘못된 정보를 맹신한다

소금을 먹으면 혈압이 높아진다는 주장의 본질은 +
소금을 섭취하면 물로 인해 혈압이 높아졌다는 것이다 +
이말은 "`고혈압 예방을 위해서라면 물을 적게 섭취하라`"고 주장하는 것과 다름없다 +
하지만 물은 생명의 근원일 뿐만 아니라, +
건강을 위해 물을 충분히 마시라는 의학계의 주장과도 모순된다

소금이나 물을 섭취해서 높아지는 혈압은 자연스러운 생리혈압이다 +
이 혈압은 인체의 자률기능으로 자연히 조절되기 때문에 생리혈압에는 대책이 필요하지 않다

소금을 더 섭취하면 그만큼 물을 더 섭취할 수 있고 또한 보유할 수 있다 +
고혈압이 위험한 경우는 물로 인한 생리혈압상승이 아니고 인체구조군제로 산소가 공급되지 않아서다

혁신은 언제나 작은 틈새에서 발생한다

[[_2_4_7_]]
=== 불순물을 소금으로 오해한다

[quote, 본초강목]
____
소금은 독이 없고 맛이 달다
____

문제는 오염된 불순물을 소금으로 본다는 것이다

그 리유는 소금이 불순물을 흡착하는 힘이 있기 때문인데, 소금이 유해하다고 오해를 받는 것은 바로 이 점에서 비롯된 것이다

중국산 소금은 류통과정에서 응결을 막기 위해 청산가리 성분을 넣는다는 사실이 밝혀졌는데, +
이 청산가리까지 소금으로 오해해서는 안 된다 +
소금에 붙어있는 간수, 중금속, 가스 등 불순물은 소금과는 반드시 구별되어야 한다 +
이 불순물은 소금이 아니라 단지 이물질일 뿐이다

소금은 인체에 절대필요적적량이 있어서 +
소금이 오염되었다면 깨끗한 소금을 섭취하라고 권장해야지 +
섭취량을 줄이라고 하는 것은 올바른 주장이 아니다

순수한 소금으로 실험해야 한다::
* 우리가 섭취하는 두부에 들어가는 간수의 량이 그리 많지 않기 때문에 인체에는 크게 문제가 되지 않을 뿐이다
* 간수 성분이 체내 단백질을 응고하여 뇌세포에 산소 공급을 막는다
* 젓갈류를 제조할 때는 조미료 등 화학 첨가제를 사용하는데, 그것은 활성산소를 발생하여 암을 유발할 수 있다

오락가락하는 의학계::
* 저염식을 하면 구토 및 어지럼증 등이 나타나며 위험할 수 있다
* 체내에 소금이 부족하면 물을 섭취하기 힘들고 산소와 영양을 제대로 전달할 수 없다

의학정보의 정당성::
* 론리
* 실험 결과
* 사례
* 검증 또 검증

[[_3_0_7_]]
== 3. 소금의 기능과 활용

[[_3_1_8_]]
=== 소금의 기능과 특징

체내에 소금이 부족하면 수분부족이 되고 체지방고 중금속이 쌓여 각종 질병에 걸린다

소금의 기능::

중금속 흡착::: 소금에 중금속과 무기질미네랄이 들어 있다는 것은 소금이 이러한 성분을 끌어당기는 성질이 있다는 것을 의미한다
* 소금으로 과일과 채소나 약초에 묻어있는 농약을 제거한다
* 잘못하여 농약을 먹었을 때에는 소금물을 먹어 토하게 하라
* 개가 쥐약을 먹고 쓰러져 거품을 물면서 죽을 것 같으면 소금물을 먹여 토하게 하면 살아나기도 한다
* 아질산나트륨: 햄·소시지 등의 가공식품에 첨가된 아질산을 흡착해서 배출

중금속 분해:::
* 소금으로 배추를 절여서 김치를 담그면 일주일 내에 잔류농약이 거의 없어진다
* 바다가 건강한 상태를 유지한다
* 태안 앞바다의 기름 류출도 불과 3~4년만에 깨끗히 정화되었다

간수(각종 미네랄) 흡착:::
* 간수의 주성분은 마그네슘이고, 칼슘·칼륨 등 다양한 미네랄이 들어 있다

환경홀몬 흡착::: 실내의 공기순환시스템에 리용

방사능 물질 흡착::: 세슘이나 요오드 등을 흡착

먼지 흡착::: 침대의 먼지나 진드기 등을 청소할 때 소금을 뿌린후 청소기를 돌린다

독 제거::: 독성을 소금물을 먹어서 해결

유해가스 흡착·제거::: 소금을 볶으면 유독가스가 빠져나온다
* 일산화탄소가 헤모글로빈과 결합하는 힘은 산소보다 210배나 커서 일산화탄소에 로출되면 산소부족현상을 겪는다. 몸속에 소금이 충분하면 소금이 일산화탄소를 흡착하여 헤모글로빈의 산소운반효률을 높인다
* 연탄가스 중독을 막기 위해 주변에 소금을 뿌린다
* 연탄가스 중독에 김칫국물 또는 동치미국물을 먹인다
* 소금을 바닥에 깔고 새우를 ㄱ워먹는다
* 바닷가에서 술을 마셔도 취하지 않는 것은 #대기중의 소금립자가 일산화탄소를 흡착하므로 충분한 산소가 공급되어# 인체의 에너지 대사효률을 높여준다

지방 흡착::: 체내의 지방을 땀이나 소변으로 함께 배설
* 수육 조시할 때 된장을 넣고 삶는다
* 고기를 숙성할 때 소금에 재우는 것은 지방을 빼는 것이다
* 오리고기에 소금을 뿌려 두었다가 료리한다
* 소금은 동물성 지방인 포화지방을 분해·흡착한다
* 비누나 화학세제에 소금을 넣어서 지방이나 불순물을 흡착한다

강력한 살균제::: 소금이 박테리아 균이나 각종 바이러스 등 유해균의 번식을 억제하기 때문이다
* 생선에 소금을 뿌려서 상하는 것을 막는다
* 감기에 걸리면 소금물로 가글을 하고
* 비염에 걸리면 콧속을 소금물로 씻는다
* 감기 초기에 소금을 빻아서 콧구멍 속에 넣으면 1~2분 후에 콧물이 줄줄 흘러내리고 감기증세가 호전된다
* 상처가 나면 소금물로 소독하면 세포가 빨리 재생한다
* 상한 음식을 먹고 배탈이 나고 안나고는 면역력과 체내 염분농도에 따라 결정된다
* 1882년 나폴레옹군의 러시아에서 퇴각한 원인은 병사들이 장기간 소금을 섭취하지 못해 질병과 세균의 감염을 이겨내지 못해서다

[[_3_2_9_]]
=== 소금의 인체 기능

[[_4_0_9_]]
== 4. 소금, 오해를 벗다

[[_4_1_10_]]
=== 암 오해를 벗다

[[_4_2_11_]]
=== 고혈압 오해를 벗다

[[_4_3_12_]]
=== 당뇨 오해를 벗다

[[_4_4_13_]]
=== 신장병 오해를 벗다

[[_4_5_14_]]
=== 소금은 최고의 장수식품이다

[[_5_0_14_]]
== 5. 소금의 기타 질병치료

[[_5_1_15_]]
=== 간염을 치료한다

[[_5_2_16_]]
=== 소금은 아토피의 특효약이다

[[_5_3_17_]]
=== 탈모를 해결

[[_5_4_18_]]
=== 변비를 해결한다

[[_5_5_19_]]
=== 요로결석을 해결한다

[[_5_6_20_]]
=== 다이어트 식품이다

[[_6_0_20_]]
== 6. 소금과 미네랄

[[_6_1_21_]]
=== 미네랄과 인체

[[_6_2_22_]]
=== 미네랄의 분류

[[_6_3_23_]]
=== 미네랄의 흡수 순서

[[_6_4_24_]]
=== 소금 속 미네랄의 특징

[[_6_5_25_]]
=== 소금 속 미네랄의 인체 영향

[[_6_6_26_]]
=== 소금 속 미네랄의 오해

[[_6_7_27_]]
=== 인체에 유용한 미네랄은 식물성 미네랄뿐이다

[[_6_8_28_]]
=== 미네랄 고갈 위험 주장은 과장이다

[[_7_0_28_]]
== 7. 소금의 선택과 섭취량

[[_7_1_29_]]
=== 소금의 가공방법과 특징

[[_7_2_30_]]
=== 용융소금의 특징 변화

[[_7_3_31_]]
=== 소금의 선택

[[_7_4_32_]]
=== 발효식품 속의 소금

[[_7_5_33_]]
=== 적정 소금 섭취량

[[_7_6_34_]]
=== 소금의 불순물 확인 방법

[[_8_0_34_]]
== 부록: 소금 활용법

[[_8_1_35_]]
=== 소금의 인체활용

[[_8_2_36_]]
=== 소금의 식품활용

[[_8_3_37_]]
=== 소금의 생활활용
