[[_0_]]
= 주역사전 역주
Joy <arbago@gmail.com>
v1.0, 2015-05-31
:icons: font
:sectanchors:
:imagesdir: images
:homepage: http://arbago.com
:toc: macro

toc::[]

[preface]
== 책

周易四箋, 丁若鏞, 1808년(순조 8)::
필사본. 24권 12책. 조선 후기의 학자 정약용(丁若鏞)이 주희(朱熹)의 『주역본의(周易本義)』에 근거, 주역사법(周易四法)을 추이(推移)·물상(物象)·호체(互體)·효변(爻變)으로 나누어 풀이하고, 괘사(卦辭)와 효사(爻辭)에 주석을 붙인 책

* 甲子本: 1804년 (순조 4) 《주역》을 주석하여 갑자본(甲子本)을 지었으며
* 乙丑本: 1805년 갑자본의 미흡한 점을 보완, 을축본(乙丑本)을 지었고
* 丙寅本: 1806년 병인본(丙寅本)을 펴냈다
* 丁卯本: 1807년 이학래(李學來)에게 병인본의 궐오(闕誤)를 바로잡게 하여 정묘본(丁卯本)을
* 戊辰本: 1808년 다시 정묘본의 정밀치 못한 사리(詞理)와 그릇된 상의(象義)를 바로잡아 무진본(戊辰本)을 완성하였다

주역사전 역주::
방인, 장정욱, 2007

[preface]
== 머릿말

[[_1_0_0_]]
== 第一卦 ☰☰ 乾 (1 乾上乾下 重天乾)

~乾下乾上~〇第一卦~復五陽進~

序卦傳曰有天地然後。 萬物生焉。

〇雜卦傳曰乾剛坤柔。

〇說卦傳曰乾健也。

〇程子曰乾天也。 健而無息之謂乾。

〇鏞案乾健者。 六書之諧聲也。 八卦消長之序。 亦如重卦。 陽起於震。 ~如復臨~ 壯於兌。 ~如大壯~ 究於乾。 ~如重乾~ 故說卦傳曰震其究爲健。 健者乾也。 以重卦則卦由復始。 ~一而六~ 爲臨爲泰。 以至於乾。 其行甚健。 ~震以行~ 故謂之乾也。 乾者氣也。 古篆氣作作又作作。 者之轉隷也。 ~古文氣早二字。 皆作。 ~ 乞者之轉隷也。 ~篆又作。 此以卦爲字也。 ~ 萬物之生。 皆受氣化。 故爲天爲父。 與坤爲配也。 又乾者燥也涸也。 坤陰旣燥。 兌澤今涸。 ~震兌而爲乾~ 所以爲乾也。 夏易首艮。 ~連山易~ 商易首坤。 ~歸藏易~ 以乾爲首者。 文王之易也。

[-]涸 마를 후, 마를 학::
* 涸轍鮒魚 학철부어: 수레바퀴 자국의 고인물에 있는 붕어라는 뜻으로, 몹시 곤궁(困窮)하거나 위급(危急)한 처지(處地)에 있는 사람을 비유(比喩ㆍ譬喩)해 이르는 말
* 燥涸: (땅의 수분(水分)이나 논밭ㆍ시내ㆍ연못 등(等)의 물이)마르거나 잦아지거나 함
* 乾涸: 내나 못의 물이 졸아 마름

[[_1_1_1_]]
=== 乾之彖 231

☰☰ 乾。  元亨利貞。

此乾之彖也。 蓍卦六畫。 皆得少陽者。 ~皆得七~ 乾而不變。 占之以彖也。

〇亨者通也。 感而遂通也。 离虛其心。 爲誠爲信。 ~見中孚~ 則至誠所格。 天心克享。 ~亨享古字通~ 時與命會。 ~嘉之會~ 運乃通焉。 此所謂嘉之會也。 其在乾卦。 雖無离形。 ~卦無斷~ 於离之位。 ~一二三~ 三陽自強。 此至誠無息也。 至誠無息。 則感而遂通。 必享天心。 故其占亨也。

〇貞者正也。 居正以幹事也。 ~貞正諧聲也~ 坎堅其心。 ~說卦文~ 爲敬爲直。 ~坤六二文言~ 則動罔不正。 事功以凝。 ~坎爲功~ 如幹築墻。 乃堅乃固。 ~事之固~ 此所謂勞乎坎也。 謂事爲貞者。 卜筮之義。 事必以正。 不正不筮也。 ~又詳屯九五~ 其在乾卦。 雖無坎形。 ~六陽純~ 於坎之位。 ~四五六~ 三剛堅固。 此勞勩~편001~ 不息也。 勞勩不息。 則事功必成。 故其占利貞也。

〇其謂之元亨者何也。 元者始也大也。 ~朱子云~ 坤之將乾也。 復一陽始生。 ~卽天편002根~ 此震德之元也。 ~善之長~ 元而遂亨。 其占元亨也。

〇其謂之利貞者何也。 利者和也宜也。 ~朱子云~ 復之爲乾也。 夬一陰未合。 ~夬五陽~ 此兌德之利也。 ~義之和~ 利於爲貞。 其占利貞也。


[-] 至誠所格: 지극한 정성이 하늘에 닿다

[-] 時與命會: 때와 천명이 적절하게 맞아들어

[-] 嘉之會也: 즐겁게 모이는 것이다

[-] 勩: 수고로울 예, 수고로울 이

[-] 勞勩 로예: 힘써 수고스럽게 노력努力함

文言曰元者善之長也。 ~震爲仁。 又爲長子。 ~ 亨者嘉之會也。 ~离爲禮。 又爲相見。 ~ 利者義之和也。 ~兌爲義。 又爲和悅。 ~ 貞者事之幹也。 ~坎爲勞。 又爲堅固。 ~ 君子體仁。 足以長人。 ~震德爲人主。 ~ 嘉會足以合禮。 ~离爲喜。 嘉者喜也。 ~ 利物足以和義。 ~利字象以刀刈禾。 和字象以口食禾。 皆兌秋之德。 ~ 貞固足以幹事。 ~*幹築墻木。 所以爲堅固。 *~ 君子行此四德者。 故曰乾元亨利貞。

[-]文言曰::
* 元者善之長也。  震爲仁。  又爲長子。
* 亨者嘉之會也。  离爲禮。  又爲相見。
* 利者義之和也。  兌爲義。  又爲和悅。
* 貞者事之幹也。  坎爲勞。  又爲堅固。

[-] 刈 벨 예: 苅(예)의 본자(本字). 㐅(오☞풀을 벰)와 刀(도)의 합자(合字)

[-]幹築墻木: 幹은 본래 담장을 쌓는데 쓰는 나무를 가리키는데, 담장을 보다 견고하게 쌓기 위해 사용한다

〇案#文言者。 古之字書。 若爾雅說文之類。 而專爲易詁者也。 ~若爾雅之有詩詁。 ~# 故孔子之生。 ~襄二十二年~ 十三年之前。 ~襄九年~ 穆姜預說文言之詞。 斯可驗也。 史記孔子世家及漢書儒林傳。 ~費直傳~ *竝別之於十翼。 * ~唯藝文志以文言序卦等爲十篇。 ~ 蓋孔子引用文言。 以爲易傳。 而後之儒者。 遂認爲孔子所作。 謬矣。 [bold underline]#君子行此四德者以下。 孔子文也。 #四方之卦。 ~卽震离兌坎~ 配於四時。 ~震爲春~ 配於四端。 ~震爲仁~ 故又以四德配於四卦也。 ~震爲元~ 元亨者。 猶言春而夏也。 ~始而亨~ 利貞者。 猶言秋以冬也。 又詳易例。

[*] 竝別之於十翼: 문언을 십익과 구별하여 병렬하였다

孔子曰乾元者。 始而亨者也。 ~萬物始乎震。 ~ 利貞者性情也。 ~行健。 故能成六陽。 ~ 乾始~復一陽~ 能以美利。 ~自臨至夬。 皆有兌。 ~ 利天下。 ~*五陽實於坤*~ 不言所利。 ~*夬之兌口亦合。 是不言也。 *~ 大矣哉。 ~陽曰大。 ~ 大哉乾乎。 剛健中正。 純粹精也。 ~六陽純~ 六爻發揮。 ~*_爻者。 變卦也。 _*發起也。 揮奮也。 ~ 旁通情也。 ~達乾之性情。 ~ 時乘六龍。 [underline]~陰在上曰乘。 ~ 以御天也。 ~五六爲天位。 ~ 雲行雨施。 ~六陰以震行。 ~ 天下平也。 ~天下坤也。 坤盡變爲陽。 ~

[-] 五陽實於坤: 다섯 개의 양이 곤(의 천하)에서 결실을 맺음

[-] 夬之兌口亦合。 是不言也。 : 건괘로 되면 쾌괘의 태의 입이 또한 다물어지니 이것이 불언이라고 한 리유

〇胡炳文曰夫子於文言。 旣分而四之。 於此又分而二之。 ~又曰乾性情。 只一健字。 ~

〇案始而亨者。 明元亨爲一句也。 性情也者。 明利貞爲一句也。 下三陽之至誠。 ~下位离~ 起於震元。 ~復一陽~ 始而亨也。 ~震而离~ 上三陽之堅固。 ~上位坎~ 合以兌利。 ~夬一陰~ 乃利貞也。 ~兌而坎~ 以利貞爲性情者。 六位旣終而後。 其剛健不息之德乃著也。 ~上卦爲利貞~ 丘氏以下卦爲元亨。 上卦爲利貞。 ~見大全~

[[_1_2_2_]]
=== 彖曰 239

彖曰大哉乾元。 萬物資始。 乃統天。 雲行雨施。 品物流形。 大明終始。 六位時成。 時乘六龍。 以御天。 乾道變化。 各正性命。 保合太和。 乃利貞。 首出庶物。 萬國咸寧。

彖者。 斷也。 ~六書之諧聲~ 本卦之斷詞也。 ~占所決~ 又彖者豕頭也。 ~見說文~ 彖詞在六[blue]*繇*之上。 如豕頭在六體之上也。 ~大傳云彖者。 材也。 ~ 彖詞本文王所作。 ~卽卦詞~ 此云彖曰者。 孔子釋彖之文也。

[-] 繇: 역사(役事) 요, 말미암을 유, 점사(占辭) 주, 점괘(占卦) 주

〇乾元者復也。 ~乾之始~ 說卦傳曰萬物出乎震。 ~復下震~ 復之一陽。 萬物之所資始也。 ~六陽始於復~ 一陽旣立。 六陽乃成。 故六陽之乾。 ~天~ *此一陽爲之綱紀。* ~如網之有綱~ 乃統天也。 大哉者。 天德也。 ~天字從大。 又至字從土。~

[-] 故六陽之乾 此一陽爲之綱紀: 그러므로 여섯 양으로 된 건괘는 이 한 개의 양을 벼리로 삼고 있는 것이니

〇陰不得陽。 不成雲雨。 ~陽氣下燭而後。 山川蒸濕。 上而爲雲雨。~ 坤之時。 有陰而已。 爲復爲臨。 以至於泰。 則陽乃交陰。 ~天地交~ 陰以震發。 ~三得震~ 此雲行而雨施也。 ~震爲行~ 流者。 陰之行也。 ~水行曰流~ 旣至於泰。 則震生蕃鮮。 ~震至三~ 坤陰流動。 ~震以動~ 此品物之流形也。 ~皆變其形質~ 乾者一氣也。 氣所施行。 莫顯乎雲雨。 而雲雨之發育萬物。 最在离夏之時。 ~一二三位离~ 故陽進至三。 ~卽离位~ 其德爲亨也。

[-] 陰以震發:

〇大明者日也。 ~卽太陽~ 冬至之時。 日躔極南。 日晷極短。 於是終而復始。 至於夏至。 則日躔極北。 日晷極長。 此大明終始也。 以此之故。 十二辟卦。 配於四時。 ~見括例~ 周而復始。 循環無端。 以此之故。 自復而泰。 爲壯爲夬。 以至於乾。 ~重卦成~ 此六位時成也。 ~時是同~

〇六龍者。 六震也。 ~說卦震爲龍~ 坤得一震以爲復。 ~復下震~ 復得一震以爲臨。 ~下互震~ 臨得一震以爲泰。 ~上互震~ 泰得一震以爲大壯。 ~上卦震~ 大壯得一震以爲夬。 ~雖少一陰仍是震~ 夬得一震以爲乾卦。 ~震以一陽爲卦主。 故雖無二陰。 仍是震。 ~ 此之謂六龍也。 ~荀九家云乾爲龍。 謬矣。 ~ 自復至夬。 陰每乘陽。 ~陰在上~ 此之謂時乘~난001~ 也。 ~龍陽物~ 至夬至乾。 遂達天位。 ~五六爲天位~ 時乘六龍。 以御天也。 ~御進也~

〇乾由坤變。 然推其本則坤由乾變。 ~自姤而剝而爲坤。 ~ 乾陽旣極。 爲姤爲剝爲復爲夬。 十辟以成。 ~自姤至夬爲十辟~ 此乾道變化。 各正性命也。 ~十辟如萬物~ 天道變遷。 以化萬物。 而萬物芸芸。 各受性命。 此其象也。

〇保者全也。 和者兌也。 ~兌爲悅~ 利物和義。 ~文言云~ 其德和也。 夬爲大兌。 ~全卦如兌形~ 是又太和也。 ~大壯亦大兌~ 陽進至夬。 ~至於五~ 合其兌和。 ~上坼者又合~ 以成乾卦。 ~夬而乾~ 此保合太和。 乃利貞也。 兌則爲秋。 ~夬上兌~ 坎則爲冬。 ~四五六位坎~ 卦體到此。 有如秋冬之成物。 故乃利貞也。 ~秋利而冬貞~

〇首出庶物者。 復一陽之始生也。 ~震長子~ 萬物出乎震。 ~說卦文~ 又帝出乎震。 ~說文卦편003~ 首出庶物。 豈非震主乎。 ~天地之長子~ 復之先坤也。 坤爲萬國。 ~虞氏云~ 國而無主。 其克寧乎。 ~坤無陽~ 一陽初出。 衆陰有主。 ~震爲主~ 於是羣賢竝進。 ~乾六陽~ 坤國大變。 此首出庶物。 萬國咸寧也。

〇或曰復至大壯。 固皆龍也。 ~皆得震~ 夬少一陰。 乾遂無陰。 尙可曰震龍乎。 曰復臨泰大壯。 皆於坤卦之上。 只加一陽。 便成震龍。 若其陰畫。 仍是坤卦之舊。 ~如所云地不改闢~ 非新造也。 以此言之。 自復臨而至夬乾。 皆以一陽爲震。 非有完缺之殊也。

[[_1_3_3_]]
=== 乾之姤 (01-1, 01)

初九。 潛龍勿用。

〇象曰潛龍勿用。 陽在下也。

〇潛龍勿用。 下也。

〇潛龍勿用。 陽氣潛藏。
此乾之姤也。 ~初爻變~ 蓍卦第一畫三掛之策。 皆得天數。 ~一三五七九~ 曰初九也。 ~參天故~

〇卦以震成。 ~復臨泰~ 本皆龍也。 ~震爲龍~ 變而爲巽。 ~下今巽~ 巽則爲隱。 ~大傳云巽稱而隱~ 爲伏爲入。 ~雜卦說卦文~ 是潛龍也。 入而不出。 ~出者震德也~ 不爲時用。 ~不以震行之~ 潛龍勿用也。 本在下位。 ~一二爲地位~ 所以爲潛也。

〇象者似也。 韓子曰象者南方大獸。 中國不識。 但見圖寫者。 故假借其義。 訓爲形似也。 ~見六書正譌~ 象詞本周公所作。 ~卽爻詞~ 此云象曰者。 孔子釋象之文也。

〇震之一陽。 是名爲龍。 ~義見前~ 龍者陽也。 位在地底。 ~一二地~ 陽在下也。 ~九者老陽也。 老陽亦陽。 ~

〇下者降也。 ~第二節~ 巽爲卑讓。 ~伏於陽~ 降於陽也。 ~下去聲~

〇乾則爲氣。 ~字從气~ 是陽氣也。 姤之旣潛。 ~下今巽~ 將以坤藏。 ~姤者坤之始。 ~ 陽氣潛藏也。 ~說卦云坤以藏之。 ~

〇案賈誼新書曰。 潛龍入而不能出。 故易曰勿用。 ~巽爲入~ 京房易傳云潛龍勿用。 厥異風行不解。 ~厥異爲風者。 以變巽也。 ~ 二家似知爻變。
孔子曰龍德而隱者也。 ~巽爲隱~ 不易乎世。 ~巽德高潔。 不爲世俗所變易。 ~ 不成乎名。 ~巽不果~ 遯世無悶。 ~大巽爲遯卦。 ~ 不見是而無悶。 ~巽撓屈。 故不見是。 ~ 樂則行之。 ~復臨至夬。 皆震行。 ~ 憂則違之。 ~與彼時相反。 ~ 確乎其不可拔。 ~巽爲入~ 潛龍也。

〇案巽德不壅。 ~下不塞~ 風以散之。 ~說卦文~ 故其象爲无悶也。 ~悶者。 心鬱也。 ~ 臨泰以往。 皆有兌悅。 ~至夬皆有兌~ 斯以震行。 ~六震乃爲乾~ 樂則行之也。 今旣爲姤憂則違之也。 ~道相反~

孔子曰君子以。 成德爲行。 ~六震之行以成乾。 ~ 曰可見之行也。 ~不入之謂行。 不隱之謂見也。 ~ 潛之爲言也。 隱而未見。 ~巽爲隱~ 行而未成。 ~巽進退~ 是以君子弗用也。

〇案雜卦傳曰兌見而巽伏。 ~見現也~ 卦相反也。 姤與夬反。 ~反易卦~ 隱而未見也。 ~夬上兌~ 巽與震反。 ~德相反~ 行而未成也。 ~震爲行。 巽爲不果。 ~ 君子之道。 欲現也欲行也。 隱而不行。 非其願也。 唯其時也。

[[_1_4_4_]]
=== 乾之同人 (01-2, 02)

九二。 見龍在田。 利見大人。

〇象曰見龍在田。 德施普也。

〇見龍在田。 時舍也。

〇見龍在田。 天下文明。
此乾之同人也。 ~二爻變~ 蓍卦第二畫三掛之策。 皆得天數。 曰九二也。

〇卦以震積。 ~復臨泰~ 二亦龍也。 ~震爲龍~ 變而爲离。 ~下今离~ 离以相見。 ~离爲目~ 是見龍也。 ~見音現~ 三才之位。 二爲地面。 ~鄭玄云初在地下。 二在地上。 ~ 地面曰田。 ~在地上~ 見龍在田也。 左傳云龍見于絳郊。 ~昭二十九年~ 見龍在田。 亦實事也。

〇乾則爲君。 ~說卦文~ 是大人也。 亦乾爲德。 ~乾直心~ 是君子也。 ~在下之聖人~ 相見乎离。 ~說卦文~ 嘉會以禮。 ~下今离~ 利見大人也。 ~利宜也~ 見龍在田者象也。 ~如詩之興體~ 利見大人者占也。

〇德者乾德也。 ~虞氏云~ 巽以施之。 ~二四互~ 离則爲寬。 ~虛中故~ 德施普也。 聖人見于世。 則雖未及擧而用之。 ~在下位~ 學問化導。 ~如孔子~ 其德施已普也。

〇五爲君位。 四三爲臣位。 ~九家易~ 而今玆聖人。 尙在二位。 ~民位也~ 如龍在田。 此時舍而不用也。 ~如舜耕歷山~

〇乾下爲离。 ~上今离~ 天下文明也。 ~离爲文爲明~
孔子曰龍德而正中者也。 ~离者四正之卦。 又二爲中。 ~ 庸言之信。 ~离爲信~ 庸行之謹。 ~离爲防~ 閑邪~离之兩剛爲防閑~ 存其誠。 ~离虛中爲誠~ 善世而不伐。 ~离爲治~ 德博而化。 ~离爲寬~ 易曰見龍在田。 利見大人。 君德也。 ~位卑而德尊~

〇案同人自夬來。 ~上之二~ 庸言者兌也。 ~夬上兌~ 庸行者震也。 ~夬五六亦震~ 移之同人。 乃信乃謹也。 ~下今离~ 又自姤來。 ~一之二~ 巽德撓曲。 ~巽爲屈~ 邪而不正。 ~卦形斜~ 移之同人。 則閑以防之也。 ~下今离~ 夬之旣移。 ~上之二~ 兌口亦嗑。 ~上兌合~ 是不伐也。 ~不自言~ 化者訛也。 ~堯典曰南訛~ 南方离火之德。 能令物化。 故易例离則爲化。
孔子曰君子學以聚之。 ~乾爲聚~ 問以辨之。 ~离爲辨~ 寬以居之。 ~离爲寬~ 仁以行之。 ~初與二爲震~ 易曰見龍在田。 利見大人。 君德也。

〇案同人自姤夬來。 巽則設敎。 ~見觀卦~ 可以學也。 ~姤下巽~ 兌則說言。 可以問也。 ~夬上兌~ 离今文明。 ~下今离~ 所以爲學問也。

[[_1_5_5_]]
=== 乾之履 (01-3, 03)

九三。 君子終日乾乾。 夕惕若。 厲無咎。

〇象曰終日乾乾。 反復道也。

〇終日乾乾。 行事也。

〇終日乾乾。 與時偕行。
此乾之履也。 ~三爻變~ 卦以震成。 六爻皆君子之用也。 ~震君子~ 於此特言君子者。 此詞爲進德修業之用。 非爲筮也。

〇下卦位离也。 ~一二三奇偶奇~ 离則爲日。 ~說卦文~ 故初爲日出。 ~見左傳~ 二爲日中。 ~見豐卦~ 三爲日夕。 ~見離卦~ 易例然也。 卦自復始。 ~義見前~ 遂以震行。 自強不息。 健而又健。 ~行又行~ 是乾乾也。 爲臨爲泰。 遂竟离位。 ~下卦終~ 終日乾乾也。

〇离位旣終。 日之夕矣。 ~离之末~ 离虛其心。 ~今互离~ 念其兌咎。 ~下今兌~ 若蹈虎尾。 ~履之象~ 如履薄氷。 ~見履卦~ 上畏乾天。 ~履上乾~ 順其巽命。 ~上互巽~ 夕惕若也。 履者踐履之卦也。 故其義如此。

〇厲者危也。 兌以一陰。 ~下今兌~ 下乘二剛。 ~初與二~ 位亦匪據。 ~陰居陽~ 其象危也。 然而无咎者。 履自夬來。 ~上之三~ 夬之時。 柔乘五剛。 ~夬上兌~ 驕之至也。 移之爲履。 ~卦今履~ 則全一卦而降之。 ~上兌今下兌。 ~ 上下以辨。 ~离爲辨~ 仰順巽命。 ~履互巽~ 是無咎也。 ~善補過~

〇乾之本坤也。 爲臨爲泰。 將以爲乾。 終而復始。 循環無端。 ~十二辟~ 反復道也。

〇乾以震行。 ~復臨泰~ 履乃踐禮。 ~中互离~ 是行事也。 ~震爲行~ 終日之所言行。 夕而思之。 不能無過。 ~兌震爲言行~ 玆所以惕若也。 此一繇乃古聖人嚴恭寅畏。 進德修業之要旨大法也。

〇十二辟卦。 與四時而偕行。 ~復臨泰。 周正爲春。 ~ 此卦象也。 四時嬗變。 流光迅速。 君子之進德修業。 豈有間哉。 孜孜不怠。 勉勉不已。 ~卽終日乾乾~ 一息不斷。 有進無退。 ~文王之純亦不已。 ~ 與流光而偕行。 死而後息焉。 此踐履也。 故曰終日乾乾。 與時偕行。

〇案班固之賦曰尸祿負乘。 夕惕若厲。 淮南子曰終日乾乾。 以陽動也。 夕惕若厲。 以陰息也。 張衡思玄賦曰夕惕若厲。 以省愆兮。 皆以夕惕若厲爲句。 漢儒之疏謬如此。 ~孔子曰雖危無咎。 故今以厲無咎爲句。 ~

〇學稼云兌則爲西。 离則爲日。 ~今互离~ 日在西則夕也。

孔子曰君子進德修業。 ~柔進而离修~ 忠信所以進德也。 ~离忠信~ 修辭立其誠。 ~兌言而离修~ 所以居業也。 ~离爲誠~ 知至至之。 ~柔自坎位來~ 可與幾也。 ~坎爲幾~ 知終終之。 ~下卦終~ 可與存義也。 ~兌爲義~ 是故居上位~下卦之上位~ 而不驕。 ~互巽爲遜順~ 在下位~全卦之下卦~ 而不憂。 ~兌悅而离喜~ 故乾乾。 因其時而惕。 雖危无咎矣。

〇案此繇以之爲筮則於出處進退祭祀婚姻戰伐之等。 皆無所當。 周公撰詞之初。 蓋恐學易者。 專主卜筮。 特於乾卦之內。 揷此一繇。 使學者知易之爲用。 不止於卜筮也。 故孔子解易。 多主義理。 ~彖傳大象傳~ 其源出於文王周公。 非自孔子始也。

孔子曰九三。 重剛而不中。 ~非二五~ 上不在天。 ~非五六~ 下不在田。 ~非一二~ 故乾乾。 因其時而惕。 雖危无咎矣。

〇案大傳曰三多凶四多懼。 以不得中也。 故乾卦三四。 皆言無咎。 孔子所言。 亦此義也。

[[_1_6_6_]]
=== 乾之小畜 (01-4, 04)

九四。 或躍在淵。 無咎。

〇象曰或躍在淵。 進無咎也。

〇或躍在淵。 自試也。

〇或躍在淵。 乾道乃革。
此乾之小畜也。 四爻變小畜自姤來。 ~一之四~ 姤之時。 巽股在下。 ~說卦巽爲股~ 移之小畜。 ~一之四~ 則巽股忽超。 ~下巽今上巽~ 幾及天位。 ~五六爲天位~ 其象躍也。 本皆震龍。 ~義見前~ 龍之躍也。 又自夬來。 ~上之四~ 上兌之澤。 ~夬上兌~ 移亦爲淵。 ~今互兌~ 躍在淵也。 ~淵止水~ 自姤來則爲進。 ~自下升~ 自夬來則爲退。 ~自上降~ 象不確定。 其位可疑。 ~如上亦如下~ 疑則或之。 ~占法也~ 或躍在淵也。

〇姤之時。 柔居陽位。 ~初數奇~ 進而小畜。 ~一之四~ 柔乃得位。 ~四數偶~ 進無咎也。 ~善補過~

〇試者。 將用而先嘗之也。 姤之時。 伏而在下。 ~姤下巽~ 移之小畜。 忽自超騰。 ~一之四~ 自試之道也。 ~將以飛~ 四則多懼。 ~大傳文~ 疑而試之也。

〇四者外卦之始也。 內乾旣竟。 外乾又始。 乾道乃革也。 ~天道變~ 乾之旣改。 ~四爻動~ 巽命又新。 ~上今巽~ 乾道乃革也。

〇案初爻四爻。 均之爲巽。 ~彼下巽~ 而彼爲潛龍者。 位在地底也。 ~三才位~ 此爲躍龍者。 位近天中也。 ~四近五~

〇學圃云巽則爲魚。 ~虞氏云~ 或躍在淵者魚也。 故蔡墨對龍。 ~昭二十九年~ 不言九四。

孔子曰上下無常。 ~躍乍上而下~ 非爲邪也。 ~巽爲屈~ 進退無恒。 ~說卦云巽爲進退~ 非離羣也。 ~乾羣而非離~ 君子進德修業。 ~离爲修~ 欲及時也。 ~畜其德以待時至~ 故无咎。

〇案小畜自姤夬來。 ~法見表~ 以姤則上進也。 ~一之四~ 以夬則下退也。 ~上之四~ 柔旣得位。 ~陰居四~ 雖巽非邪也。 ~得其正~ 乾羣猶完。 ~下乾全~ 雖离非離也。 進修及時。 以小畜也。 ~畜其德~

孔子曰九四。 重剛而不中。 ~非二五~ 上不在天。 ~非五六~ 下不在田。 ~非一二~ 中不在人。 ~四者卿相之位。 故三爲衆人之位。 ~ 故或之。 或之者疑之也。 故无咎。

〇案四則多懼。 所以疑也。

[[_1_7_7_]]
=== 乾之大有 (01-5, 05)

九五。 飛龍在天。 利見大人。

〇象曰飛龍在天。 大人造也。

〇飛龍在天。 上治也。

〇飛龍在天。 乃位乎天德。
此乾之大有也。 ~ 五爻變~ 卦以震成。 五亦龍也。 變而爲离。 ~ 上今离~ 离則爲飛。 ~ 荀九家~ 是飛龍也。 ~ 震爲龍~ 三才之位。 五六爲天。 ~ 見大傳~ 飛龍在天也。

〇上乾聖君也。 ~ 卽大人~ 下乾聖人也。 相見乎离。 ~ 上今离~ 正而有禮。 ~ 易例坎离皆爲正。 ~ 利見大人也。 ~ 利宜也~ 九二九五。 皆變爲离。 故其占皆利見也。

〇离則爲化。 ~ 書所云南訛~ 造者化也。 大人造者。 聖人之變化也。 又造猶作也。 ~ 大人造。 卽聖人作。 ~ 篆文化與作相近。

〇聖人南面而治。 蓋取諸离。 ~ 說卦文~ 故离則爲治。 ~ 上今离~ 此之謂上治也。 ~ 治道明於上~

〇二五皆离。 而彼爲見龍者。 尙位乎地面也。 ~ 二位地~ 此爲飛龍者。 乃位乎天德也。 ~ 五位天~

〇案离則爲雉。 ~ 說卦~ 文飛鳥之卦也。 離字從隹。 禽字從离。 荀九家之离爲飛。 其有徵矣。

〇又按伊尹就見殷湯。 師尙父遇見文王。 若於此時。 筮而遇是則其占吉也。 ~ 九二同~

孔子曰同聲相應。 同氣相求。 水流濕。 火就燥。 雲從龍。 風從虎。 ~ 兌爲虎~ 聖人作而萬物覩。 ~ 离爲見~ 本乎天者親上。 ~ 天與火~ 本乎地者親下。 ~ 水附地~ 則各從其類也。

〇案大有之卦。 姤夬其本也。 ~ 移之五~ 風雷相會。 ~ 姤巽而夬震~ 同聲相應也。 四正之卦。 火天其類也。 ~ 火天一類。 又水地一類。 ~ 火天相遇。 ~ 今大有~ 同氣相求也。 兌澤之水。 ~ 夬上兌~ 移之爲淵。 ~ 今互兌~ 水流濕也。 ~ 自上而流下~ 离火之焰。 ~ 姤之時。 一陰在离位。 ~ 上延乾燥。 ~ 乾純陽故燥。 ~ 火就燥也。 ~ 上今巽~ 巽之密雲。 ~ 姤下巽~ 上而從震。 ~ 夬五六爲震~ 雲從龍也。 ~ 小畜以巽爲密雲。 ~ 遂以巽風。 ~ 姤下巽~ 上而從兌。 ~ 夬上兌。 今互兌。 ~ 風從虎也。 ~ 兌爲虎~ 乾之聖君。 ~ 上本乾~ 化以离文。 ~ 上今离~ 聖人作也。 ~ 作化也~ 羣陽在下。 ~ 下亦乾~ 相見乎离。 ~ 說卦文~ 萬物覩也。 表記曰火土親而不尊。 ~ 卑近也~ 火天尊而不親。 此所謂本乎天者親上。 本乎地者親下也。 火天大有。 氣類相感也。 ~ 火天爲一類~ 飛龍在天。 利見大人。 亦氣類相感也。 世有聖君則聖人必與相見。 此各從其類也。

〇程子曰聖人旣得天位。 則利見在下大德之人。 ~ 程子於九二則通上下而言之。 ~ 朱子曰所利見者。 在上之大人。 ~ 朱子於此爻則通上下而言之。 ~ 王昭素之對宋太祖。 又欲互用於君臣之占。 ~ 見永樂大全~ 此疑案也。 然當以孔子之言決之。 孔子曰聖人作而萬物覩。 聖人者。 在上之聖君也。 ~ 卽飛龍~ 物覩者。 在下者之利見也。

〇又按近儒之說。 以風雷爲同聲。 山澤爲同氣。 坎离爲水火。 遂有乾龍坤虎之說。 其義非也。 八卦之德。 非此爻之所得專。 況以乾坤爲龍虎哉。 乾本非龍。 坤又何虎。 ~ 兌虎之義。 見履頤革卦。 ~

孔子曰夫大人者。 與天地合其德。 ~ 二五剛柔應~ 與日月合其明。 ~ 离在坎位。 爲日月。 ~ 與四時合其序。 ~ 乾元亨利貞~ 與鬼神合其吉凶。 ~ 五與六。 爲艮鬼。 ~ 先天而天不違。 ~ 下之乾。 先於上乾。 ~ 後天而奉天時。 ~ 上之乾。 後於下乾。 ~ 天且不違。 ~ 嘉會以合。 又二五應。 ~ 而況於人乎。 況於鬼神乎。

〇案大人者聖君也。 必有聖君而後。 爲聖人之所利見。 故形容其德之盛如此。

[[_1_8_8_]]
=== 乾之夬 (01-6, 06)

上九。 亢龍有悔。

〇象曰亢龍有悔。 盈不可久也。

〇亢龍有悔。 窮之災也。

〇亢龍有悔。 與時偕極。
此乾之夬也。 ~上爻變~ 卦以震成。 上亦龍也。 ~震爲龍~ 其位高極。 是亢龍也。 ~亢極也~ 變而爲兌。 ~上今兌~ 兌則爲決。 ~說卦文~ 盈之決也。 ~乾爲盈~ 人之修德。 悔則必改。 故卦爻之變。 亦名爲悔。 ~此易之大義~ 悔者變也。 ~何楷云~ 乾變爲夬。 亢龍有悔也。

〇盈者六陽皆滿也。 滿則必潰。 何可久也。 雜卦傳曰夬決也。

〇窮者極也。 憂患極者。 或反致福。 ~見震卦~ 名位極者。 必反致災。 ~盈不久~ 亢龍之悔。 ~上剛變~ 窮之災也。

〇時者四時也。 冬至一陽始生。 ~復一陽~ 至于夏至。 六陽已極。 ~日長極~ 乾之上剛。 與時偕極也。

〇案洪範曰貞曰悔。 悔者其變也。 貞者其不變也。 又改過曰悔。 不改過曰吝。

〇學稼云上一陽。 本震龍之無陰者。 ~義見前~ 陽道太亢。 是亢龍也。 ~如亢旱之亢~
孔子曰貴而無位。 ~六者陰位也。 乾之上剛。 以陽居陰。 ~ 高而無民。 ~坤爲民也。 乾至於六。 無一陰。 ~ 賢人在下位而無輔。 ~衆陽在下。 而皆不爲臣也。 坤爲臣。 ~ 是以動而有悔也。 ~動者爻變也。 ~

〇案亢龍驕傲自亢。 不少卑降。 故無民無臣也。
孔子曰亢之爲言也。 知進而不知退。 ~夬旣足矣。 又進一步。 ~ 知存而不知亡。 知得而不知喪。 ~兌爲失~ 其唯聖人乎。 知進退存亡而不失其正者。 其唯聖人乎。

〇案聖人謂下乾之聖人也。 乾變爲兌。 上失其正。 ~卦形斜~ 不失正者。 下卦也。

[[_1_9_9_]]
=== 乾之坤 291

用九。 見羣龍無首吉。

〇象曰用九。 天德不可爲首也。

〇乾元用九。 天下治也。

〇乾元用九。 乃見天則。

此乾之坤也。 ~蔡墨云~ 蓍卦十八變。 成卦之時。 ~三六爲十八~ 其十八卦之策。 皆得天數。 ~一三五七九~ 則六位盡變。 ~皆老陽~ 此之謂用九也。

〇乾本六震。 ~義見前~ 見羣龍也。 ~見音現~ 乾亦爲首。 ~說卦文~ 龍有首也。 變而爲坤。 ~六盡變~ 遂無乾剛。 ~無一陽~ 見羣龍無首也。 龍而無龍~편004~ 則神龍也。 ~張氏云神龍。 見尾而不見首。 ~ 故吉。

〇本是乾卦。 固天德也。 雖曰天德。 今旣無乾。 ~無一陽~ 不可以爲首也。 ~乾爲首~ 〇天下者坤也。 ~卦今坤~ 本以君德。 ~卦本乾~ 施以巽敎。 ~初之變爲姤~ 以漸濡潤。 ~六陽次第變爲陰。 ~ 丕化坤民。 ~卦今坤~ 化民曰治。 天下治也。

〇天道好變。 四時萬物。 莫不變易。 此易之所以主乎變也。 今六陽皆變。 ~變之極~ 天道天法。 於此乎可驗。 ~神變而無形~ 乃見天則也。

〇案春秋傳蔡墨對龍。 ~昭二十九年~ 以此爲乾之坤。 ~朱子曰六爻皆變者。 卽此占之。 ~ 則乾坤之有純變審矣。 然六爻純變則用之。 其或雜變者。 皆所不用。 ~詳見蓍卦箋~ 故謂其所用者曰用九也。

〇學稼云其或雜變者。 九六參錯。 不可指名。 ~曰九不可。 曰六亦不可。 ~ 故以法求變。 卒歸于九六。 ~非九則六~ 若六位皆變者。 九六之名得立。 故因而用之也。

[편~001]勩 : 勩音以勞也又音預[편~002]天 : 大[난~001] : 龍[편~003]文卦 : 卦文[편~004]龍 : 首

[[_2_0_9_]]
== 第二卦 ☷☷ 坤 (2 坤上坤下 重地坤)

~坤下坤上~ 〇第二卦~姤五陰進~

說卦傳曰坤。 順也。

〇朱子曰坤者。 順也。 陰之性也。

〇鏞案坤之本。 姤也。 ~一陰生~ 爲遯爲否。 以至於剝陰。 每在下終。 不敢乘陽跨陽。 順之至也。 此其所以名坤也。 四正之中。 在下者水土也。 而一撮之土。 投之水中。 亦必塌然而下沈。 蓋其性有所任載。 無所乘跨。 順之至也。 古文作巛~象三斷~ 亦作。 ~與申字不同~ 者。 卦形也。 川者順之義也。 順馴等字。 皆從川。 其實從巛也。 ~流字從巛則川本巛也。 ~ 故周行中土。 謂之巡。 ~字從巛~ 而音與馴同也。

[[_2_1_10_]]
=== 坤之彖 298

坤。 元亨。 ~句~ 利牝馬之貞。 君子有攸往。 先迷後得主。 ~句~ 利西南得朋。 東北喪朋。 安貞吉。
此坤之彖也。 蓍卦六畫。 皆得少陰者。 ~皆得八~ 坤而不變。 占之以彖也。

〇元者善之長也。 唯震爲善。 ~東方生物之仁~ 則唯震爲元也。 利者義之和也。 唯兌爲和。 則唯兌爲利也。 坤之六陰。 不由震兌。 ~不由復與夬~ 不可謂元利也。 雖然乾坤者。 敵對之物。 ~不相下~ 德雖相反。 理無不具。 彼以其震。 ~復一陽~ 我以吾巽。 姤一陰彼以其兌。 ~夬上兌~ 我以吾艮。 ~剝上艮~ 譬之於馬。 彼以䭸馬爲馬。 ~乾爲馬~ 我以牝馬爲馬也。 ~乾之配~ 坤以姤始。 ~一陰生~ 巽其元也。 ~姤下巽~ 剝而爲坤。 ~如乾之有夬~ 艮其利也。

〇元亨者。 君道之亨也。 ~元良元首。 古以君爲元。 ~ 乾則震主始出。 ~復一陽~ 爲臨爲泰。 以竟离位。 ~一二三~ 此震主之亨也。 ~元亨屬下卦~ 坤則巽妃始生。 ~姤者女后也~ 爲遯爲否。 以竟离位。 ~一二三~ 此巽妃之亨也。

〇貞者。 坎之德也。 坤之將坤也。 於坎之位。 ~四五六~ 爲觀爲剝。 ~利貞屬上卦~ 以成純陰。 凡陰功婦功。 皆所宜也。 故曰利牝馬之貞。 ~貞事也~ 牝馬之貞。 如孳育轉輸。 駕田車~納禾稼~ 給宮役~見禮注~ 之類是也。 若軍旅之事。 蒐獮之禮。 皆用牝馬。 筮而遇是則非所宜也。 ~利宜也~

〇君子者震也。 ~震爲仁爲主~ 坤國旣成。 ~六陰成~ 復之君子。 ~震一陽~ 可往爲主。 ~往則主坤國~ 有攸往也。

〇坤之先剝也。 剝則上艮。 ~山地剝~ 艮爲徑路。 ~說卦文~ 徑路多岐。 ~所以迷~ 是先迷以失道也。 ~復上九亦艮爲迷~ 後於坤者復也。 復則下震。 ~地雷復~ 震爲大道。 ~說卦文~ 又爲人主。 ~帝出震~ 是後順以得主也。

〇西南者坤也。 東北者艮也。 ~見說卦~ 坤之旣重。 ~上下坤~ 坤朋有耦。 ~易例坤爲朋~ 西南得朋也。 剝之坤朋。 ~坤之先剝也。 ~ 曾以艮死。 ~剝上艮~ 東北喪朋也。 ~萬物終乎艮~ 旣將得朋。 利西南也。

〇安貞者。 安靜之事也。 ~筮問事曰貞~ 坤之爲德。 安然不動。 ~安字象女在室中。 ~ 安貞吉也。 左傳畢萬之筮。 以坤爲安。 ~閔元年~ 義有據也。 洪範曰用靜吉。 卽所謂安貞吉也。 訟九四宜參看。

〇案程子曰四德同而貞體則異。 ~又曰利字不聯牝馬爲義。 如云利牝馬之貞。 則坤只有三德。 ~ 然當以朱子說爲正。 ~朱子曰不可將利字自作一句。 伊川只爲泥那四德。 所以如此說。 不通。 ~

〇又案蹇曰利西南。 ~彖詞文~ 解曰利西南。 ~亦彖詞~ 此卦亦當以利西南爲句。 ~吳幼淸亦云~

〇又按朋者耦也。 坤之三畫。 皆成匹耦。 故易例坤爲朋也。 ~兩貝謂之朋。 ~

〇學圃云周禮牧師。 孟春焚牧。 仲春通淫。 ~又校人六馬之屬。 有種焉。 ~ 此孳育之政也。

文言曰坤。 至柔而動也剛。 ~變則陽~ 至靜而德方。 ~土性不圓轉~ 後得主而有常。 ~後得震~ 含萬物而化光。 ~坤上藏~ 坤道其順乎。 ~巽爲順~ 承天而時行。 ~姤下巽承乾~

〇案此云文言者。 鄭康成之所加也。 ~或云王輔嗣所加。 ~ 孔子於乾坤二卦。 特於彖傳象傳之外。 重重贊美。 反復詠歎。 雖與諸卦之例不同。 其文則亦彖傳象傳也。 本是一通文字。 自東萊費直始裂傳文。 分隷各繇之下。 而鄭玄見章首有文言二字。 ~孔子引用古書名。 ~ 遂認爲別編。 乃於坤卦之傳。 亦增文言二字。 然乾之文言。 是孔子引用古文也。 此節是孔子所自作。 讀者詳之。

[[_2_2_11_]]
=== 彖曰 307

彖曰至哉坤元。 萬物資生。 乃順承天。 坤厚載物。 德合无疆。 含弘光大。 品物咸亨。 牝馬地類。 行地无疆。 柔順利貞。 君子攸行。 先迷失道。 後順得常。 西南得朋。 乃與類行。 東北喪朋。 乃終有慶。 安貞之吉。 應地无疆。

坤元者姤也。 姤之一陰。 生於地底。 三才位此坤土之本也。 ~元始也~ 衆萬之生。 根皆著土。 ~古文生作。 象出土。 ~ 萬物資生也。 六陰之生。 以巽爲根。 ~姤一陰~ 萬物資生也。 ~易例卦畫爲萬物。 ~ 姤以下巽。 ~天風姤~ 上接乾天。 爲遯爲否爲觀爲剝。 皆巽以順之。 ~皆有巽~ 艮以承之。 ~艮爲手~ 以成坤卦。 乃順承天也。 ~每陰在陽下~ 至者極也。 ~字從土~

〇自姤至剝。 上必載陽。 ~易例陰在上爲乘。 ~ 陽在上則爲載。 坤之本德。 利載物也。 坤爲大輿。 ~說卦文~ 非以是乎。 六陰旣積。 厚載物也。 ~載物故能厚。 ~ 疆者限也。 自姤至剝。 艮限在前。 ~艮爲限~ 坤之旣成。 遂無限界。 ~今無艮~ 德合无疆也。 ~六陰合~

〇陰進至否。 ~下三陰~ 坤道恢闊。 ~下坤成~ 艮以含蓄。 ~上三陽塞之~ 是含弘也。 ~畜其廣~ 照以天光。 ~左傳文~ 坤文乃著。 ~陰得陽有光~ 是光大也。 於离之位。 ~一二三~ 陰道會合。 ~三陰合~ 品物咸亨也。 ~三陰爲品物~ 亨者會也。 ~元亨屬下卦~

〇坤爲孳母。 ~說卦文~ 牝馬地類也。 ~坤之類~ 爲觀爲剝。 遂以爲坤。 行地无疆也。 程子曰乾以剛固爲貞。 坤以柔順爲貞。 卽所謂柔順利貞也。 ~利貞屬上卦~

〇坤之旣國。 震將爲主。 ~坤則復~ 君子攸行也。 ~震爲行~

〇失道者。 艮徑也。 ~剝上艮~ 得常者。 震道也。 ~復下震~

〇剝之反復也。 艮雖喪朋。 剝必爲復。 東北喪朋。 乃終有慶也。

〇凡求安之事。 貴在久安。 應地无疆。 能久安也。

[[_2_3_12_]]
=== 坤之復 (02-1, 07)

初六。 履霜堅氷至。

〇象曰履霜堅氷。 陰始凝也。 馴致其道。 至堅氷也。
此坤之復也。 ~初爻動~ 蓍卦第一畫至三掛之策。 皆得地數。 ~二四六八十~ 曰初六也。 ~兩地故~

〇初之旣動。 陰乃凝合。 ~初今剛~ 陰之始凝。 其象霜也。 ~霜而後霰。 而雪而爲氷。 ~ 遂以震足。 ~下今震~ 踐此凝陰。 是履霜也。 今卦復也。 再凝三凝。 ~爲臨泰~ 六陰盡合。 勢將爲乾。 ~勢莫遏~ 乾則爲氷。 ~說卦文~ 堅氷至也。 至者將然之辭。

〇凝者水堅也。 ~字從。 ~ 本以坤溫。 ~左傳坤爲溫~ 乾始爲寒。 ~震者乾之始~ 陰始凝也。

〇馴者習也。 ~習重也~ 自復至乾。 每得一震。 ~義見前~ 震則爲道。 ~說卦文~ 馴致其道也。 ~致者至之也~
孔子曰積善之家。 必有餘慶。 ~震爲善~ 積不善之家。 必有餘殃。 ~艮不善~ 臣弑其君。 子弑其父。 非一朝一夕之故。 ~一卦爲朝夕~ 其所由來者漸矣。 由辨之不早辨也。 ~辨分也~ 易曰履霜堅氷至。 蓋言順也。 ~朱子曰順當作愼。 或曰當作馴。 ~ 〇案乾以復始。 ~卽天根~ 震仁兌義。 積之至六。 ~自復至夬。 皆震兌。 ~ 積善之家也。 坤以姤始。 ~卽月窟~ 不仁不義。 積之至六。 ~自姤至剝。 德相反。 ~ 積不善之家也。 餘慶餘殃。 將然之效也。 陰之凝合。 小人之固結也。 ~坤而凝。 故爲小人。 ~ 旣凝旣固。 ~爲乾氷~ 乃散厥惡。 ~自乾而爲姤~ 則爲遯爲否。 臣弑其君。 ~旣否則下坤成而下乾先亡。 ~ 爲剝爲坤。 子弑其父。 ~艮男進而上乾亡。 ~ 陰凝之禍。 不其遠矣乎。 下卦爲离。 ~一二三~ 离則爲晝。 ~离爲日~ 上卦位坎。 ~四五六~ 坎則爲夜。 ~坎爲月~ 一朝一夕者。 一卦之謂也。 姤而爲復~편001。 積不善~ 坤而爲復。 ~陰始凝~ 復而爲乾。 ~堅氷至~ 乾反爲姤。 乃散厥惡。 ~臣弑君而子弑父。 ~ 非一朝一夕也。 辨者分也。 陰之始凝。 不早分之。 ~初今合~ 馴致其惡。 禍將滔天。 聖人之義。 貴早辨也。 小人之聚合凝固。 其漸雖微。 不可不辨。 此其戒也。 ~易例初爲早~

[[_2_4_13_]]
=== 坤之師 (02-2, 08)

六二。 直方。 ~句~大不習。 ~句~无不利。

〇象曰六二之動。 直以方也。 不習无不利。 地道光也。

此坤之師也。 ~二爻動~ 蓍卦第二畫三掛之策。 皆得地數。 曰六二也。

〇師自復來。 ~一之二~ 復者君子之所以修身也。 ~復初九曰以修身~ 移之爲師。 下乃爲坎。 ~下今坎~ 坎之爲卦。 一剛中橫。 其德直也。 外形方正。 ~外四片~ 直以方也。 蓋其爲卦。 得乾之中剛。 ~坎中男~ 乾則爲直。 ~見大傳~ 得坤之二陰。 ~外四片~ 坤則爲方。 ~見文言~ 其德直方也。

〇大不習者。 剛不重也。 ~習重也~ 旣非習坎。 ~只下坎~ 無不利也。 ~易例陽曰大~ 曷云哉。 坤者臣道也。 臣之爲道。 不失其敬。 ~爲人臣止於敬~ 以行其義。 ~不枉道以事君~ 外順內剛。 ~外坤而內坎~ 以正其身。 ~內爲我~ 苟其內外皆剛。 ~習坎象~ 失於柔順。 ~不外順~ 非爲人臣之道也。 今雖內剛。 旣不習坎。 ~上猶坤~ 無不利也。

〇動者爻變也。

〇地道者。 臣道也。 坤本純陰。 今乃剛中。 ~二今剛~ 地道光也。 ~陽爲光~ 師自復來。 震其道也。

〇案諸家皆以直方大爲句。 然霜方章囊。 ~又裳黃~ 本相叶韻。 當以直方爲句也。 象傳只擧直方二字。 大傳及深衣之文亦然。 直方爲句無疑也。

孔子曰直其正也。 ~坎中直~ 方其義也。 ~坎之外四片~ 君子敬以直內。 ~坎爲敬~ 義以方外。 ~外形端~ 敬義立而德不孤。 ~剛柔相表裏~ 直方~句~ 大不習~句~ 無不利。 則不疑其所行也。 ~雖坎不疑震爲行。 ~

〇案爲人臣者。 敬以直內~敬其君~ 則不失其身。 ~其身正~ 義以方外則不枉其道。 ~不枉己以循人~ 敬義內固而柔順外著。 ~外則坤~ 則其德不偏於剛果。 不偏於柔順。 所以爲不孤也。 以此道行。 可以爲臣。 ~坤爲臣~ 無復可疑。 ~內雖剛無害~ 大不習無不利者。 破疑之辭也。

〇禮記深衣篇曰負繩抱方者。 以直其政~편002。 ~ 方其義也。 故易曰坤六二之動。 直以方也。

[[_2_5_14_]]
=== 坤之謙 (02-3, 09)

六三。 含章可貞。 或從王事。 无成有終。

〇象曰含章可貞。 以時發也。 或從王事。 知光大也。

此坤之謙也。 ~三爻動~ 謙自復來。 一之三復之時。 震蕃鮮。 ~復下震~ 如樹方華。 ~震爲花~ 移之爲謙。 則艮以含之。 ~止其外~ 坤文內蘊。 ~說卦坤爲文~ 是含章也。 ~又离位~ 謙自剝來。 ~上之三~ 艮者果也。 ~剝上九碩果~ 震華旣蕃。 ~復下震~ 艮果成實。 ~說卦艮爲果~ 含章之象也。 ~艮果含生物之理~ 曷然哉。 坤變爲謙。 含章不發。 坤臣之執謙也。 姤九五宜參看。 ~豐六五亦然~

〇謙以坎貞。 ~全卦如坎形~ 可以幹也。 ~事之固~ 謙自復來。 始事于震。 ~復下震~ 艮以終之。 ~下今艮~ 是可貞也。 ~可幹事~ 不云利貞者。 以無成也。

〇謙自復來。 震其王也。 ~乾天之長子~ 坤其臣也。 ~地雷卦~ 移之爲坎。 ~謙互坎~ 則坤臣致役。 ~說卦文~ 坎以爲勞。 ~坎爲功~ 從王事也。 其位可疑。 ~在上下之中~ 疑則或之。 ~乾九四~ 或從王事也。 艮以止之。 ~下今艮~ 物所成終。 ~說卦文~ 然六位未竟。 ~艮在下~ 無所成也。 內卦已終。 ~終於三~ 有所終也。 臣道之無攸成。 如妻道之無攸遂。 ~見家人~ 此天地之大義也。 謙九三宜參看。 ~彼亦云有終~

〇艮以止之。 蘊其文章。 然其互爲震。 ~三五互~ 震將旉蕃。 ~敷花也~ 以時發也。 君子之德。 蘊以畜之。 待時而發。 譬彼草木。 斂其英華。 含其蓓蕾。 及其時而發之也。

〇坎則爲知。 ~北方之水德~ 陽光今大。 ~三今剛~ 知光大也。 ~坤德本光大~ 含而无成。 ~含其文~ 謹守臣道。 非大智乎。

〇學稼云章者樂之一終也。 ~說文云~ 震爲音樂之卦。 故震則爲章也。 ~字從音從十~

〇學圃云兌上坼故爲口。 艮上合故爲含。

孔子曰陰雖有美。 含之。 ~合其口~ 以從王事。 弗敢成也。 ~婦人無遂事~ 地道也。 ~坤爲地~ 妻道也。 ~坤爲母~ 臣道也。 ~坤爲臣~ 地道。 無成而代有終也。 ~代天工~ 〇案陰有美者。 坤得剛也。 坤得剛則爲復。 ~一陽生於坤~ 復而含則爲謙也。 ~一之三~

[[_2_6_15_]]
=== 坤之豫 (02-4, 10)

六四。 括囊。 無咎無譽。

〇象曰括囊無咎。 愼不害也。

此坤之豫也。 ~四爻動~ 括者。 結也閉也。 ~義見下~ 囊者震也。 坤則爲布。 ~說卦文~ 布塞其底。 ~震下連~ 其象囊也。 ~詩詁云有底曰囊。 ~ 無底曰橐。 豫自復來。 ~一之四~ 復之時。 大震之囊。 ~復大震~ 布于地面。 ~初位地~ 發其糗糧。 ~震爲稼~ 以活坤民。 ~震以生~ 移之爲豫。 ~一之四~ 則垂其艮手。 ~今互艮~ 闔然收結。 而震囊在上。 ~升于上~ 不顧坤民。 坤在後是括囊也。 豫自剝來。 ~上之四~ 剝有艮手。 所以括也。 括之奈何。 四多懼也。 ~大傳文~ 謹約如此。 何咎之有。 然我有其糧。 藏之不出。 亦無譽也。

〇剝之時。 迷失其道。 ~艮爲徑~ 今乃得道。 ~上今震~ 是無咎也。 ~善補過~

〇成言乎艮。 ~說卦文~ 非無言也。 坎則爲險。 ~上互坎~ 險言非譽。 是無譽也。

〇艮止有節。 ~下互艮~ 愼之至也。 雖有坎險。 ~上互坎~ 曷其能害。

〇案荀九家云坤爲囊。 非矣。 ~布不塞底。 不成囊。 ~ 星湖先生曰四之動爲震。 有囊象。

〇又按揚子方言曰括。 關閉也。 ~王風云羊牛下括。 亦牢柵牧閉也。 ~ 艮爲開門。 震爲閉關。 ~門下有橫木~ 故復之大象曰至日閉關。 ~復下震~ 括者閉也。 剝之艮門。 今以震閉。 ~上今震~ 其象括也。
孔子曰天地變化。 草木蕃。 天地閉。 賢人隱。 ~坎爲隱~ 易曰括囊無咎無譽。 蓋言謹也。

〇案豫自復剝來。 復者自坤爲乾之始。 ~天根也~ 卽天地變化之卦也。 復之時。 君子得道。 草木蕃鮮。 ~復下震~ 移之爲豫。 則天位地位之間。 ~四在二五間~ 一梗中橫。 ~四今剛~ 而剝之艮門。 今乃閉關。 ~義見前~ 天地閉也。 ~豫有重門象~ 震之君子。 ~復下震~ 坎用隱伏。 ~上互坎~ 賢人隱也。 曷然哉。 君臣之間。 ~五與二之間~ 小人居中。 ~下互艮~ 讒慝公行。 ~艮言坎險爲讒言~ 此遠害之時也。 可不愼乎。

[[_2_7_16_]]
=== 坤之比 (02-5, 11)

六五。 黃裳。 元吉。

〇象曰黃裳元吉。 文在中也。

此坤之比也。 ~五爻動~ 坤配乾衣。 其象裳也。 ~荀九家~ 裳本飾下。 ~左傳文~ 下卦裳也。 ~在下者爲裳~ 比自復來。 ~一之五~ 復之時。 震以飾下。 ~復下震~ 其色玄黃。 ~說卦震玄黃~ 是爲雜裳。 ~玄黃。 天地之雜也。 士冠禮有雜裳。 ~ 移之爲比。 則玄德上升。 ~一之五~ 遂正君位。 ~玄天色~ 坤裳順德。 ~坤在下~ 厥色純黃。 ~中土之正色~ 於是乎黃裳也。 本以震升。 ~復下震~ 元之吉也。 ~君爲元~ 坤之六五。 王后之位也。 周禮王后六服。 一曰鞠衣。 ~注云鞠黃色~ 而古者婦人之服。 衣裳相連。 ~見禮疏~ 黃裳者。 鞠衣也。

〇坤則爲文。 ~說卦文~ 今坤在內。 ~下爲內~ 文在中也。 ~易例內卦爲中。 如所云天在山中。 ~ 亦陽得五。 ~五今剛~ 文在中也。 ~兼二義~

〇案春秋傳南蒯之坤~편003~ 遇此爻。 ~昭十二年~ 子服惠伯曰黃。 中之色也。 裳。 下之飾也。 ~指下坤~ 元。 善之長也。 又曰上美爲元。 下美則裳。 ~詳見春秋官占注~ 惠伯亦以下坤爲裳。 中剛爲元。 讀者詳之。

〇離鼎解噬嗑宜參看。 ~黃之例~

孔子曰君子黃中通理。 ~坎爲通~ 正位居體。 ~陽居五~ 美在其中。 ~坎中陽~ 而暢於四支。 ~坎之外四片~ 發於事業。 ~坎幹事~ 美之至也。 ~易例陽爲美~

〇案比自復來。 君子者震也。 內純正則物理通。 ~內坤而外坎~ 正其位則體膚安。 ~外坎而內坤~ 黃中者坤也。 通理者坎也。 正位者坎也。 居體者坤也。 復之震足。 剝之艮手。 移之爲比。 則坎血流通。 美在其中。 而暢於四支也。 德之在中。 發於四體。 ~威儀之外著~ 亦猶是也。

[[_2_8_17_]]
=== 坤之剝 (02-6, 12)

上六。 龍戰于野。 其血玄黃。

〇象曰龍戰于野。 其道窮也。

此坤之剝也。 ~上爻動~ 剝以觀進。 ~四而五~ 觀有二陽。 ~上二剛~ 是二龍也。 ~乾之時。 本是六龍。 ~ 進而爲剝則一龍又死。 一龍獨存。 ~剝一剛~ 龍之戰也。 其戰奈何。 以本乾也。 ~說卦戰乎乾~ 坤邑之外。 其地曠遠。 ~上位最在外~ 邑外曰野。 ~邑而郊而野~ 龍戰于野也。

〇上卦位坎。 ~四五六~ 坎爲血卦。 ~說卦文~ 是其血也。 剝進爲坤。 ~四時之本序~ 坤變爲剝。 ~坤上六~ 陰陽屢變。 ~剝坤剝~ 天地相雜。 ~剝一陽本乾~ 其血玄黃也。 天~玄而地黃~

〇艮爲徑路。 ~說卦文~ 其道窮也。

〇案左傳龍鬪鄭門。 ~昭十九年~ 易詞取象。 皆合實理。

〇學圃云陰陽屢變。 倐忽往來。 支離攫拏。 困極而死。 其血玄黃也。 ~亟死則血赤~ 坎爲赤血。 ~說卦文~ 今坎非坎。 ~剝上艮~ 色有渝也。

孔子曰陰疑於陽。 必戰。 ~臣擬於君。 必有戰。 ~ 爲其嫌於無陽也。 ~坤純陰~ 故稱龍焉。 ~龍陽物~ 猶未離其類也。 ~觀二陽~ 故稱血焉。 ~坎爲血~ 夫玄黃者。 天地之雜也。 天玄而地黃。

〇案坤本純陰。 陰旣至六。 又得老陰。 ~老陰徒爻變~ 是無陽也。 觀之二陽。 本是同類。 血脈相通。 故血爲戒也。

[[_2_9_18_]]
=== 坤之乾 346

用六。 利永貞。

〇象曰用六永貞。 以大終也。

此坤之乾也。 著卦十八變成卦之時。 ~三變爲一畫~ 其十八掛之策。 皆得地數。 ~二四六八十~ 則六位盡變。 此之謂用六也。

〇永貞者。 久長之事也。 周禮大祝求永貞。 ~春官文~ 有年祝化祝之等。 ~其目多~ 年者歷年之短長。 ~如卜年八百~ 化者敎化之始終。 筮家以此謂之永貞也。 ~筮問事曰貞~ 坤體無疆。 乾德不息。 利於年也。 ~卜年吉~ 坤之爲乾也。 必自震始。 震主首出。 以臨坤民。 而坤之六陰。 盡化爲陽。 坤而乾利於化也。 ~利化民~ 久長之事。 無不相宜。 利永貞也。

〇終六位而皆剛。 以大終也。 ~陽曰大~

[편~001]復 : 坤[편~002]政 : 敬[편~003]坤 : 筮

[[_3_0_18_]]
== 第三卦之正 ☵☳ 屯 (3 坎上震下 水雷屯)

[[_3_1_19_]]
=== 屯之不變者 25

[[_3_2_20_]]
=== 彖曰 28

[[_3_3_21_]]
=== 屯之比 (03-1, 13) 33

[[_3_4_22_]]
=== 屯之節 (03-2, 14) 40

[[_3_5_23_]]
=== 屯之旣濟 (03-3, 15) 47

[[_3_6_24_]]
=== 屯之隨 (03-4, 16) 52

[[_3_7_25_]]
=== 屯之復 (03-5, 17) 54

[[_3_8_26_]]
=== 屯之益 (03-6, 18) 59

[[_4_0_26_]]
== 第三卦之反 ☶☵ 蒙 (4 艮上坎下 山水蒙)

[[_4_1_27_]]
=== 蒙之不變者 65

[[_4_2_28_]]
=== 彖曰 71

[[_4_3_29_]]
=== 蒙之損 (04-1, 19) 74

[[_4_4_30_]]
=== 蒙之剝 (04-2, 20) 78

[[_4_5_31_]]
=== 蒙之蠱 (04-3, 21) 81

[[_4_6_32_]]
=== 蒙之未濟 (04-4, 22) 85

[[_4_7_33_]]
=== 蒙之渙 (04-5, 23) 87

[[_4_8_34_]]
=== 蒙之師 (04-6, 24) 89

[[_5_0_34_]]
== 第四卦之正 ☵☰ 需 (5 坎上乾下 水天需)

[[_5_1_35_]]
=== 需之不變者 95

[[_5_2_36_]]
=== 彖曰 98

[[_5_3_37_]]
=== 需之井 (05-1, 25) 100

[[_5_4_38_]]
=== 需之旣濟 (05-2, 26) 103

[[_5_5_39_]]
=== 需之節 (05-3, 27) 107

[[_5_6_40_]]
=== 需之夬 (05-4, 28) 110

[[_5_7_41_]]
=== 需之泰 (05-5, 29) 112

[[_5_8_42_]]
=== 需之小畜 (05-6, 30) 114

[[_6_0_42_]]
== 第四卦之反 ☰☵ 訟 (6 乾上坎下 天水訟)

[[_6_1_43_]]
=== 此訟之不變者 122

[[_6_2_44_]]
=== 彖曰 125

[[_6_3_45_]]
=== 訟之履 (06-1, 31) 127

[[_6_4_46_]]
=== 訟之否 (06-2, 32) 130

[[_6_5_47_]]
=== 訟之姤 (06-3, 33) 135

[[_6_6_48_]]
=== 訟之渙 (06-4, 34) 138

[[_6_7_49_]]
=== 訟之未濟 (06-5, 35) 141

[[_6_8_50_]]
=== 訟之困 (06-6, 36) 143

[[_7_0_50_]]
== 第五卦之正 ☷☵ 師 (7 坤上坎下 地水師)

[[_7_1_51_]]
=== 師之不變者 153

[[_7_2_52_]]
=== 彖曰 156

[[_7_3_53_]]
=== 師之臨 (07-1, 37) 158

[[_7_4_54_]]
=== 師之坤 (07-2, 38) 162

[[_7_5_55_]]
=== 師之升 (07-3, 39) 166

[[_7_6_56_]]
=== 師之解 (07-4, 40) 169

[[_7_7_57_]]
=== 師之坎 (07-5, 41) 172

[[_7_8_58_]]
=== 師之蒙 (07-6, 42) 177

[[_8_0_58_]]
== 第五卦之反 ☵☷ 比 (8 坎上坤下 水地比)

[[_8_1_59_]]
=== 比之不變者 182

[[_8_2_60_]]
=== 彖曰 188

[[_8_3_61_]]
=== 比之屯 (08-1, 43) 190

[[_8_4_62_]]
=== 比之坎 (08-2, 44) 195

[[_8_5_63_]]
=== 比之蹇 (08-3, 45) 197

[[_8_6_64_]]
=== 比之萃 (08-4, 46) 198

[[_8_7_65_]]
=== 比之坤 (08-5, 47) 200

[[_8_8_66_]]
=== 比之觀 (08-6, 48) 208

[[_9_0_66_]]
== 第六卦之正 ☴☰ 小畜 (9 巽上乾下 風天小畜)

[[_9_1_67_]]
=== 小畜之不變者 214

[[_9_2_68_]]
=== 彖曰 216

[[_9_3_69_]]
=== 小畜之巽 (09-1, 49)  219

[[_9_4_70_]]
=== 小畜之家人 (09-2, 50) 222

[[_9_5_71_]]
=== 小畜之中孚 (09-3, 51) 224

[[_9_6_72_]]
=== 小畜之乾 (09-4, 52) 231

[[_9_7_73_]]
=== 小畜之大畜 (09-5, 53) 234

[[_9_8_74_]]
=== 小畜之需 (09-6, 54) 239

[[_10_0_74_]]
== 第六卦之反 ☰☱ 履 (10 乾上兌下 天澤履)

[[_10_1_75_]]
=== 履之不變者 248

[[_10_2_76_]]
=== 彖曰 252

[[_10_3_77_]]
=== 履之訟 (10-1, 55) 254

[[_10_4_78_]]
=== 履之無妄 (10-2, 56) 256

[[_10_5_79_]]
=== 履之乾 (10-3, 57) 259

[[_10_6_80_]]
=== 履之中孚 (10-4, 58) 262

[[_10_7_81_]]
=== 履之睽 (10-5, 59) 264

[[_10_8_82_]]
=== 履之兌 (10-6, 60) 267

[[_11_0_82_]]
== 第七卦之正 ☷☰ 泰 (11 坤上乾下 地天泰)

[[_11_1_83_]]
=== 泰之不變者 273

[[_11_2_84_]]
=== 彖曰 275

[[_11_3_85_]]
=== 泰之升 (11-1, 61) 278

[[_11_4_86_]]
=== 泰之明夷 (11-2, 62) 285

[[_11_5_87_]]
=== 泰之臨 (11-3, 63) 291

[[_11_6_88_]]
=== 泰之大壯 (11-4, 64) 297

[[_11_7_89_]]
=== 泰之需 (11-5, 65) 303

[[_11_8_90_]]
=== 泰之大畜 (11-6, 66) 311

[[_12_0_90_]]
== 第七卦之反 ☰☷ 否 (12 乾上坤下 天地否)

[[_12_1_91_]]
=== 否之不變者 319

[[_12_2_92_]]
=== 彖曰 321

[[_12_3_93_]]
=== 否之無妄 (12-1, 67) 322

[[_12_4_94_]]
=== 否之訟 (12-2, 68) 326

[[_12_5_95_]]
=== 否之遯 (12-3, 69) 329

[[_12_6_96_]]
=== 否之觀 (12-4, 70) 331

[[_12_7_97_]]
=== 否之晉 (12-5, 71) 334

[[_12_8_98_]]
=== 否之萃 (12-6, 72) 342

[[_13_0_98_]]
== 第八卦之正 ☰☲ 同人(13 乾上離下 天火同人)

[[_13_1_99_]]
=== 同人之不變者 347

[[_13_2_100_]]
=== 彖曰 351

[[_13_3_101_]]
=== 同人之遯 (13-1, 73) 353

[[_13_4_102_]]
=== 同人之乾 (13-2, 74) 355

[[_13_5_103_]]
=== 同人之无妄 (13-3, 75) 358

[[_13_6_104_]]
=== 同人之家人 (13-4, 76) 363

[[_13_7_105_]]
=== 同人之離 (13-5, 77) 366

[[_13_8_106_]]
=== 同人之革 (13-6, 78) 374

[[_14_0_106_]]
== 第八卦之反 ☲☰ 大有 (14 離上乾下 火天大有)

[[_14_1_107_]]
=== 大有之不變者 379

[[_14_2_108_]]
=== 彖曰 380

[[_14_3_109_]]
=== 大有之鼎 (14-1, 79) 382

[[_14_4_110_]]
=== 大有之離 (14-2, 80) 384

[[_14_5_111_]]
=== 大有之睽 (14-3, 81) 386

[[_14_6_112_]]
=== 大有之大畜 (14-4, 82) 391

[[_14_7_113_]]
=== 大有之乾 (14-5, 83) 393

[[_14_8_114_]]
=== 大有之大壯 (14-6, 84) 397

[[_15_0_114_]]
== 第九卦之正 ☷☶ 謙 (15 坤上坎下 地山謙)

[[_15_1_115_]]
=== 謙之不變者 24

[[_15_2_116_]]
=== 彖曰 25

[[_15_3_117_]]
=== 謙之明夷 (15-1, 85) 31

[[_15_4_118_]]
=== 謙之升 (15-2, 86) 33

[[_15_5_119_]]
=== 謙之坤 (15-3, 87) 35

[[_15_6_120_]]
=== 謙之小過 (15-4, 88) 39

[[_15_7_121_]]
=== 謙之蹇 (15-5, 89) 42

[[_15_8_122_]]
=== 謙之艮 (15-6, 90) 45

[[_16_0_122_]]
== 第九卦之反 ☳☷ 豫 (16 震上坤下 雷地豫)

[[_16_1_123_]]
=== 豫之不變者 53

[[_16_2_124_]]
=== 彖曰 55

[[_16_3_125_]]
=== 豫之震 (16-1, 91) 58

[[_16_4_126_]]
=== 豫之解 (16-2, 92) 60

[[_16_5_127_]]
=== 豫之小過 (16-3, 93) 68

[[_16_6_128_]]
=== 豫之坤 (16-4, 94) 71

[[_16_7_129_]]
=== 豫之萃 (16-5, 95) 77

[[_16_8_130_]]
=== 豫之晉 (16-6, 96) 80

[[_17_0_130_]]
== 第十卦之正 ☱☳ 隨 (17 兌上震下 澤雷隨)

[[_17_1_131_]]
=== 隨之不變者 87

[[_17_2_132_]]
=== 彖曰 89

[[_17_3_133_]]
=== 隨之萃 (17-1, 97) 91

[[_17_4_134_]]
=== 隨之兌 (17-2, 98) 94

[[_17_5_135_]]
=== 隨之革 (17-3, 99) 97

[[_17_6_136_]]
=== 隨之屯 (17-4, 100) 100

[[_17_7_137_]]
=== 隨之震 (17-5, 101) 104

[[_17_8_138_]]
=== 隨之无妄 (17-6, 102) 106

[[_18_0_138_]]
== 第十卦之反 ☶☴ 蠱 (18 艮上巽下 山風蠱)

[[_18_1_139_]]
=== 蠱之不變者 115

[[_18_2_140_]]
=== 彖曰 125

[[_18_3_141_]]
=== 蠱之大畜 (18-1, 103) 127

[[_18_4_142_]]
=== 蠱之艮 (18-2, 104) 134

[[_18_5_143_]]
=== 蠱之蒙 (18-3, 105) 136

[[_18_6_144_]]
=== 蠱之鼎 (18-4, 106) 139

[[_18_7_145_]]
=== 蠱之巽 (18-5, 107) 141

[[_18_8_146_]]
=== 蠱之升 (18-6, 108) 143

[[_19_0_146_]]
== 第十一卦之正 ☷☱ 臨 (19 坤上兌下 地澤臨)

[[_19_1_147_]]
=== 臨之不變者 150

[[_19_2_148_]]
=== 彖曰 153

[[_19_3_149_]]
=== 臨之師 (19-1, 109) 156

[[_19_4_150_]]
=== 臨之復 (19-2, 110) 158

[[_19_5_151_]]
=== 臨之泰 (19-3, 111) 160

[[_19_6_152_]]
=== 臨之歸妹 (19-4, 112) 162

[[_19_7_153_]]
=== 臨之節 (19-5, 113) 164

[[_19_8_154_]]
=== 臨之損 (19-6, 114) 167

[[_20_0_154_]]
== 第十一卦之反 ☴☷ 觀 (20 巽上坤下 風地觀)

[[_20_1_155_]]
=== 觀之不變者 172

[[_20_2_156_]]
=== 彖曰 178

[[_20_3_157_]]
=== 觀之益 (20-1, 115) 182

[[_20_4_158_]]
=== 觀之渙 (20-2, 116) 185

[[_20_5_159_]]
=== 觀之漸 (20-3, 117) 189

[[_20_6_160_]]
=== 觀之否 (20-4, 118) 191

[[_20_7_161_]]
=== 觀之剝 (20-5, 119) 197

[[_20_8_162_]]
=== 觀之比 (20-6, 120) 199

[[_21_0_162_]]
== 第十二卦之正 ☲☳ 噬嗑 (21 離上震下 火雷噬嗑)

[[_21_1_163_]]
=== 噬嗑之不變者 206

[[_21_2_164_]]
=== 彖曰 207

[[_21_3_165_]]
=== 噬嗑之晉 (21-1, 121) 211

[[_21_4_166_]]
=== 噬嗑之睽 (21-2, 122) 216

[[_21_5_167_]]
=== 噬嗑之离 (21-3, 123) 220

[[_21_6_168_]]
=== 噬嗑之頤 (21-4, 124) 222

[[_21_7_169_]]
=== 噬嗑之無妄 (21-5, 125) 227

[[_21_8_170_]]
=== 噬嗑之震 (21-6, 126) 232

[[_22_0_170_]]
== 第十二卦之反 ☶☲ 賁(22 艮上離下 山火賁)

[[_22_1_171_]]
=== 賁之不變者 241

[[_22_2_172_]]
=== 彖曰 242

[[_22_3_173_]]
=== 賁之艮 (22-1, 127) 245

[[_22_4_174_]]
=== 賁之大畜 (22-2, 128) 248

[[_22_5_175_]]
=== 賁之頤 (22-3, 129) 250

[[_22_6_176_]]
=== 賁之離 (22-4, 130) 254

[[_22_7_177_]]
=== 賁之家人 (22-5, 131) 259

[[_22_8_178_]]
=== 賁之明夷 (22-6, 132) 265

[[_23_0_178_]]
== 第十三卦之正 ☶☷ 剝 (23 艮上坤下 山地剝)

[[_23_1_179_]]
=== 剝之不變者 272

[[_23_2_180_]]
=== 彖曰 272

[[_23_3_181_]]
=== 剝之頤 (23-1, 133) 274

[[_23_4_182_]]
=== 剝之蒙 (23-2, 134) 281

[[_23_5_183_]]
=== 剝之艮 (23-3, 135) 285

[[_23_6_184_]]
=== 剝之晉 (23-4, 136) 287

[[_23_7_185_]]
=== 剝之觀 (23-5, 137) 289

[[_23_8_186_]]
=== 剝之坤 (23-6, 138) 294

[[_24_0_186_]]
== 第十三卦之反 ☷☳ 復 (24 坤上震下 地雷復)

[[_24_1_187_]]
=== 復之不變者 300

[[_24_2_188_]]
=== 彖曰 305

[[_24_3_189_]]
=== 復之坤 (24-1, 139) 306

[[_24_4_190_]]
=== 復之臨 (24-2, 140) 310

[[_24_5_191_]]
=== 復之明夷 (24-3, 141) 312

[[_24_6_192_]]
=== 復之震 (24-4, 142) 315

[[_24_7_193_]]
=== 復之屯 (24-5, 143) 316

[[_24_8_194_]]
=== 復之頤 (24-6, 144) 319

[[_25_0_194_]]
== 第十四卦之正 ☰☳ 无妄 (25 乾上震下 天雷无妄)

[[_25_1_195_]]
=== 無妄之不變者 327

[[_25_2_196_]]
=== 彖曰 330

[[_25_3_197_]]
=== 無妄之否 (25-1, 145) 333

[[_25_4_198_]]
=== 無妄之履 (25-2, 146) 334

[[_25_5_199_]]
=== 無妄之同人 (25-3, 147) 339

[[_25_6_200_]]
=== 無妄之益 (25-4, 148) 342

[[_25_7_201_]]
=== 無妄之噬嗑 (25-5, 149) 344

[[_25_8_202_]]
=== 無妄之隨 (25-6, 150) 347

[[_26_0_202_]]
== 第十四卦之反 ☶☰ 大畜 (26 艮上乾下 山天大畜)

[[_26_1_203_]]
=== 大畜之不變者 351

[[_26_2_204_]]
=== 彖曰 354

[[_26_3_205_]]
=== 大畜之蠱 (26-1, 151) 358

[[_26_4_206_]]
=== 大畜之賁 (26-2, 152) 360

[[_26_5_207_]]
=== 大畜之損 (26-3, 153) 363

[[_26_6_208_]]
=== 大畜之大有 (26-4, 154) 370

[[_26_7_209_]]
=== 大畜之小畜 (26-5, 155) 372

[[_26_8_210_]]
=== 大畜之泰 (26-6, 156) 376

[[_27_0_210_]]
== 第十五卦 ☶☳ 頤 (27 艮上震下 山雷頤)

[[_27_1_211_]]
=== 頤之不變者 23

[[_27_2_212_]]
=== 彖曰 26

[[_27_3_213_]]
=== 頤之剝 (27-1, 157) 29

[[_27_4_214_]]
=== 頤之損 (27-2, 158) 34

[[_27_5_215_]]
=== 頤之賁 (27-3, 159) 38

[[_27_6_216_]]
=== 頤之噬嗑 (27-4, 160) 41

[[_27_7_217_]]
=== 頤之益 (27-5, 161) 48

[[_27_8_218_]]
=== 頤之復 (27-6, 162) 50

[[_28_0_218_]]
== 第十六卦 ☱☴ 大過 (28 兌上巽下 澤風大過)

[[_28_1_219_]]
=== 大過之不變者 56

[[_28_2_220_]]
=== 彖曰 58

[[_28_3_221_]]
=== 大過之夬 (28-1, 163) 59

[[_28_4_222_]]
=== 大過之咸 (28-2, 164) 64

[[_28_5_223_]]
=== 大過之困 (28-3, 165) 68

[[_28_6_224_]]
=== 大過之井 (28-4, 166) 70

[[_28_7_225_]]
=== 大過之恒 (28-5, 167) 72

[[_28_8_226_]]
=== 大過之姤 (28-6, 168) 76

[[_29_0_226_]]
== 第十七卦 ☵☵ 坎 (29 坎上坎下 重水坎)

[[_29_1_227_]]
=== 坎之不變者 79

[[_29_2_228_]]
=== 彖曰 82

[[_29_3_229_]]
=== 坎之節 (29-1, 169) 85

[[_29_4_230_]]
=== 坎之比 (29-2, 170) 87

[[_29_5_231_]]
=== 坎之井 (29-3, 171) 89

[[_29_6_232_]]
=== 坎之困 (29-4, 172) 93

[[_29_7_233_]]
=== 坎之師 (29-5, 173) 99

[[_29_8_234_]]
=== 坎之渙 (29-6, 174) 102

[[_30_0_234_]]
== 第十八卦 ☲☲ 離 (30 離上離下 重火離)

[[_30_1_235_]]
=== 離之不變者 109

[[_30_2_236_]]
=== 彖曰 111

[[_30_3_237_]]
=== 離之旅 (30-1, 175) 113

[[_30_4_238_]]
=== 離之大有 (30-2, 176) 118

[[_30_5_239_]]
=== 離之噬嗑 (30-3, 177) 120

[[_30_6_240_]]
=== 離之賁 (30-4, 178) 125

[[_30_7_241_]]
=== 離之同人 (30-5, 179) 127

[[_30_8_242_]]
=== 離之豐 (30-6, 180) 130

[[_31_0_242_]]
== 第十九卦之正 ☱☶ 咸(31 兌上艮下 澤山咸)

[[_31_1_243_]]
=== 咸之不變者 192

[[_31_2_244_]]
=== 彖曰 195

[[_31_3_245_]]
=== 咸之革 (31-1, 181) 198

[[_31_4_246_]]
=== 咸之大過 (31-2, 182) 200

[[_31_5_247_]]
=== 咸之萃 (31-3, 183) 203

[[_31_6_248_]]
=== 咸之蹇 (31-4, 184) 207

[[_31_7_249_]]
=== 咸之小過 (31-5, 185) 220

[[_31_8_250_]]
=== 咸之遯 (31-6, 186) 222

[[_32_0_250_]]
== 第十九卦之反 ☳☴ 恒 (32 震上巽下 雷風恒)

[[_32_1_251_]]
=== 恒之不變者 228

[[_32_2_252_]]
=== 彖曰 230

[[_32_3_253_]]
=== 恒之大壯 (32-1, 187) 234

[[_32_4_254_]]
=== 恒之小過 (32-2, 188) 237

[[_32_5_255_]]
=== 恒之解 (32-3, 189) 239

[[_32_6_256_]]
=== 恒之升 (32-4, 190) 243

[[_32_7_257_]]
=== 恒之大過 (32-5, 191) 245

[[_32_8_258_]]
=== 恒之鼎 (32-6, 192) 248

[[_33_0_258_]]
== 第二十卦之正 ☰☶ 遯 (33 乾上艮下 天山遯)

[[_33_1_259_]]
=== 遯之不變者 256

[[_33_2_260_]]
=== 彖曰 257

[[_33_3_261_]]
=== 遯之同人 (33-1, 193) 258

[[_33_4_262_]]
=== 遯之姤 (33-2, 194) 260

[[_33_5_263_]]
=== 遯之否 (33-3, 195) 263

[[_33_6_264_]]
=== 遯之漸 (33-4, 196) 267

[[_33_7_265_]]
=== 遯之旅 (33-5, 197) 270

[[_33_8_266_]]
=== 遯之咸 (33-6, 198) 271

[[_34_0_266_]]
== 第二十卦之反 ☳☰ 大壯 (34 震上乾下 雷天大壯)

[[_34_1_267_]]
=== 大壯之不變者 281

[[_34_2_268_]]
=== 彖曰 282

[[_34_3_269_]]
=== 大壯之恒 (34-1, 199) 283

[[_34_4_270_]]
=== 大壯之豐 (34-2, 200) 285

[[_34_5_271_]]
=== 大壯之歸妹 (34-3, 201) 286

[[_34_6_272_]]
=== 大壯之泰 (34-4, 202) 291

[[_34_7_273_]]
=== 大壯之夬 (34-5, 203) 294

[[_34_8_274_]]
=== 大壯之大有 (34-6, 204) 297

[[_35_0_274_]]
== 第二十一卦之正 ☲☷ 晉 (35 離上坤下 火地晉)

[[_35_1_275_]]
=== 晉之不變者 304

[[_35_2_276_]]
=== 彖曰 308

[[_35_3_277_]]
=== 晉之噬嗑 (35-1, 205) 310

[[_35_4_278_]]
=== 晉之未濟 (35-2, 206) 314

[[_35_5_279_]]
=== 晉之旅 (35-3, 207) 318

[[_35_6_280_]]
=== 晉之剝 (35-4, 208) 320

[[_35_7_281_]]
=== 晉之否 (35-5, 209) 324

[[_35_8_282_]]
=== 晉之豫 (35-6, 210) 327

[[_36_0_282_]]
== 第二十一卦之反 ☷☲ 明夷 (36 坤上離下 地火明夷)

[[_36_1_283_]]
=== 明夷之不變者 337

[[_36_2_284_]]
=== 彖曰 339

[[_36_3_285_]]
=== 明夷之謙 (36-1, 211) 341

[[_36_4_286_]]
=== 明夷之泰 (36-2, 212) 348

[[_36_5_287_]]
=== 明夷之復 (36-3, 213) 353

[[_36_6_288_]]
=== 明夷之豐 (36-4, 214) 358

[[_36_7_289_]]
=== 明夷之旣濟 (36-5, 215) 362

[[_36_8_290_]]
=== 明夷之賁 (36-6, 216) 366

[[_37_0_290_]]
== 第二十二卦之正 ☴☲ 家人 (37 巽上離下 風火家人)

[[_37_1_291_]]
=== 家人之不變者 25

[[_37_2_292_]]
=== 彖曰 26

[[_37_3_293_]]
=== 家人之漸 (37-1, 217) 29

[[_37_4_294_]]
=== 家人之小畜 (37-2, 218) 31

[[_37_5_295_]]
=== 家人之益 (37-3, 219) 36

[[_37_6_296_]]
=== 家人之同人 (37-4, 220) 42

[[_37_7_297_]]
=== 家人之賁 (37-5, 221) 44

[[_37_8_298_]]
=== 家人之旣濟 (37-6, 222) 46

[[_38_0_298_]]
== 第二十二卦之反 ☲☱ 睽(38 離上兌下 火澤睽)

[[_38_1_299_]]
=== 睽之不變者 52

[[_38_2_300_]]
=== 彖曰 53

[[_38_3_301_]]
=== 睽之未濟 (38-1, 223) 57

[[_38_4_302_]]
=== 睽之噬嗑 (38-2, 224) 61

[[_38_5_303_]]
=== 睽之大有 (38-3, 225) 64

[[_38_6_304_]]
=== 睽之損 (38-4, 226) 69

[[_38_7_305_]]
=== 睽之履 (38-5, 227) 73

[[_38_8_306_]]
=== 睽之歸妹 (38-6, 228) 76

[[_39_0_306_]]
== 第二十三卦之正 ☵☶ 蹇 (39 坎上艮下 水山蹇)

[[_39_1_307_]]
=== 蹇之不變者 88

[[_39_2_308_]]
=== 彖曰 91

[[_39_3_309_]]
=== 蹇之旣濟 (39-1, 229) 94

[[_39_4_310_]]
=== 蹇之井 (39-2, 230) 96

[[_39_5_311_]]
=== 蹇之比 (39-3, 231) 99

[[_39_6_312_]]
=== 蹇之咸 (39-4, 232) 101

[[_39_7_313_]]
=== 蹇之謙 (39-5, 233) 102

[[_39_8_314_]]
=== 蹇之漸 (39-6, 234) 104

[[_40_0_314_]]
== 第二十三卦之反 ☳☵ 解(40 震上坎下 雷水解)

[[_40_1_315_]]
=== 解之不變者 110

[[_40_2_316_]]
=== 彖曰 112

[[_40_3_317_]]
=== 解之歸妹 (40-1, 235) 115

[[_40_4_318_]]
=== 解之豫 (40-2, 236) 117

[[_40_5_319_]]
=== 解之恒 (40-3, 237) 120

[[_40_6_320_]]
=== 解之師 (40-4, 238) 125

[[_40_7_321_]]
=== 解之困 (40-5, 239) 128

[[_40_8_322_]]
=== 解之未濟 (40-6, 240) 130

[[_41_0_322_]]
== 第二十四卦之正 ☶☱ 損 (41 艮上兌下 山澤損)

[[_41_1_323_]]
=== 損之不變者 138

[[_41_2_324_]]
=== 彖曰 144

[[_41_3_325_]]
=== 損之蒙 (41-1, 241) 147

[[_41_4_326_]]
=== 損之頤 (41-2, 242) 152

[[_41_5_327_]]
=== 損之大畜 (41-3, 243) 154

[[_41_6_328_]]
=== 損之睽 (41-4, 244) 158

[[_41_7_329_]]
=== 損之中孚 (41-5, 245) 161

[[_41_8_330_]]
=== 損之臨 (41-6, 246) 166

[[_42_0_330_]]
== 第二十四卦之反 ☴☳ 益 (42 巽上震下 風雷益)

[[_42_1_331_]]
=== 益之不變者 172

[[_42_2_332_]]
=== 彖曰 173

[[_42_3_333_]]
=== 益之觀 (42-1, 247) 177

[[_42_4_334_]]
=== 益之中孚 (42-2, 248) 180

[[_42_5_335_]]
=== 益之家人 (42-3, 249) 185

[[_42_6_336_]]
=== 益之無妄 (42-4, 250) 192

[[_42_7_337_]]
=== 益之頤 (42-5, 251) 194

[[_42_8_338_]]
=== 益之屯 (42-6, 252) 198

[[_43_0_338_]]
== 第二十五卦之正 ☱☰ 夬 (43 兌上乾下 澤天夬)

[[_43_1_339_]]
=== 夬之不變者 205

[[_43_2_340_]]
=== 彖曰 210

[[_43_3_341_]]
=== 夬之大過 (43-1, 253) 213

[[_43_4_342_]]
=== 夬之革 (43-2, 254) 217

[[_43_5_343_]]
=== 夬之兌 (43-3, 255) 221

[[_43_6_344_]]
=== 夬之需 (43-4, 256) 225

[[_43_7_345_]]
=== 夬之大壯 (43-5, 257) 231

[[_43_8_346_]]
=== 夬之乾 (43-6, 258) 236

[[_44_0_346_]]
== 第二十五卦之反 ☰☴ 姤 (44 乾上巽下 天風姤)

[[_44_1_347_]]
=== 姤之不變者 240

[[_44_2_348_]]
=== 彖曰 241

[[_44_3_349_]]
=== 姤之乾 (44-1, 259) 243

[[_44_4_350_]]
=== 姤之遯 (44-2, 260) 249

[[_44_5_351_]]
=== 姤之訟 (44-3, 261) 252

[[_44_6_352_]]
=== 姤之巽 (44-4, 262) 256

[[_44_7_353_]]
=== 姤之鼎 (44-5, 263) 259

[[_44_8_354_]]
=== 姤之大過 (44-6, 264) 263

[[_45_0_354_]]
== 第二十六卦之正 ☱☷ 萃 (45 兌上坤下 澤地萃)

[[_45_1_355_]]
=== 萃之不變者 270

[[_45_2_356_]]
=== 彖曰 275

[[_45_3_357_]]
=== 萃之隨 (45-1, 265) 277

[[_45_4_358_]]
=== 萃之困 (45-2, 266) 282

[[_45_5_359_]]
=== 萃之咸 (45-3, 267) 287

[[_45_6_360_]]
=== 萃之比 (45-4, 268) 290

[[_45_7_361_]]
=== 萃之豫 (45-5, 269) 292

[[_45_8_362_]]
=== 萃之否 (45-6, 270) 296

[[_46_0_362_]]
== 第二十六卦之反 ☷☴ 升 (46 坤上巽下 地風升)

[[_46_1_363_]]
=== 升之不變者 302

[[_46_2_364_]]
=== 彖曰 306

[[_46_3_365_]]
=== 升之泰 (46-1, 271) 307

[[_46_4_366_]]
=== 升之謙 (46-2, 272) 309

[[_46_5_367_]]
=== 升之師 (46-3, 273) 312

[[_46_6_368_]]
=== 升之恒 (46-4, 274) 313

[[_46_7_369_]]
=== 升之井 (46-5, 275) 316

[[_46_8_370_]]
=== 升之蠱 (46-6, 276) 318

[[_47_0_370_]]
== 第二十七卦之正 ☱☵ 困 (47 兌上坎下 澤水困)

[[_47_1_371_]]
=== 困之不變者 326

[[_47_2_372_]]
=== 彖曰 329

[[_47_3_373_]]
=== 困之兌 (47-1, 277) 331

[[_47_4_374_]]
=== 困之萃 (47-2, 278) 336

[[_47_5_375_]]
=== 困之大過 (47-3, 279) 342

[[_47_6_376_]]
=== 困之坎 (47-4, 280) 347

[[_47_7_377_]]
=== 困之解 (47-5, 281) 352

[[_47_8_378_]]
=== 困之訟 (47-6, 282) 357

[[_48_0_378_]]
== 第二十七卦之反 ☵☴ 井 (48 坎上巽下 水風井)

[[_48_1_379_]]
=== 井之不變者 365

[[_48_2_380_]]
=== 彖曰 370

[[_48_3_381_]]
=== 井之需 (48-1, 283) 373

[[_48_4_382_]]
=== 井之蹇 (48-2, 284) 376

[[_48_5_383_]]
=== 井之坎 (48-3, 285) 381

[[_48_6_384_]]
=== 井之大過 (48-4, 286) 384

[[_48_7_385_]]
=== 井之升 (48-5, 287) 386

[[_48_8_386_]]
=== 井之巽 (48-6, 288) 388

[[_49_0_386_]]
== 第二十八卦之正 ☱☲ 革 (49 兌上離下 澤火革)

[[_49_1_387_]]
=== 革之不變者 24

[[_49_2_388_]]
=== 彖曰 27

[[_49_3_389_]]
=== 革之咸 (49-1, 289) 31

[[_49_4_390_]]
=== 革之夬 (49-2, 290) 34

[[_49_5_391_]]
=== 革之隨 (49-3, 291) 36

[[_49_6_392_]]
=== 革之旣濟 (49-4, 292) 41

[[_49_7_393_]]
=== 革之豐 (49-5, 293) 45

[[_49_8_394_]]
=== 革之同人 (49-6, 294) 47

[[_50_0_394_]]
== 第二十八卦之反 ☲☴ 鼎 (50 離上巽下 火風鼎)

[[_50_1_395_]]
=== 鼎之不變者 58

[[_50_2_396_]]
=== 彖曰 60

[[_50_3_397_]]
=== 鼎之大有 (50-1, 295) 63

[[_50_4_398_]]
=== 鼎之旅 (50-2, 296) 68

[[_50_5_399_]]
=== 鼎之未濟 (50-3, 297) 73

[[_50_6_400_]]
=== 鼎之蠱 (50-4, 298) 80

[[_50_7_401_]]
=== 鼎之姤 (50-5, 299) 89

[[_50_8_402_]]
=== 鼎之恒 (50-6, 300) 92

[[_51_0_402_]]
== 第二十九卦之正 ☳☳ 震 (51 震上震下 重雷震)

[[_51_1_403_]]
=== 震之不變者 97

[[_51_2_404_]]
=== 彖曰 103

[[_51_3_405_]]
=== 震之豫 (51-1, 301) 105

[[_51_4_406_]]
=== 震之歸妹 (51-2, 302) 107

[[_51_5_407_]]
=== 震之豐 (51-3, 303) 112

[[_51_6_408_]]
=== 震之復 (51-4, 304) 115

[[_51_7_409_]]
=== 震之隨 (51-5, 305) 117

[[_51_8_410_]]
=== 震之噬嗑 (51-6, 306) 122

[[_52_0_410_]]
== 第二十九卦之反 ☶☶ 艮 (52 艮上艮下 重山艮)

[[_52_1_411_]]
=== 艮之不變者 130

[[_52_2_412_]]
=== 彖曰 135

[[_52_3_413_]]
=== 艮之賁 (52-1, 307) 138

[[_52_4_414_]]
=== 艮之蠱 (52-2, 308) 141

[[_52_5_415_]]
=== 艮之剝 (52-3, 309) 145

[[_52_6_416_]]
=== 艮之旅 (52-4, 310) 150

[[_52_7_417_]]
=== 艮之漸 (52-5, 311) 152

[[_52_8_418_]]
=== 艮之謙 (52-6, 312) 156

[[_53_0_418_]]
== 第三十卦之正 ☴☶ 漸 (53 巽上艮下 風山漸)

[[_53_1_419_]]
=== 漸之不變者 162

[[_53_2_420_]]
=== 彖曰 163

[[_53_3_421_]]
=== 漸之家人 (53-1, 313) 167

[[_53_4_422_]]
=== 漸之巽 (53-2, 314) 171

[[_53_5_423_]]
=== 漸之觀 (53-3, 315) 175

[[_53_6_424_]]
=== 漸之遯 (53-4, 316) 180

[[_53_7_425_]]
=== 漸之艮 (53-5, 317) 183

[[_53_8_426_]]
=== 漸之蹇 (53-6, 318) 187

[[_54_0_426_]]
== 第三十卦之反 ☳☱ 歸妹 (54 震上兌下 雷澤歸妹)

[[_54_1_427_]]
=== 歸妹之不變者 194

[[_54_2_428_]]
=== 彖曰 196

[[_54_3_429_]]
=== 歸妹之解 (54-1, 319) 198

[[_54_4_430_]]
=== 歸妹之震 (54-2, 320) 203

[[_54_5_431_]]
=== 歸妹之大壯 (54-3, 321) 207

[[_54_6_432_]]
=== 歸妹之臨 (54-4, 322) 211

[[_54_7_433_]]
=== 歸妹之兌 (54-5, 323) 212

[[_54_8_434_]]
=== 歸妹之睽 (54-6, 324) 219

[[_55_0_434_]]
== 第三十一卦之正 ☳☲ 豊 (55 震上離下 雷火豊)

[[_55_1_435_]]
=== 豐之不變者 227

[[_55_2_436_]]
=== 彖曰 232

[[_55_3_437_]]
=== 豐之小過 (55-1, 325) 234

[[_55_4_438_]]
=== 豐之大壯 (55-2, 326) 239

[[_55_5_439_]]
=== 豐之震 (55-3, 327) 247

[[_55_6_440_]]
=== 豐之明夷 (55-4, 328) 253

[[_55_7_441_]]
=== 豐之革 (55-5, 329) 256

[[_55_8_442_]]
=== 豐之離 (55-6, 330) 258

[[_56_0_442_]]
== 第三十一卦之反 ☲☶ 旅 (56 離上艮下 火山旅)

[[_56_1_443_]]
=== 旅之不變者 269

[[_56_2_444_]]
=== 彖曰 271

[[_56_3_445_]]
=== 旅之離 (56-1, 331) 273

[[_56_4_446_]]
=== 旅之鼎 (56-2, 332) 278

[[_56_5_447_]]
=== 旅之晉 (56-3, 333) 281

[[_56_6_448_]]
=== 旅之艮 (56-4, 334) 284

[[_56_7_449_]]
=== 旅之遯 (56-5, 335) 288

[[_56_8_450_]]
=== 旅之小過 (56-6, 336) 292

[[_57_0_450_]]
== 第三十二卦之正 ☴☴ 巽 (57 巽上巽下 重風巽)

[[_57_1_451_]]
=== 巽之不變者 303

[[_57_2_452_]]
=== 彖曰 305

[[_57_3_453_]]
=== 巽之小畜 (57-1, 337) 307

[[_57_4_454_]]
=== 巽之漸 (57-2, 338) 310

[[_57_5_455_]]
=== 巽之渙 (57-3, 339) 314

[[_57_6_456_]]
=== 巽之姤 (57-4, 340) 317

[[_57_7_457_]]
=== 巽之蠱 (57-5, 341) 322

[[_57_8_458_]]
=== 巽之井 (57-6, 342) 327

[[_58_0_458_]]
== 第三十二卦之反 ☱☱ 兌 (58 兌上兌下 重澤兌)

[[_58_1_459_]]
=== 兌之不變者 337

[[_58_2_460_]]
=== 彖曰 338

[[_58_3_461_]]
=== 兌之困 (58-1, 343) 340

[[_58_4_462_]]
=== 兌之隨 (58-2, 344) 342

[[_58_5_463_]]
=== 兌之夬 (58-3, 345) 344

[[_58_6_464_]]
=== 兌之節 (58-4, 346) 345

[[_58_7_465_]]
=== 兌之歸妹 (58-5, 347) 348

[[_58_8_466_]]
=== 兌之履 (58-6, 348) 350

[[_59_0_466_]]
== 第三十三卦之正 ☴☵ 渙 (59 巽上坎下 風水渙)

[[_59_1_467_]]
=== 渙之不變者 355

[[_59_2_468_]]
=== 彖曰 358

[[_59_3_469_]]
=== 渙之中孚 (59-1, 349) 359

[[_59_4_470_]]
=== 渙之觀 (59-2, 350) 361

[[_59_5_471_]]
=== 渙之巽 (59-3, 351) 366

[[_59_6_472_]]
=== 渙之訟 (59-4, 352) 367

[[_59_7_473_]]
=== 渙之蒙 (59-5, 353) 373

[[_59_8_474_]]
=== 渙之坎 (59-6, 354) 376

[[_60_0_474_]]
== 第三十三卦之反 ☵☱ 節 (60 坎上兌下 水澤節)

[[_60_1_475_]]
=== 節之不變者 385

[[_60_2_476_]]
=== 彖曰 389

[[_60_3_477_]]
=== 節之坎 (60-1, 355) 392

[[_60_4_478_]]
=== 節之屯 (60-2, 356) 396

[[_60_5_479_]]
=== 節之需 (60-3, 357) 398

[[_60_6_480_]]
=== 節之兌 (60-4, 358) 400

[[_60_7_481_]]
=== 節之臨 (60-5, 359) 403

[[_60_8_482_]]
=== 節之中孚 (60-6, 360) 405

[[_61_0_482_]]
== 第三十四卦 ☴☱ 中孚 (61 巽上兌下 風澤中孚)

[[_61_1_483_]]
=== 中孚之不變者 27

[[_61_2_484_]]
=== 彖曰 31

[[_61_3_485_]]
=== 中孚之渙 (61-1, 361) 37

[[_61_4_486_]]
=== 中孚之益 (61-2, 362) 41

[[_61_5_487_]]
=== 中孚之小畜 (61-3, 363) 47

[[_61_6_488_]]
=== 中孚之履 (61-4, 364) 51

[[_61_7_489_]]
=== 中孚之損 (61-5, 365) 54

[[_61_8_490_]]
=== 中孚之節 (61-6, 366) 57

[[_62_0_490_]]
== 第三十五卦 ☳☶ 小過 (62 震上艮下 雷山小過)

[[_62_1_491_]]
=== 小過之不變者 61

[[_62_2_492_]]
=== 彖曰 65

[[_62_3_493_]]
=== 小過之豐 (62-1, 367) 68

[[_62_4_494_]]
=== 小過之恒 (62-2, 368) 71

[[_62_5_495_]]
=== 小過之豫 (62-3, 369) 74

[[_62_6_496_]]
=== 小過之謙 (62-4, 370) 76

[[_62_7_497_]]
=== 小過之咸 (62-5, 371) 81

[[_62_8_498_]]
=== 小過之旅 (62-6, 372) 85

[[_63_0_498_]]
== 第三十六卦之正 ☵☲ 旣濟 (63 坎上離下 水火旣濟)

[[_63_1_499_]]
=== 旣濟之不變者 91

[[_63_2_500_]]
=== 彖曰 93

[[_63_3_501_]]
=== 旣濟之蹇 (63-1, 373) 96

[[_63_4_502_]]
=== 旣濟之需 (63-2, 374) 100

[[_63_5_503_]]
=== 旣濟之屯 (63-3, 375) 105

[[_63_6_504_]]
=== 旣濟之革 (63-4, 376) 110

[[_63_7_505_]]
=== 旣濟之明夷 (63-5, 377) 116

[[_63_8_506_]]
=== 旣濟之家人 (63-6, 378) 122

[[_64_0_506_]]
== 第三十六卦之反 ☲☵ 未濟 (64 離上坎下 火水未濟)

[[_64_1_507_]]
=== 未濟之不變者 127

[[_64_2_508_]]
=== 彖曰 133

[[_64_3_509_]]
=== 未濟之睽 (64-1, 379) 135

[[_64_4_510_]]
=== 未濟之晉 (64-2, 380) 137

[[_64_5_511_]]
=== 未濟之鼎 (64-3, 381) 138

[[_64_6_512_]]
=== 未濟之蒙 (64-4, 382) 141

[[_64_7_513_]]
=== 未濟之訟 (64-5, 383) 145

[[_64_8_514_]]
=== 未濟之解 (64-6, 384) 149
